/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoteRouteImport } from './routes/note'
import { Route as IndexRouteImport } from './routes/index'

const JournalsLazyRouteImport = createFileRoute('/journals')()
const AllNotesLazyRouteImport = createFileRoute('/all-notes')()
const AboutLazyRouteImport = createFileRoute('/about')()
const NoteDocIdIndexLazyRouteImport = createFileRoute('/note/$docId/')()
const NoteDocIdNodeIdLazyRouteImport = createFileRoute('/note/$docId/$nodeId')()

const JournalsLazyRoute = JournalsLazyRouteImport.update({
  id: '/journals',
  path: '/journals',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/journals.lazy').then((d) => d.Route))
const AllNotesLazyRoute = AllNotesLazyRouteImport.update({
  id: '/all-notes',
  path: '/all-notes',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/all-notes.lazy').then((d) => d.Route))
const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const NoteRoute = NoteRouteImport.update({
  id: '/note',
  path: '/note',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteDocIdIndexLazyRoute = NoteDocIdIndexLazyRouteImport.update({
  id: '/$docId/',
  path: '/$docId/',
  getParentRoute: () => NoteRoute,
} as any).lazy(() =>
  import('./routes/note/$docId/index.lazy').then((d) => d.Route),
)
const NoteDocIdNodeIdLazyRoute = NoteDocIdNodeIdLazyRouteImport.update({
  id: '/$docId/$nodeId',
  path: '/$docId/$nodeId',
  getParentRoute: () => NoteRoute,
} as any).lazy(() =>
  import('./routes/note/$docId/$nodeId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/note': typeof NoteRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/all-notes': typeof AllNotesLazyRoute
  '/journals': typeof JournalsLazyRoute
  '/note/$docId/$nodeId': typeof NoteDocIdNodeIdLazyRoute
  '/note/$docId/': typeof NoteDocIdIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/note': typeof NoteRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/all-notes': typeof AllNotesLazyRoute
  '/journals': typeof JournalsLazyRoute
  '/note/$docId/$nodeId': typeof NoteDocIdNodeIdLazyRoute
  '/note/$docId': typeof NoteDocIdIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/note': typeof NoteRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/all-notes': typeof AllNotesLazyRoute
  '/journals': typeof JournalsLazyRoute
  '/note/$docId/$nodeId': typeof NoteDocIdNodeIdLazyRoute
  '/note/$docId/': typeof NoteDocIdIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/note'
    | '/about'
    | '/all-notes'
    | '/journals'
    | '/note/$docId/$nodeId'
    | '/note/$docId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/note'
    | '/about'
    | '/all-notes'
    | '/journals'
    | '/note/$docId/$nodeId'
    | '/note/$docId'
  id:
    | '__root__'
    | '/'
    | '/note'
    | '/about'
    | '/all-notes'
    | '/journals'
    | '/note/$docId/$nodeId'
    | '/note/$docId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NoteRoute: typeof NoteRouteWithChildren
  AboutLazyRoute: typeof AboutLazyRoute
  AllNotesLazyRoute: typeof AllNotesLazyRoute
  JournalsLazyRoute: typeof JournalsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/journals': {
      id: '/journals'
      path: '/journals'
      fullPath: '/journals'
      preLoaderRoute: typeof JournalsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-notes': {
      id: '/all-notes'
      path: '/all-notes'
      fullPath: '/all-notes'
      preLoaderRoute: typeof AllNotesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note': {
      id: '/note'
      path: '/note'
      fullPath: '/note'
      preLoaderRoute: typeof NoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/$docId/': {
      id: '/note/$docId/'
      path: '/$docId'
      fullPath: '/note/$docId/'
      preLoaderRoute: typeof NoteDocIdIndexLazyRouteImport
      parentRoute: typeof NoteRoute
    }
    '/note/$docId/$nodeId': {
      id: '/note/$docId/$nodeId'
      path: '/$docId/$nodeId'
      fullPath: '/note/$docId/$nodeId'
      preLoaderRoute: typeof NoteDocIdNodeIdLazyRouteImport
      parentRoute: typeof NoteRoute
    }
  }
}

interface NoteRouteChildren {
  NoteDocIdNodeIdLazyRoute: typeof NoteDocIdNodeIdLazyRoute
  NoteDocIdIndexLazyRoute: typeof NoteDocIdIndexLazyRoute
}

const NoteRouteChildren: NoteRouteChildren = {
  NoteDocIdNodeIdLazyRoute: NoteDocIdNodeIdLazyRoute,
  NoteDocIdIndexLazyRoute: NoteDocIdIndexLazyRoute,
}

const NoteRouteWithChildren = NoteRoute._addFileChildren(NoteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NoteRoute: NoteRouteWithChildren,
  AboutLazyRoute: AboutLazyRoute,
  AllNotesLazyRoute: AllNotesLazyRoute,
  JournalsLazyRoute: JournalsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
