import inject from '@stylexjs/stylex/lib/stylex-inject'

const toastifyThemeRules = [
  '.memorilo-toast-container.memorilo-toast-container { --toastify-container-width: min(372px, calc(100vw - 32px)); --toastify-toast-width: 372px; --toastify-toast-offset: 68px; --toastify-toast-min-height: 56px; --toastify-toast-max-height: min(480px, calc(100vh - 96px)); --toastify-toast-bd-radius: var(--ui-surface-radius); --toastify-font-family: var(--ui-font-family); --toastify-z-index: 100; position: fixed; z-index: var(--toastify-z-index); display: flex; width: var(--toastify-container-width); box-sizing: border-box; flex-direction: column; align-items: stretch; gap: 10px; color: var(--ui-text); pointer-events: none; transform: translate3d(0, 0, var(--toastify-z-index)); }',
  '.memorilo-toast-container.Toastify__toast-container--top-right { top: 68px; right: 16px; }',
  '.memorilo-toast.memorilo-toast { --memorilo-toast-status: var(--ui-text-muted); position: relative; display: flex; width: min(372px, calc(100vw - 32px)); min-height: 56px; max-height: var(--toastify-toast-max-height); margin: 0; overflow: hidden; align-items: center; border: var(--ui-surface-stroke) solid var(--ui-border); border-radius: var(--ui-surface-radius); padding: 12px 40px 12px 15px; background-color: var(--ui-surface-raised); background-image: var(--ui-surface-background-image); backdrop-filter: var(--ui-material-filter); box-shadow: var(--ui-overlay-shadow); color: var(--ui-text); font-family: var(--toastify-font-family); font-size: 14px; font-weight: 420; letter-spacing: 0; line-height: 20px; pointer-events: auto; transform-origin: top right; }',
  '.memorilo-toast.memorilo-toast::before { position: absolute; z-index: 0; inset: 0; border-radius: inherit; padding: 3px; background-color: rgba(255, 255, 255, 0.08); backdrop-filter: var(--ui-material-filter); content: ""; opacity: var(--ui-material-decoration-opacity); -webkit-mask: linear-gradient(#000 0 0) content-box, linear-gradient(#000 0 0); -webkit-mask-composite: xor; mask: linear-gradient(#000 0 0) content-box, linear-gradient(#000 0 0); mask-composite: exclude; pointer-events: none; }',
  '.memorilo-toast.Toastify__toast--warning { --memorilo-toast-status: var(--ui-warning); }',
  '.memorilo-toast.Toastify__toast--error { --memorilo-toast-status: var(--ui-danger); }',
  '.memorilo-toast .Toastify__toast-icon { display: grid; width: 18px; height: 18px; flex: 0 0 18px; align-self: center; margin: 0 10px 0 0; place-items: center; color: var(--memorilo-toast-status); }',
  '.memorilo-toast .Toastify__toast-icon svg { width: 17px; height: 17px; }',
  '.memorilo-toast > div:not(.Toastify__toast-icon):not(.Toastify__progress-bar--wrp) { display: grid; min-width: 0; flex: 1; grid-template-columns: minmax(0, 1fr) auto; align-items: center; column-gap: 12px; }',
  '.memorilo-toast :is(p, h1, h2, h3) { margin: 0; }',
  '.memorilo-toast :is(button:not(.memorilo-toast-dismiss), a) { appearance: none; display: inline-flex; min-height: 28px; align-items: center; justify-content: center; margin: 0; border: 0; border-radius: var(--ui-control-radius); padding: 3px 4px; background-color: transparent; box-shadow: none; color: var(--ui-text-muted); cursor: default; font: inherit; font-size: 13px; font-weight: 520; letter-spacing: 0; line-height: 18px; outline: none; text-decoration: none; transition: color 100ms ease-out, opacity 100ms ease-out, transform 100ms ease-out; }',
  '.memorilo-toast :is(button:not(.memorilo-toast-dismiss), a):hover { color: var(--ui-text); }',
  '.memorilo-toast :is(button:not(.memorilo-toast-dismiss), a):active { opacity: 0.58; transform: scale(0.97); }',
  '.memorilo-toast :is(button:not(.memorilo-toast-dismiss), a):focus-visible { box-shadow: 0 0 0 2px var(--ui-focus); }',
  '.memorilo-toast :is(button:not(.memorilo-toast-dismiss), a) + :is(button:not(.memorilo-toast-dismiss), a) { margin-left: 2px; }',
  '.memorilo-toast-dismiss { position: absolute; z-index: 2; top: 50%; right: 8px; display: grid; width: 26px; height: 26px; place-items: center; border: 0; border-radius: var(--ui-pill-radius); padding: 0; background-color: transparent; color: var(--ui-text-quiet); cursor: default; outline: none; transform: translateY(-50%) scale(1); transition: background-color 110ms ease-out, color 110ms ease-out, transform 110ms ease-out; }',
  '.memorilo-toast-dismiss:hover { background-color: var(--ui-control-hover); color: var(--ui-text); }',
  '.memorilo-toast-dismiss:active { background-color: var(--ui-control-pressed); transform: translateY(-50%) scale(0.92); }',
  '.memorilo-toast-dismiss:focus-visible { box-shadow: 0 0 0 2px var(--ui-focus); color: var(--ui-text); }',
  '.memorilo-toast-dismiss svg { width: 15px; height: 15px; }',
  '.memorilo-toast .Toastify__progress-bar--wrp { position: absolute; right: 15px; bottom: 7px; left: 15px; width: auto; height: 2px; overflow: hidden; border-radius: 1px; background-color: rgba(58, 59, 64, 0.08); }',
  '.memorilo-toast .Toastify__progress-bar--wrp[data-hidden="true"] { opacity: 0; }',
  '.memorilo-toast .memorilo-toast-progress { position: absolute; z-index: 1; bottom: 0; left: 0; width: 100%; height: 100%; border-radius: inherit; background: rgba(58, 59, 64, 0.46); opacity: 0.7; transform-origin: left; }',
  '.memorilo-toast .memorilo-toast-progress.Toastify__progress-bar--animated { animation: memorilo-toast-track-progress linear 1 forwards; }',
  '.memorilo-toast .memorilo-toast-progress.Toastify__progress-bar--controlled { transition: transform 200ms; }',
  '.memorilo-toast .Toastify__progress-bar--bg { width: 100%; height: 100%; background: rgba(58, 59, 64, 0.08); opacity: 1; }',
  '.memorilo-toast-spinner { animation: memorilo-toast-spin 900ms linear infinite; color: rgba(58, 59, 64, 0.46); }',
  '.memorilo-toast-enter { animation: memorilo-toast-materialize 300ms cubic-bezier(0.22, 1, 0.36, 1) both; }',
  '.memorilo-toast-exit { animation: memorilo-toast-dematerialize 190ms cubic-bezier(0.4, 0, 1, 1) both; }',
  '@keyframes memorilo-toast-materialize { from { opacity: 0; filter: blur(5px) saturate(120%); transform: translate3d(0, -10px, 0) scale(0.97); } 55% { opacity: 1; filter: blur(0) saturate(170%); } to { opacity: 1; filter: blur(0) saturate(100%); transform: translate3d(0, 0, 0) scale(1); } }',
  '@keyframes memorilo-toast-dematerialize { from { opacity: 1; filter: blur(0); transform: translate3d(0, 0, 0) scale(1); } to { opacity: 0; filter: blur(4px); transform: translate3d(0, -7px, 0) scale(0.985); } }',
  '@keyframes memorilo-toast-track-progress { from { transform: scaleX(1); } to { transform: scaleX(0); } }',
  '@keyframes memorilo-toast-spin { to { transform: rotate(360deg); } }',
  '@media (prefers-reduced-transparency: reduce) { .memorilo-toast { background-color: var(--ui-surface-opaque); background-image: none; backdrop-filter: none; } .memorilo-toast::before { display: none; } }',
  '@media (prefers-contrast: more) { .memorilo-toast { border-color: var(--ui-border-strong); background-color: var(--ui-surface-opaque); background-image: none; color: var(--ui-text); } .memorilo-toast::before { display: none; } .memorilo-toast .Toastify__toast-body { color: var(--ui-text); } }',
  '@media (prefers-reduced-motion: reduce) { .memorilo-toast, .memorilo-toast-dismiss, .memorilo-toast :is(button:not(.memorilo-toast-dismiss), a) { transition-duration: 0ms; } .memorilo-toast-enter { animation: memorilo-toast-fade-in 120ms ease-out both; } .memorilo-toast-exit { animation: memorilo-toast-fade-out 100ms ease-in both; } .memorilo-toast-spinner { animation: none; } }',
  '@keyframes memorilo-toast-fade-in { from { opacity: 0; } to { opacity: 1; } }',
  '@keyframes memorilo-toast-fade-out { from { opacity: 1; } to { opacity: 0; } }',
]

for (const rule of toastifyThemeRules)
  inject({ ltr: rule, priority: 2 })
