import inject from '@stylexjs/stylex/lib/stylex-inject'

const toastifyThemeRules = [
  '.memorilo-toast-container.memorilo-toast-container { --toastify-container-width: min(372px, calc(100vw - 32px)); --toastify-toast-width: 372px; --toastify-toast-offset: 68px; --toastify-toast-min-height: 56px; --toastify-toast-max-height: min(480px, calc(100vh - 96px)); --toastify-toast-bd-radius: 18px; --toastify-font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; --toastify-z-index: 100; position: fixed; z-index: var(--toastify-z-index); display: flex; width: var(--toastify-container-width); box-sizing: border-box; flex-direction: column; align-items: stretch; gap: 10px; color: rgba(24, 28, 34, 0.92); pointer-events: none; transform: translate3d(0, 0, var(--toastify-z-index)); }',
  '.memorilo-toast-container.Toastify__toast-container--top-right { top: 68px; right: 16px; }',
  '.memorilo-toast.memorilo-toast { --memorilo-toast-status: rgba(42, 43, 48, 0.58); position: relative; display: flex; width: min(372px, calc(100vw - 32px)); min-height: 56px; max-height: var(--toastify-toast-max-height); margin: 0; overflow: hidden; align-items: center; border: 1px solid rgba(255, 255, 255, 0.88); border-radius: 18px; padding: 12px 40px 12px 15px; background-color: rgba(250, 250, 250, 0.92); background-image: none; backdrop-filter: saturate(118%) contrast(106%) brightness(1.015); box-shadow: 0 13px 30px rgba(30, 30, 32, 0.13), 0 2px 6px rgba(30, 30, 32, 0.08), 0 0 0 0.5px rgba(70, 70, 72, 0.18), inset 0 1.5px rgba(255, 255, 255, 0.96), inset 1px 0 rgba(255, 255, 255, 0.66), inset 0 -1px rgba(72, 72, 74, 0.16), inset -1px 0 rgba(72, 72, 74, 0.1); color: rgba(24, 24, 26, 0.94); font-family: var(--toastify-font-family); font-size: 14px; font-weight: 420; letter-spacing: 0; line-height: 20px; pointer-events: auto; transform-origin: top right; }',
  '.memorilo-toast.memorilo-toast::before { position: absolute; z-index: 0; inset: 0; border-radius: inherit; padding: 3px; background-color: rgba(255, 255, 255, 0.08); backdrop-filter: blur(2px) saturate(130%) contrast(110%) brightness(1.03); content: ""; -webkit-mask: linear-gradient(#000 0 0) content-box, linear-gradient(#000 0 0); -webkit-mask-composite: xor; mask: linear-gradient(#000 0 0) content-box, linear-gradient(#000 0 0); mask-composite: exclude; pointer-events: none; }',
  '.memorilo-toast.Toastify__toast--warning { --memorilo-toast-status: rgba(166, 100, 24, 0.82); }',
  '.memorilo-toast.Toastify__toast--error { --memorilo-toast-status: rgba(174, 56, 56, 0.82); }',
  '.memorilo-toast .Toastify__toast-icon { display: grid; width: 18px; height: 18px; flex: 0 0 18px; align-self: center; margin: 0 10px 0 0; place-items: center; color: var(--memorilo-toast-status); }',
  '.memorilo-toast .Toastify__toast-icon svg { width: 17px; height: 17px; }',
  '.memorilo-toast > div:not(.Toastify__toast-icon):not(.Toastify__progress-bar--wrp) { display: grid; min-width: 0; flex: 1; grid-template-columns: minmax(0, 1fr) auto; align-items: center; column-gap: 12px; }',
  '.memorilo-toast :is(p, h1, h2, h3) { margin: 0; }',
  '.memorilo-toast :is(button:not(.memorilo-toast-dismiss), a) { appearance: none; display: inline-flex; min-height: 28px; align-items: center; justify-content: center; margin: 0; border: 0; border-radius: 0; padding: 3px 4px; background-color: transparent; box-shadow: none; color: rgba(31, 33, 39, 0.7); cursor: default; font: inherit; font-size: 13px; font-weight: 520; letter-spacing: 0; line-height: 18px; outline: none; text-decoration: none; transition: color 100ms ease-out, opacity 100ms ease-out, transform 100ms ease-out; }',
  '.memorilo-toast :is(button:not(.memorilo-toast-dismiss), a):hover { color: rgba(22, 24, 29, 0.94); }',
  '.memorilo-toast :is(button:not(.memorilo-toast-dismiss), a):active { opacity: 0.58; transform: scale(0.97); }',
  '.memorilo-toast :is(button:not(.memorilo-toast-dismiss), a):focus-visible { box-shadow: 0 0 0 2px rgba(54, 54, 56, 0.72); }',
  '.memorilo-toast :is(button:not(.memorilo-toast-dismiss), a) + :is(button:not(.memorilo-toast-dismiss), a) { margin-left: 2px; }',
  '.memorilo-toast-dismiss { position: absolute; z-index: 2; top: 50%; right: 8px; display: grid; width: 26px; height: 26px; place-items: center; border: 0; border-radius: 50%; padding: 0; background-color: transparent; color: rgba(38, 42, 49, 0.38); cursor: default; outline: none; transform: translateY(-50%) scale(1); transition: background-color 110ms ease-out, color 110ms ease-out, transform 110ms ease-out; }',
  '.memorilo-toast-dismiss:hover { background-color: rgba(255, 255, 255, 0.24); color: rgba(28, 32, 38, 0.78); }',
  '.memorilo-toast-dismiss:active { background-color: rgba(62, 70, 82, 0.1); transform: translateY(-50%) scale(0.92); }',
  '.memorilo-toast-dismiss:focus-visible { box-shadow: 0 0 0 2px rgba(54, 54, 56, 0.72); color: rgba(28, 28, 30, 0.82); }',
  '.memorilo-toast-dismiss svg { width: 15px; height: 15px; }',
  '.memorilo-toast .Toastify__progress-bar--wrp { position: absolute; right: 15px; bottom: 7px; left: 15px; width: auto; height: 2px; overflow: hidden; border-radius: 1px; background-color: rgba(58, 59, 64, 0.08); }',
  '.memorilo-toast .Toastify__progress-bar--wrp[data-hidden="true"] { opacity: 0; }',
  '.memorilo-toast .memorilo-toast-progress { position: absolute; z-index: 1; bottom: 0; left: 0; width: 100%; height: 100%; border-radius: inherit; background: rgba(58, 59, 64, 0.46); opacity: 0.7; transform-origin: left; }',
  '.memorilo-toast .memorilo-toast-progress.Toastify__progress-bar--animated { animation: memorilo-toast-track-progress linear 1 forwards; }',
  '.memorilo-toast .memorilo-toast-progress.Toastify__progress-bar--controlled { transition: transform 200ms; }',
  '.memorilo-toast .Toastify__progress-bar--bg { width: 100%; height: 100%; background: rgba(58, 59, 64, 0.08); opacity: 1; }',
  '.memorilo-toast-spinner { animation: memorilo-toast-spin 900ms linear infinite; color: rgba(58, 59, 64, 0.46); }',
  '.memorilo-toast-enter { animation: memorilo-toast-materialize 300ms cubic-bezier(0.22, 1, 0.36, 1) both; }',
  '.memorilo-toast-exit { animation: memorilo-toast-dematerialize 190ms cubic-bezier(0.4, 0, 1, 1) both; }',
  '@keyframes memorilo-toast-materialize { from { opacity: 0; filter: blur(5px) saturate(120%); transform: translate3d(0, -10px, 0) scale(0.97); } 55% { opacity: 1; filter: blur(0) saturate(170%); } to { opacity: 1; filter: blur(0) saturate(100%); transform: translate3d(0, 0, 0) scale(1); } }',
  '@keyframes memorilo-toast-dematerialize { from { opacity: 1; filter: blur(0); transform: translate3d(0, 0, 0) scale(1); } to { opacity: 0; filter: blur(4px); transform: translate3d(0, -7px, 0) scale(0.985); } }',
  '@keyframes memorilo-toast-track-progress { from { transform: scaleX(1); } to { transform: scaleX(0); } }',
  '@keyframes memorilo-toast-spin { to { transform: rotate(360deg); } }',
  '@media (prefers-reduced-transparency: reduce) { .memorilo-toast { border-color: rgba(64, 72, 84, 0.2); background-color: rgb(249, 250, 252); backdrop-filter: none; box-shadow: 0 12px 30px rgba(29, 36, 48, 0.16), 0 0 0 0.5px rgba(64, 72, 84, 0.2); } .memorilo-toast::before { display: none; } }',
  '@media (prefers-contrast: more) { .memorilo-toast { border-color: rgba(24, 29, 36, 0.62); background-color: rgba(255, 255, 255, 0.98); background-image: none; color: rgb(18, 21, 26); box-shadow: 0 10px 26px rgba(20, 25, 33, 0.22), inset 0 0 0 1px rgba(255, 255, 255, 0.84); } .memorilo-toast::before { display: none; } .memorilo-toast .Toastify__toast-body { color: rgb(18, 21, 26); } }',
  '@media (prefers-reduced-motion: reduce) { .memorilo-toast, .memorilo-toast-dismiss, .memorilo-toast :is(button:not(.memorilo-toast-dismiss), a) { transition-duration: 0ms; } .memorilo-toast-enter { animation: memorilo-toast-fade-in 120ms ease-out both; } .memorilo-toast-exit { animation: memorilo-toast-fade-out 100ms ease-in both; } .memorilo-toast-spinner { animation: none; } }',
  '@keyframes memorilo-toast-fade-in { from { opacity: 0; } to { opacity: 1; } }',
  '@keyframes memorilo-toast-fade-out { from { opacity: 1; } to { opacity: 0; } }',
]

for (const rule of toastifyThemeRules)
  inject({ ltr: rule, priority: 2 })
