import * as stylex from '@stylexjs/stylex'

const colors = {
  error: 'rgb(176, 61, 61)',
  focus: 'rgba(41, 97, 194, 0.85)',
  success: 'rgb(54, 105, 67)',
  text: 'rgba(31, 31, 35, 0.88)',
  textMuted: 'rgba(48, 46, 51, 0.66)',
  textQuiet: 'rgba(48, 46, 51, 0.5)',
  warning: 'rgb(156, 99, 27)',
} as const

export const p2pSidebarStatusStyles = stylex.create({
  navigation: {
    flex: 1,
  },
  motion: {
    position: 'relative',
    flex: '0 0 auto',
  },
  footer: {
    position: 'relative',
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 10,
  },
  trigger: {
    display: 'grid',
    width: '100%',
    height: 38,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '24px minmax(0, 1fr) 14px',
    gap: 8,
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 8,
    paddingLeft: 8,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.22)',
      ':hover': 'rgba(255, 255, 255, 0.4)',
      ':active': 'rgba(72, 70, 76, 0.12)',
    },
    color: colors.text,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'inset 0 1px rgba(255, 255, 255, 0.38)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.985)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform, box-shadow',
    transitionTimingFunction: 'ease-out',
  },
  icon: {
    display: 'grid',
    width: 24,
    height: 24,
    placeItems: 'center',
    color: colors.textMuted,
  },
  iconSynced: {
    color: colors.success,
  },
  iconPaused: {
    color: colors.warning,
  },
  iconError: {
    color: colors.error,
  },
  spinner: {
    animationName: stylex.keyframes({ to: { transform: 'rotate(360deg)' } }),
    animationDuration: {
      'default': '900ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    animationIterationCount: 'infinite',
    animationTimingFunction: 'linear',
  },
  summary: {
    display: 'grid',
    minWidth: 0,
    gap: 1,
    textAlign: 'left',
  },
  summaryLabel: {
    overflow: 'hidden',
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '16px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  summaryDetail: {
    overflow: 'hidden',
    color: colors.textQuiet,
    fontSize: 10,
    fontWeight: 450,
    letterSpacing: 0,
    lineHeight: '13px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  disclosure: {
    color: colors.textQuiet,
  },
  popover: {
    position: 'absolute',
    zIndex: 30,
    right: 10,
    bottom: 54,
    left: 10,
    overflow: 'hidden',
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.78)',
      '@media (prefers-contrast: more)': 'rgba(34, 37, 43, 0.52)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    padding: 6,
    backgroundColor: {
      'default': 'rgba(247, 248, 250, 0.88)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(247, 248, 250)',
      '@media (prefers-contrast: more)': 'rgb(250, 250, 251)',
    },
    backdropFilter: {
      'default': 'blur(22px) saturate(170%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 12px 30px rgba(31, 38, 48, 0.18), 0 2px 8px rgba(31, 38, 48, 0.1), inset 0 1px rgba(255, 255, 255, 0.82)',
  },
  popoverHeading: {
    margin: 0,
    paddingTop: 4,
    paddingRight: 7,
    paddingBottom: 6,
    paddingLeft: 7,
    color: colors.textMuted,
    fontSize: 10,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '14px',
  },
  deviceList: {
    display: 'grid',
    gap: 2,
  },
  deviceRow: {
    display: 'grid',
    minHeight: 38,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '24px minmax(0, 1fr)',
    gap: 8,
    borderRadius: 6,
    paddingTop: 4,
    paddingRight: 7,
    paddingBottom: 4,
    paddingLeft: 7,
  },
  deviceCopy: {
    display: 'grid',
    minWidth: 0,
    gap: 1,
  },
  deviceName: {
    overflow: 'hidden',
    color: colors.text,
    fontSize: 12,
    fontWeight: 550,
    letterSpacing: 0,
    lineHeight: '16px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  deviceState: {
    overflow: 'hidden',
    color: colors.textQuiet,
    fontSize: 10,
    letterSpacing: 0,
    lineHeight: '13px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  globalError: {
    margin: 0,
    paddingTop: 6,
    paddingRight: 7,
    paddingBottom: 7,
    paddingLeft: 7,
    color: colors.error,
    fontSize: 11,
    letterSpacing: 0,
    lineHeight: '16px',
  },
})
