import * as stylex from '@stylexjs/stylex'

export const windowTitlebarStyles = stylex.create({
  bar: {
    position: 'relative',
    zIndex: 30,
    display: 'flex',
    height: 40,
    minHeight: 40,
    flexShrink: 0,
    alignItems: 'center',
    backgroundColor: 'var(--ui-canvas, rgb(250, 250, 249))',
    color: 'var(--ui-text, rgb(37, 38, 42))',
    userSelect: 'none',
  },
  content: {
    position: 'absolute',
    left: 'env(titlebar-area-x, 0px)',
    display: 'flex',
    width: 'env(titlebar-area-width, calc(100% - 138px))',
    height: '100%',
    minWidth: 0,
    alignItems: 'center',
    gap: 16,
    paddingRight: 16,
    paddingLeft: 16,
  },
  brand: {
    display: 'flex',
    flexShrink: 0,
    alignItems: 'center',
    gap: 8,
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: '0.01em',
    lineHeight: '16px',
  },
  mark: {
    display: 'flex',
    alignItems: 'center',
    color: 'var(--ui-text-muted, rgb(93, 95, 100))',
  },
  menus: {
    display: 'flex',
    height: 28,
    flexShrink: 0,
    alignItems: 'center',
    gap: 2,
  },
  menu: {
    minHeight: 28,
    height: 28,
    borderRadius: 5,
    borderWidth: 0,
    paddingRight: 10,
    paddingLeft: 10,
    color: 'var(--ui-text-muted, rgb(93, 95, 100))',
    fontSize: 12,
    fontWeight: 400,
    boxShadow: {
      'default': 'none',
      ':focus-visible': 'none',
    },
    outline: {
      'default': 'none',
      ':focus-visible': '1px solid var(--ui-border-strong, rgb(93, 95, 100))',
    },
    outlineOffset: -1,
    transitionProperty: 'background-color, color',
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
  },
  menuOpen: {
    backgroundColor: 'var(--ui-control-pressed, rgba(80, 91, 108, 0.14))',
    color: 'var(--ui-text, rgb(37, 38, 42))',
  },
})
