import * as stylex from '@stylexjs/stylex'

const colors = {
  controlHover: 'var(--ui-control-hover, rgba(60, 60, 67, 0.08))',
  controlPressed: 'var(--ui-control-pressed, rgba(60, 60, 67, 0.14))',
  focus: 'var(--ui-focus, rgba(41, 97, 194, 0.85))',
  textMuted: 'var(--ui-text-muted, rgba(48, 46, 51, 0.66))',
  textQuiet: 'var(--ui-text-quiet, rgba(48, 46, 51, 0.5))',
} as const

export const workspaceSidebarStyles = stylex.create({
  toggle: {
    position: 'absolute',
    zIndex: 21,
    top: 14,
    display: 'grid',
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyItems: 'center',
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': colors.controlHover,
      ':active': colors.controlPressed,
    },
    color: colors.textMuted,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  groupHeading: {
    display: 'flex',
    width: '100%',
    height: 28,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 0,
    paddingRight: 7,
    paddingLeft: 8,
    backgroundColor: 'transparent',
    color: colors.textMuted,
    cursor: 'pointer',
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `inset 0 0 0 2px ${colors.focus}`,
    },
  },
  disclosureIcon: {
    display: 'grid',
    width: 14,
    height: 14,
    alignItems: 'center',
    justifyItems: 'center',
    color: colors.textQuiet,
  },
  sourceList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
  emptySourceList: {
    height: 31,
    margin: 0,
    paddingRight: 9,
    paddingLeft: 35,
    color: colors.textQuiet,
    fontSize: 12,
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: '31px',
    userSelect: 'none',
  },
  animatedSourceList: {
    overflow: 'hidden',
  },
  virtualSourceViewport: {
    width: '100%',
    overflowX: 'hidden',
    overflowY: 'auto',
    overscrollBehavior: 'contain',
  },
  virtualSourceSizer: {
    position: 'relative',
    width: '100%',
  },
  virtualSourceItem: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: 33,
  },
})
