import * as stylex from '@stylexjs/stylex'

const colors = {
  blue50: 'oklch(0.97 0.014 254.604)',
  blue600: 'oklch(0.546 0.245 262.881)',
  canvas: '#ffffff',
  gray100: 'oklch(0.967 0.003 264.542)',
  gray200: 'oklch(0.928 0.006 264.531)',
  gray500: 'oklch(0.551 0.027 264.364)',
  gray700: 'oklch(0.373 0.034 259.733)',
  gray900: 'oklch(0.21 0.034 264.665)',
  red50: 'oklch(0.971 0.013 17.38)',
  red700: 'oklch(0.505 0.213 27.518)',
} as const

export const outlineEditorStyles = stylex.create({
  root: {
    display: 'flex',
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
  },
  toolbar: {
    display: 'flex',
    minHeight: 42,
    alignItems: 'center',
    gap: 8,
    borderBottomColor: colors.gray200,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingBlock: 5,
    paddingInline: 12,
    backgroundColor: colors.canvas,
  },
  breadcrumbs: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 6,
    flex: 1,
    color: colors.gray500,
    fontSize: 13,
  },
  focusLabel: {
    overflow: 'hidden',
    color: colors.gray700,
    fontWeight: 600,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  controls: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  button: {
    minHeight: 32,
    borderColor: colors.gray200,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    paddingBlock: 5,
    paddingInline: 9,
    backgroundColor: {
      'default': colors.canvas,
      ':hover': colors.gray100,
      ':active': colors.gray200,
      ':disabled': colors.gray100,
    },
    color: {
      'default': colors.gray900,
      ':disabled': colors.gray500,
    },
    cursor: {
      'default': 'pointer',
      ':disabled': 'not-allowed',
    },
    fontSize: 13,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.gray900}`,
    },
  },
  select: {
    minHeight: 32,
    borderColor: colors.gray200,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    paddingBlock: 4,
    paddingInline: 8,
    backgroundColor: colors.canvas,
    color: colors.gray900,
    fontSize: 13,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.gray900}`,
    },
  },
  status: {
    minHeight: 28,
    borderBottomColor: colors.gray200,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingBlock: 5,
    paddingInline: 12,
    backgroundColor: colors.blue50,
    color: colors.blue600,
    fontSize: 12,
  },
  statusError: {
    backgroundColor: colors.red50,
    color: colors.red700,
  },
})
