import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'rgb(0, 113, 227)',
  canvas: 'rgb(247, 248, 250)',
  canvasSolid: 'rgb(248, 248, 249)',
  focus: 'rgba(41, 97, 194, 0.85)',
  text: 'rgba(25, 27, 31, 0.9)',
  textMuted: 'rgba(48, 52, 59, 0.62)',
  textQuiet: 'rgba(48, 52, 59, 0.46)',
} as const

const loadingRotation = stylex.keyframes({
  to: { transform: 'rotate(360deg)' },
})

export const todoPageStyles = stylex.create({
  page: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    paddingTop: 56,
    backgroundColor: {
      'default': colors.canvas,
      '@media (prefers-reduced-transparency: reduce)': colors.canvasSolid,
      '@media (prefers-contrast: more)': 'rgb(252, 252, 253)',
    },
    color: colors.text,
    boxShadow: 'inset 0 1px rgba(255, 255, 255, 0.92)',
  },
  content: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    paddingTop: 10,
    paddingRight: 18,
    paddingBottom: 12,
    paddingLeft: 18,
  },
  titlebarViews: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    borderColor: 'rgba(72, 72, 74, 0.13)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    padding: 2,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.4)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 251, 253)',
      '@media (prefers-contrast: more)': 'rgb(248, 249, 251)',
    },
    backdropFilter: {
      'default': 'blur(28px) saturate(135%) brightness(1.02)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 4px 14px rgba(28, 28, 30, 0.08), 0 0 0 0.5px rgba(255, 255, 255, 0.58), inset 0 1px rgba(255, 255, 255, 0.9)',
  },
  titlebarViewOption: {
    display: 'grid',
    width: 28,
    height: 24,
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 7,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.56)',
      ':active': 'rgba(118, 118, 128, 0.12)',
    },
    color: colors.textMuted,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  titlebarViewOptionSelected: {
    backgroundColor: 'rgba(255, 255, 255, 0.74)',
    boxShadow: '0 1px 4px rgba(28, 28, 30, 0.12), 0 0 0 0.5px rgba(72, 72, 74, 0.08), inset 0 1px rgba(255, 255, 255, 0.96)',
    color: colors.text,
  },
  controls: {
    display: 'flex',
    minHeight: 42,
    flex: '0 0 auto',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    paddingRight: 8,
    paddingLeft: 8,
  },
  listTitle: {
    overflow: 'hidden',
    margin: 0,
    color: colors.text,
    fontSize: 14,
    fontWeight: 620,
    letterSpacing: 0,
    lineHeight: '20px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  count: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    margin: 0,
    color: colors.textMuted,
    fontSize: 12,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 500,
    lineHeight: '18px',
  },
  countLoadingIcon: {
    width: 13,
    height: 13,
  },
  listLayout: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
  },
  listSidebarMotion: {
    'position': 'relative',
    'zIndex': 5,
    'height': '100%',
    'minHeight': 0,
    'overflow': 'hidden',
    'flex': '0 0 auto',
    '@media (max-width: 980px)': {
      position: 'absolute',
      top: 0,
      bottom: 0,
      left: 0,
      boxShadow: '14px 0 34px rgba(31, 38, 48, 0.14)',
    },
  },
  listSidebarScrim: {
    'position': 'absolute',
    'zIndex': 4,
    'display': 'none',
    'inset': 0,
    'borderWidth': 0,
    'padding': 0,
    'backgroundColor': 'rgba(31, 35, 42, 0.08)',
    '@media (max-width: 980px)': {
      display: 'block',
    },
  },
  listMain: {
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flex: 1,
    flexDirection: 'column',
    paddingLeft: 14,
  },
  viewRegion: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flex: 1,
    backgroundColor: 'transparent',
  },
  status: {
    display: 'grid',
    width: '100%',
    height: 'clamp(240px, 52vh, 520px)',
    placeItems: 'center',
    color: colors.textMuted,
  },
  statusContent: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    gap: 8,
    fontSize: 13,
    fontWeight: 500,
    textAlign: 'center',
  },
  statusGlyph: {
    width: 22,
    height: 22,
    color: colors.textQuiet,
  },
  loadingIcon: {
    'animationDuration': '850ms',
    'animationIterationCount': 'infinite',
    'animationName': loadingRotation,
    'animationTimingFunction': 'linear',
    '@media (prefers-reduced-motion: reduce)': {
      animationName: 'none',
    },
  },
  errorIcon: {
    color: 'rgb(184, 83, 69)',
  },
  retryButton: {
    height: 28,
    borderColor: 'rgba(0, 100, 210, 0.25)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 14,
    paddingRight: 12,
    paddingLeft: 12,
    backgroundColor: 'rgba(0, 113, 227, 0.12)',
    color: colors.accent,
    cursor: 'default',
    fontSize: 12,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
})
