import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'rgb(0, 113, 227)',
  canvas: 'rgba(239, 243, 248, 0.88)',
  canvasSolid: 'rgb(244, 246, 249)',
  focus: 'rgba(41, 97, 194, 0.85)',
  glassBorder: 'rgba(255, 255, 255, 0.78)',
  separator: 'rgba(72, 77, 86, 0.12)',
  text: 'rgba(25, 27, 31, 0.9)',
  textMuted: 'rgba(48, 52, 59, 0.62)',
  textQuiet: 'rgba(48, 52, 59, 0.46)',
} as const

const loadingRotation = stylex.keyframes({
  to: { transform: 'rotate(360deg)' },
})

export const todoPageStyles = stylex.create({
  page: {
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    paddingTop: 56,
    backgroundColor: {
      'default': colors.canvas,
      '@media (prefers-reduced-transparency: reduce)': colors.canvasSolid,
      '@media (prefers-contrast: more)': 'rgb(248, 249, 251)',
    },
    backdropFilter: {
      'default': 'blur(24px) saturate(135%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    color: colors.text,
  },
  content: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    paddingTop: 10,
    paddingRight: 18,
    paddingBottom: 12,
    paddingLeft: 18,
  },
  titlebarView: {
    display: 'flex',
    height: 28,
    alignItems: 'center',
    gap: 6,
    borderColor: {
      'default': colors.glassBorder,
      '@media (prefers-reduced-transparency: reduce)': 'rgba(72, 77, 86, 0.18)',
      '@media (prefers-contrast: more)': 'rgba(35, 39, 46, 0.5)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    paddingRight: 9,
    paddingLeft: 8,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.52)',
      ':hover': 'rgba(255, 255, 255, 0.7)',
      ':active': 'rgba(225, 230, 238, 0.7)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 251, 253)',
      '@media (prefers-contrast: more)': 'rgb(248, 249, 251)',
    },
    backdropFilter: {
      'default': 'blur(18px) saturate(165%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 12,
    fontWeight: 550,
    outline: 'none',
    boxShadow: {
      'default': '0 3px 10px rgba(31, 38, 48, 0.1), inset 0 1px rgba(255, 255, 255, 0.9)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.97)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
    userSelect: 'none',
  },
  titlebarViews: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    borderColor: colors.glassBorder,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    padding: 2,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.42)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 251, 253)',
      '@media (prefers-contrast: more)': 'rgb(248, 249, 251)',
    },
    backdropFilter: {
      'default': 'blur(18px) saturate(165%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 3px 10px rgba(31, 38, 48, 0.1), inset 0 1px rgba(255, 255, 255, 0.9)',
  },
  titlebarViewOption: {
    display: 'grid',
    width: 28,
    height: 24,
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 7,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.58)',
      ':active': 'rgba(225, 230, 238, 0.72)',
    },
    color: colors.textMuted,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  titlebarViewOptionSelected: {
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    boxShadow: '0 1px 3px rgba(36, 42, 51, 0.12), inset 0 1px rgba(255, 255, 255, 0.95)',
    color: colors.text,
  },
  controls: {
    display: 'flex',
    minHeight: 42,
    flex: '0 0 auto',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    paddingRight: 8,
    paddingLeft: 8,
  },
  filterList: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    borderRadius: 10,
    padding: 2,
    backgroundColor: {
      'default': 'rgba(220, 225, 234, 0.52)',
      '@media (prefers-reduced-transparency: reduce)': 'rgba(218, 222, 229, 0.8)',
      '@media (prefers-contrast: more)': 'rgba(210, 215, 223, 0.92)',
    },
    boxShadow: 'inset 0 1px rgba(255, 255, 255, 0.55), inset 0 -1px rgba(72, 77, 86, 0.08)',
  },
  filter: {
    height: 26,
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.55)',
      ':active': 'rgba(255, 255, 255, 0.75)',
    },
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 12,
    fontWeight: 550,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.97)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  filterSelected: {
    borderColor: 'rgba(255, 255, 255, 0.86)',
    backgroundColor: 'rgba(255, 255, 255, 0.74)',
    boxShadow: '0 1px 3px rgba(36, 42, 51, 0.12), inset 0 1px rgba(255, 255, 255, 0.95)',
    color: colors.text,
  },
  count: {
    margin: 0,
    color: colors.textMuted,
    fontSize: 12,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 500,
    lineHeight: '18px',
  },
  listRegion: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    backdropFilter: {
      'default': 'blur(8px) saturate(120%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
  },
  listViewport: {
    width: '100%',
    minWidth: 0,
    minHeight: 0,
    overflowX: 'auto',
    overflowY: 'auto',
    overscrollBehavior: 'contain',
  },
  boardViewport: {
    width: '100%',
    minWidth: 0,
    minHeight: 0,
    overflowX: 'auto',
    overflowY: 'auto',
    padding: 14,
    overscrollBehavior: 'contain',
  },
  boardGrid: {
    display: 'grid',
    minWidth: 780,
    minHeight: '100%',
    gridTemplateColumns: 'repeat(3, minmax(240px, 1fr))',
    alignItems: 'start',
    gap: 14,
  },
  boardColumn: {
    display: 'flex',
    minHeight: 'clamp(300px, 78vh, 760px)',
    flexDirection: 'column',
    overflow: 'hidden',
    borderColor: {
      'default': colors.glassBorder,
      '@media (prefers-reduced-transparency: reduce)': 'rgba(72, 77, 86, 0.16)',
      '@media (prefers-contrast: more)': 'rgba(35, 39, 46, 0.42)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 12,
    backgroundColor: {
      'default': 'rgba(230, 235, 243, 0.62)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(238, 241, 246)',
      '@media (prefers-contrast: more)': 'rgb(245, 246, 248)',
    },
    backdropFilter: {
      'default': 'blur(26px) saturate(150%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': '0 12px 28px rgba(31, 38, 48, 0.1), 0 2px 6px rgba(31, 38, 48, 0.06), inset 0 1px rgba(255, 255, 255, 0.86), inset 1px 0 rgba(255, 255, 255, 0.42)',
      '@media (prefers-contrast: more)': '0 8px 20px rgba(31, 38, 48, 0.16), 0 0 0 1px rgba(35, 39, 46, 0.3), inset 0 1px rgba(255, 255, 255, 0.92)',
    },
  },
  boardColumnHeader: {
    display: 'flex',
    height: 42,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: 12,
    paddingLeft: 12,
    borderBottomColor: 'rgba(255, 255, 255, 0.48)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
  },
  boardColumnTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    color: colors.text,
    fontSize: 12,
    fontWeight: 650,
  },
  boardColumnCount: {
    minWidth: 22,
    height: 20,
    borderRadius: 10,
    paddingRight: 6,
    paddingLeft: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.38)',
    borderColor: 'rgba(255, 255, 255, 0.62)',
    borderStyle: 'solid',
    borderWidth: 1,
    color: colors.textMuted,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 600,
    lineHeight: '20px',
    textAlign: 'center',
  },
  boardColumnBody: {
    display: 'flex',
    minHeight: 168,
    flexDirection: 'column',
    gap: 8,
    padding: 10,
  },
  boardColumnEmpty: {
    margin: 'auto',
    padding: 24,
    color: colors.textQuiet,
    fontSize: 12,
    textAlign: 'center',
  },
  boardColumnLoading: {
    padding: 8,
    color: colors.textQuiet,
    fontSize: 11,
    textAlign: 'center',
  },
  boardCard: {
    display: 'flex',
    minHeight: 86,
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 6,
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.82)',
      '@media (prefers-reduced-transparency: reduce)': 'rgba(72, 77, 86, 0.14)',
      '@media (prefers-contrast: more)': 'rgba(35, 39, 46, 0.34)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.68)',
      ':hover': 'rgba(255, 255, 255, 0.82)',
      ':active': 'rgba(231, 235, 242, 0.78)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(255, 255, 255)',
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    backdropFilter: {
      'default': 'blur(16px) saturate(155%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    color: colors.text,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': '0 3px 9px rgba(36, 42, 51, 0.08), 0 1px 2px rgba(36, 42, 51, 0.05), inset 0 1px rgba(255, 255, 255, 0.82)',
      ':hover': '0 7px 16px rgba(36, 42, 51, 0.12), 0 2px 4px rgba(36, 42, 51, 0.06), inset 0 1px rgba(255, 255, 255, 0.94)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'translateY(0) scale(1)',
      ':hover': 'translateY(-1px) scale(1.002)',
      ':active': 'translateY(1px) scale(0.985)',
    },
    transitionDuration: {
      'default': '110ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  boardCardShell: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 3,
  },
  boardCardText: {
    overflow: 'hidden',
    fontSize: 13,
    fontWeight: 560,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  boardCardSource: {
    overflow: 'hidden',
    color: colors.textQuiet,
    fontSize: 11,
    lineHeight: '15px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  boardCardFooter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    color: colors.textMuted,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    lineHeight: '15px',
  },
  list: {
    position: 'relative',
    width: '100%',
    margin: 0,
    padding: 0,
    listStyle: 'none',
  },
  row: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: 58,
    borderBottomColor: colors.separator,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
  },
  rowShell: {
    display: 'flex',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    gap: 4,
  },
  rowButton: {
    display: 'grid',
    width: 'auto',
    height: '100%',
    flex: 1,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '28px minmax(0, 1fr) auto',
    gap: 10,
    borderWidth: 0,
    borderRadius: 8,
    paddingRight: 14,
    paddingLeft: 12,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(70, 79, 93, 0.055)',
      ':active': 'rgba(70, 79, 93, 0.095)',
    },
    color: colors.text,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `inset 0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.995)',
    },
    transitionDuration: {
      'default': '90ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  statusIcon: {
    width: 19,
    height: 19,
    justifySelf: 'center',
    color: colors.textQuiet,
  },
  statusDoing: {
    color: 'rgb(214, 127, 16)',
  },
  statusDone: {
    color: 'rgb(42, 145, 87)',
  },
  taskContent: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    gap: 3,
  },
  taskText: {
    overflow: 'hidden',
    color: colors.text,
    fontSize: 13,
    fontWeight: 540,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  taskDone: {
    color: colors.textMuted,
    textDecorationLine: 'line-through',
  },
  source: {
    overflow: 'hidden',
    color: colors.textQuiet,
    fontSize: 11,
    fontWeight: 450,
    lineHeight: '15px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  elapsed: {
    minWidth: 52,
    color: colors.textMuted,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 550,
    lineHeight: '16px',
    textAlign: 'right',
    whiteSpace: 'nowrap',
  },
  status: {
    display: 'grid',
    height: 'clamp(240px, 52vh, 520px)',
    placeItems: 'center',
    color: colors.textMuted,
  },
  statusContent: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    gap: 8,
    fontSize: 13,
    fontWeight: 500,
    textAlign: 'center',
  },
  statusGlyph: {
    width: 22,
    height: 22,
    color: colors.textQuiet,
  },
  loadingIcon: {
    'animationDuration': '850ms',
    'animationIterationCount': 'infinite',
    'animationName': loadingRotation,
    'animationTimingFunction': 'linear',
    '@media (prefers-reduced-motion: reduce)': {
      animationName: 'none',
    },
  },
  errorIcon: {
    color: 'rgb(184, 83, 69)',
  },
  retryButton: {
    height: 28,
    borderColor: 'rgba(0, 100, 210, 0.25)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 14,
    paddingRight: 12,
    paddingLeft: 12,
    backgroundColor: 'rgba(0, 113, 227, 0.12)',
    color: colors.accent,
    cursor: 'default',
    fontSize: 12,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  loadingMore: {
    display: 'flex',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    color: colors.textQuiet,
    fontSize: 11,
    fontWeight: 500,
  },
  loadingMoreIcon: {
    width: 14,
    height: 14,
  },
})
