import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'rgb(0, 113, 227)',
  border: 'rgba(72, 72, 74, 0.12)',
  panelSolid: 'rgb(250, 250, 251)',
  text: 'rgba(25, 27, 31, 0.9)',
  textMuted: 'rgba(48, 52, 59, 0.62)',
  textQuiet: 'rgba(48, 52, 59, 0.46)',
} as const

export const todoPlanningStyles = stylex.create({
  planningRoot: {
    display: 'flex',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    gap: 12,
    overflow: 'auto',
    padding: 14,
    boxSizing: 'border-box',
  },
  planningToolbar: {
    display: 'flex',
    minHeight: 32,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  planningToolbarTitle: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'baseline',
    gap: 8,
  },
  planningTitle: {
    overflow: 'hidden',
    color: colors.text,
    fontSize: 15,
    fontWeight: 650,
    lineHeight: '20px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  planningSubtitle: {
    overflow: 'hidden',
    color: colors.textQuiet,
    fontSize: 11,
    lineHeight: '16px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  planningToolbarActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  planningPeriodControl: {
    display: 'flex',
    height: 30,
    alignItems: 'center',
    gap: 2,
    borderColor: colors.border,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    paddingRight: 3,
    paddingLeft: 3,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.42)',
      '@media (prefers-reduced-transparency: reduce)': colors.panelSolid,
      '@media (prefers-contrast: more)': 'rgb(248, 249, 251)',
    },
    backdropFilter: {
      'default': 'blur(28px) saturate(130%) brightness(1.02)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 4px 14px rgba(28, 28, 30, 0.075), 0 0 0 0.5px rgba(255, 255, 255, 0.58), inset 0 1px rgba(255, 255, 255, 0.9)',
  },
  planningIconButton: {
    display: 'grid',
    width: 26,
    height: 26,
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 7,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.62)',
      ':active': 'rgba(118, 118, 128, 0.12)',
      ':disabled': 'transparent',
    },
    color: {
      'default': colors.textMuted,
      ':disabled': colors.textQuiet,
    },
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgba(41, 97, 194, 0.85)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  planningTodayButton: {
    height: 26,
    borderColor: 'rgba(72, 72, 74, 0.1)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 7,
    paddingRight: 9,
    paddingLeft: 9,
    backgroundColor: 'rgba(255, 255, 255, 0.58)',
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': '0 1px 4px rgba(28, 28, 30, 0.1), 0 0 0 0.5px rgba(255, 255, 255, 0.6), inset 0 1px rgba(255, 255, 255, 0.94)',
      ':focus-visible': '0 0 0 2px rgba(41, 97, 194, 0.85)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.97)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  planningPeriodLabel: {
    minWidth: 116,
    paddingRight: 6,
    paddingLeft: 6,
    color: colors.text,
    fontSize: 12,
    fontWeight: 650,
    lineHeight: '20px',
    textAlign: 'center',
    whiteSpace: 'nowrap',
  },
  timelineViewport: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    gap: 14,
    overflow: 'auto',
    padding: 4,
  },
  timelineGroup: {
    position: 'relative',
    display: 'grid',
    minWidth: 620,
    gridTemplateColumns: '132px minmax(0, 1fr)',
    gap: 18,
    paddingBottom: 4,
  },
  timelineDate: {
    position: 'relative',
    display: 'flex',
    minHeight: 64,
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: 2,
    paddingTop: 4,
    paddingRight: 18,
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: 600,
    textAlign: 'right',
  },
  timelineDateNumber: {
    color: colors.text,
    fontSize: 18,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 650,
    lineHeight: '22px',
  },
  timelineDateToday: {
    color: colors.accent,
  },
  timelineRail: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: 1,
    backgroundColor: 'rgba(72, 72, 74, 0.11)',
  },
  timelineDot: {
    position: 'absolute',
    top: 8,
    right: -4,
    zIndex: 1,
    width: 9,
    height: 9,
    borderColor: 'rgba(255, 255, 255, 0.92)',
    borderStyle: 'solid',
    borderWidth: 2,
    borderRadius: 6,
    backgroundColor: colors.accent,
    boxShadow: '0 2px 5px rgba(0, 90, 180, 0.26)',
  },
  timelineItems: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    gap: 7,
  },
  planningTask: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    minHeight: 62,
    alignItems: 'center',
    gap: 10,
    borderColor: {
      'default': 'rgba(72, 72, 74, 0.12)',
      '@media (prefers-reduced-transparency: reduce)': 'rgba(72, 72, 74, 0.16)',
      '@media (prefers-contrast: more)': 'rgba(35, 35, 37, 0.4)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    boxSizing: 'border-box',
    paddingTop: 9,
    paddingRight: 44,
    paddingBottom: 9,
    paddingLeft: 9,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.78)',
      ':hover': 'rgba(255, 255, 255, 0.94)',
      ':active': 'rgba(118, 118, 128, 0.1)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(255, 255, 255)',
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    color: colors.text,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': '0 2px 7px rgba(28, 28, 30, 0.07), 0 0 0 0.5px rgba(255, 255, 255, 0.7), inset 0 1px rgba(255, 255, 255, 0.92)',
      ':hover': '0 6px 16px rgba(28, 28, 30, 0.1), 0 0 0 0.5px rgba(255, 255, 255, 0.8), inset 0 1px rgba(255, 255, 255, 0.98)',
      ':focus-visible': '0 0 0 2px rgba(41, 97, 194, 0.85)',
    },
    transform: {
      'default': 'translateY(0) scale(1)',
      ':hover': 'translateY(-1px) scale(1.002)',
      ':active': 'translateY(1px) scale(0.985)',
    },
    transitionDuration: {
      'default': '110ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
    contentVisibility: 'auto',
    containIntrinsicSize: '62px',
  },
  planningTaskShell: {
    position: 'relative',
    width: '100%',
    minWidth: 0,
  },
  planningTaskActions: {
    position: 'absolute',
    top: '50%',
    right: 6,
    transform: 'translateY(-50%)',
  },
  planningTaskIcon: {
    width: 18,
    height: 18,
    flex: '0 0 18px',
    color: colors.textQuiet,
  },
  planningTaskDoing: {
    color: 'rgb(214, 127, 16)',
  },
  planningTaskDoneIcon: {
    color: 'rgb(42, 145, 87)',
  },
  planningTaskContent: {
    display: 'flex',
    minWidth: 0,
    flex: 1,
    flexDirection: 'column',
    gap: 3,
  },
  planningTaskTitle: {
    overflow: 'hidden',
    color: colors.text,
    fontSize: 12,
    fontWeight: 600,
    lineHeight: '17px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  planningTaskMeta: {
    overflow: 'hidden',
    color: colors.textQuiet,
    fontSize: 10,
    lineHeight: '14px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  planningTaskElapsed: {
    flex: '0 0 auto',
    color: colors.textMuted,
    fontSize: 10,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 600,
    lineHeight: '15px',
    whiteSpace: 'nowrap',
  },
  planningTaskDone: {
    color: colors.textMuted,
    textDecorationLine: 'line-through',
  },
  planningEmpty: {
    display: 'grid',
    minHeight: 180,
    placeItems: 'center',
    color: colors.textQuiet,
    fontSize: 12,
    textAlign: 'center',
  },
  timelineUnscheduled: {
    display: 'grid',
    minWidth: 620,
    gridTemplateColumns: '132px minmax(0, 1fr)',
    gap: 18,
    borderTopColor: 'rgba(72, 72, 74, 0.1)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 14,
  },
  timelineUnscheduledLabel: {
    paddingRight: 18,
    color: colors.textQuiet,
    fontSize: 11,
    fontWeight: 600,
    textAlign: 'right',
  },
  calendarToolbar: {
    display: 'flex',
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
  },
  calendarMonthTitle: {
    minWidth: 0,
    overflow: 'hidden',
    margin: 0,
    color: 'rgba(20, 20, 22, 0.94)',
    fontSize: 26,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: '32px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  calendarNavigationControl: {
    display: 'flex',
    height: 30,
    alignItems: 'center',
    gap: 1,
    borderColor: 'rgba(72, 72, 74, 0.12)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    paddingRight: 2,
    paddingLeft: 2,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.5)',
      '@media (prefers-reduced-transparency: reduce)': colors.panelSolid,
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    backdropFilter: {
      'default': 'blur(28px) saturate(135%) brightness(1.02)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 4px 14px rgba(28, 28, 30, 0.075), 0 0 0 0.5px rgba(255, 255, 255, 0.58), inset 0 1px rgba(255, 255, 255, 0.92)',
  },
  calendarTodayButton: {
    height: 24,
    borderWidth: 0,
    borderRadius: 6,
    paddingRight: 9,
    paddingLeft: 9,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.64)',
      ':active': 'rgba(118, 118, 128, 0.12)',
    },
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgba(41, 97, 194, 0.85)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.97)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  calendarLayout: {
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
  },
  calendarSurface: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflow: 'visible',
  },
  calendarRoot: {
    display: 'flex',
    width: '100%',
    height: '100%',
    minHeight: 0,
    flexDirection: 'column',
    color: colors.text,
    fontFamily: 'inherit',
  },
  calendarGrid: {
    display: 'grid',
    minHeight: 510,
    flex: 1,
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    gridTemplateRows: 'repeat(6, minmax(82px, 1fr))',
    gap: 1,
    overflow: 'visible',
    backgroundColor: 'rgba(72, 72, 74, 0.105)',
    boxShadow: '0 0 0 0.5px rgba(72, 72, 74, 0.1)',
  },
  calendarWeekdays: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    borderBottomColor: 'rgba(72, 72, 74, 0.12)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
  },
  calendarWeekday: {
    minWidth: 0,
    paddingTop: 4,
    paddingRight: 9,
    paddingBottom: 7,
    color: colors.textQuiet,
    fontSize: 10,
    fontWeight: 650,
    lineHeight: '15px',
    textAlign: 'right',
  },
  calendarCell: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 82,
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 3,
    paddingTop: 5,
    paddingRight: 5,
    paddingBottom: 5,
    paddingLeft: 5,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.72)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(255, 255, 255)',
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    zIndex: {
      'default': 0,
      ':focus-within': 3,
    },
  },
  calendarCellNeighbor: {
    backgroundColor: 'rgba(247, 247, 248, 0.72)',
  },
  calendarDayButton: {
    display: 'grid',
    width: 24,
    height: 24,
    flex: '0 0 auto',
    alignSelf: 'flex-end',
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 12,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(118, 118, 128, 0.1)',
      ':active': 'rgba(118, 118, 128, 0.16)',
    },
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 650,
    lineHeight: '24px',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgba(41, 97, 194, 0.85)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  calendarDayButtonNeighbor: {
    color: 'rgba(48, 52, 59, 0.34)',
  },
  calendarDayButtonSelected: {
    backgroundColor: 'rgba(118, 118, 128, 0.14)',
    color: colors.text,
  },
  calendarDayButtonToday: {
    backgroundColor: 'rgb(255, 59, 48)',
    color: 'rgb(255, 255, 255)',
    boxShadow: '0 1px 4px rgba(184, 28, 21, 0.2)',
  },
  calendarTaskList: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    gap: 2,
    overflow: 'visible',
  },
  calendarTaskShell: {
    position: 'relative',
    minWidth: 0,
    height: 20,
  },
  calendarTaskButton: {
    display: 'flex',
    width: '100%',
    height: 20,
    minWidth: 0,
    alignItems: 'center',
    gap: 5,
    overflow: 'hidden',
    borderWidth: 0,
    borderRadius: 4,
    paddingTop: 0,
    paddingRight: 20,
    paddingBottom: 0,
    paddingLeft: 5,
    backgroundColor: {
      'default': 'rgba(0, 122, 255, 0.09)',
      ':hover': 'rgba(0, 122, 255, 0.14)',
      ':active': 'rgba(0, 122, 255, 0.18)',
    },
    color: 'rgba(18, 64, 111, 0.88)',
    cursor: 'default',
    fontSize: 10,
    fontWeight: 550,
    lineHeight: '20px',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgba(41, 97, 194, 0.85)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow',
    transitionTimingFunction: 'ease-out',
  },
  calendarTaskStatus: {
    width: 6,
    height: 6,
    flex: '0 0 auto',
    borderRadius: 3,
    backgroundColor: 'rgb(0, 122, 255)',
  },
  calendarTaskStatusDoing: {
    backgroundColor: 'rgb(255, 159, 10)',
  },
  calendarTaskStatusDone: {
    backgroundColor: 'rgb(52, 199, 89)',
  },
  calendarTaskText: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  calendarTaskTextDone: {
    opacity: 0.58,
    textDecoration: 'line-through',
  },
  calendarTaskActions: {
    position: 'absolute',
    top: 0,
    right: 1,
    zIndex: 2,
    display: 'grid',
    width: 18,
    height: 20,
    placeItems: 'center',
    opacity: {
      'default': 0.42,
      ':hover': 1,
      ':focus-within': 1,
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'opacity',
    transitionTimingFunction: 'ease-out',
  },
  calendarEventPreview: {
    display: 'flex',
    height: 20,
    minWidth: 0,
    alignItems: 'center',
    gap: 4,
    overflow: 'hidden',
    borderRadius: 4,
    paddingRight: 5,
    paddingLeft: 5,
    backgroundColor: 'rgba(255, 59, 48, 0.09)',
    color: 'rgba(111, 29, 25, 0.9)',
    fontSize: 10,
    fontWeight: 550,
    lineHeight: '20px',
  },
  calendarEventAccent: {
    width: 3,
    height: 12,
    flex: '0 0 auto',
    borderRadius: 2,
    backgroundColor: 'rgb(255, 59, 48)',
  },
  calendarEventText: {
    minWidth: 0,
    overflow: 'hidden',
    flex: 1,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  calendarEventSource: {
    display: {
      'default': 'block',
      '@media (max-width: 1050px)': 'none',
    },
    maxWidth: '42%',
    overflow: 'hidden',
    flex: '0 1 auto',
    color: 'rgba(111, 29, 25, 0.52)',
    fontSize: 9,
    fontWeight: 500,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  calendarOverflow: {
    position: 'relative',
    minWidth: 0,
  },
  calendarTaskMore: {
    width: 'fit-content',
    overflow: 'hidden',
    paddingRight: 3,
    paddingLeft: 3,
    color: colors.textQuiet,
    cursor: 'default',
    fontSize: 9,
    lineHeight: '15px',
    listStyle: 'none',
    outline: 'none',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  calendarOverflowPopover: {
    position: 'absolute',
    top: 19,
    left: '50%',
    zIndex: 8,
    display: 'flex',
    width: 260,
    maxHeight: 300,
    boxSizing: 'border-box',
    flexDirection: 'column',
    gap: 7,
    overflow: 'auto',
    borderColor: 'rgba(255, 255, 255, 0.82)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    padding: 9,
    backgroundColor: {
      'default': 'rgba(246, 247, 249, 0.9)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 250, 251)',
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    backdropFilter: {
      'default': 'blur(24px) saturate(145%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 14px 32px rgba(28, 28, 30, 0.18), 0 0 0 0.5px rgba(72, 72, 74, 0.08), inset 0 1px rgba(255, 255, 255, 0.92)',
    transform: 'translateX(-50%)',
  },
  calendarOverflowTitle: {
    color: colors.text,
    fontSize: 11,
    fontWeight: 650,
    lineHeight: '16px',
  },
  calendarOverflowList: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    gap: 3,
  },
  quadrantGrid: {
    display: 'grid',
    minWidth: 820,
    minHeight: 0,
    flex: 1,
    gridTemplateColumns: 'repeat(2, minmax(320px, 1fr))',
    gridTemplateRows: 'repeat(2, minmax(220px, 1fr))',
    gap: 1,
    overflow: 'hidden',
    borderColor: {
      'default': 'rgba(72, 72, 74, 0.1)',
      '@media (prefers-reduced-transparency: reduce)': 'rgba(72, 72, 74, 0.14)',
      '@media (prefers-contrast: more)': 'rgba(35, 35, 37, 0.42)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: 'rgba(72, 72, 74, 0.095)',
    boxShadow: {
      'default': '0 2px 8px rgba(28, 28, 30, 0.035), 0 0 0 0.5px rgba(255, 255, 255, 0.58), inset 0 1px rgba(255, 255, 255, 0.74)',
      '@media (prefers-contrast: more)': '0 0 0 1px rgba(35, 35, 37, 0.22)',
    },
  },
  quadrantPanel: {
    display: 'flex',
    minHeight: 0,
    flexDirection: 'column',
    overflow: 'hidden',
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.34)',
      '@media (prefers-reduced-transparency: reduce)': colors.panelSolid,
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
  },
  quadrantHeader: {
    display: 'flex',
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingTop: 8,
    paddingRight: 14,
    paddingBottom: 6,
    paddingLeft: 14,
  },
  quadrantTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    color: colors.text,
    fontSize: 13,
    fontWeight: 650,
    lineHeight: '18px',
  },
  quadrantSignal: {
    width: 6,
    height: 6,
    flex: '0 0 6px',
    borderRadius: 3,
    backgroundColor: 'rgb(255, 59, 48)',
    boxShadow: '0 1px 3px rgba(184, 28, 21, 0.22)',
  },
  quadrantSignalImportant: {
    backgroundColor: 'rgb(255, 149, 0)',
    boxShadow: '0 1px 3px rgba(180, 96, 0, 0.2)',
  },
  quadrantSignalUrgent: {
    backgroundColor: 'rgb(0, 122, 255)',
    boxShadow: '0 1px 3px rgba(0, 84, 180, 0.2)',
  },
  quadrantSignalQuiet: {
    backgroundColor: 'rgba(72, 77, 86, 0.3)',
    boxShadow: 'none',
  },
  quadrantCount: {
    minWidth: 16,
    color: colors.textQuiet,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 600,
    lineHeight: '16px',
    textAlign: 'right',
  },
  quadrantBody: {
    display: 'flex',
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    gap: 8,
    overflow: 'auto',
    paddingTop: 4,
    paddingRight: 12,
    paddingBottom: 12,
    paddingLeft: 12,
  },
  quadrantEmpty: {
    display: 'grid',
    minHeight: 90,
    flex: 1,
    placeItems: 'center',
    color: colors.textQuiet,
    fontSize: 11,
  },
  quadrantRule: {
    color: colors.textQuiet,
    fontSize: 10,
    lineHeight: '14px',
  },
})
