import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'rgb(0, 113, 227)',
  focus: 'rgba(41, 97, 194, 0.85)',
  text: 'rgba(25, 27, 31, 0.9)',
  textMuted: 'rgba(48, 52, 59, 0.62)',
  textQuiet: 'rgba(48, 52, 59, 0.44)',
} as const

export const todoListSidebarStyles = stylex.create({
  root: {
    width: 224,
    height: '100%',
    minHeight: 0,
    overflowX: 'hidden',
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    borderRightColor: 'rgba(72, 72, 74, 0.1)',
    borderRightStyle: 'solid',
    borderRightWidth: 1,
    paddingTop: 7,
    paddingRight: 10,
    paddingBottom: 18,
    paddingLeft: 6,
    backgroundColor: {
      'default': 'rgba(242, 243, 246, 0.64)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(244, 245, 247)',
      '@media (prefers-contrast: more)': 'rgb(248, 249, 251)',
    },
  },
  section: {
    marginBottom: 15,
  },
  sectionHeader: {
    display: 'flex',
    width: '100%',
    height: 26,
    alignItems: 'center',
    justifyContent: 'space-between',
    margin: 0,
    borderWidth: 0,
    paddingRight: 7,
    paddingLeft: 9,
    backgroundColor: 'transparent',
    color: colors.textQuiet,
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '16px',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `inset 0 0 0 2px ${colors.focus}`,
    },
  },
  sectionHeaderInteractive: {
    cursor: 'pointer',
    borderRadius: 7,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(76, 84, 96, 0.06)',
      ':active': 'rgba(76, 84, 96, 0.12)',
    },
  },
  disclosure: {
    width: 14,
    height: 14,
    color: colors.textQuiet,
    transform: 'rotate(0deg)',
    transitionDuration: {
      'default': '160ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'transform',
    transitionTimingFunction: 'ease-out',
  },
  disclosureCollapsed: {
    transform: 'rotate(-90deg)',
  },
  list: {
    display: 'flex',
    margin: 0,
    padding: 0,
    flexDirection: 'column',
    gap: 2,
    listStyle: 'none',
  },
  item: {
    display: 'grid',
    width: '100%',
    height: 32,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '19px minmax(0, 1fr) auto',
    gap: 7,
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 9,
    paddingLeft: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(76, 84, 96, 0.07)',
      ':active': 'rgba(76, 84, 96, 0.14)',
    },
    color: colors.text,
    cursor: 'default',
    fontSize: 13,
    fontWeight: 450,
    letterSpacing: 0,
    lineHeight: '18px',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.985)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  itemActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.76)',
    color: colors.text,
    fontWeight: 560,
    boxShadow: '0 1px 4px rgba(28, 28, 30, 0.09), 0 0 0 0.5px rgba(72, 72, 74, 0.06), inset 0 1px rgba(255, 255, 255, 0.9)',
  },
  icon: {
    display: 'grid',
    width: 17,
    height: 17,
    placeItems: 'center',
    color: colors.textMuted,
  },
  iconActive: {
    color: colors.accent,
  },
  label: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  count: {
    minWidth: 18,
    color: colors.textQuiet,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 500,
    textAlign: 'right',
  },
  empty: {
    minHeight: 30,
    margin: 0,
    paddingRight: 9,
    paddingLeft: 35,
    color: colors.textQuiet,
    fontSize: 11,
    lineHeight: '30px',
  },
})
