import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'rgb(0, 113, 227)',
  border: 'rgba(255, 255, 255, 0.78)',
  panel: 'rgba(230, 235, 243, 0.58)',
  panelSolid: 'rgb(242, 244, 248)',
  text: 'rgba(25, 27, 31, 0.9)',
  textMuted: 'rgba(48, 52, 59, 0.62)',
  textQuiet: 'rgba(48, 52, 59, 0.46)',
} as const

export const todoPlanningStyles = stylex.create({
  planningRoot: {
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    gap: 12,
    overflow: 'auto',
    padding: 14,
  },
  planningToolbar: {
    display: 'flex',
    minHeight: 32,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  planningToolbarTitle: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'baseline',
    gap: 8,
  },
  planningTitle: {
    overflow: 'hidden',
    color: colors.text,
    fontSize: 15,
    fontWeight: 650,
    lineHeight: '20px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  planningSubtitle: {
    overflow: 'hidden',
    color: colors.textQuiet,
    fontSize: 11,
    lineHeight: '16px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  planningToolbarActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  planningPeriodControl: {
    display: 'flex',
    height: 30,
    alignItems: 'center',
    gap: 2,
    borderColor: colors.border,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    paddingRight: 3,
    paddingLeft: 3,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.46)',
      '@media (prefers-reduced-transparency: reduce)': colors.panelSolid,
      '@media (prefers-contrast: more)': 'rgb(248, 249, 251)',
    },
    backdropFilter: {
      'default': 'blur(18px) saturate(150%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 3px 10px rgba(31, 38, 48, 0.08), inset 0 1px rgba(255, 255, 255, 0.9)',
  },
  planningIconButton: {
    display: 'grid',
    width: 26,
    height: 26,
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 7,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.62)',
      ':active': 'rgba(225, 230, 238, 0.78)',
      ':disabled': 'transparent',
    },
    color: {
      'default': colors.textMuted,
      ':disabled': colors.textQuiet,
    },
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgba(41, 97, 194, 0.85)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  planningTodayButton: {
    height: 26,
    borderColor: 'rgba(255, 255, 255, 0.82)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 7,
    paddingRight: 9,
    paddingLeft: 9,
    backgroundColor: 'rgba(255, 255, 255, 0.62)',
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': '0 1px 3px rgba(36, 42, 51, 0.1), inset 0 1px rgba(255, 255, 255, 0.92)',
      ':focus-visible': '0 0 0 2px rgba(41, 97, 194, 0.85)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.97)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  planningPeriodLabel: {
    minWidth: 116,
    paddingRight: 6,
    paddingLeft: 6,
    color: colors.text,
    fontSize: 12,
    fontWeight: 650,
    lineHeight: '20px',
    textAlign: 'center',
    whiteSpace: 'nowrap',
  },
  timelineViewport: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    gap: 14,
    overflow: 'auto',
    padding: 4,
  },
  timelineGroup: {
    position: 'relative',
    display: 'grid',
    minWidth: 620,
    gridTemplateColumns: '132px minmax(0, 1fr)',
    gap: 18,
    paddingBottom: 4,
  },
  timelineDate: {
    position: 'relative',
    display: 'flex',
    minHeight: 64,
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: 2,
    paddingTop: 4,
    paddingRight: 18,
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: 600,
    textAlign: 'right',
  },
  timelineDateNumber: {
    color: colors.text,
    fontSize: 18,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 650,
    lineHeight: '22px',
  },
  timelineDateToday: {
    color: colors.accent,
  },
  timelineRail: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.78)',
    boxShadow: '1px 0 rgba(72, 77, 86, 0.08)',
  },
  timelineDot: {
    position: 'absolute',
    top: 8,
    right: -4,
    zIndex: 1,
    width: 9,
    height: 9,
    borderColor: 'rgba(255, 255, 255, 0.92)',
    borderStyle: 'solid',
    borderWidth: 2,
    borderRadius: 6,
    backgroundColor: colors.accent,
    boxShadow: '0 2px 5px rgba(0, 90, 180, 0.26)',
  },
  timelineItems: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    gap: 7,
  },
  planningTask: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    minHeight: 62,
    alignItems: 'center',
    gap: 10,
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.8)',
      '@media (prefers-reduced-transparency: reduce)': 'rgba(72, 77, 86, 0.16)',
      '@media (prefers-contrast: more)': 'rgba(35, 39, 46, 0.4)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    padding: 9,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.66)',
      ':hover': 'rgba(255, 255, 255, 0.82)',
      ':active': 'rgba(231, 235, 242, 0.78)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(255, 255, 255)',
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    backdropFilter: {
      'default': 'blur(15px) saturate(150%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    color: colors.text,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': '0 3px 9px rgba(36, 42, 51, 0.08), inset 0 1px rgba(255, 255, 255, 0.86)',
      ':hover': '0 7px 16px rgba(36, 42, 51, 0.12), inset 0 1px rgba(255, 255, 255, 0.94)',
      ':focus-visible': '0 0 0 2px rgba(41, 97, 194, 0.85)',
    },
    transform: {
      'default': 'translateY(0) scale(1)',
      ':hover': 'translateY(-1px) scale(1.002)',
      ':active': 'translateY(1px) scale(0.985)',
    },
    transitionDuration: {
      'default': '110ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
    contentVisibility: 'auto',
    containIntrinsicSize: '62px',
  },
  planningTaskShell: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 3,
  },
  planningTaskIcon: {
    width: 18,
    height: 18,
    flex: '0 0 18px',
    color: colors.textQuiet,
  },
  planningTaskDoing: {
    color: 'rgb(214, 127, 16)',
  },
  planningTaskDoneIcon: {
    color: 'rgb(42, 145, 87)',
  },
  planningTaskContent: {
    display: 'flex',
    minWidth: 0,
    flex: 1,
    flexDirection: 'column',
    gap: 3,
  },
  planningTaskTitle: {
    overflow: 'hidden',
    color: colors.text,
    fontSize: 12,
    fontWeight: 600,
    lineHeight: '17px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  planningTaskMeta: {
    overflow: 'hidden',
    color: colors.textQuiet,
    fontSize: 10,
    lineHeight: '14px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  planningTaskElapsed: {
    flex: '0 0 auto',
    color: colors.textMuted,
    fontSize: 10,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 600,
    lineHeight: '15px',
    whiteSpace: 'nowrap',
  },
  planningTaskDone: {
    color: colors.textMuted,
    textDecorationLine: 'line-through',
  },
  planningEmpty: {
    display: 'grid',
    minHeight: 180,
    placeItems: 'center',
    color: colors.textQuiet,
    fontSize: 12,
    textAlign: 'center',
  },
  timelineUnscheduled: {
    display: 'grid',
    minWidth: 620,
    gridTemplateColumns: '132px minmax(0, 1fr)',
    gap: 18,
    borderTopColor: 'rgba(255, 255, 255, 0.68)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 14,
  },
  timelineUnscheduledLabel: {
    paddingRight: 18,
    color: colors.textQuiet,
    fontSize: 11,
    fontWeight: 600,
    textAlign: 'right',
  },
  calendarLayout: {
    display: 'grid',
    minWidth: 900,
    minHeight: 0,
    flex: 1,
    gridTemplateColumns: 'minmax(0, 1fr) 286px',
    gap: 14,
  },
  calendarSurface: {
    minWidth: 0,
    overflow: 'hidden',
    borderColor: colors.border,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 12,
    padding: 10,
    backgroundColor: {
      'default': colors.panel,
      '@media (prefers-reduced-transparency: reduce)': colors.panelSolid,
      '@media (prefers-contrast: more)': 'rgb(245, 246, 248)',
    },
    backdropFilter: {
      'default': 'blur(25px) saturate(145%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 10px 24px rgba(31, 38, 48, 0.08), inset 0 1px rgba(255, 255, 255, 0.88)',
  },
  calendarRoot: {
    width: '100%',
    height: '100%',
    color: colors.text,
    fontFamily: 'inherit',
  },
  calendarGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    gridTemplateRows: 'repeat(6, minmax(0, 1fr))',
    gap: 4,
  },
  calendarWeekdays: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    gap: 4,
    marginBottom: 4,
  },
  calendarWeekday: {
    paddingTop: 3,
    paddingBottom: 5,
    color: colors.textQuiet,
    fontSize: 10,
    fontWeight: 650,
    textAlign: 'center',
  },
  calendarTile: {
    display: 'flex',
    height: 112,
    minWidth: 0,
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 5,
    overflow: 'hidden',
    borderColor: 'rgba(255, 255, 255, 0.62)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    padding: 7,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.25)',
      ':hover': 'rgba(255, 255, 255, 0.48)',
      ':active': 'rgba(225, 230, 238, 0.64)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 251, 253)',
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    color: colors.text,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgba(41, 97, 194, 0.85)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow',
    transitionTimingFunction: 'ease-out',
  },
  calendarTileNeighbor: {
    opacity: 0.48,
  },
  calendarTileToday: {
    borderColor: 'rgba(0, 113, 227, 0.42)',
    boxShadow: 'inset 0 1px rgba(255, 255, 255, 0.9), 0 0 0 1px rgba(0, 113, 227, 0.08)',
  },
  calendarTileSelected: {
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    borderColor: 'rgba(255, 255, 255, 0.96)',
    boxShadow: '0 5px 12px rgba(36, 42, 51, 0.1), inset 0 1px rgba(255, 255, 255, 0.96)',
  },
  calendarDayNumber: {
    color: colors.textMuted,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 650,
    lineHeight: '15px',
  },
  calendarDayNumberToday: {
    color: colors.accent,
  },
  calendarTaskList: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    gap: 2,
    overflow: 'hidden',
  },
  calendarTaskPreview: {
    overflow: 'hidden',
    borderRadius: 4,
    paddingRight: 4,
    paddingLeft: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.46)',
    color: colors.textMuted,
    fontSize: 10,
    lineHeight: '16px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  calendarEventPreview: {
    overflow: 'hidden',
    borderRadius: 4,
    paddingRight: 4,
    paddingLeft: 4,
    backgroundColor: 'rgba(0, 113, 227, 0.12)',
    color: 'rgb(0, 94, 190)',
    fontSize: 10,
    lineHeight: '16px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  calendarTaskMore: {
    color: colors.textQuiet,
    fontSize: 9,
    lineHeight: '13px',
  },
  calendarDetails: {
    display: 'flex',
    minHeight: 0,
    flexDirection: 'column',
    overflow: 'hidden',
    borderColor: colors.border,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 12,
    backgroundColor: {
      'default': 'rgba(230, 235, 243, 0.52)',
      '@media (prefers-reduced-transparency: reduce)': colors.panelSolid,
      '@media (prefers-contrast: more)': 'rgb(245, 246, 248)',
    },
    backdropFilter: {
      'default': 'blur(24px) saturate(145%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 10px 24px rgba(31, 38, 48, 0.08), inset 0 1px rgba(255, 255, 255, 0.86)',
  },
  calendarDetailsHeader: {
    display: 'flex',
    minHeight: 58,
    flexDirection: 'column',
    justifyContent: 'center',
    gap: 3,
    borderBottomColor: 'rgba(255, 255, 255, 0.58)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingRight: 14,
    paddingLeft: 14,
  },
  calendarDetailsTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: 650,
    lineHeight: '18px',
  },
  calendarDetailsCount: {
    color: colors.textQuiet,
    fontSize: 10,
    lineHeight: '14px',
  },
  calendarDetailsList: {
    display: 'flex',
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    gap: 7,
    overflow: 'auto',
    padding: 10,
  },
  calendarEventDetail: {
    display: 'flex',
    minHeight: 46,
    flexDirection: 'column',
    justifyContent: 'center',
    gap: 3,
    borderColor: 'rgba(255, 255, 255, 0.72)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 9,
    paddingLeft: 9,
    backgroundColor: 'rgba(0, 113, 227, 0.09)',
  },
  calendarEventTitle: {
    overflow: 'hidden',
    color: 'rgba(25, 27, 31, 0.88)',
    fontSize: 11,
    fontWeight: 600,
    lineHeight: '15px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  calendarEventSource: {
    overflow: 'hidden',
    color: 'rgba(48, 52, 59, 0.56)',
    fontSize: 10,
    lineHeight: '14px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  calendarSubscriptions: {
    display: 'flex',
    minHeight: 24,
    alignItems: 'center',
    gap: 6,
    color: 'rgba(48, 52, 59, 0.56)',
    fontSize: 10,
  },
  quadrantGrid: {
    display: 'grid',
    minWidth: 820,
    minHeight: 0,
    flex: 1,
    gridTemplateColumns: 'repeat(2, minmax(320px, 1fr))',
    gridTemplateRows: 'repeat(2, minmax(220px, 1fr))',
    gap: 12,
  },
  quadrantPanel: {
    display: 'flex',
    minHeight: 0,
    flexDirection: 'column',
    overflow: 'hidden',
    borderColor: colors.border,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 12,
    backgroundColor: {
      'default': colors.panel,
      '@media (prefers-reduced-transparency: reduce)': colors.panelSolid,
      '@media (prefers-contrast: more)': 'rgb(245, 246, 248)',
    },
    backdropFilter: {
      'default': 'blur(24px) saturate(145%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 10px 24px rgba(31, 38, 48, 0.08), inset 0 1px rgba(255, 255, 255, 0.86)',
  },
  quadrantHeader: {
    display: 'flex',
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    borderBottomColor: 'rgba(255, 255, 255, 0.56)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingRight: 13,
    paddingLeft: 13,
  },
  quadrantTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    color: colors.text,
    fontSize: 12,
    fontWeight: 650,
  },
  quadrantSignal: {
    width: 8,
    height: 8,
    borderRadius: 5,
    backgroundColor: colors.accent,
    boxShadow: '0 1px 3px rgba(0, 90, 180, 0.28)',
  },
  quadrantSignalQuiet: {
    backgroundColor: 'rgba(72, 77, 86, 0.3)',
    boxShadow: 'none',
  },
  quadrantCount: {
    minWidth: 22,
    height: 20,
    borderColor: 'rgba(255, 255, 255, 0.62)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    paddingRight: 6,
    paddingLeft: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    color: colors.textMuted,
    fontSize: 10,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 600,
    lineHeight: '18px',
    textAlign: 'center',
  },
  quadrantBody: {
    display: 'flex',
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    gap: 7,
    overflow: 'auto',
    padding: 10,
  },
  quadrantEmpty: {
    display: 'grid',
    minHeight: 90,
    flex: 1,
    placeItems: 'center',
    color: colors.textQuiet,
    fontSize: 11,
  },
  quadrantRule: {
    color: colors.textQuiet,
    fontSize: 10,
    lineHeight: '14px',
  },
})
