import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'var(--ui-accent, rgb(0, 122, 255))',
  controlHover: 'var(--ui-control-hover, rgba(60, 60, 67, 0.08))',
  controlPressed: 'var(--ui-control-pressed, rgba(60, 60, 67, 0.14))',
  controlSelected: 'var(--ui-control-selected, rgba(118, 118, 128, 0.12))',
  focus: 'var(--ui-focus, rgba(0, 122, 255, 0.72))',
  surface: 'var(--ui-surface, rgb(255, 255, 255))',
  text: 'var(--ui-text, rgba(28, 28, 30, 0.94))',
  textMuted: 'var(--ui-text-muted, rgba(60, 60, 67, 0.64))',
  textQuiet: 'var(--ui-text-quiet, rgba(60, 60, 67, 0.46))',
} as const

export const todoListSidebarStyles = stylex.create({
  root: {
    width: 224,
    height: '100%',
    minHeight: 0,
    overflowX: 'hidden',
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    borderRightColor: 'var(--ui-divider, rgba(60, 60, 67, 0.12))',
    borderRightStyle: 'solid',
    borderRightWidth: 1,
    paddingTop: 10,
    paddingRight: 8,
    paddingBottom: 18,
    paddingLeft: 8,
    backgroundColor: colors.surface,
    backgroundImage: 'none',
    boxShadow: 'none',
  },
  section: {
    marginBottom: 15,
  },
  sectionHeader: {
    display: 'flex',
    width: '100%',
    height: 26,
    alignItems: 'center',
    justifyContent: 'space-between',
    margin: 0,
    borderWidth: 0,
    paddingRight: 7,
    paddingLeft: 9,
    backgroundColor: 'transparent',
    color: colors.textQuiet,
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '16px',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `inset 0 0 0 2px ${colors.focus}`,
    },
  },
  sectionHeaderInteractive: {
    cursor: 'pointer',
    borderRadius: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': colors.controlHover,
      ':active': colors.controlPressed,
    },
  },
  disclosure: {
    width: 14,
    height: 14,
    color: colors.textQuiet,
    transform: 'rotate(0deg)',
    transitionDuration: {
      'default': '160ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'transform',
    transitionTimingFunction: 'ease-out',
  },
  disclosureCollapsed: {
    transform: 'rotate(-90deg)',
  },
  list: {
    display: 'flex',
    margin: 0,
    padding: 0,
    flexDirection: 'column',
    gap: 1,
    listStyle: 'none',
  },
  item: {
    display: 'grid',
    width: '100%',
    height: 32,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '19px minmax(0, 1fr) auto',
    gap: 7,
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    paddingRight: 9,
    paddingLeft: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': colors.controlHover,
      ':active': colors.controlPressed,
    },
    color: colors.text,
    cursor: 'default',
    fontSize: 13,
    fontWeight: 450,
    letterSpacing: 0,
    lineHeight: '18px',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.985)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  itemActive: {
    borderColor: 'transparent',
    backgroundColor: colors.controlSelected,
    backgroundImage: 'none',
    color: colors.text,
    fontWeight: 590,
    boxShadow: 'none',
  },
  icon: {
    display: 'grid',
    width: 17,
    height: 17,
    placeItems: 'center',
    color: colors.textMuted,
  },
  iconActive: {
    color: colors.accent,
  },
  label: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  count: {
    minWidth: 18,
    color: colors.textQuiet,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 500,
    textAlign: 'right',
  },
  countActive: {
    color: colors.textQuiet,
  },
  empty: {
    minHeight: 30,
    margin: 0,
    paddingRight: 9,
    paddingLeft: 35,
    color: colors.textQuiet,
    fontSize: 11,
    lineHeight: '30px',
  },
})
