import * as stylex from '@stylexjs/stylex'

export const assetSettingsStyles = stylex.create({
  assetActionRow: {
    display: 'grid',
    minHeight: 72,
    alignItems: 'center',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    gap: 24,
    paddingTop: 11,
    paddingRight: 18,
    paddingBottom: 11,
    paddingLeft: 18,
  },
  compactAssetActionRow: {
    '@media (max-width: 420px)': {
      alignItems: 'stretch',
      gridTemplateColumns: 'minmax(0, 1fr)',
    },
  },
  assetCopy: {
    minWidth: 0,
  },
  assetLabel: {
    display: 'block',
    color: {
      'default': 'rgba(28, 29, 32, 0.9)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(246, 247, 249, 0.9)',
    },
    fontSize: 13,
    fontWeight: 550,
    letterSpacing: 0,
    lineHeight: '18px',
  },
  assetDescription: {
    marginTop: 3,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: {
      'default': 'rgba(53, 55, 61, 0.62)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(231, 233, 238, 0.6)',
    },
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: '17px',
  },
  secondaryButton: {
    display: 'inline-flex',
    height: 30,
    minHeight: 30,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderColor: {
      'default': 'rgba(71, 76, 86, 0.2)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(255, 255, 255, 0.16)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.78)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(255, 255, 255, 0.09)',
    },
    color: {
      'default': 'rgba(28, 29, 32, 0.88)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(246, 247, 249, 0.88)',
      ':disabled': 'rgba(90, 92, 99, 0.4)',
    },
    fontSize: 12,
    fontWeight: 550,
    letterSpacing: 0,
    lineHeight: '18px',
    cursor: {
      'default': 'default',
      ':disabled': 'not-allowed',
    },
    outline: 'none',
    boxShadow: {
      'default': '0 1px 2px rgba(25, 30, 38, 0.05)',
      ':focus-visible': '0 0 0 2px rgba(41, 97, 194, 0.16)',
    },
  },
  assetResults: {
    borderTopColor: {
      'default': 'rgba(57, 62, 70, 0.1)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(255, 255, 255, 0.1)',
    },
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 10,
    paddingRight: 18,
    paddingBottom: 12,
    paddingLeft: 18,
  },
  assetSummary: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 12,
    color: {
      'default': 'rgba(53, 55, 61, 0.62)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(231, 233, 238, 0.6)',
    },
    fontSize: 11,
    letterSpacing: 0,
    lineHeight: '16px',
  },
  missingAssetWarning: {
    display: 'grid',
    alignItems: 'start',
    gridTemplateColumns: '18px minmax(0, 1fr)',
    gap: 7,
    marginTop: 10,
    borderColor: {
      'default': 'rgba(181, 98, 20, 0.28)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(255, 177, 94, 0.3)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    paddingTop: 8,
    paddingRight: 9,
    paddingBottom: 8,
    paddingLeft: 9,
    backgroundColor: {
      'default': 'rgba(255, 247, 237, 0.72)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(181, 98, 20, 0.1)',
    },
    color: {
      'default': 'rgb(135, 67, 10)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgb(255, 188, 118)',
    },
    fontSize: 11,
    letterSpacing: 0,
    lineHeight: '16px',
  },
  missingAssetCopy: {
    display: 'grid',
    minWidth: 0,
    gap: 2,
  },
  missingAssetName: {
    overflow: 'hidden',
    color: {
      'default': 'rgba(112, 59, 15, 0.78)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(255, 203, 151, 0.78)',
    },
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  assetSelectionHeader: {
    display: 'flex',
    minHeight: 32,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    color: {
      'default': 'rgba(53, 55, 61, 0.62)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(231, 233, 238, 0.6)',
    },
    fontSize: 11,
    letterSpacing: 0,
  },
  inlineButton: {
    minHeight: 0,
    borderWidth: 0,
    borderRadius: 0,
    padding: 0,
    backgroundColor: 'transparent',
    color: 'rgb(0, 113, 227)',
    fontSize: 11,
    fontWeight: 550,
    letterSpacing: 0,
    cursor: 'default',
  },
  assetList: {
    maxHeight: 132,
    overflowY: 'auto',
    borderTopColor: {
      'default': 'rgba(57, 62, 70, 0.1)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(255, 255, 255, 0.1)',
    },
    borderTopStyle: 'solid',
    borderTopWidth: 1,
  },
  assetItem: {
    display: 'grid',
    minHeight: 34,
    alignItems: 'center',
    gridTemplateColumns: '18px minmax(0, 1fr) auto',
    gap: 8,
    borderBottomColor: {
      'default': 'rgba(57, 62, 70, 0.08)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(255, 255, 255, 0.08)',
    },
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    color: {
      'default': 'rgba(28, 29, 32, 0.86)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(246, 247, 249, 0.86)',
    },
    fontSize: 12,
    letterSpacing: 0,
  },
  assetName: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  assetSize: {
    color: {
      'default': 'rgba(53, 55, 61, 0.58)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(231, 233, 238, 0.58)',
    },
    fontVariantNumeric: 'tabular-nums',
  },
  assetButtons: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: 8,
    paddingTop: 10,
  },
  dangerButton: {
    display: 'inline-flex',
    height: 30,
    minHeight: 30,
    alignItems: 'center',
    gap: 6,
    borderWidth: 0,
    borderRadius: 6,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: {
      'default': 'rgb(190, 45, 45)',
      ':disabled': 'rgba(190, 45, 45, 0.42)',
    },
    color: 'white',
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: 0,
    cursor: {
      'default': 'default',
      ':disabled': 'not-allowed',
    },
  },
  warningButton: {
    display: 'inline-flex',
    minHeight: 30,
    alignItems: 'center',
    gap: 6,
    borderColor: 'rgb(181, 98, 20)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: 'transparent',
    color: {
      'default': 'rgb(148, 72, 8)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgb(255, 177, 94)',
    },
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: 0,
    cursor: 'default',
  },
  emptyAssets: {
    display: 'flex',
    minHeight: 44,
    alignItems: 'center',
    gap: 7,
    color: {
      'default': 'rgba(46, 109, 67, 0.82)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(128, 211, 151, 0.86)',
    },
    fontSize: 12,
    letterSpacing: 0,
  },
  assetStatus: {
    minHeight: 28,
    marginTop: 0,
    marginRight: 2,
    marginBottom: 0,
    marginLeft: 2,
    paddingTop: 6,
    paddingBottom: 6,
    color: {
      'default': 'rgba(53, 55, 61, 0.68)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(231, 233, 238, 0.68)',
    },
    fontSize: 11,
    letterSpacing: 0,
    lineHeight: '16px',
  },
  spinningIcon: {
    animationName: stylex.keyframes({ to: { transform: 'rotate(360deg)' } }),
    animationDuration: '800ms',
    animationIterationCount: 'infinite',
    animationTimingFunction: 'linear',
  },
})
