import { uiColors } from '@memorilo/ui/theme.stylex'
import * as stylex from '@stylexjs/stylex'

export const assetSettingsStyles = stylex.create({
  assetActionRow: {
    display: 'grid',
    minHeight: 72,
    alignItems: 'center',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    gap: 24,
    paddingTop: 11,
    paddingRight: 18,
    paddingBottom: 11,
    paddingLeft: 18,
  },
  compactAssetActionRow: {
    '@media (max-width: 420px)': {
      alignItems: 'stretch',
      gridTemplateColumns: 'minmax(0, 1fr)',
    },
  },
  assetCopy: {
    minWidth: 0,
  },
  assetLabel: {
    display: 'block',
    color: uiColors.text,
    fontSize: 13,
    fontWeight: 550,
    letterSpacing: 0,
    lineHeight: '18px',
  },
  assetDescription: {
    marginTop: 3,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: uiColors.textMuted,
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: '17px',
  },
  secondaryButton: {
    display: 'inline-flex',
    height: 30,
    minHeight: 30,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderColor: uiColors.border,
    borderStyle: 'solid',
    borderWidth: uiColors.controlStroke,
    borderRadius: uiColors.controlRadius,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: uiColors.controlBackground,
    backgroundImage: uiColors.controlBackgroundImage,
    color: {
      'default': uiColors.text,
      ':disabled': uiColors.textQuiet,
    },
    fontSize: 12,
    fontWeight: 550,
    letterSpacing: 0,
    lineHeight: '18px',
    cursor: {
      'default': 'default',
      ':disabled': 'not-allowed',
    },
    outline: 'none',
    boxShadow: {
      'default': uiColors.controlShadow,
      ':focus-visible': `0 0 0 2px ${uiColors.focus}`,
    },
  },
  assetResults: {
    borderTopColor: uiColors.divider,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 10,
    paddingRight: 18,
    paddingBottom: 12,
    paddingLeft: 18,
  },
  assetSummary: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 12,
    color: uiColors.textMuted,
    fontSize: 11,
    letterSpacing: 0,
    lineHeight: '16px',
  },
  missingAssetWarning: {
    display: 'grid',
    alignItems: 'start',
    gridTemplateColumns: '18px minmax(0, 1fr)',
    gap: 7,
    marginTop: 10,
    borderColor: uiColors.warning,
    borderStyle: 'solid',
    borderWidth: uiColors.controlStroke,
    borderRadius: uiColors.controlRadius,
    paddingTop: 8,
    paddingRight: 9,
    paddingBottom: 8,
    paddingLeft: 9,
    backgroundColor: uiColors.surfaceSunken,
    color: uiColors.warning,
    fontSize: 11,
    letterSpacing: 0,
    lineHeight: '16px',
  },
  missingAssetCopy: {
    display: 'grid',
    minWidth: 0,
    gap: 2,
  },
  missingAssetName: {
    overflow: 'hidden',
    color: uiColors.warning,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  assetSelectionHeader: {
    display: 'flex',
    minHeight: 32,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    color: uiColors.textMuted,
    fontSize: 11,
    letterSpacing: 0,
  },
  inlineButton: {
    minHeight: 0,
    borderWidth: 0,
    borderRadius: 0,
    padding: 0,
    backgroundColor: 'transparent',
    color: uiColors.accent,
    fontSize: 11,
    fontWeight: 550,
    letterSpacing: 0,
    cursor: 'default',
  },
  assetList: {
    maxHeight: 132,
    overflowY: 'auto',
    borderTopColor: uiColors.divider,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
  },
  assetItem: {
    display: 'grid',
    minHeight: 34,
    alignItems: 'center',
    gridTemplateColumns: '18px minmax(0, 1fr) auto',
    gap: 8,
    borderBottomColor: uiColors.divider,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    color: uiColors.text,
    fontSize: 12,
    letterSpacing: 0,
  },
  assetName: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  assetSize: {
    color: uiColors.textMuted,
    fontVariantNumeric: 'tabular-nums',
  },
  assetButtons: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: 8,
    paddingTop: 10,
  },
  dangerButton: {
    display: 'inline-flex',
    height: 30,
    minHeight: 30,
    alignItems: 'center',
    gap: 6,
    borderWidth: 0,
    borderRadius: uiColors.controlRadius,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: {
      'default': uiColors.danger,
      ':disabled': uiColors.surfaceSunken,
    },
    color: uiColors.onDanger,
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: 0,
    cursor: {
      'default': 'default',
      ':disabled': 'not-allowed',
    },
  },
  warningButton: {
    display: 'inline-flex',
    minHeight: 30,
    alignItems: 'center',
    gap: 6,
    borderColor: uiColors.warning,
    borderStyle: 'solid',
    borderWidth: uiColors.controlStroke,
    borderRadius: uiColors.controlRadius,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: 'transparent',
    color: uiColors.warning,
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: 0,
    cursor: 'default',
  },
  emptyAssets: {
    display: 'flex',
    minHeight: 44,
    alignItems: 'center',
    gap: 7,
    color: uiColors.statusSuccess,
    fontSize: 12,
    letterSpacing: 0,
  },
  assetStatus: {
    minHeight: 28,
    marginTop: 0,
    marginRight: 2,
    marginBottom: 0,
    marginLeft: 2,
    paddingTop: 6,
    paddingBottom: 6,
    color: uiColors.textMuted,
    fontSize: 11,
    letterSpacing: 0,
    lineHeight: '16px',
  },
  spinningIcon: {
    animationName: stylex.keyframes({ to: { transform: 'rotate(360deg)' } }),
    animationDuration: '800ms',
    animationIterationCount: 'infinite',
    animationTimingFunction: 'linear',
  },
})
