import { uiColors } from '@memorilo/ui/theme.stylex'
import * as stylex from '@stylexjs/stylex'

export const calendarSettingsStyles = stylex.create({
  manager: {
    overflow: 'hidden',
    borderColor: {
      'default': uiColors.border,
      '@media (prefers-contrast: more)': uiColors.borderStrong,
    },
    borderStyle: 'solid',
    borderWidth: uiColors.surfaceStroke,
    borderRadius: uiColors.surfaceRadius,
    backgroundColor: {
      'default': uiColors.surfaceTranslucent,
      '@media (prefers-reduced-transparency: reduce)': uiColors.surfaceOpaque,
    },
    backgroundImage: uiColors.surfaceBackgroundImage,
    backdropFilter: {
      'default': uiColors.materialFilter,
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: uiColors.shadowSubtle,
  },
  list: {
    minHeight: 150,
  },
  row: {
    position: 'relative',
    display: 'grid',
    width: '100%',
    minHeight: 52,
    gridTemplateColumns: '14px minmax(0, 1fr) minmax(72px, auto)',
    alignItems: 'center',
    gap: 9,
    borderWidth: 0,
    borderRadius: 0,
    paddingBlock: 7,
    paddingInline: 11,
    backgroundColor: {
      'default': 'transparent',
      ':hover': uiColors.controlHover,
      ':active': uiColors.controlPressed,
    },
    color: uiColors.text,
    cursor: 'default',
    fontFamily: 'inherit',
    textAlign: 'left',
    outline: 'none',
    boxShadow: {
      'default': `inset 0 -1px ${uiColors.divider}`,
      ':focus-visible': `inset 0 0 0 2px ${uiColors.focus}`,
    },
  },
  rowSelected: {
    backgroundColor: uiColors.accentSoft,
  },
  swatch: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: 'var(--calendar-color)',
    boxShadow: 'inset 0 0 0 0.5px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.1)',
  },
  rowText: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    gap: 2,
  },
  rowTitle: {
    overflow: 'hidden',
    fontSize: 12,
    fontWeight: 600,
    lineHeight: '16px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  rowUrl: {
    overflow: 'hidden',
    color: uiColors.textQuiet,
    fontSize: 10,
    lineHeight: '14px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  rowMeta: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 4,
    color: uiColors.textQuiet,
    fontSize: 9,
    lineHeight: '14px',
    whiteSpace: 'nowrap',
  },
  empty: {
    display: 'grid',
    minHeight: 150,
    placeItems: 'center',
    color: uiColors.textQuiet,
    fontSize: 11,
  },
  toolbar: {
    display: 'flex',
    height: 29,
    alignItems: 'center',
    borderTopColor: uiColors.divider,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingInline: 4,
    backgroundColor: uiColors.surfaceSunken,
  },
  toolButton: {
    'display': 'grid',
    'width': 26,
    'height': 24,
    'placeItems': 'center',
    'borderWidth': 0,
    'borderRadius': 5,
    'padding': 0,
    'backgroundColor': {
      'default': 'transparent',
      ':hover': uiColors.controlHover,
      ':active': uiColors.controlPressed,
    },
    'color': uiColors.textMuted,
    'outline': 'none',
    ':disabled': {
      opacity: 0.3,
    },
    ':focus-visible': {
      boxShadow: `0 0 0 2px ${uiColors.focus}`,
    },
  },
  toolbarSpacer: {
    flex: 1,
  },
  spinning: {
    animationDuration: '900ms',
    animationIterationCount: 'infinite',
    animationName: stylex.keyframes({ to: { transform: 'rotate(360deg)' } }),
    animationTimingFunction: 'linear',
  },
  dialogForm: {
    display: 'grid',
    width: '100%',
  },
  field: {
    display: 'grid',
    gap: 6,
    color: uiColors.textMuted,
    fontSize: 11,
    fontWeight: 560,
  },
  input: {
    'minWidth': 0,
    'height': 32,
    'boxSizing': 'border-box',
    'borderColor': uiColors.fieldBorder,
    'borderStyle': 'solid',
    'borderWidth': uiColors.controlStroke,
    'borderRadius': uiColors.controlRadius,
    'paddingInline': 9,
    'backgroundColor': uiColors.fieldBackground,
    'color': 'inherit',
    'fontFamily': 'inherit',
    'fontSize': 11,
    'outline': 'none',
    ':focus': {
      borderColor: uiColors.focus,
      boxShadow: `0 0 0 2px ${uiColors.accentSoft}`,
    },
  },
  dialogError: {
    margin: 0,
    color: uiColors.danger,
    fontSize: 11,
    lineHeight: '16px',
  },
  secondaryButton: {
    'height': 30,
    'borderColor': uiColors.border,
    'borderStyle': 'solid',
    'borderWidth': uiColors.controlStroke,
    'borderRadius': uiColors.controlRadius,
    'paddingInline': 11,
    'backgroundColor': uiColors.controlBackground,
    'backgroundImage': uiColors.controlBackgroundImage,
    'color': uiColors.text,
    'boxShadow': uiColors.controlShadow,
    'fontSize': 11,
    ':disabled': { opacity: 0.45 },
    ':active': { transform: 'scale(0.97)' },
    ':focus-visible': { boxShadow: `0 0 0 2px ${uiColors.focus}` },
  },
  primaryButton: {
    'height': 30,
    'borderWidth': 0,
    'borderRadius': uiColors.controlRadius,
    'paddingInline': 12,
    'backgroundColor': uiColors.accent,
    'backgroundImage': uiColors.accentBackgroundImage,
    'color': uiColors.onAccent,
    'fontSize': 11,
    'fontWeight': 600,
    ':disabled': { opacity: 0.42 },
    ':active': { transform: 'scale(0.97)' },
    ':focus-visible': { boxShadow: `0 0 0 2px ${uiColors.surfaceOpaque}, 0 0 0 4px ${uiColors.focus}` },
  },
  error: {
    marginTop: 8,
    marginBottom: 0,
    color: uiColors.danger,
    fontSize: 11,
    lineHeight: '16px',
  },
})
