import * as stylex from '@stylexjs/stylex'

export const calendarSettingsStyles = stylex.create({
  manager: {
    overflow: 'hidden',
    borderColor: {
      'default': 'rgba(80, 87, 98, 0.15)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(255, 255, 255, 0.13)',
      '@media (prefers-contrast: more)': 'currentColor',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.38)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(255, 255, 255, 0.055)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(245, 246, 248)',
    },
    boxShadow: 'inset 0 1px rgba(255, 255, 255, 0.68)',
  },
  list: {
    minHeight: 150,
  },
  row: {
    position: 'relative',
    display: 'grid',
    width: '100%',
    minHeight: 52,
    gridTemplateColumns: '14px minmax(0, 1fr) minmax(72px, auto)',
    alignItems: 'center',
    gap: 9,
    borderWidth: 0,
    borderRadius: 0,
    paddingBlock: 7,
    paddingInline: 11,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(118, 118, 128, 0.07)',
      ':active': 'rgba(118, 118, 128, 0.11)',
    },
    color: {
      'default': 'rgba(28, 30, 35, 0.92)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(247, 248, 250, 0.92)',
    },
    cursor: 'default',
    fontFamily: 'inherit',
    textAlign: 'left',
    outline: 'none',
    boxShadow: {
      'default': 'inset 0 -1px rgba(80, 87, 98, 0.1)',
      ':focus-visible': 'inset 0 0 0 2px rgba(0, 113, 227, 0.72)',
    },
  },
  rowSelected: {
    backgroundColor: {
      'default': 'rgba(0, 113, 227, 0.11)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(36, 125, 232, 0.2)',
    },
  },
  swatch: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: 'var(--calendar-color)',
    boxShadow: 'inset 0 0 0 0.5px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.1)',
  },
  rowText: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    gap: 2,
  },
  rowTitle: {
    overflow: 'hidden',
    fontSize: 12,
    fontWeight: 600,
    lineHeight: '16px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  rowUrl: {
    overflow: 'hidden',
    color: {
      'default': 'rgba(48, 52, 59, 0.5)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(235, 237, 242, 0.5)',
    },
    fontSize: 10,
    lineHeight: '14px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  rowMeta: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 4,
    color: {
      'default': 'rgba(48, 52, 59, 0.48)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(235, 237, 242, 0.5)',
    },
    fontSize: 9,
    lineHeight: '14px',
    whiteSpace: 'nowrap',
  },
  empty: {
    display: 'grid',
    minHeight: 150,
    placeItems: 'center',
    color: {
      'default': 'rgba(48, 52, 59, 0.48)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(235, 237, 242, 0.5)',
    },
    fontSize: 11,
  },
  toolbar: {
    display: 'flex',
    height: 29,
    alignItems: 'center',
    borderTopColor: {
      'default': 'rgba(80, 87, 98, 0.12)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(255, 255, 255, 0.1)',
    },
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingInline: 4,
    backgroundColor: {
      'default': 'rgba(247, 248, 250, 0.58)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(255, 255, 255, 0.035)',
    },
  },
  toolButton: {
    'display': 'grid',
    'width': 26,
    'height': 24,
    'placeItems': 'center',
    'borderWidth': 0,
    'borderRadius': 5,
    'padding': 0,
    'backgroundColor': {
      'default': 'transparent',
      ':hover': 'rgba(118, 118, 128, 0.1)',
      ':active': 'rgba(118, 118, 128, 0.16)',
    },
    'color': {
      'default': 'rgba(35, 38, 44, 0.72)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(242, 244, 248, 0.74)',
    },
    'outline': 'none',
    ':disabled': {
      opacity: 0.3,
    },
    ':focus-visible': {
      boxShadow: '0 0 0 2px rgba(0, 113, 227, 0.72)',
    },
  },
  toolbarSpacer: {
    flex: 1,
  },
  spinning: {
    animationDuration: '900ms',
    animationIterationCount: 'infinite',
    animationName: stylex.keyframes({ to: { transform: 'rotate(360deg)' } }),
    animationTimingFunction: 'linear',
  },
  dialogForm: {
    display: 'grid',
    width: '100%',
  },
  field: {
    display: 'grid',
    gap: 6,
    color: {
      'default': 'rgba(35, 38, 44, 0.78)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(242, 244, 248, 0.78)',
    },
    fontSize: 11,
    fontWeight: 560,
  },
  input: {
    'minWidth': 0,
    'height': 32,
    'boxSizing': 'border-box',
    'borderColor': {
      'default': 'rgba(80, 87, 98, 0.2)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(255, 255, 255, 0.15)',
    },
    'borderStyle': 'solid',
    'borderWidth': 1,
    'borderRadius': 7,
    'paddingInline': 9,
    'backgroundColor': {
      'default': 'rgba(255, 255, 255, 0.76)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(15, 17, 21, 0.54)',
    },
    'color': 'inherit',
    'fontFamily': 'inherit',
    'fontSize': 11,
    'outline': 'none',
    ':focus': {
      borderColor: 'rgba(0, 113, 227, 0.68)',
      boxShadow: '0 0 0 2px rgba(0, 113, 227, 0.15)',
    },
  },
  dialogError: {
    margin: 0,
    color: {
      'default': 'rgb(176, 65, 54)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgb(255, 139, 128)',
    },
    fontSize: 11,
    lineHeight: '16px',
  },
  secondaryButton: {
    'height': 30,
    'borderColor': {
      'default': 'rgba(80, 87, 98, 0.18)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(255, 255, 255, 0.14)',
    },
    'borderStyle': 'solid',
    'borderWidth': 1,
    'borderRadius': 6,
    'paddingInline': 11,
    'backgroundColor': {
      'default': 'rgba(255, 255, 255, 0.56)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(255, 255, 255, 0.08)',
    },
    'color': 'inherit',
    'fontSize': 11,
    ':disabled': { opacity: 0.45 },
    ':active': { transform: 'scale(0.97)' },
    ':focus-visible': { boxShadow: '0 0 0 2px rgba(0, 113, 227, 0.64)' },
  },
  primaryButton: {
    'height': 30,
    'borderWidth': 0,
    'borderRadius': 6,
    'paddingInline': 12,
    'backgroundColor': 'rgb(0, 113, 227)',
    'color': 'white',
    'fontSize': 11,
    'fontWeight': 600,
    ':disabled': { opacity: 0.42 },
    ':active': { transform: 'scale(0.97)' },
    ':focus-visible': { boxShadow: '0 0 0 2px rgba(0, 113, 227, 0.28), 0 0 0 4px rgba(0, 113, 227, 0.16)' },
  },
  error: {
    marginTop: 8,
    marginBottom: 0,
    color: {
      'default': 'rgb(176, 65, 54)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgb(255, 139, 128)',
    },
    fontSize: 11,
    lineHeight: '16px',
  },
})
