import * as stylex from '@stylexjs/stylex'

export const deviceSettingsStyles = stylex.create({
  root: {
    display: 'grid',
    gap: 10,
  },
  surface: {
    overflow: 'hidden',
    borderColor: 'var(--ui-border)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 'var(--ui-surface-radius)',
    backgroundColor: 'var(--ui-surface)',
    boxShadow: 'var(--ui-shadow-subtle)',
  },
  summary: {
    display: 'grid',
    minHeight: 76,
    alignItems: 'center',
    gridTemplateColumns: '40px minmax(0, 1fr) auto',
    gap: 12,
    paddingBlock: 13,
    paddingInline: 18,
  },
  glyph: {
    display: 'grid',
    width: 40,
    height: 40,
    placeItems: 'center',
    borderColor: 'var(--ui-border)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: 'var(--ui-surface-sunken)',
    color: 'var(--ui-text-muted)',
  },
  summaryCopy: {
    display: 'grid',
    minWidth: 0,
    gap: 2,
  },
  summaryTitle: {
    overflow: 'hidden',
    margin: 0,
    color: 'var(--ui-text)',
    fontSize: 14,
    fontWeight: 650,
    letterSpacing: '-0.005em',
    lineHeight: '19px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  summaryDetail: {
    margin: 0,
    color: 'var(--ui-text-muted)',
    fontSize: 11,
    lineHeight: '16px',
  },
  compactButton: {
    minHeight: 30,
    flex: '0 0 auto',
    borderRadius: 7,
    paddingInline: 10,
    fontSize: 12,
    whiteSpace: 'nowrap',
  },
  section: {
    borderTopColor: 'var(--ui-divider)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
  },
  sectionTitle: {
    margin: 0,
    paddingTop: 10,
    paddingRight: 18,
    paddingBottom: 7,
    paddingLeft: 18,
    color: 'var(--ui-text-quiet)',
    fontSize: 10,
    fontWeight: 650,
    letterSpacing: '0.025em',
    lineHeight: '15px',
    textTransform: 'uppercase',
  },
  deviceList: {
    display: 'grid',
  },
  deviceButton: {
    display: 'grid',
    minHeight: 52,
    alignItems: 'center',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    gap: 12,
    marginInline: 18,
    border: 0,
    borderRadius: 7,
    paddingBlock: 8,
    paddingInline: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'var(--ui-control-hover)',
      ':active': 'var(--ui-control-pressed)',
      ':focus-visible': 'var(--ui-control-hover)',
    },
    color: 'var(--ui-text)',
    cursor: 'default',
    textAlign: 'left',
    outlineColor: 'var(--ui-focus)',
    outlineOffset: -2,
    outlineStyle: 'solid',
    outlineWidth: {
      'default': 0,
      ':focus-visible': 2,
    },
  },
  deviceName: {
    overflow: 'hidden',
    fontSize: 12,
    fontWeight: 600,
    lineHeight: '17px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  deviceAction: {
    color: 'var(--ui-text-muted)',
    fontSize: 11,
    lineHeight: '16px',
  },
  pairing: {
    display: 'grid',
    gap: 12,
    paddingTop: 4,
    paddingRight: 18,
    paddingBottom: 16,
    paddingLeft: 18,
  },
  pairingCode: {
    display: 'inline-flex',
    width: 'fit-content',
    minHeight: 38,
    alignItems: 'center',
    borderColor: 'var(--ui-field-border)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingInline: 12,
    backgroundColor: 'var(--ui-field-background)',
    color: 'var(--ui-text)',
    fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
    fontSize: 18,
    fontWeight: 650,
    letterSpacing: '0.12em',
    lineHeight: '26px',
  },
  pairingInput: {
    maxWidth: 160,
    fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
    letterSpacing: '0.12em',
  },
  actions: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: 8,
  },
  form: {
    display: 'grid',
  },
  row: {
    'display': 'grid',
    'minHeight': 66,
    'alignItems': 'center',
    'gridTemplateColumns': 'minmax(150px, 0.78fr) minmax(220px, 1.22fr)',
    'gap': 24,
    'borderTopColor': 'var(--ui-divider)',
    'borderTopStyle': 'solid',
    'borderTopWidth': 1,
    'paddingBlock': 10,
    'paddingInline': 18,
    '@media (max-width: 560px)': {
      alignItems: 'stretch',
      gridTemplateColumns: 'minmax(0, 1fr)',
      gap: 8,
    },
  },
  rowCopy: {
    display: 'grid',
    minWidth: 0,
    gap: 2,
  },
  label: {
    color: 'var(--ui-text)',
    fontSize: 13,
    fontWeight: 550,
    lineHeight: '18px',
  },
  description: {
    margin: 0,
    color: 'var(--ui-text-muted)',
    fontSize: 11,
    lineHeight: '16px',
  },
  control: {
    width: '100%',
    minWidth: 0,
  },
  switchControl: {
    justifySelf: 'end',
  },
  rowActions: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: 8,
  },
  footer: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 10,
    borderTopColor: 'var(--ui-divider)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingBlock: 12,
    paddingInline: 18,
  },
  footerGroup: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
  },
  status: {
    minHeight: 22,
    paddingInline: 4,
    fontSize: 11,
    lineHeight: '16px',
  },
})
