import * as stylex from '@stylexjs/stylex'

export const deviceGalleryStyles = stylex.create({
  root: {
    display: 'grid',
    gap: 12,
    borderTopColor: 'var(--ui-divider)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingBlock: 16,
    paddingInline: 18,
    backgroundColor: 'var(--ui-surface)',
  },
  headingRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
  },
  heading: {
    margin: 0,
    color: 'var(--ui-text)',
    fontSize: 14,
    fontWeight: 650,
    letterSpacing: '-0.005em',
    lineHeight: '19px',
  },
  label: {
    color: 'var(--ui-text)',
    fontSize: 13,
    fontWeight: 550,
    lineHeight: '18px',
  },
  description: {
    margin: 0,
    color: 'var(--ui-text-muted)',
    fontSize: 11,
    lineHeight: '16px',
  },
  compactButton: {
    minHeight: 30,
    gap: 6,
    borderRadius: 7,
    paddingInline: 10,
    fontSize: 12,
    whiteSpace: 'nowrap',
  },
  connectionRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(180px, 260px) minmax(0, 1fr)',
    alignItems: 'center',
    gap: 12,
  },
  address: {
    width: '100%',
  },
  addressHint: {
    color: 'var(--ui-text-muted)',
    fontSize: 11,
    lineHeight: '16px',
  },
  metrics: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 6,
    color: 'var(--ui-text-muted)',
    fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
    fontSize: 10,
    lineHeight: '15px',
  },
  uploadGrid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(220px, 1fr) minmax(190px, 0.72fr)',
    gap: 14,
    alignItems: 'stretch',
  },
  preview: {
    overflow: 'hidden',
    minHeight: 170,
    borderColor: 'var(--ui-border)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    backgroundColor: '#fffdf8',
  },
  emptyPreview: {
    display: 'grid',
    height: '100%',
    minHeight: 170,
    placeContent: 'center',
    justifyItems: 'center',
    gap: 7,
    color: 'var(--ui-text-muted)',
    fontSize: 11,
  },
  canvas: {
    display: 'block',
    width: '100%',
    height: 'auto',
    imageRendering: 'auto',
  },
  uploadControls: {
    display: 'grid',
    alignContent: 'start',
    gap: 8,
  },
  fileButton: {
    display: 'inline-flex',
    minHeight: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: 'var(--ui-field-border)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 7,
    paddingInline: 10,
    backgroundColor: {
      'default': 'var(--ui-field-background)',
      ':hover': 'var(--ui-control-hover)',
      ':active': 'var(--ui-control-pressed)',
    },
    color: 'var(--ui-text)',
    cursor: 'default',
    fontSize: 12,
    fontWeight: 550,
  },
  fileInput: {
    position: 'absolute',
    width: 1,
    height: 1,
    overflow: 'hidden',
    clip: 'rect(0 0 0 0)',
    clipPath: 'inset(50%)',
    whiteSpace: 'nowrap',
  },
  slideshowRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(140px, 210px)',
    alignItems: 'center',
    gap: 14,
    borderTopColor: 'var(--ui-divider)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 12,
  },
  assetList: {
    display: 'grid',
    borderTopColor: 'var(--ui-divider)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
  },
  emptyList: {
    margin: 0,
    paddingBlock: 18,
    color: 'var(--ui-text-muted)',
    fontSize: 12,
    textAlign: 'center',
  },
  assetRow: {
    display: 'grid',
    minHeight: 48,
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: 12,
    borderBottomColor: 'var(--ui-divider)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingBlock: 7,
  },
  assetCopy: {
    display: 'grid',
    minWidth: 0,
    gap: 1,
  },
  assetName: {
    overflow: 'hidden',
    color: 'var(--ui-text)',
    fontSize: 12,
    fontWeight: 550,
    lineHeight: '17px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  assetMeta: {
    color: 'var(--ui-text-muted)',
    fontSize: 10,
    lineHeight: '15px',
  },
  assetActions: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 4,
  },
  iconButton: {
    minWidth: 28,
    minHeight: 28,
    gap: 4,
    borderRadius: 6,
    paddingInline: 7,
    color: 'var(--ui-text-muted)',
    fontSize: 11,
  },
})
