import { uiColors } from '@memorilo/ui/theme.stylex'
import * as stylex from '@stylexjs/stylex'

export const p2pSettingsStyles = stylex.create({
  root: {
    display: 'grid',
    gap: 10,
  },
  surface: {
    overflow: 'hidden',
    borderColor: {
      'default': uiColors.border,
      '@media (prefers-contrast: more)': uiColors.borderStrong,
    },
    borderStyle: 'solid',
    borderWidth: uiColors.surfaceStroke,
    borderRadius: uiColors.surfaceRadius,
    backgroundColor: {
      'default': uiColors.surfaceTranslucent,
      '@media (prefers-reduced-transparency: reduce)': uiColors.surfaceOpaque,
      '@media (prefers-contrast: more)': uiColors.surfaceOpaque,
    },
    backgroundImage: uiColors.surfaceBackgroundImage,
    backdropFilter: {
      'default': uiColors.materialFilter,
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: uiColors.shadowSubtle,
  },
  identitySection: {
    display: 'grid',
    minHeight: 78,
    alignItems: 'center',
    gridTemplateColumns: '42px minmax(0, 1fr)',
    gap: 12,
    paddingBlock: 14,
    paddingInline: 18,
  },
  deviceGlyph: {
    display: 'grid',
    width: 42,
    height: 42,
    placeItems: 'center',
    borderColor: uiColors.border,
    borderStyle: 'solid',
    borderWidth: uiColors.controlStroke,
    borderRadius: uiColors.controlRadius,
    backgroundColor: uiColors.accentSoft,
    color: uiColors.accent,
    boxShadow: uiColors.controlShadow,
  },
  identityCopy: {
    display: 'grid',
    minWidth: 0,
    gap: 3,
  },
  identityEyebrow: {
    color: uiColors.textQuiet,
    fontSize: 10,
    fontWeight: 650,
    letterSpacing: '0.025em',
    lineHeight: '14px',
    textTransform: 'uppercase',
  },
  identityHeadingLine: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  identityTitle: {
    overflow: 'hidden',
    margin: 0,
    color: uiColors.text,
    fontSize: 14,
    fontWeight: 650,
    letterSpacing: '-0.005em',
    lineHeight: '19px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  identityDescription: {
    margin: 0,
    color: uiColors.textMuted,
    fontSize: 11,
    lineHeight: '16px',
  },
  connectionState: {
    display: 'inline-flex',
    flex: '0 0 auto',
    alignItems: 'center',
    gap: 5,
    color: uiColors.textMuted,
    fontSize: 10,
    fontWeight: 550,
    lineHeight: '15px',
  },
  connectionStateReady: {
    color: uiColors.statusSuccess,
  },
  stateDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'currentColor',
    boxShadow: '0 0 0 2px color-mix(in srgb, currentColor 14%, transparent)',
  },
  settingRow: {
    'display': 'grid',
    'minHeight': 68,
    'alignItems': 'center',
    'gridTemplateColumns': 'minmax(150px, 0.78fr) minmax(220px, 1.22fr)',
    'gap': 24,
    'borderTopColor': uiColors.divider,
    'borderTopStyle': 'solid',
    'borderTopWidth': 1,
    'paddingBlock': 11,
    'paddingInline': 18,
    '@media (max-width: 560px)': {
      alignItems: 'stretch',
      gridTemplateColumns: 'minmax(0, 1fr)',
      gap: 9,
    },
  },
  rowCopy: {
    display: 'grid',
    minWidth: 0,
    gap: 3,
  },
  rowLabel: {
    color: uiColors.text,
    fontSize: 13,
    fontWeight: 550,
    lineHeight: '18px',
  },
  rowDescription: {
    margin: 0,
    color: uiColors.textMuted,
    fontSize: 11,
    lineHeight: '16px',
  },
  serverWarning: {
    color: uiColors.warning,
  },
  serverSummary: {
    display: 'grid',
    minWidth: 0,
    justifyItems: 'end',
    gap: 3,
  },
  serverState: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    color: uiColors.textMuted,
    fontSize: 12,
    fontWeight: 650,
    lineHeight: '17px',
  },
  serverStateReady: {
    color: uiColors.statusSuccess,
  },
  serverAddress: {
    overflow: 'hidden',
    maxWidth: '100%',
    color: uiColors.textMuted,
    fontSize: 10,
    lineHeight: '15px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  serverModes: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: 8,
    color: uiColors.text,
    fontSize: 10,
    fontWeight: 600,
    lineHeight: '15px',
  },
  serverMode: {
    display: 'inline-flex',
  },
  serverEpochs: {
    color: uiColors.textQuiet,
    fontSize: 10,
    lineHeight: '15px',
  },
  nameEditor: {
    minWidth: 0,
    justifyContent: 'flex-end',
    gap: 8,
  },
  nameInput: {
    maxWidth: 260,
  },
  compactButton: {
    minHeight: 30,
    flex: '0 0 auto',
    borderRadius: uiColors.controlRadius,
    paddingInline: 10,
    fontSize: 12,
    whiteSpace: 'nowrap',
  },
  deviceSection: {
    borderTopColor: uiColors.divider,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
  },
  sectionLabel: {
    margin: 0,
    paddingTop: 10,
    paddingRight: 18,
    paddingBottom: 7,
    paddingLeft: 18,
    color: uiColors.textQuiet,
    fontSize: 10,
    fontWeight: 650,
    letterSpacing: '0.025em',
    lineHeight: '15px',
  },
  deviceList: {
    display: 'grid',
  },
  deviceRow: {
    'display': 'grid',
    'minHeight': 54,
    'alignItems': 'center',
    'gridTemplateColumns': 'minmax(0, 1fr) auto',
    'gap': 12,
    'marginInline': 18,
    'paddingBlock': 8,
    'boxShadow': `inset 0 -1px ${uiColors.divider}`,
    ':last-child': {
      boxShadow: 'none',
    },
    '@media (max-width: 560px)': {
      alignItems: 'start',
      gridTemplateColumns: 'minmax(0, 1fr)',
    },
  },
  deviceRowStacked: {
    alignItems: 'start',
    gridTemplateColumns: 'minmax(0, 1fr)',
    paddingBlock: 11,
  },
  deviceCopy: {
    display: 'grid',
    minWidth: 0,
    gap: 2,
  },
  deviceName: {
    overflow: 'hidden',
    color: uiColors.text,
    fontSize: 12,
    fontWeight: 600,
    lineHeight: '17px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  deviceDetail: {
    overflow: 'hidden',
    color: uiColors.textQuiet,
    fontFamily: 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: 10,
    lineHeight: '15px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  emojiConfirmation: {
    'display': 'flex',
    'alignItems': 'center',
    'justifyContent': 'space-between',
    'gap': 12,
    '@media (max-width: 560px)': {
      alignItems: 'stretch',
      flexDirection: 'column',
    },
  },
  emojiCode: {
    display: 'inline-flex',
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: uiColors.border,
    borderStyle: 'solid',
    borderWidth: uiColors.controlStroke,
    borderRadius: uiColors.controlRadius,
    paddingInline: 12,
    backgroundColor: uiColors.surfaceSunken,
    fontFamily: 'Apple Color Emoji, Segoe UI Emoji, sans-serif',
    fontSize: 20,
    letterSpacing: '0.08em',
    lineHeight: '28px',
    boxShadow: uiColors.controlShadow,
  },
  emptyState: {
    minHeight: 44,
    margin: 0,
    paddingTop: 11,
    paddingRight: 18,
    paddingBottom: 14,
    paddingLeft: 18,
    color: uiColors.textQuiet,
    fontSize: 11,
    lineHeight: '16px',
  },
  removeButton: {
    minHeight: 28,
    borderRadius: uiColors.controlRadius,
    paddingInline: 8,
    color: uiColors.danger,
    fontSize: 11,
    fontWeight: 550,
  },
  feedback: {
    minHeight: 22,
    paddingInline: 4,
    fontSize: 11,
    lineHeight: '16px',
  },
})
