import * as stylex from '@stylexjs/stylex'

export const p2pSettingsStyles = stylex.create({
  root: {
    display: 'grid',
    gap: 10,
  },
  surface: {
    overflow: 'hidden',
    borderColor: {
      'default': 'rgba(80, 87, 98, 0.13)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(255, 255, 255, 0.12)',
      '@media (prefers-contrast: more)': 'currentColor',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 12,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.34)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(255, 255, 255, 0.055)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(245, 246, 248)',
      '@media (prefers-contrast: more)': 'rgba(248, 249, 251, 0.98)',
    },
    backdropFilter: {
      'default': 'blur(24px) saturate(150%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: 'inset 0 1px rgba(255, 255, 255, 0.68), inset 0 -1px rgba(68, 74, 84, 0.06), 0 8px 24px rgba(31, 38, 48, 0.045)',
  },
  identitySection: {
    display: 'grid',
    minHeight: 78,
    alignItems: 'center',
    gridTemplateColumns: '42px minmax(0, 1fr)',
    gap: 12,
    paddingBlock: 14,
    paddingInline: 18,
  },
  deviceGlyph: {
    display: 'grid',
    width: 42,
    height: 42,
    placeItems: 'center',
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.58)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(255, 255, 255, 0.14)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 11,
    backgroundColor: {
      'default': 'rgba(225, 237, 251, 0.72)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(36, 125, 232, 0.18)',
    },
    color: {
      'default': 'rgb(0, 101, 204)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgb(105, 177, 255)',
    },
    boxShadow: 'inset 0 1px rgba(255, 255, 255, 0.72), 0 2px 6px rgba(31, 73, 120, 0.1)',
  },
  identityCopy: {
    display: 'grid',
    minWidth: 0,
    gap: 3,
  },
  identityEyebrow: {
    color: {
      'default': 'rgba(53, 55, 61, 0.5)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(231, 233, 238, 0.5)',
    },
    fontSize: 10,
    fontWeight: 650,
    letterSpacing: '0.025em',
    lineHeight: '14px',
    textTransform: 'uppercase',
  },
  identityHeadingLine: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  identityTitle: {
    overflow: 'hidden',
    margin: 0,
    color: {
      'default': 'rgba(28, 29, 32, 0.92)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(246, 247, 249, 0.92)',
    },
    fontSize: 14,
    fontWeight: 650,
    letterSpacing: '-0.005em',
    lineHeight: '19px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  identityDescription: {
    margin: 0,
    color: {
      'default': 'rgba(53, 55, 61, 0.6)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(231, 233, 238, 0.6)',
    },
    fontSize: 11,
    lineHeight: '16px',
  },
  connectionState: {
    display: 'inline-flex',
    flex: '0 0 auto',
    alignItems: 'center',
    gap: 5,
    color: {
      'default': 'rgba(53, 55, 61, 0.58)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(231, 233, 238, 0.58)',
    },
    fontSize: 10,
    fontWeight: 550,
    lineHeight: '15px',
  },
  connectionStateReady: {
    color: {
      'default': 'rgb(45, 118, 65)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgb(111, 201, 130)',
    },
  },
  stateDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'currentColor',
    boxShadow: '0 0 0 2px color-mix(in srgb, currentColor 14%, transparent)',
  },
  settingRow: {
    'display': 'grid',
    'minHeight': 68,
    'alignItems': 'center',
    'gridTemplateColumns': 'minmax(150px, 0.78fr) minmax(220px, 1.22fr)',
    'gap': 24,
    'borderTopColor': {
      'default': 'rgba(57, 62, 70, 0.1)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(255, 255, 255, 0.1)',
    },
    'borderTopStyle': 'solid',
    'borderTopWidth': 1,
    'paddingBlock': 11,
    'paddingInline': 18,
    '@media (max-width: 560px)': {
      alignItems: 'stretch',
      gridTemplateColumns: 'minmax(0, 1fr)',
      gap: 9,
    },
  },
  rowCopy: {
    display: 'grid',
    minWidth: 0,
    gap: 3,
  },
  rowLabel: {
    color: {
      'default': 'rgba(28, 29, 32, 0.9)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(246, 247, 249, 0.9)',
    },
    fontSize: 13,
    fontWeight: 550,
    lineHeight: '18px',
  },
  rowDescription: {
    margin: 0,
    color: {
      'default': 'rgba(53, 55, 61, 0.58)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(231, 233, 238, 0.58)',
    },
    fontSize: 11,
    lineHeight: '16px',
  },
  nameEditor: {
    minWidth: 0,
    justifyContent: 'flex-end',
    gap: 8,
  },
  nameInput: {
    maxWidth: 260,
  },
  compactButton: {
    minHeight: 30,
    flex: '0 0 auto',
    borderRadius: 7,
    paddingInline: 10,
    fontSize: 12,
    whiteSpace: 'nowrap',
  },
  deviceSection: {
    borderTopColor: {
      'default': 'rgba(57, 62, 70, 0.1)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(255, 255, 255, 0.1)',
    },
    borderTopStyle: 'solid',
    borderTopWidth: 1,
  },
  sectionLabel: {
    margin: 0,
    paddingTop: 10,
    paddingRight: 18,
    paddingBottom: 7,
    paddingLeft: 18,
    color: {
      'default': 'rgba(53, 55, 61, 0.54)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(231, 233, 238, 0.54)',
    },
    fontSize: 10,
    fontWeight: 650,
    letterSpacing: '0.025em',
    lineHeight: '15px',
  },
  deviceList: {
    display: 'grid',
  },
  deviceRow: {
    'display': 'grid',
    'minHeight': 54,
    'alignItems': 'center',
    'gridTemplateColumns': 'minmax(0, 1fr) auto',
    'gap': 12,
    'marginInline': 18,
    'paddingBlock': 8,
    'boxShadow': 'inset 0 -1px rgba(80, 87, 98, 0.09)',
    ':last-child': {
      boxShadow: 'none',
    },
    '@media (max-width: 560px)': {
      alignItems: 'start',
      gridTemplateColumns: 'minmax(0, 1fr)',
    },
  },
  deviceRowStacked: {
    alignItems: 'start',
    gridTemplateColumns: 'minmax(0, 1fr)',
    paddingBlock: 11,
  },
  deviceCopy: {
    display: 'grid',
    minWidth: 0,
    gap: 2,
  },
  deviceName: {
    overflow: 'hidden',
    color: {
      'default': 'rgba(28, 29, 32, 0.9)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(246, 247, 249, 0.9)',
    },
    fontSize: 12,
    fontWeight: 600,
    lineHeight: '17px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  deviceDetail: {
    overflow: 'hidden',
    color: {
      'default': 'rgba(53, 55, 61, 0.52)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(231, 233, 238, 0.52)',
    },
    fontFamily: 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: 10,
    lineHeight: '15px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  emojiConfirmation: {
    'display': 'flex',
    'alignItems': 'center',
    'justifyContent': 'space-between',
    'gap': 12,
    '@media (max-width: 560px)': {
      alignItems: 'stretch',
      flexDirection: 'column',
    },
  },
  emojiCode: {
    display: 'inline-flex',
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: {
      'default': 'rgba(80, 87, 98, 0.12)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(255, 255, 255, 0.11)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    paddingInline: 12,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.46)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(8, 10, 14, 0.22)',
    },
    fontFamily: 'Apple Color Emoji, Segoe UI Emoji, sans-serif',
    fontSize: 20,
    letterSpacing: '0.08em',
    lineHeight: '28px',
    boxShadow: 'inset 0 1px rgba(255, 255, 255, 0.58)',
  },
  emptyState: {
    minHeight: 44,
    margin: 0,
    paddingTop: 11,
    paddingRight: 18,
    paddingBottom: 14,
    paddingLeft: 18,
    color: {
      'default': 'rgba(53, 55, 61, 0.48)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgba(231, 233, 238, 0.48)',
    },
    fontSize: 11,
    lineHeight: '16px',
  },
  removeButton: {
    minHeight: 28,
    borderRadius: 6,
    paddingInline: 8,
    color: {
      'default': 'rgb(176, 65, 54)',
      ':root[data-ui-theme-resolved-appearance="dark"] &': 'rgb(255, 139, 128)',
    },
    fontSize: 11,
    fontWeight: 550,
  },
  feedback: {
    minHeight: 22,
    paddingInline: 4,
    fontSize: 11,
    lineHeight: '16px',
  },
})
