import * as stylex from '@stylexjs/stylex'

const colors = {
  text: 'var(--ui-text, rgba(26, 28, 32, 0.94))',
  muted: 'var(--ui-text-muted, rgba(42, 45, 52, 0.62))',
} as const

const themeColors = {
  accent: 'var(--ui-accent, rgb(0, 113, 227))',
  canvas: 'var(--ui-canvas, rgb(250, 250, 249))',
  controlHover: 'var(--ui-control-hover, rgba(76, 84, 96, 0.07))',
  fieldBorder: 'var(--ui-field-border, rgba(71, 76, 86, 0.2))',
  focus: 'var(--ui-focus, rgba(41, 97, 194, 0.84))',
  controlRadius: 'var(--ui-control-radius, 9px)',
  surfaceRadius: 'var(--ui-surface-radius, 12px)',
  controlStroke: 'var(--ui-control-stroke, 1px)',
  surfaceStroke: 'var(--ui-surface-stroke, 1px)',
  materialFilter: 'var(--ui-material-filter, blur(20px) saturate(170%))',
  onAccent: 'var(--ui-on-accent, white)',
  shadowRaised: 'var(--ui-shadow-raised, 0 20px 48px rgba(26, 32, 42, 0.22), 0 4px 12px rgba(26, 32, 42, 0.1))',
  shadowSubtle: 'var(--ui-shadow-subtle, 0 4px 12px rgba(24, 30, 40, 0.1))',
  surface: 'var(--ui-surface, rgba(250, 250, 251, 0.9))',
  surfaceTranslucent: 'var(--ui-surface-translucent, rgba(244, 246, 249, 0.5))',
  text: 'var(--ui-text, rgba(27, 28, 31, 0.92))',
  textMuted: 'var(--ui-text-muted, rgba(46, 48, 54, 0.64))',
} as const

export const settingsShellStyles = stylex.create({
  window: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    fontFamily: 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    backgroundColor: themeColors.canvas,
    color: themeColors.text,
  },
  dragRegion: {
    position: 'absolute',
    zIndex: 3,
    top: 0,
    right: 0,
    left: 0,
    height: 42,
  },
  layout: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
  },
  sidebar: {
    position: 'relative',
    zIndex: 2,
    display: 'flex',
    width: 204,
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flexDirection: 'column',
    marginTop: 8,
    marginBottom: 8,
    marginLeft: 8,
    borderColor: themeColors.fieldBorder,
    borderStyle: 'solid',
    borderWidth: themeColors.surfaceStroke,
    borderRadius: themeColors.surfaceRadius,
    backgroundColor: themeColors.surfaceTranslucent,
    backdropFilter: {
      'default': themeColors.materialFilter,
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: themeColors.shadowRaised,
  },
  sidebarHeader: {
    display: 'flex',
    height: 72,
    alignItems: 'flex-end',
    paddingRight: 18,
    paddingBottom: 13,
    paddingLeft: 18,
  },
  sidebarTitle: {
    color: themeColors.textMuted,
    fontSize: 12,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '18px',
  },
  navigation: {
    display: 'flex',
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    gap: 3,
    paddingRight: 10,
    paddingLeft: 10,
  },
  navigationItem: {
    display: 'flex',
    width: '100%',
    minHeight: 34,
    alignItems: 'center',
    gap: 10,
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: themeColors.surfaceStroke,
    borderRadius: themeColors.controlRadius,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: {
      'default': 'transparent',
      ':hover': themeColors.controlHover,
      ':active': 'var(--ui-control-pressed, rgba(80, 91, 108, 0.14))',
    },
    color: colors.text,
    cursor: 'default',
    fontSize: 13,
    fontWeight: 500,
    letterSpacing: 0,
    lineHeight: '18px',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${themeColors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.985)',
    },
    transitionDuration: {
      'default': '120ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, color, transform, box-shadow',
    transitionTimingFunction: 'ease-out',
  },
  navigationItemSelected: {
    backgroundColor: themeColors.accent,
    borderColor: themeColors.fieldBorder,
    color: themeColors.onAccent,
    fontWeight: 600,
    boxShadow: themeColors.shadowSubtle,
  },
  navigationIcon: {
    flex: '0 0 auto',
    color: colors.muted,
  },
  navigationIconSelected: {
    color: themeColors.onAccent,
  },
  contentPane: {
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflow: 'hidden',
    backgroundColor: 'transparent',
  },
  contentScroll: {
    width: '100%',
    minHeight: 0,
    overflowY: 'auto',
    paddingTop: 58,
    paddingRight: 'clamp(24px, 7vw, 64px)',
    paddingBottom: 40,
    paddingLeft: 'clamp(24px, 7vw, 64px)',
  },
  contentHeader: {
    marginBottom: 20,
  },
  pageTitle: {
    margin: 0,
    color: themeColors.text,
    fontSize: 17,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '22px',
  },
  pageDescription: {
    marginTop: 7,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: themeColors.textMuted,
    fontSize: 13,
    letterSpacing: 0,
    lineHeight: '19px',
  },
  sectionTitle: {
    marginTop: 24,
    marginRight: 0,
    marginBottom: 10,
    marginLeft: 0,
    color: themeColors.text,
    fontSize: 13,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '18px',
  },
  sectionTitleFirst: {
    marginTop: 0,
  },
  settingsGroup: {
    overflow: 'hidden',
    borderColor: themeColors.fieldBorder,
    borderStyle: 'solid',
    borderWidth: themeColors.surfaceStroke,
    borderRadius: themeColors.surfaceRadius,
    backgroundColor: themeColors.surfaceTranslucent,
    boxShadow: themeColors.shadowSubtle,
  },
  themeSection: {
    marginBottom: 24,
  },
  themeGallery: {
    'display': 'grid',
    'gridTemplateColumns': 'repeat(3, minmax(0, 1fr))',
    'gap': 10,
    'margin': 0,
    'padding': 0,
    'borderWidth': 0,
    '@media (max-width: 720px)': {
      gridTemplateColumns: '1fr',
    },
  },
  themeLegend: {
    marginBottom: 10,
    padding: 0,
    color: themeColors.text,
    fontSize: 13,
    fontWeight: 650,
    lineHeight: '18px',
  },
  themeInput: {
    position: 'absolute',
    width: 1,
    height: 1,
    overflow: 'hidden',
    clip: 'rect(0 0 0 0)',
    clipPath: 'inset(50%)',
    whiteSpace: 'nowrap',
  },
  themeCard: {
    'position': 'relative',
    'display': 'flex',
    'minWidth': 0,
    'minHeight': 150,
    'flexDirection': 'column',
    'gap': 9,
    'borderColor': themeColors.fieldBorder,
    'borderStyle': 'solid',
    'borderWidth': themeColors.surfaceStroke,
    'borderRadius': themeColors.surfaceRadius,
    'padding': 10,
    'backgroundColor': themeColors.surface,
    'color': themeColors.text,
    'cursor': 'default',
    'boxShadow': themeColors.shadowSubtle,
    'transitionDuration': '110ms',
    'transitionProperty': 'background-color, border-color, box-shadow, transform',
    'transitionTimingFunction': 'ease-out',
    ':hover': {
      backgroundColor: themeColors.controlHover,
    },
    ':active': {
      transform: 'translateY(1px)',
    },
    ':has(input:focus-visible)': {
      boxShadow: `0 0 0 2px ${themeColors.focus}`,
    },
  },
  themeCardSelected: {
    borderColor: themeColors.accent,
    boxShadow: `0 0 0 1px ${themeColors.accent}, ${themeColors.shadowSubtle}`,
  },
  themePreview: {
    position: 'relative',
    height: 72,
    overflow: 'hidden',
    borderColor: 'rgba(0, 0, 0, 0.18)',
    borderStyle: 'solid',
    borderWidth: themeColors.controlStroke,
    borderRadius: themeColors.controlRadius,
  },
  themePreviewSidebar: {
    position: 'absolute',
    top: 7,
    bottom: 7,
    left: 7,
    width: '28%',
    borderColor: 'rgba(0, 0, 0, 0.18)',
    borderStyle: 'solid',
    borderWidth: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
  },
  themePreviewContent: {
    position: 'absolute',
    top: 7,
    right: 7,
    bottom: 7,
    left: '36%',
    borderColor: 'rgba(0, 0, 0, 0.18)',
    borderStyle: 'solid',
    borderWidth: 1,
  },
  themePreviewAccent: {
    width: '64%',
    height: 8,
    marginTop: 9,
    marginLeft: 8,
  },
  themePreviewLine: {
    width: '72%',
    height: 4,
    marginTop: 7,
    marginLeft: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.28)',
  },
  themeCardHeader: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  themeCardName: {
    overflow: 'hidden',
    fontSize: 13,
    fontWeight: 650,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  themeSelection: {
    display: 'grid',
    width: 17,
    height: 17,
    flex: '0 0 17px',
    placeItems: 'center',
    borderColor: themeColors.accent,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: themeColors.controlRadius,
    backgroundColor: themeColors.accent,
    color: themeColors.onAccent,
  },
  themeCardDescription: {
    margin: 0,
    color: themeColors.textMuted,
    fontSize: 11,
    lineHeight: '16px',
  },
  appearanceRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    marginTop: 14,
    paddingTop: 14,
    borderTopColor: themeColors.fieldBorder,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
  },
  appearanceLabel: {
    color: themeColors.text,
    fontSize: 13,
    fontWeight: 550,
    lineHeight: '18px',
  },
  themeStatus: {
    marginTop: 8,
    color: themeColors.textMuted,
    fontSize: 11,
    lineHeight: '16px',
  },
  status: {
    display: 'grid',
    width: '100%',
    height: '100%',
    placeItems: 'center',
    backgroundColor: themeColors.canvas,
    color: themeColors.textMuted,
    fontSize: 12,
    letterSpacing: 0,
  },
})
