import * as stylex from '@stylexjs/stylex'

const colors = {
  text: 'rgba(26, 28, 32, 0.94)',
  muted: 'rgba(42, 45, 52, 0.62)',
} as const

export const settingsShellStyles = stylex.create({
  window: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    fontFamily: 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    backgroundColor: {
      'default': 'rgb(255, 255, 255)',
      '@media (prefers-color-scheme: dark)': 'rgb(31, 34, 41)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(242, 244, 248)',
    },
  },
  dragRegion: {
    position: 'absolute',
    zIndex: 3,
    top: 0,
    right: 0,
    left: 0,
    height: 42,
  },
  layout: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
  },
  sidebar: {
    position: 'relative',
    zIndex: 2,
    display: 'flex',
    width: 204,
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flexDirection: 'column',
    marginTop: 8,
    marginBottom: 8,
    marginLeft: 8,
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.62)',
      '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.18)',
      '@media (prefers-contrast: more)': 'rgba(0, 0, 0, 0.42)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 18,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.48)',
      '@media (prefers-color-scheme: dark)': 'rgba(45, 47, 54, 0.58)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(255, 255, 255)',
      '@media (prefers-contrast: more)': 'rgba(248, 249, 251, 0.96)',
    },
    backdropFilter: {
      'default': 'blur(30px) saturate(170%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 12px 30px rgba(31, 38, 48, 0.13), 0 2px 7px rgba(31, 38, 48, 0.09), inset 0 1px rgba(255, 255, 255, 0.8), inset 1px 0 rgba(255, 255, 255, 0.48)',
  },
  sidebarHeader: {
    display: 'flex',
    height: 72,
    alignItems: 'flex-end',
    paddingRight: 18,
    paddingBottom: 13,
    paddingLeft: 18,
  },
  sidebarTitle: {
    color: {
      'default': 'rgba(30, 31, 35, 0.58)',
      '@media (prefers-color-scheme: dark)': 'rgba(246, 247, 249, 0.58)',
    },
    fontSize: 12,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '18px',
  },
  navigation: {
    display: 'flex',
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    gap: 3,
    paddingRight: 10,
    paddingLeft: 10,
  },
  navigationItem: {
    display: 'flex',
    width: '100%',
    minHeight: 34,
    alignItems: 'center',
    gap: 10,
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.32)',
      ':active': 'rgba(80, 91, 108, 0.14)',
    },
    color: colors.text,
    cursor: 'default',
    fontSize: 13,
    fontWeight: 500,
    letterSpacing: 0,
    lineHeight: '18px',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgba(0, 113, 227, 0.78)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.985)',
    },
    transitionDuration: {
      'default': '120ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, color, transform, box-shadow',
    transitionTimingFunction: 'ease-out',
  },
  navigationItemSelected: {
    backgroundColor: {
      'default': 'rgba(0, 113, 227, 0.9)',
      '@media (prefers-color-scheme: dark)': 'rgba(36, 125, 232, 0.86)',
      '@media (prefers-contrast: more)': 'rgb(0, 91, 196)',
    },
    borderColor: 'rgba(255, 255, 255, 0.2)',
    color: 'white',
    fontWeight: 600,
    boxShadow: 'inset 0 1px rgba(255, 255, 255, 0.34), 0 2px 6px rgba(0, 75, 164, 0.22)',
  },
  navigationIcon: {
    flex: '0 0 auto',
    color: colors.muted,
  },
  navigationIconSelected: {
    color: 'white',
  },
  contentPane: {
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflow: 'hidden',
    backgroundColor: 'transparent',
  },
  contentScroll: {
    width: '100%',
    minHeight: 0,
    overflowY: 'auto',
    paddingTop: 58,
    paddingRight: 'clamp(24px, 7vw, 64px)',
    paddingBottom: 40,
    paddingLeft: 'clamp(24px, 7vw, 64px)',
  },
  contentHeader: {
    marginBottom: 20,
  },
  pageTitle: {
    margin: 0,
    color: {
      'default': colors.text,
      '@media (prefers-color-scheme: dark)': 'rgba(249, 250, 252, 0.94)',
    },
    fontSize: 17,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '22px',
  },
  pageDescription: {
    marginTop: 7,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: {
      'default': colors.muted,
      '@media (prefers-color-scheme: dark)': 'rgba(236, 238, 243, 0.62)',
    },
    fontSize: 13,
    letterSpacing: 0,
    lineHeight: '19px',
  },
  sectionTitle: {
    marginTop: 24,
    marginRight: 0,
    marginBottom: 10,
    marginLeft: 0,
    color: {
      'default': colors.text,
      '@media (prefers-color-scheme: dark)': 'rgba(249, 250, 252, 0.94)',
    },
    fontSize: 13,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '18px',
  },
  sectionTitleFirst: {
    marginTop: 0,
  },
  settingsGroup: {
    overflow: 'hidden',
    borderColor: {
      'default': 'rgba(80, 87, 98, 0.13)',
      '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.12)',
      '@media (prefers-contrast: more)': 'rgba(0, 0, 0, 0.35)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 12,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.34)',
      '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.055)',
      '@media (prefers-reduced-transparency: reduce)': 'rgba(245, 246, 248, 0.96)',
    },
    boxShadow: 'inset 0 1px rgba(255, 255, 255, 0.64), inset 0 -1px rgba(68, 74, 84, 0.06)',
  },
  status: {
    display: 'grid',
    width: '100%',
    height: '100%',
    placeItems: 'center',
    backgroundColor: 'rgb(242, 244, 248)',
    color: 'rgba(45, 48, 55, 0.68)',
    fontSize: 12,
    letterSpacing: 0,
  },
})
