import { uiColors } from '@memorilo/ui/theme.stylex'
import * as stylex from '@stylexjs/stylex'

export const settingsShellStyles = stylex.create({
  window: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    fontFamily: uiColors.fontFamily,
    backgroundColor: uiColors.canvas,
    color: uiColors.text,
  },
  dragRegion: {
    position: 'absolute',
    zIndex: 3,
    top: 0,
    right: 0,
    left: 0,
    height: 42,
  },
  layout: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
  },
  contentPane: {
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflow: 'hidden',
    backgroundColor: 'transparent',
  },
  contentScroll: {
    width: '100%',
    minHeight: 0,
    overflowY: 'auto',
    paddingTop: 58,
    paddingRight: 'clamp(24px, 7vw, 64px)',
    paddingBottom: 40,
    paddingLeft: 'clamp(24px, 7vw, 64px)',
  },
  contentHeader: {
    marginBottom: 20,
  },
  pageTitle: {
    margin: 0,
    color: uiColors.text,
    fontSize: 17,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '22px',
  },
  pageDescription: {
    marginTop: 7,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: uiColors.textMuted,
    fontSize: 13,
    letterSpacing: 0,
    lineHeight: '19px',
  },
  sectionTitle: {
    marginTop: 24,
    marginRight: 0,
    marginBottom: 10,
    marginLeft: 0,
    color: uiColors.text,
    fontSize: 13,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '18px',
  },
  sectionTitleFirst: {
    marginTop: 0,
  },
  settingsGroup: {
    overflow: 'hidden',
    borderColor: uiColors.border,
    borderStyle: 'solid',
    borderWidth: uiColors.surfaceStroke,
    borderRadius: uiColors.surfaceRadius,
    backgroundColor: uiColors.surfaceTranslucent,
    backgroundImage: uiColors.surfaceBackgroundImage,
    backdropFilter: {
      'default': uiColors.materialFilter,
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: uiColors.shadowSubtle,
  },
  themeSection: {
    marginBottom: 24,
  },
  themeGallery: {
    'display': 'grid',
    'gridTemplateColumns': 'repeat(3, minmax(0, 1fr))',
    'gap': 10,
    'margin': 0,
    'padding': 0,
    'borderWidth': 0,
    '@media (max-width: 720px)': {
      gridTemplateColumns: '1fr',
    },
  },
  themeLegend: {
    marginBottom: 10,
    padding: 0,
    color: uiColors.text,
    fontSize: 13,
    fontWeight: 650,
    lineHeight: '18px',
  },
  themeInput: {
    position: 'absolute',
    width: 1,
    height: 1,
    overflow: 'hidden',
    clip: 'rect(0 0 0 0)',
    clipPath: 'inset(50%)',
    whiteSpace: 'nowrap',
  },
  themeCard: {
    'position': 'relative',
    'display': 'flex',
    'minWidth': 0,
    'minHeight': 150,
    'flexDirection': 'column',
    'gap': 9,
    'borderColor': uiColors.border,
    'borderStyle': 'solid',
    'borderWidth': uiColors.surfaceStroke,
    'borderRadius': uiColors.surfaceRadius,
    'padding': 10,
    'backgroundColor': uiColors.surface,
    'backgroundImage': uiColors.surfaceBackgroundImage,
    'color': uiColors.text,
    'cursor': 'default',
    'boxShadow': uiColors.shadowSubtle,
    'transitionDuration': '110ms',
    'transitionProperty': 'background-color, border-color, box-shadow, transform',
    'transitionTimingFunction': 'ease-out',
    ':hover': {
      backgroundColor: uiColors.controlHover,
    },
    ':active': {
      transform: 'translateY(1px)',
    },
    ':has(input:focus-visible)': {
      boxShadow: `0 0 0 2px ${uiColors.focus}`,
    },
  },
  themeCardSelected: {
    borderColor: uiColors.accent,
    boxShadow: `0 0 0 1px ${uiColors.accent}, ${uiColors.shadowSubtle}`,
  },
  themePreview: {
    position: 'relative',
    height: 72,
    overflow: 'hidden',
    borderColor: 'rgba(0, 0, 0, 0.18)',
    borderStyle: 'solid',
    borderWidth: uiColors.controlStroke,
    borderRadius: uiColors.controlRadius,
  },
  themePreviewSidebar: {
    position: 'absolute',
    top: 7,
    bottom: 7,
    left: 7,
    width: '28%',
    borderColor: 'rgba(0, 0, 0, 0.18)',
    borderStyle: 'solid',
    borderWidth: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
  },
  themePreviewContent: {
    position: 'absolute',
    top: 7,
    right: 7,
    bottom: 7,
    left: '36%',
    borderColor: 'rgba(0, 0, 0, 0.18)',
    borderStyle: 'solid',
    borderWidth: 1,
  },
  themePreviewAccent: {
    width: '64%',
    height: 8,
    marginTop: 9,
    marginLeft: 8,
  },
  themePreviewLine: {
    width: '72%',
    height: 4,
    marginTop: 7,
    marginLeft: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.28)',
  },
  themeCardHeader: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  themeCardName: {
    overflow: 'hidden',
    fontSize: 13,
    fontWeight: 650,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  themeSelection: {
    display: 'grid',
    width: 17,
    height: 17,
    flex: '0 0 17px',
    placeItems: 'center',
    borderColor: uiColors.accent,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: uiColors.controlRadius,
    backgroundColor: uiColors.accent,
    color: uiColors.onAccent,
  },
  themeCardDescription: {
    margin: 0,
    color: uiColors.textMuted,
    fontSize: 11,
    lineHeight: '16px',
  },
  appearanceRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    marginTop: 14,
    paddingTop: 14,
    borderTopColor: uiColors.fieldBorder,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
  },
  appearanceLabel: {
    color: uiColors.text,
    fontSize: 13,
    fontWeight: 550,
    lineHeight: '18px',
  },
  themeStatus: {
    marginTop: 8,
    color: uiColors.textMuted,
    fontSize: 11,
    lineHeight: '16px',
  },
  status: {
    display: 'grid',
    width: '100%',
    height: '100%',
    placeItems: 'center',
    backgroundColor: uiColors.canvas,
    color: uiColors.textMuted,
    fontSize: 12,
    letterSpacing: 0,
  },
})
