import { uiColors } from '@memorilo/ui/theme.stylex'
import * as stylex from '@stylexjs/stylex'

const spin = stylex.keyframes({
  '0%': { transform: 'rotate(0deg)' },
  '100%': { transform: 'rotate(360deg)' },
})

export const syncServerStatusStyles = stylex.create({
  container: {
    display: 'grid',
    gap: 14,
  },
  statusCard: {
    display: 'grid',
    gap: 14,
    borderColor: {
      'default': uiColors.border,
      '@media (prefers-contrast: more)': uiColors.borderStrong,
    },
    borderStyle: 'solid',
    borderWidth: uiColors.surfaceStroke,
    borderRadius: uiColors.surfaceRadius,
    paddingBlock: 18,
    paddingInline: 20,
    backgroundColor: {
      'default': uiColors.surfaceTranslucent,
      '@media (prefers-reduced-transparency: reduce)': uiColors.surfaceOpaque,
      '@media (prefers-contrast: more)': uiColors.surfaceOpaque,
    },
    backgroundImage: uiColors.surfaceBackgroundImage,
    backdropFilter: {
      'default': uiColors.materialFilter,
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: uiColors.shadowSubtle,
  },
  statusHeader: {
    display: 'grid',
    gridTemplateColumns: 'auto minmax(0, 1fr)',
    gap: 14,
    alignItems: 'start',
  },
  statusIcon: {
    display: 'grid',
    width: 44,
    height: 44,
    placeItems: 'center',
    borderColor: uiColors.border,
    borderStyle: 'solid',
    borderWidth: uiColors.controlStroke,
    borderRadius: uiColors.controlRadius,
    backgroundColor: uiColors.surfaceSunken,
    color: uiColors.accent,
    boxShadow: uiColors.controlShadow,
    transition: 'background-color 0.2s ease, color 0.2s ease',
  },
  statusIconSuccess: {
    backgroundColor: uiColors.statusSuccessSoft,
    color: uiColors.statusSuccess,
  },
  statusIconError: {
    backgroundColor: uiColors.statusDangerSoft,
    color: uiColors.danger,
  },
  statusContent: {
    display: 'grid',
    gap: 6,
    minWidth: 0,
  },
  statusTitleLine: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    minWidth: 0,
  },
  statusTitle: {
    overflow: 'hidden',
    margin: 0,
    color: uiColors.text,
    fontSize: 14,
    fontWeight: 650,
    letterSpacing: '-0.008em',
    lineHeight: '20px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  statusBadge: {
    flex: '0 0 auto',
    fontSize: 12,
    lineHeight: '16px',
    fontWeight: 600,
  },
  serverUrl: {
    overflow: 'hidden',
    margin: 0,
    color: uiColors.textMuted,
    fontSize: 12,
    fontFamily: 'ui-monospace, "SF Mono", Menlo, Monaco, "Cascadia Code", "Segoe UI Mono", "Roboto Mono", monospace',
    lineHeight: '16px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  metadata: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 10,
  },
  metadataItem: {
    color: uiColors.textQuiet,
    fontSize: 12,
    lineHeight: '16px',
  },
  modes: {
    display: 'flex',
    gap: 8,
  },
  modeTag: {
    display: 'inline-flex',
    alignItems: 'center',
    borderRadius: 4,
    paddingBlock: 2,
    paddingInline: 7,
    backgroundColor: uiColors.surfaceSunken,
    color: uiColors.accent,
    fontSize: 12,
    fontWeight: 600,
    lineHeight: '16px',
  },
  alert: {
    flexDirection: 'column',
    gap: 6,
    alignItems: 'flex-start',
  },
  alertDetail: {
    margin: 0,
    marginTop: 2,
    fontSize: 12,
    lineHeight: '16px',
    opacity: 0.92,
  },
  spinner: {
    width: 13,
    height: 13,
    borderColor: 'transparent',
    borderTopColor: 'currentColor',
    borderRightColor: 'currentColor',
    borderStyle: 'solid',
    borderWidth: 1.5,
    borderRadius: '50%',
    animationName: spin,
    animationDuration: '0.8s',
    animationTimingFunction: 'linear',
    animationIterationCount: 'infinite',
  },
})
