import { uiColors } from '@memorilo/ui/theme.stylex'
import * as stylex from '@stylexjs/stylex'

export const syncServerSetupStyles = stylex.create({
  setupCard: {
    display: 'grid',
    gap: 16,
    borderColor: {
      'default': uiColors.border,
      '@media (prefers-contrast: more)': uiColors.borderStrong,
    },
    borderStyle: 'solid',
    borderWidth: uiColors.surfaceStroke,
    borderRadius: uiColors.surfaceRadius,
    paddingBlock: 18,
    paddingInline: 20,
    backgroundColor: {
      'default': uiColors.surfaceTranslucent,
      '@media (prefers-reduced-transparency: reduce)': uiColors.surfaceOpaque,
      '@media (prefers-contrast: more)': uiColors.surfaceOpaque,
    },
    backgroundImage: uiColors.surfaceBackgroundImage,
    backdropFilter: {
      'default': uiColors.materialFilter,
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: uiColors.shadowSubtle,
  },
  setupHeader: {
    display: 'grid',
    gridTemplateColumns: 'auto minmax(0, 1fr)',
    gap: 14,
    alignItems: 'start',
  },
  setupIcon: {
    display: 'grid',
    width: 44,
    height: 44,
    placeItems: 'center',
    borderColor: uiColors.border,
    borderStyle: 'solid',
    borderWidth: uiColors.controlStroke,
    borderRadius: uiColors.controlRadius,
    backgroundColor: uiColors.surfaceSunken,
    color: uiColors.accent,
    boxShadow: uiColors.controlShadow,
  },
  setupHeadingGroup: {
    display: 'grid',
    gap: 4,
    minWidth: 0,
  },
  setupTitle: {
    margin: 0,
    color: uiColors.text,
    fontSize: 14,
    fontWeight: 650,
    letterSpacing: '-0.008em',
    lineHeight: '20px',
  },
  setupDescription: {
    margin: 0,
    color: uiColors.textMuted,
    fontSize: 14,
    lineHeight: '20px',
  },
  setupButton: {
    justifySelf: 'start',
    minHeight: 32,
    paddingInline: 14,
    fontSize: 14,
  },
  wizardContainer: {
    display: 'grid',
    gap: 14,
  },
  restartBanner: {
    flexDirection: 'column',
    gap: 6,
    alignItems: 'flex-start',
  },
  restartNote: {
    margin: 0,
    marginTop: 2,
    fontSize: 12,
    lineHeight: '16px',
    opacity: 0.92,
  },
  wizardCard: {
    display: 'grid',
    gap: 0,
    overflow: 'hidden',
    borderColor: {
      'default': uiColors.border,
      '@media (prefers-contrast: more)': uiColors.borderStrong,
    },
    borderStyle: 'solid',
    borderWidth: uiColors.surfaceStroke,
    borderRadius: uiColors.surfaceRadius,
    backgroundColor: {
      'default': uiColors.surfaceTranslucent,
      '@media (prefers-reduced-transparency: reduce)': uiColors.surfaceOpaque,
      '@media (prefers-contrast: more)': uiColors.surfaceOpaque,
    },
    backgroundImage: uiColors.surfaceBackgroundImage,
    backdropFilter: {
      'default': uiColors.materialFilter,
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: uiColors.shadowSubtle,
  },
  wizardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 16,
    borderBottomColor: uiColors.divider,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingBlock: 16,
    paddingInline: 20,
  },
  wizardTitle: {
    margin: 0,
    color: uiColors.text,
    fontSize: 14,
    fontWeight: 650,
    letterSpacing: '-0.006em',
    lineHeight: '20px',
  },
  stepIndicator: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
  },
  stepText: {
    color: uiColors.textQuiet,
    fontSize: 12,
    fontWeight: 550,
    lineHeight: '16px',
  },
  stepDots: {
    display: 'flex',
    gap: 6,
  },
  stepDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: uiColors.divider,
    transition: 'background-color 0.2s ease',
  },
  stepDotActive: {
    backgroundColor: uiColors.accent,
  },
  wizardContent: {
    display: 'grid',
    gap: 20,
    paddingBlock: 20,
    paddingInline: 20,
  },
  successStatus: {
    borderRadius: uiColors.controlRadius,
    padding: 10,
    backgroundColor: uiColors.statusSuccessSoft,
  },
  fieldGroup: {
    display: 'grid',
    gap: 8,
  },
  fieldLabel: {
    color: uiColors.text,
    fontSize: 14,
    fontWeight: 600,
    lineHeight: '20px',
  },
  fieldHelp: {
    margin: 0,
    color: uiColors.textMuted,
    fontSize: 12,
    lineHeight: '16px',
  },
  responseDisplay: {
    overflow: 'hidden',
    borderColor: uiColors.border,
    borderStyle: 'solid',
    borderWidth: uiColors.controlStroke,
    borderRadius: uiColors.controlRadius,
    padding: 12,
    backgroundColor: uiColors.surfaceSunken,
    boxShadow: uiColors.controlShadow,
  },
  responseCode: {
    display: 'block',
    overflow: 'auto',
    color: uiColors.text,
    fontFamily: 'ui-monospace, "SF Mono", Menlo, Monaco, "Cascadia Code", "Segoe UI Mono", "Roboto Mono", "Oxygen Mono", "Ubuntu Monospace", "Source Code Pro", "Fira Mono", "Droid Sans Mono", "Courier New", monospace',
    fontSize: 12,
    lineHeight: '16px',
    wordBreak: 'break-all',
  },
  copyButton: {
    justifySelf: 'start',
    minHeight: 30,
    paddingInline: 12,
    fontSize: 12,
  },
  wizardActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 10,
    borderTopColor: uiColors.divider,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 16,
  },
})
