import * as stylex from '@stylexjs/stylex'

export const readerPageStyles = stylex.create({
  page: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    paddingTop: 56,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
  },
  pageOpen: {
    paddingTop: 0,
  },
  empty: {
    display: 'grid',
    minHeight: 0,
    flex: 1,
    alignContent: 'center',
    justifyItems: 'center',
    padding: 32,
    color: 'rgba(48, 46, 51, 0.62)',
  },
  emptyIcon: {
    width: 34,
    height: 34,
    marginBottom: 14,
    color: 'rgba(48, 46, 51, 0.42)',
  },
  emptyTitle: {
    marginTop: 0,
    marginBottom: 6,
    color: 'rgba(27, 27, 30, 0.9)',
    fontSize: 15,
    fontWeight: 600,
    lineHeight: '21px',
  },
  emptyDetail: {
    maxWidth: 360,
    marginTop: 0,
    marginBottom: 18,
    fontSize: 12,
    lineHeight: '18px',
    textAlign: 'center',
  },
  openButton: {
    display: 'flex',
    height: 32,
    alignItems: 'center',
    gap: 7,
    borderColor: 'rgba(0, 90, 190, 0.22)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 12,
    paddingLeft: 11,
    backgroundColor: {
      'default': 'rgb(0, 113, 227)',
      ':hover': 'rgb(0, 103, 211)',
      ':active': 'rgb(0, 92, 192)',
    },
    color: 'white',
    cursor: 'default',
    fontSize: 12,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': '0 1px 2px rgba(0, 64, 140, 0.18)',
      ':focus-visible': '0 0 0 3px rgba(41, 97, 194, 0.38)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.97)',
    },
    transitionDuration: {
      'default': '90ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  toolbarActionButton: {
    position: 'relative',
    display: 'grid',
    width: 30,
    height: 30,
    flexShrink: 0,
    alignItems: 'center',
    justifyItems: 'center',
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(69, 72, 79, 0.08)',
      ':active': 'rgba(69, 72, 79, 0.14)',
      ':focus-visible': 'rgba(69, 72, 79, 0.08)',
    },
    color: 'rgba(27, 27, 30, 0.9)',
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      ':focus-visible': '0 0 0 2px rgba(41, 97, 194, 0.72)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  fileInput: {
    position: 'absolute',
    width: 1,
    height: 1,
    overflow: 'hidden',
    clip: 'rect(0, 0, 0, 0)',
    whiteSpace: 'nowrap',
  },
  routeStatus: {
    display: 'flex',
    minHeight: 0,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    padding: 32,
    color: 'rgba(48, 46, 51, 0.58)',
    textAlign: 'center',
  },
  statusIcon: {
    marginBottom: 12,
    color: 'rgba(48, 46, 51, 0.42)',
  },
  statusTitle: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 6,
    marginLeft: 0,
    color: 'rgba(27, 27, 30, 0.9)',
    fontSize: 15,
    fontWeight: 620,
    letterSpacing: 0,
    lineHeight: '21px',
  },
  statusDetail: {
    maxWidth: 380,
    marginTop: 0,
    marginRight: 0,
    marginBottom: 18,
    marginLeft: 0,
    color: 'rgba(48, 46, 51, 0.62)',
    fontSize: 12,
    lineHeight: '18px',
  },
  backLink: {
    textDecoration: 'none',
  },
  spinner: {
    marginBottom: 12,
    animationDuration: {
      'default': '850ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    animationIterationCount: 'infinite',
    animationName: stylex.keyframes({
      to: { transform: 'rotate(360deg)' },
    }),
    animationTimingFunction: 'linear',
  },
})
