import * as stylex from '@stylexjs/stylex'

const colors = {
  blue500: 'oklch(0.623 0.214 259.815)',
  canvas: '#ffffff',
  gray50: 'oklch(0.985 0.002 247.839)',
  gray100: 'oklch(0.967 0.003 264.542)',
  gray200: 'oklch(0.928 0.006 264.531)',
  gray800: 'oklch(0.278 0.033 256.848)',
  gray900: 'oklch(0.21 0.034 264.665)',
} as const

const reveal = stylex.keyframes({
  from: { opacity: 0, transform: 'translateY(4px)' },
  to: { opacity: 1, transform: 'translateY(0)' },
})

export const cardPreviewStyles = stylex.create({
  surface: {
    boxSizing: 'border-box',
    width: '100%',
    maxWidth: 720,
    borderColor: colors.gray200,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 16,
    paddingBlock: 28,
    paddingInline: 30,
    backgroundColor: colors.canvas,
    boxShadow: '0 12px 40px rgb(26 39 51 / 8%)',
    color: colors.gray900,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: 17,
    lineHeight: 1.65,
  },
  embeddedSurface: {
    maxWidth: 'none',
    borderWidth: 0,
    borderRadius: 0,
    paddingBlock: 20,
    paddingInline: 20,
    boxShadow: 'none',
    fontSize: 15,
    lineHeight: 1.6,
  },
  blockYellow: { backgroundColor: '#fffaf0' },
  blockGreen: { backgroundColor: '#f4fbf4' },
  blockBlue: { backgroundColor: '#f3f8ff' },
  blockPink: { backgroundColor: '#fff6f9' },
  blockOrange: { backgroundColor: '#fff8f0' },
  blockPurple: { backgroundColor: '#f8f5ff' },
  content: {
    minWidth: 0,
  },
  paragraph: {
    marginBlock: 0,
    whiteSpace: 'pre-wrap',
  },
  heading: {
    marginBlock: 0,
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: 1.25,
  },
  blockquote: {
    marginBlock: 0,
    marginInline: 0,
    borderLeftColor: colors.gray200,
    borderLeftStyle: 'solid',
    borderLeftWidth: 3,
    paddingLeft: 16,
    color: colors.gray800,
  },
  codeBlock: {
    overflowX: 'auto',
    borderRadius: 8,
    padding: 12,
    backgroundColor: colors.gray900,
    color: colors.gray50,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 14,
  },
  inlineCode: {
    borderRadius: 4,
    paddingBlock: 1,
    paddingInline: 4,
    backgroundColor: colors.gray100,
    color: '#8d2d42',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: '0.9em',
  },
  link: {
    color: colors.blue500,
    textDecorationLine: 'underline',
    textUnderlineOffset: 2,
  },
  formula: {
    display: 'inline-flex',
    alignItems: 'center',
    maxWidth: '100%',
    overflowX: 'auto',
    verticalAlign: 'middle',
  },
  formulaBlock: {
    display: 'flex',
    justifyContent: 'center',
    marginBlock: 12,
  },
  hiddenCloze: {
    display: 'inline-flex',
    minWidth: '2.5em',
    height: '1.35em',
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomColor: '#4f86c6',
    borderBottomStyle: 'solid',
    borderBottomWidth: 2,
    borderRadius: 4,
    paddingInline: 6,
    backgroundColor: '#e8f1ff',
    color: '#2563a9',
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: 1,
    verticalAlign: 'baseline',
  },
  revealedCloze: {
    borderRadius: 4,
    paddingInline: 2,
    backgroundColor: '#e8f1ff',
    boxShadow: 'inset 0 -1px 0 #79a9df',
    color: '#174f8d',
  },
  inlineYellow: { backgroundColor: '#fff1a8' },
  inlineGreen: { backgroundColor: '#cceecf' },
  inlineBlue: { backgroundColor: '#cfe7ff' },
  inlinePink: { backgroundColor: '#ffd8e7' },
  inlineOrange: { backgroundColor: '#ffdfb8' },
  inlinePurple: { backgroundColor: '#e6d9ff' },
  answer: {
    animationName: {
      'default': reveal,
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
    animationDuration: '160ms',
    animationTimingFunction: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
  },
  divider: {
    height: 1,
    marginBlock: 24,
    borderWidth: 0,
    backgroundColor: colors.gray200,
  },
  actions: {
    display: 'flex',
    justifyContent: 'center',
    marginTop: 26,
  },
  revealButton: {
    minHeight: 42,
    borderWidth: 0,
    borderRadius: 9,
    paddingBlock: 10,
    paddingInline: 18,
    backgroundColor: {
      'default': colors.gray900,
      ':hover': colors.gray800,
    },
    boxShadow: {
      'default': '0 1px 2px rgb(0 0 0 / 12%)',
      ':focus-visible': `0 0 0 3px ${colors.blue500}`,
    },
    color: '#ffffff',
    cursor: 'pointer',
    font: 'inherit',
    fontSize: 14,
    fontWeight: 650,
    outline: 'none',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.97)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform, box-shadow',
    transitionTimingFunction: 'ease-out',
  },
  itemList: {
    display: 'grid',
    gap: 10,
    marginBlock: 16,
    paddingLeft: 26,
  },
  item: {
    paddingLeft: 4,
  },
  nestedList: {
    display: 'grid',
    gap: 6,
    marginBlock: 8,
    paddingLeft: 26,
  },
  table: {
    width: '100%',
    marginBlock: 12,
    borderCollapse: 'collapse',
  },
  tableCell: {
    borderColor: colors.gray200,
    borderStyle: 'solid',
    borderWidth: 1,
    paddingBlock: 8,
    paddingInline: 10,
    textAlign: 'left',
    verticalAlign: 'top',
  },
  image: {
    display: 'block',
    maxWidth: '100%',
    height: 'auto',
    borderRadius: 8,
  },
})
