import inject from '@stylexjs/stylex/lib/stylex-inject'

const cardContentRules = [
  '[data-editor-card-topic] [data-card-delimiter] { display: none !important; }',
  '[data-editor-card-topic] [data-card-hover-controls] { display: none !important; }',
  '[data-editor-card-preview-disabled] [data-card-control="preview"] { display: none !important; }',
  '[data-editor-card-preview-disabled] [data-cloze-card-controls] { display: none !important; }',
  '[data-editor-card-preview-disabled] [data-card-hover-controls]:not([data-cloze-card-controls]) { width: 34px; }',
  '[data-editor-card-topic] [data-card-definition-scope] > .list-content > [data-card-material] { display: none !important; }',
  '[data-editor-card-topic] [data-cloze-group-id], [data-editor-card-topic] [data-inline-highlight] { background: transparent; box-shadow: none; color: inherit; }',
  '[data-editor-card-topic] [data-block-highlight] > .list-content { border-radius: 0; background: transparent; }',
  '[data-editor-content] [data-card-delimiter] { position: static; display: inline-flex; min-width: 1.1em; height: 1.1em; align-items: center; justify-content: center; margin-inline: 0.12em; border-radius: 999px; padding-inline: 0.06em; background: transparent; color: #4f78a6; cursor: default; font-size: 0.88em; font-weight: 650; line-height: 1; user-select: none; vertical-align: -0.05em; }',
  '[data-editor-content] [data-card-direction-symbol] { display: inline-flex; transform: rotate(0deg); transition: color 120ms ease, transform 160ms cubic-bezier(0.23, 1, 0.32, 1); }',
  '[data-editor-content] [data-card-delimiter].card-delimiter-multiline [data-card-direction-symbol] { transform: rotate(90deg); }',
  '[data-editor-content] [data-card-delimiter].ProseMirror-selectednode, [data-editor-content] [data-card-delimiter].card-delimiter-selected { color: #285b91; }',
  '[data-editor-content] [data-card-hover-controls] { position: absolute; z-index: 4; top: 0; right: -6px; box-sizing: border-box; display: inline-flex; width: 60px; height: 32px; align-items: center; gap: 2px; border: 0; border-radius: 10px; padding: 3px; background-color: rgb(245 248 251 / 72%); backdrop-filter: blur(18px) saturate(165%); box-shadow: 0 10px 24px -16px rgb(24 39 54 / 42%), inset 0 1px 0 rgb(255 255 255 / 94%), inset 0 -1px 0 rgb(72 94 116 / 9%); filter: blur(0.8px); opacity: 0; pointer-events: none; transform: translate3d(0, 2px, 0) scale(0.97); transform-origin: right top; transition: opacity 140ms ease-out, transform 160ms cubic-bezier(0.23, 1, 0.32, 1), filter 140ms ease-out; }',
  '[data-editor-content] [data-cloze-card-controls] { width: 34px; }',
  '[data-editor-content] [data-card-control] { display: inline-flex; width: 26px; height: 26px; align-items: center; justify-content: center; border: 0; border-radius: 7px; padding: 0; background-color: transparent; color: #425e76; cursor: pointer; outline: none; transition: background-color 120ms ease, box-shadow 120ms ease, color 120ms ease, transform 120ms cubic-bezier(0.23, 1, 0.32, 1); }',
  '[data-editor-content] [data-card-control]:hover { background-color: rgb(255 255 255 / 68%); box-shadow: inset 0 0 0 1px rgb(255 255 255 / 72%), 0 2px 6px rgb(28 47 65 / 12%); color: #1f5687; }',
  '[data-editor-content] [data-card-control]:active { background-color: rgb(227 238 247 / 78%); transform: scale(0.94); }',
  '[data-editor-content] [data-card-control]:focus-visible { box-shadow: 0 0 0 2px rgb(68 132 198 / 42%); }',
  '[data-editor-readonly] [data-card-hover-controls] { display: none; }',
  '[data-editor-content] [data-card-definition-scope] { position: relative; isolation: isolate; border-radius: 14px; background-color: transparent; }',
  '[data-editor-content] [data-card-definition-scope] > .list-content > [data-card-material] { position: absolute; z-index: -1; inset: -3px -9px; display: block; border: 1px solid transparent; border-radius: 13px; background-color: transparent; box-shadow: none; opacity: 0; pointer-events: none; transform: scale(0.992); transform-origin: center; backdrop-filter: blur(0) saturate(100%); transition: opacity 150ms ease-out, transform 170ms cubic-bezier(0.23, 1, 0.32, 1), background-color 150ms ease-out, border-color 150ms ease-out, backdrop-filter 170ms ease-out, box-shadow 170ms ease-out; }',
  '[data-editor-content] [data-card-definition-scope]:hover:not(:has([data-card-definition-scope]:hover)) > .list-content > [data-card-material], [data-editor-content] [data-card-definition-scope]:focus-within > .list-content > [data-card-material], [data-editor-content] [data-card-definition-scope][data-card-scope-active] > .list-content > [data-card-material] { border-color: rgb(255 255 255 / 82%); background-color: rgb(245 248 251 / 62%); backdrop-filter: blur(18px) saturate(155%); box-shadow: 0 0 0 1px rgb(75 96 117 / 10%), 0 18px 38px -28px rgb(23 39 54 / 55%), inset 0 1px 0 rgb(255 255 255 / 96%), inset 0 -1px 0 rgb(70 91 111 / 8%); opacity: 1; transform: scale(1); }',
  '[data-editor-content] [data-card-definition-scope][data-card-scope-active] > .list-content > [data-card-material] { border-color: rgb(255 255 255 / 92%); background-color: rgb(243 247 250 / 72%); box-shadow: 0 0 0 1px rgb(65 91 116 / 14%), 0 20px 42px -28px rgb(22 39 55 / 62%), inset 0 1px 0 rgb(255 255 255 / 100%), inset 0 -1px 0 rgb(61 86 110 / 10%); }',
  '[data-editor-content] [data-card-definition-scope]:hover:not(:has([data-card-definition-scope]:hover)) [data-card-hover-controls], [data-editor-content] [data-card-definition-scope]:focus-within [data-card-hover-controls], [data-editor-content] [data-card-definition-scope][data-card-scope-active] [data-card-hover-controls] { filter: blur(0); opacity: 1; pointer-events: auto; transform: translate3d(0, 0, 0) scale(1); }',
  '[data-editor-content] [data-cloze-group-id] { border-radius: 0.16em; padding-inline: 0.06em; background: #edf4fc; box-shadow: inset 0 -1px 0 #82a9d3; color: inherit; }',
  '[data-editor-content] [data-inline-highlight="yellow"] { background: #fff1a8; }',
  '[data-editor-content] [data-inline-highlight="green"] { background: #cceecf; }',
  '[data-editor-content] [data-inline-highlight="blue"] { background: #cfe7ff; }',
  '[data-editor-content] [data-inline-highlight="pink"] { background: #ffd8e7; }',
  '[data-editor-content] [data-inline-highlight="orange"] { background: #ffdfb8; }',
  '[data-editor-content] [data-inline-highlight="purple"] { background: #e6d9ff; }',
  '[data-editor-content] [data-block-highlight="yellow"] > .list-content { border-radius: 0.3rem; background: #fff8d8; }',
  '[data-editor-content] [data-block-highlight="green"] > .list-content { border-radius: 0.3rem; background: #eaf7eb; }',
  '[data-editor-content] [data-block-highlight="blue"] > .list-content { border-radius: 0.3rem; background: #eaf4ff; }',
  '[data-editor-content] [data-block-highlight="pink"] > .list-content { border-radius: 0.3rem; background: #fff0f5; }',
  '[data-editor-content] [data-block-highlight="orange"] > .list-content { border-radius: 0.3rem; background: #fff1df; }',
  '[data-editor-content] [data-block-highlight="purple"] > .list-content { border-radius: 0.3rem; background: #f4efff; }',
  '@media (prefers-reduced-motion: reduce) { [data-editor-content] [data-card-direction-symbol], [data-editor-content] [data-card-material], [data-editor-content] [data-card-hover-controls], [data-editor-content] [data-card-control] { transition-duration: 0ms; } [data-editor-content] [data-card-material], [data-editor-content] [data-card-hover-controls] { transform: none; } }',
  '@media (prefers-reduced-transparency: reduce) { [data-editor-content] [data-card-definition-scope]:hover:not(:has([data-card-definition-scope]:hover)) > .list-content > [data-card-material], [data-editor-content] [data-card-definition-scope]:focus-within > .list-content > [data-card-material], [data-editor-content] [data-card-definition-scope][data-card-scope-active] > .list-content > [data-card-material] { background-color: #f4f7f9; backdrop-filter: none; } [data-editor-content] [data-card-hover-controls] { background-color: #f4f7f9; backdrop-filter: none; } }',
  '@media (prefers-contrast: more) { [data-editor-content] [data-card-definition-scope]:hover:not(:has([data-card-definition-scope]:hover)) > .list-content > [data-card-material], [data-editor-content] [data-card-definition-scope]:focus-within > .list-content > [data-card-material], [data-editor-content] [data-card-definition-scope][data-card-scope-active] > .list-content > [data-card-material] { border-color: #52677d; background-color: #ffffff; box-shadow: 0 0 0 1px #ffffff, 0 0 0 3px #52677d; } [data-editor-content] [data-card-hover-controls] { border-color: #52677d; background-color: #ffffff; box-shadow: 0 0 0 1px #ffffff, 0 0 0 2px #52677d; } }',
]

for (const rule of cardContentRules)
  inject({ ltr: rule, priority: 1 })
