import inject from '@stylexjs/stylex/lib/stylex-inject'

const cardContentRules = [
  '[data-editor-learning-disabled] [data-editor-content] [data-card-delimiter] { display: none; }',
  '[data-editor-card-topic] [data-card-delimiter] { display: none !important; }',
  '[data-editor-card-topic] [data-card-hover-controls] { display: none !important; }',
  '[data-editor-card-preview-disabled] [data-card-control="preview"] { display: none !important; }',
  '[data-editor-card-preview-disabled] [data-cloze-card-controls] { display: none !important; }',
  '[data-editor-card-preview-disabled] [data-card-hover-controls]:not([data-cloze-card-controls]) { width: 34px; }',
  '[data-editor-card-topic] [data-card-definition-scope] > .list-content > [data-card-material] { display: none !important; }',
  '[data-editor-card-topic] [data-cloze-group-id], [data-editor-card-topic] [data-inline-highlight] { background: transparent; box-shadow: none; color: inherit; }',
  '[data-editor-card-topic] [data-block-highlight] > .list-content { border-radius: 0; background: transparent; }',
  '[data-editor-content] [data-card-delimiter] { position: static; display: inline-flex; min-width: 1.1em; height: 1.1em; align-items: center; justify-content: center; margin-inline: 0.12em; border-radius: 999px; padding-inline: 0.06em; background: transparent; color: #4f78a6; cursor: default; font-size: 0.88em; font-weight: 650; line-height: 1; user-select: none; vertical-align: -0.05em; }',
  '[data-editor-content] [data-card-direction-symbol] { display: inline-flex; transform: rotate(0deg); transition: color 120ms ease, transform 160ms cubic-bezier(0.23, 1, 0.32, 1); }',
  '[data-editor-content] [data-card-delimiter].card-delimiter-multiline [data-card-direction-symbol] { transform: rotate(90deg); }',
  '[data-editor-content] [data-card-delimiter].ProseMirror-selectednode, [data-editor-content] [data-card-delimiter].card-delimiter-selected { color: #285b91; }',
  '[data-editor-content] [data-card-hover-controls] { position: absolute; z-index: 4; top: 0; right: -6px; box-sizing: border-box; display: inline-flex; width: 60px; height: 32px; align-items: center; gap: 2px; border: var(--ui-control-stroke, 1px) solid var(--ui-border, rgb(71 76 86 / 20%)); border-radius: var(--ui-control-radius, 9px); padding: 3px; background-color: var(--ui-surface-translucent, rgb(244 246 249 / 72%)); background-image: var(--ui-control-background-image, none); backdrop-filter: var(--ui-material-filter, blur(18px) saturate(155%)); box-shadow: var(--ui-control-shadow, 0 4px 12px rgb(24 30 40 / 10%)); filter: blur(0.8px); opacity: 0; pointer-events: none; transform: translate3d(0, 2px, 0) scale(0.97); transform-origin: right top; transition: opacity 140ms ease-out, transform 160ms cubic-bezier(0.23, 1, 0.32, 1), filter 140ms ease-out; }',
  '[data-editor-content] [data-cloze-card-controls] { width: 34px; }',
  '[data-editor-content] [data-card-control] { display: inline-flex; width: 26px; height: 26px; align-items: center; justify-content: center; border: 0; border-radius: var(--ui-control-radius, 9px); padding: 0; background-color: transparent; color: var(--ui-text-muted, rgb(46 48 54 / 64%)); cursor: pointer; outline: none; transition: background-color 120ms ease, box-shadow 120ms ease, color 120ms ease, transform 120ms cubic-bezier(0.23, 1, 0.32, 1); }',
  '[data-editor-content] [data-card-control]:hover { background-color: var(--ui-control-hover, rgb(76 84 96 / 7%)); color: var(--ui-text, rgb(27 28 31 / 92%)); }',
  '[data-editor-content] [data-card-control]:active { background-color: var(--ui-control-pressed, rgb(80 91 108 / 14%)); transform: scale(0.94); }',
  '[data-editor-content] [data-card-control]:focus-visible { box-shadow: 0 0 0 2px var(--ui-focus, rgb(41 97 194 / 84%)); }',
  '[data-editor-readonly] [data-card-hover-controls] { display: none; }',
  '[data-editor-content] [data-card-definition-scope] { position: relative; isolation: isolate; border-radius: var(--ui-surface-radius, 12px); background-color: transparent; }',
  '[data-editor-content] [data-card-definition-scope] > .list-content > [data-card-material] { position: absolute; z-index: -1; inset: -3px -9px; display: block; border: var(--ui-surface-stroke, 1px) solid transparent; border-radius: var(--ui-surface-radius, 12px); background-color: transparent; box-shadow: none; opacity: 0; pointer-events: none; transform: scale(0.992); transform-origin: center; backdrop-filter: none; transition: opacity 150ms ease-out, transform 170ms cubic-bezier(0.23, 1, 0.32, 1), background-color 150ms ease-out, border-color 150ms ease-out, backdrop-filter 170ms ease-out, box-shadow 170ms ease-out; }',
  '[data-editor-content] [data-card-definition-scope]:hover:not(:has([data-card-definition-scope]:hover)) > .list-content > [data-card-material], [data-editor-content] [data-card-definition-scope]:focus-within > .list-content > [data-card-material], [data-editor-content] [data-card-definition-scope][data-card-scope-active] > .list-content > [data-card-material] { border-color: var(--ui-border, rgb(71 76 86 / 20%)); background-color: var(--ui-surface-translucent, rgb(244 246 249 / 62%)); background-image: var(--ui-surface-background-image, none); backdrop-filter: var(--ui-material-filter, blur(18px) saturate(155%)); box-shadow: var(--ui-shadow-subtle, 0 4px 12px rgb(24 30 40 / 10%)); opacity: 1; transform: scale(1); }',
  '[data-editor-content] [data-card-definition-scope][data-card-scope-active] > .list-content > [data-card-material] { border-color: var(--ui-border-strong, rgb(46 51 59 / 50%)); background-color: var(--ui-surface-raised, rgb(250 251 253 / 96%)); box-shadow: var(--ui-shadow-raised, 0 20px 48px rgb(26 32 42 / 22%)); }',
  '[data-editor-content] [data-card-definition-scope]:hover:not(:has([data-card-definition-scope]:hover)) [data-card-hover-controls], [data-editor-content] [data-card-definition-scope]:focus-within [data-card-hover-controls], [data-editor-content] [data-card-definition-scope][data-card-scope-active] [data-card-hover-controls] { filter: blur(0); opacity: 1; pointer-events: auto; transform: translate3d(0, 0, 0) scale(1); }',
  '[data-editor-content] [data-cloze-group-id] { border-radius: 0.16em; padding-inline: 0.06em; background: #edf4fc; box-shadow: inset 0 -1px 0 #82a9d3; color: inherit; }',
  '[data-editor-content] [data-inline-highlight="yellow"] { background: #fff1a8; }',
  '[data-editor-content] [data-inline-highlight="green"] { background: #cceecf; }',
  '[data-editor-content] [data-inline-highlight="blue"] { background: #cfe7ff; }',
  '[data-editor-content] [data-inline-highlight="pink"] { background: #ffd8e7; }',
  '[data-editor-content] [data-inline-highlight="orange"] { background: #ffdfb8; }',
  '[data-editor-content] [data-inline-highlight="purple"] { background: #e6d9ff; }',
  '[data-editor-content] [data-block-highlight="yellow"] > .list-content { border-radius: 0.3rem; background: #fff8d8; }',
  '[data-editor-content] [data-block-highlight="green"] > .list-content { border-radius: 0.3rem; background: #eaf7eb; }',
  '[data-editor-content] [data-block-highlight="blue"] > .list-content { border-radius: 0.3rem; background: #eaf4ff; }',
  '[data-editor-content] [data-block-highlight="pink"] > .list-content { border-radius: 0.3rem; background: #fff0f5; }',
  '[data-editor-content] [data-block-highlight="orange"] > .list-content { border-radius: 0.3rem; background: #fff1df; }',
  '[data-editor-content] [data-block-highlight="purple"] > .list-content { border-radius: 0.3rem; background: #f4efff; }',
  '@media (prefers-reduced-motion: reduce) { [data-editor-content] [data-card-direction-symbol], [data-editor-content] [data-card-material], [data-editor-content] [data-card-hover-controls], [data-editor-content] [data-card-control] { transition-duration: 0ms; } [data-editor-content] [data-card-material], [data-editor-content] [data-card-hover-controls] { transform: none; } }',
  '@media (prefers-reduced-transparency: reduce) { [data-editor-content] [data-card-definition-scope]:hover:not(:has([data-card-definition-scope]:hover)) > .list-content > [data-card-material], [data-editor-content] [data-card-definition-scope]:focus-within > .list-content > [data-card-material], [data-editor-content] [data-card-definition-scope][data-card-scope-active] > .list-content > [data-card-material], [data-editor-content] [data-card-hover-controls] { background-color: var(--ui-surface-opaque, rgb(250 251 253)); background-image: none; backdrop-filter: none; } }',
  '@media (prefers-contrast: more) { [data-editor-content] [data-card-definition-scope]:hover:not(:has([data-card-definition-scope]:hover)) > .list-content > [data-card-material], [data-editor-content] [data-card-definition-scope]:focus-within > .list-content > [data-card-material], [data-editor-content] [data-card-definition-scope][data-card-scope-active] > .list-content > [data-card-material], [data-editor-content] [data-card-hover-controls] { border-color: var(--ui-border-strong, rgb(46 51 59 / 50%)); background-color: var(--ui-surface-opaque, rgb(250 251 253)); background-image: none; } }',
]

for (const rule of cardContentRules)
  inject({ ltr: rule, priority: 1 })
