import antfu from '@antfu/eslint-config'

export default antfu({
  react: true,
  ignores: [
    'dist/**',
    'node_modules/**',
    'build/**',
    '.*/**',
    'src-tauri/target/**',
    'src-tauri/gen/**',
    '**/*.gen.ts',
    '**/rust/android/.tauri/**',
    '**/rust/android/build/**',
    '**/permissions/autogenerated/**',
    '**/permissions/schemas/schema.json',
    '**/rust/permissions/schemas/schema.json',
  ],
})
