packages:
  - apps/*
  - packages/*

catalog:
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-switch': ^1.2.6
  '@radix-ui/react-tooltip': ^1.2.8
  '@tauri-apps/plugin-fs': ^2.4.4
  '@tauri-apps/plugin-log': 2.7.1
  '@tauri-apps/plugin-opener': ^2.5.2
  '@types/is-hotkey': ^0.1.10
  '@types/prismjs': ^1.26.5
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vscode/vscode-languagedetection': ^1.0.22
  cmdk: ^1.1.1
  dayjs: ^1.11.19
  effect: ^3.19.12
  es-toolkit: ^1.43.0
  i18next: ^25.7.3
  image-extensions: ^1.1.0
  is-hotkey: ^0.2.0
  jotai: ^2.16.0
  katex: ^0.16.27
  mitt: ^3.0.1
  motion: 12.23.25
  prismjs: ^1.30.0
  react: ^19.2.3
  react-dom: ^19.2.3
  react-i18next: ^16.5.0
  react-icons: ^5.5.0
  react-use: ^17.6.0
  slate: ^0.120.0
  slate-history: ^0.113.1
  slate-hotkeys: ^0.2.11
  slate-react: ^0.120.0
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  vite: ^7.3.0
  vitest: ^4.0.15
  zod: ^4.2.0

catalogMode: prefer

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - esbuild

shellEmulator: true

trustPolicy: no-downgrade
