import * as stylex from '@stylexjs/stylex'

const colors = {
  focus: 'rgba(0, 96, 204, 0.72)',
  text: 'rgba(25, 28, 34, 0.9)',
  textMuted: 'rgba(49, 54, 63, 0.62)',
} as const

export const learningRouteStyles = stylex.create({
  startReviewButton: {
    display: 'inline-flex',
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderWidth: 0,
    borderRadius: 15,
    paddingRight: 11,
    paddingLeft: 10,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.3)',
      ':active': 'rgba(58, 66, 78, 0.14)',
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    color: 'rgb(0, 94, 196)',
    cursor: 'default',
    fontSize: 11,
    fontWeight: 640,
    letterSpacing: 0,
    outline: 'none',
    textDecoration: 'none',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.96)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  page: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flexDirection: 'column',
    paddingTop: 56,
    backgroundColor: 'rgb(255, 255, 255)',
    color: colors.text,
  },
  tabRegion: {
    position: 'relative',
    zIndex: 2,
    display: 'flex',
    width: '100%',
    flex: '0 0 auto',
    justifyContent: 'center',
    paddingTop: 12,
    paddingRight: 20,
    paddingLeft: 20,
  },
  tabList: {
    position: 'relative',
    display: 'grid',
    width: 'min(196px, 100%)',
    height: 32,
    isolation: 'isolate',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 2,
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.88)',
      '@media (prefers-contrast: more)': 'rgba(39, 44, 52, 0.72)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    padding: 3,
    backgroundColor: {
      'default': 'rgba(244, 246, 249, 0.72)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(235, 239, 245)',
      '@media (prefers-contrast: more)': 'rgb(245, 247, 250)',
    },
    backdropFilter: {
      'default': 'blur(18px) saturate(165%) contrast(1.045) brightness(1.015)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': '0 3px 8px rgba(32, 42, 58, 0.08), 0 1px 2px rgba(32, 42, 58, 0.06)',
      '@media (prefers-contrast: more)': '0 8px 20px rgba(31, 37, 47, 0.16), 0 0 0 1px rgba(39, 44, 52, 0.42), inset 0 1px rgba(255, 255, 255, 0.94)',
    },
    userSelect: 'none',
  },
  tab: {
    position: 'relative',
    zIndex: 3,
    display: 'grid',
    height: 24,
    minWidth: 0,
    alignItems: 'center',
    justifyItems: 'center',
    borderWidth: 0,
    borderRadius: 7,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: 'transparent',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    color: colors.textMuted,
    cursor: 'default',
    outline: 'none',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.975)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'color, transform',
    transitionTimingFunction: 'ease-out',
  },
  tabSelected: {
    color: colors.text,
  },
  selectionIndicator: {
    position: 'absolute',
    zIndex: 0,
    inset: 0,
    borderColor: {
      'default': 'rgba(63, 69, 79, 0.1)',
      '@media (prefers-contrast: more)': 'rgba(31, 35, 42, 0.58)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 7,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.82)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(255, 255, 255)',
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    boxShadow: '0 1px 4px rgba(31, 37, 47, 0.11), 0 0 0 0.5px rgba(63, 69, 79, 0.06), inset 0 1px rgba(255, 255, 255, 0.98), inset 0 -1px rgba(72, 79, 90, 0.07)',
    pointerEvents: 'none',
    willChange: 'transform',
  },
  tabLabel: {
    position: 'relative',
    zIndex: 1,
    overflow: 'hidden',
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    textShadow: '0 1px rgba(255, 255, 255, 0.72)',
    whiteSpace: 'nowrap',
  },
  panelRegion: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
  },
  panel: {
    width: '100%',
    minWidth: 0,
    minHeight: 0,
  },
})
