/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const JournalsLazyRouteImport = createFileRoute('/journals')()
const AllNotesLazyRouteImport = createFileRoute('/all-notes')()

const JournalsLazyRoute = JournalsLazyRouteImport.update({
  id: '/journals',
  path: '/journals',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/journals.lazy').then((d) => d.Route))
const AllNotesLazyRoute = AllNotesLazyRouteImport.update({
  id: '/all-notes',
  path: '/all-notes',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/all-notes.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all-notes': typeof AllNotesLazyRoute
  '/journals': typeof JournalsLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all-notes': typeof AllNotesLazyRoute
  '/journals': typeof JournalsLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all-notes': typeof AllNotesLazyRoute
  '/journals': typeof JournalsLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/all-notes' | '/journals'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/all-notes' | '/journals'
  id: '__root__' | '/' | '/all-notes' | '/journals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllNotesLazyRoute: typeof AllNotesLazyRoute
  JournalsLazyRoute: typeof JournalsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/journals': {
      id: '/journals'
      path: '/journals'
      fullPath: '/journals'
      preLoaderRoute: typeof JournalsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-notes': {
      id: '/all-notes'
      path: '/all-notes'
      fullPath: '/all-notes'
      preLoaderRoute: typeof AllNotesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllNotesLazyRoute: AllNotesLazyRoute,
  JournalsLazyRoute: JournalsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
