/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const JournalsLazyRouteImport = createFileRoute('/journals')()
const AllNotesLazyRouteImport = createFileRoute('/all-notes')()
const AboutLazyRouteImport = createFileRoute('/about')()
const NoteDocIdLazyRouteImport = createFileRoute('/note/$docId')()

const JournalsLazyRoute = JournalsLazyRouteImport.update({
  id: '/journals',
  path: '/journals',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/journals.lazy').then((d) => d.Route))
const AllNotesLazyRoute = AllNotesLazyRouteImport.update({
  id: '/all-notes',
  path: '/all-notes',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/all-notes.lazy').then((d) => d.Route))
const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteDocIdLazyRoute = NoteDocIdLazyRouteImport.update({
  id: '/note/$docId',
  path: '/note/$docId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/note/$docId.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/all-notes': typeof AllNotesLazyRoute
  '/journals': typeof JournalsLazyRoute
  '/note/$docId': typeof NoteDocIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/all-notes': typeof AllNotesLazyRoute
  '/journals': typeof JournalsLazyRoute
  '/note/$docId': typeof NoteDocIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/all-notes': typeof AllNotesLazyRoute
  '/journals': typeof JournalsLazyRoute
  '/note/$docId': typeof NoteDocIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/all-notes' | '/journals' | '/note/$docId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/all-notes' | '/journals' | '/note/$docId'
  id: '__root__' | '/' | '/about' | '/all-notes' | '/journals' | '/note/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutLazyRoute: typeof AboutLazyRoute
  AllNotesLazyRoute: typeof AllNotesLazyRoute
  JournalsLazyRoute: typeof JournalsLazyRoute
  NoteDocIdLazyRoute: typeof NoteDocIdLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/journals': {
      id: '/journals'
      path: '/journals'
      fullPath: '/journals'
      preLoaderRoute: typeof JournalsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-notes': {
      id: '/all-notes'
      path: '/all-notes'
      fullPath: '/all-notes'
      preLoaderRoute: typeof AllNotesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/$docId': {
      id: '/note/$docId'
      path: '/note/$docId'
      fullPath: '/note/$docId'
      preLoaderRoute: typeof NoteDocIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutLazyRoute: AboutLazyRoute,
  AllNotesLazyRoute: AllNotesLazyRoute,
  JournalsLazyRoute: JournalsLazyRoute,
  NoteDocIdLazyRoute: NoteDocIdLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
