import * as stylex from '@stylexjs/stylex'

export const editorStyles = stylex.create({
  viewport: {
    display: 'flex',
    flexDirection: 'column',
    height: 'calc(100vh - 132px)',
    minHeight: 480,
    overflow: 'hidden',
    borderColor: '#d7dce1',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    backgroundColor: '#ffffff',
  },
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    minHeight: 46,
    overflowX: 'auto',
    borderBottomColor: '#e0e4e8',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingBlock: 5,
    paddingInline: 8,
    backgroundColor: '#fafbfc',
  },
  toolbarDivider: {
    flexShrink: 0,
    width: 1,
    height: 22,
    marginInline: 4,
    backgroundColor: '#d9dde2',
  },
  scrolling: {
    position: 'relative',
    minHeight: 0,
    flex: 1,
    overflow: 'auto',
    backgroundColor: '#ffffff',
  },
  content: {
    width: 'min(100%, 820px)',
    minHeight: '100%',
    marginInline: 'auto',
    paddingBlockEnd: 160,
    paddingBlockStart: 56,
    paddingInline: 64,
    color: '#25282d',
    lineHeight: 1.65,
  },
  uploadStatus: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 34,
    borderBottomColor: '#dce1e5',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingInline: 12,
    backgroundColor: '#edf7f2',
    color: '#225a47',
    fontSize: 13,
  },
  uploadStatusError: {
    backgroundColor: '#fff0f0',
    color: '#9e3030',
  },
  uploadStatusButton: {
    borderWidth: 0,
    backgroundColor: 'transparent',
    color: 'inherit',
    cursor: 'pointer',
    fontWeight: 600,
  },
  actionButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 32,
    height: 32,
    borderWidth: 0,
    borderRadius: 5,
    backgroundColor: {
      'default': 'transparent',
      ':hover': '#e7ecef',
    },
    color: {
      'default': '#5c636d',
      ':hover': '#171a1f',
    },
    cursor: {
      'default': 'pointer',
      ':disabled': 'default',
    },
    opacity: {
      'default': 1,
      ':disabled': 0.35,
    },
  },
  actionButtonPressed: {
    backgroundColor: '#e7ecef',
    color: '#171a1f',
  },
  positioner: {
    zIndex: 50,
  },
  handlePositioner: {
    zIndex: 20,
  },
  tooltipPopup: {
    borderRadius: 4,
    paddingBlock: 5,
    paddingInline: 8,
    backgroundColor: '#20242a',
    color: '#ffffff',
    fontSize: 12,
  },
  popup: {
    minWidth: 180,
    overflow: 'hidden',
    borderColor: '#d8dde2',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    padding: 5,
    backgroundColor: '#ffffff',
    boxShadow: '0 10px 30px rgb(25 31 38 / 16%)',
  },
  inlineMenu: {
    display: 'flex',
    minWidth: 0,
  },
  popupContent: {
    maxHeight: 280,
    overflowY: 'auto',
  },
  menuItem: {
    'display': 'flex',
    'alignItems': 'center',
    'justifyContent': 'space-between',
    'width': '100%',
    'minHeight': 34,
    'borderRadius': 4,
    'paddingBlock': 6,
    'paddingInline': 9,
    'color': '#30343a',
    'cursor': 'pointer',
    'fontSize': 13,
    ':is([data-highlighted])': {
      backgroundColor: '#e9f2ee',
      color: '#164f3c',
    },
  },
  dangerMenuItem: {
    color: '#a32d2d',
  },
  shortcut: {
    color: '#8a929d',
    fontSize: 11,
  },
  uploadCard: {
    display: 'grid',
    gap: 8,
    width: 280,
    padding: 12,
  },
  formLabel: {
    color: '#5c636d',
    fontSize: 12,
    fontWeight: 600,
  },
  textInput: {
    width: '100%',
    height: 34,
    borderColor: '#cfd5da',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 4,
    paddingInline: 9,
  },
  primaryButton: {
    minHeight: 34,
    borderWidth: 0,
    borderRadius: 4,
    paddingInline: 12,
    backgroundColor: '#256a53',
    color: '#ffffff',
    cursor: 'pointer',
  },
  removeButton: {
    marginTop: 5,
    backgroundColor: '#9e3030',
  },
  handlePopup: {
    display: 'flex',
    borderColor: '#d8dde2',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: '#ffffff',
    boxShadow: '0 4px 14px rgb(25 31 38 / 12%)',
  },
  dropIndicator: {
    height: 2,
    backgroundColor: '#2d7a63',
  },
  imageResizable: {
    position: 'relative',
    display: 'inline-flex',
    maxWidth: '100%',
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 2,
  },
  imageSelected: {
    borderColor: '#2d7a63',
  },
  image: {
    display: 'block',
    width: '100%',
    height: '100%',
    objectFit: 'contain',
  },
  imageHandle: {
    position: 'absolute',
    right: -5,
    bottom: -5,
    width: 11,
    height: 11,
    borderColor: '#ffffff',
    borderStyle: 'solid',
    borderWidth: 2,
    borderRadius: '50%',
    backgroundColor: '#2d7a63',
  },
  imageOverlay: {
    position: 'absolute',
    inset: 0,
    display: 'grid',
    placeContent: 'center',
    backgroundColor: 'rgb(255 255 255 / 88%)',
    color: '#40464f',
    textAlign: 'center',
  },
  imageError: {
    color: '#9e3030',
  },
  languageWrapper: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginBottom: -38,
    padding: 6,
  },
  languageSelect: {
    position: 'relative',
    zIndex: 2,
    height: 28,
    maxWidth: 180,
    borderColor: '#4c555f',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 4,
    backgroundColor: '#2b3137',
    color: '#e8eaed',
  },
  codeSourceHidden: {
    display: 'none',
  },
  codePreview: {
    overflow: 'auto',
    borderColor: '#d9dde2',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 5,
    padding: 18,
    backgroundColor: '#fbfcfd',
    cursor: 'text',
  },
  visuallyHidden: {
    position: 'absolute',
    width: 1,
    height: 1,
    overflow: 'hidden',
    clip: 'rect(0, 0, 0, 0)',
    whiteSpace: 'nowrap',
  },
  faded: {
    opacity: 0.5,
  },
})
