import * as stylex from '@stylexjs/stylex'

const colors = {
  blue500: 'oklch(0.623 0.214 259.815)',
  canvas: '#ffffff',
  gray50: 'oklch(0.985 0.002 247.839)',
  gray100: 'oklch(0.967 0.003 264.542)',
  gray200: 'oklch(0.928 0.006 264.531)',
  gray400: 'oklch(0.707 0.022 261.325)',
  gray500: 'oklch(0.551 0.027 264.364)',
  gray800: 'oklch(0.278 0.033 256.848)',
  gray900: 'oklch(0.21 0.034 264.665)',
  red500: 'oklch(0.637 0.237 25.331)',
} as const

export const editorStyles = stylex.create({
  viewport: {
    boxSizing: 'border-box',
    display: 'flex',
    width: '100%',
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
    flexDirection: 'column',
    backgroundColor: colors.canvas,
    color: '#000000',
  },
  scrolling: {
    position: 'relative',
    boxSizing: 'border-box',
    width: '100%',
    minHeight: 0,
    flex: 1,
    overflowY: 'auto',
    backgroundColor: colors.canvas,
  },
  content: {
    boxSizing: 'border-box',
    width: '100%',
    minHeight: '100%',
    paddingBlock: 32,
    paddingInline: 'max(4rem, calc(50% - 20rem))',
    outline: 'none',
  },
  uploadStatus: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 34,
    borderBottomColor: '#dce1e5',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingInline: 12,
    backgroundColor: '#edf7f2',
    color: '#225a47',
    fontSize: 13,
  },
  uploadStatusError: {
    backgroundColor: '#fff0f0',
    color: '#9e3030',
  },
  uploadStatusButton: {
    borderWidth: 0,
    backgroundColor: 'transparent',
    color: 'inherit',
    cursor: 'pointer',
    fontWeight: 600,
  },
  tooltipTrigger: {
    display: 'block',
  },
  actionButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 36,
    minHeight: 36,
    borderWidth: 0,
    borderRadius: 6,
    padding: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': colors.gray100,
    },
    color: {
      'default': colors.gray900,
      ':disabled': 'oklch(0.21 0.034 264.665 / 50%)',
    },
    cursor: {
      'default': 'pointer',
      ':disabled': 'default',
    },
    fontSize: 14,
    fontWeight: 500,
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.gray900}`,
    },
    outline: 'none',
    outlineOffset: 0,
    pointerEvents: {
      'default': 'auto',
      ':disabled': 'none',
    },
    transitionDuration: '150ms',
    transitionProperty: 'color, background-color, border-color, outline-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, translate, scale, rotate, filter, backdrop-filter',
    transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
  },
  actionButtonPressed: {
    backgroundColor: colors.gray200,
  },
  positioner: {
    display: 'block',
    width: 'min-content',
    height: 'min-content',
    margin: 0,
    overflow: 'visible',
    borderWidth: 0,
    padding: 0,
    backgroundColor: 'transparent',
    zIndex: 50,
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'transform, translate, scale, rotate',
    transitionTimingFunction: 'cubic-bezier(0, 0, 0.2, 1)',
  },
  floatingSurfaceMotion: {
    'boxSizing': 'border-box',
    'transformOrigin': 'var(--transform-origin)',
    'transitionDuration': {
      'default': '40ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    'transitionProperty': 'opacity, scale',
    'transitionTimingFunction': 'cubic-bezier(0.4, 0, 0.2, 1)',
    ':is([data-state="closed"])': {
      opacity: 0,
      scale: 0.95,
      transitionDuration: '150ms',
    },
  },
  tooltipPopup: {
    display: 'flex',
    overflow: 'hidden',
    borderColor: colors.gray50,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    paddingBlock: 6,
    paddingInline: 12,
    backgroundColor: colors.gray900,
    boxShadow: '0 1px 2px rgb(0 0 0 / 5%)',
    color: colors.gray50,
    fontSize: 12,
    whiteSpace: 'nowrap',
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
  },
  popupSurface: {
    borderColor: colors.gray200,
    borderStyle: 'solid',
    borderWidth: 1,
    backgroundColor: colors.canvas,
    boxShadow: '0 10px 15px -3px rgb(0 0 0 / 10%), 0 4px 6px -4px rgb(0 0 0 / 10%)',
  },
  autocompletePopup: {
    position: 'relative',
    display: 'flex',
    minWidth: 240,
    minHeight: 0,
    maxHeight: 400,
    overflow: 'hidden',
    flexDirection: 'column',
    borderRadius: 12,
    userSelect: 'none',
    whiteSpace: 'nowrap',
  },
  autocompletePopupContent: {
    display: 'flex',
    minHeight: 0,
    overflowY: 'auto',
    flex: 1,
    flexDirection: 'column',
    overscrollBehavior: 'contain',
    padding: 4,
    backgroundColor: colors.canvas,
  },
  autocompleteMenuItem: {
    'position': 'relative',
    'boxSizing': 'border-box',
    'display': 'flex',
    'alignItems': 'center',
    'justifyContent': 'space-between',
    'minWidth': 128,
    'borderRadius': 6,
    'paddingBlock': 6,
    'paddingInline': 12,
    'cursor': 'default',
    'fontSize': 14,
    'outline': 'none',
    'scrollMarginBlock': 4,
    'userSelect': 'none',
    'whiteSpace': 'nowrap',
    ':is([data-highlighted])': {
      backgroundColor: colors.gray100,
    },
  },
  autocompleteKeyboard: {
    color: colors.gray400,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 12,
    letterSpacing: 0,
  },
  inlineMainPopup: {
    position: 'relative',
    display: 'flex',
    minWidth: 128,
    gap: 4,
    overflow: 'auto',
    borderRadius: 8,
    padding: 4,
    whiteSpace: 'nowrap',
  },
  headingMenuTrigger: {
    display: 'block',
  },
  headingMenuButton: {
    minWidth: 58,
    gap: 4,
    paddingInline: 9,
  },
  editorMenuPopup: {
    display: 'flex',
    minWidth: 160,
    overflow: 'auto',
    flexDirection: 'column',
    borderRadius: 10,
    padding: 4,
    outline: 'none',
    userSelect: 'none',
  },
  editorMenuItem: {
    'display': 'flex',
    'alignItems': 'center',
    'justifyContent': 'space-between',
    'minHeight': 34,
    'gap': 24,
    'borderRadius': 6,
    'paddingBlock': 6,
    'paddingInline': 10,
    'fontSize': 14,
    'outline': 'none',
    ':is([data-highlighted])': {
      backgroundColor: colors.gray100,
    },
    ':is([data-disabled="true"])': {
      opacity: 0.45,
      pointerEvents: 'none',
    },
  },
  inlineLinkPopup: {
    position: 'relative',
    display: 'flex',
    alignItems: 'stretch',
    width: 320,
    flexDirection: 'column',
    gap: 8,
    borderRadius: 8,
    padding: 16,
  },
  tableMenuPopup: {
    position: 'relative',
    display: 'flex',
    minWidth: 128,
    maxHeight: 400,
    overflow: 'auto',
    flexDirection: 'column',
    borderRadius: 12,
    padding: 4,
    outline: 'none',
    userSelect: 'none',
    whiteSpace: 'nowrap',
  },
  tableMenuItem: {
    'position': 'relative',
    'boxSizing': 'border-box',
    'display': 'flex',
    'alignItems': 'center',
    'justifyContent': 'space-between',
    'minWidth': 128,
    'gap': 32,
    'borderRadius': 4,
    'paddingBlock': 6,
    'paddingInline': 12,
    'cursor': 'default',
    'outline': 'none',
    'scrollMarginBlock': 4,
    'userSelect': 'none',
    'whiteSpace': 'nowrap',
    ':is([data-highlighted])': {
      backgroundColor: colors.gray100,
    },
    ':is([data-disabled="true"])': {
      opacity: 0.5,
      pointerEvents: 'none',
    },
  },
  dangerMenuItem: {
    color: colors.red500,
  },
  tableMenuShortcut: {
    color: colors.gray500,
    fontSize: 12,
    letterSpacing: '0.1em',
  },
  uploadCard: {
    display: 'flex',
    width: 384,
    flexDirection: 'column',
    gap: 16,
    borderRadius: 12,
    padding: 24,
    fontSize: 14,
  },
  imageUploadForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  formLabel: {
    fontSize: 14,
  },
  textInput: {
    'boxSizing': 'border-box',
    'display': 'flex',
    'width': '100%',
    'height': 36,
    'borderColor': colors.gray200,
    'borderStyle': 'solid',
    'borderWidth': 1,
    'borderRadius': 6,
    'paddingBlock': 8,
    'paddingInline': 12,
    'backgroundColor': colors.canvas,
    'fontSize': 14,
    'boxShadow': {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.gray900}`,
    },
    'outline': 'none',
    'transitionDuration': '150ms',
    'transitionTimingFunction': 'cubic-bezier(0.4, 0, 0.2, 1)',
    '::placeholder': {
      color: colors.gray500,
    },
  },
  fileInput: {
    '::file-selector-button': {
      borderWidth: 0,
      padding: 0,
      backgroundColor: 'transparent',
      fontSize: 14,
      fontWeight: 500,
    },
  },
  primaryButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: 40,
    borderWidth: 0,
    borderRadius: 6,
    paddingBlock: 8,
    paddingInline: 16,
    backgroundColor: {
      'default': colors.gray900,
      ':hover': 'rgb(17 24 39 / 90%)',
    },
    color: colors.gray50,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 500,
    opacity: {
      'default': 1,
      ':disabled': 0.5,
    },
    outline: 'none',
    pointerEvents: {
      'default': 'auto',
      ':disabled': 'none',
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.canvas}, 0 0 0 4px ${colors.gray900}`,
    },
    transitionDuration: '150ms',
    transitionProperty: 'color, background-color, border-color, box-shadow',
    transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
    whiteSpace: 'nowrap',
  },
  removeButton: {
    width: 'auto',
    height: 36,
    paddingInline: 12,
  },
  contextMenuPopup: {
    position: 'fixed',
    zIndex: 100,
    boxSizing: 'border-box',
    display: 'flex',
    width: 232,
    maxHeight: 'calc(100vh - 16px)',
    overflowY: 'auto',
    flexDirection: 'column',
    borderRadius: 10,
    padding: 5,
    color: colors.gray900,
    fontSize: 13,
    outline: 'none',
    userSelect: 'none',
  },
  contextMenuItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    minHeight: 32,
    gap: 16,
    borderWidth: 0,
    borderRadius: 6,
    paddingBlock: 6,
    paddingInline: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': colors.gray100,
      ':focus-visible': colors.gray100,
    },
    color: {
      'default': colors.gray900,
      ':disabled': colors.gray400,
    },
    cursor: {
      'default': 'default',
      ':disabled': 'default',
    },
    fontSize: 13,
    outline: 'none',
    textAlign: 'left',
  },
  contextMenuItemOpen: {
    backgroundColor: colors.gray100,
  },
  contextMenuItemLabel: {
    display: 'flex',
    alignItems: 'center',
    minWidth: 0,
    gap: 9,
  },
  contextMenuIcon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 17,
    height: 17,
    color: colors.gray500,
  },
  contextMenuTrailing: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    minWidth: 18,
    color: colors.gray400,
  },
  contextMenuShortcut: {
    color: colors.gray400,
    fontSize: 12,
    letterSpacing: 0,
  },
  contextMenuSeparator: {
    height: 1,
    marginBlock: 4,
    marginInline: 7,
    backgroundColor: colors.gray200,
  },
  contextSubmenuPopup: {
    zIndex: 101,
  },
  contextMenuOverlay: {
    position: 'fixed',
    zIndex: 100,
    inset: 0,
    backgroundColor: 'transparent',
  },
  contextImagePanel: {
    position: 'fixed',
    zIndex: 101,
    boxSizing: 'border-box',
    width: 'min(384px, calc(100vw - 16px))',
    borderRadius: 12,
    padding: 20,
    color: colors.gray900,
    fontSize: 14,
  },
  contextImageHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  contextImageClose: {
    'display': 'flex',
    'alignItems': 'center',
    'justifyContent': 'center',
    'width': 28,
    'height': 28,
    'borderWidth': 0,
    'borderRadius': 6,
    'padding': 0,
    'backgroundColor': {
      'default': 'transparent',
      ':hover': colors.gray100,
    },
    'color': colors.gray500,
    'cursor': 'pointer',
    'outline': 'none',
    ':focus-visible': {
      boxShadow: `0 0 0 2px ${colors.gray900}`,
    },
  },
  blockHandlePopup: {
    display: 'flex',
    boxSizing: 'border-box',
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
  },
  blockHandleAdd: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxSizing: 'border-box',
    width: 24,
    height: 24,
    borderWidth: 0,
    borderRadius: 4,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': colors.gray100,
    },
    color: 'oklch(0.551 0.027 264.364 / 50%)',
    cursor: 'pointer',
  },
  blockHandleDrag: {
    width: 20,
    cursor: 'grab',
  },
  tableColumnPopup: {
    display: 'flex',
    boxSizing: 'border-box',
    translate: '0 50%',
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
  },
  tableRowPopup: {
    display: 'flex',
    boxSizing: 'border-box',
    translate: '50% 0',
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
  },
  tableRowPopupRtl: {
    translate: '-50% 0',
  },
  tableColumnTrigger: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxSizing: 'border-box',
    width: 24,
    height: 18,
    overflow: 'clip',
    borderColor: colors.gray200,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 4,
    padding: 0,
    backgroundColor: {
      'default': colors.canvas,
      ':hover': colors.gray100,
    },
    color: 'oklch(0.551 0.027 264.364 / 50%)',
    transitionDuration: '150ms',
    transitionProperty: 'color, background-color, border-color',
    transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
  },
  tableRowTrigger: {
    width: 18,
    height: 24,
  },
  dropIndicator: {
    zIndex: 50,
    backgroundColor: colors.blue500,
    transitionDuration: '150ms',
    transitionProperty: 'all',
    transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
  },
  imageResizable: {
    position: 'relative',
    boxSizing: 'border-box',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 64,
    minHeight: 64,
    maxWidth: '100%',
    maxHeight: 600,
    overflow: 'hidden',
    marginBlock: 8,
    outlineColor: 'transparent',
    outlineStyle: 'solid',
    outlineWidth: 2,
  },
  imageSelected: {
    outlineColor: colors.blue500,
  },
  image: {
    display: 'block',
    width: '100%',
    height: '100%',
    maxWidth: '100%',
    maxHeight: '100%',
    objectFit: 'contain',
  },
  imageHandle: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 24,
    height: 24,
    margin: 6,
    borderWidth: 0,
    borderRadius: 4,
    padding: 4,
    backgroundColor: 'rgb(17 24 39 / 30%)',
    color: 'rgb(255 255 255 / 50%)',
    opacity: {
      'default': 0,
      ':hover': 1,
    },
    transitionDuration: '150ms',
  },
  imageOverlay: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    padding: 8,
    backgroundColor: colors.gray200,
    color: colors.gray800,
    fontSize: 14,
    textAlign: 'center',
  },
  imageError: {
    color: colors.red500,
  },
  codeBlock: {
    position: 'relative',
    marginBlock: '1em',
  },
  languageWrapper: {
    position: 'absolute',
    top: 6,
    right: 8,
    zIndex: 1,
    display: 'flex',
    alignItems: 'center',
    color: '#c8cdd5',
    userSelect: 'none',
  },
  languageSelect: {
    boxSizing: 'border-box',
    width: 132,
    height: 24,
    overflow: 'hidden',
    borderColor: 'rgb(255 255 255 / 12%)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 5,
    paddingBlock: 2,
    paddingLeft: 8,
    paddingRight: 22,
    appearance: 'none',
    backgroundColor: {
      'default': 'rgb(255 255 255 / 6%)',
      ':hover': 'rgb(255 255 255 / 10%)',
    },
    color: '#c8cdd5',
    cursor: 'pointer',
    fontSize: 11,
    fontWeight: 500,
    letterSpacing: '0.01em',
    outline: 'none',
    textOverflow: 'ellipsis',
    transitionDuration: '120ms',
    transitionProperty: 'background-color, border-color, box-shadow, color',
    userSelect: 'none',
    whiteSpace: 'nowrap',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgb(97 175 239 / 55%)',
    },
  },
  languageChevron: {
    position: 'absolute',
    right: 7,
    pointerEvents: 'none',
  },
  codeSourceHidden: {
    display: 'none',
  },
  codePreview: {
    display: 'block',
    overflow: 'auto',
    minHeight: 96,
    paddingTop: 36,
    paddingBottom: 12,
  },
  visuallyHidden: {
    position: 'absolute',
    width: 1,
    height: 1,
    overflow: 'hidden',
    margin: -1,
    borderWidth: 0,
    padding: 0,
    clip: 'rect(0, 0, 0, 0)',
    whiteSpace: 'nowrap',
  },
  faded: {
    opacity: 0.5,
  },
})
