import * as stylex from '@stylexjs/stylex'
import { shelfTheme } from './shelf-shared.stylex'

const controlTransition = {
  'default': shelfTheme.controlDuration,
  '@media (prefers-reduced-motion: reduce)': '0ms',
} as const

export const shelfPageStyles = stylex.create({
  page: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    backgroundColor: shelfTheme.canvas,
    color: shelfTheme.text,
  },
  toolbarWrap: {
    position: 'absolute',
    zIndex: 14,
    top: 58,
    right: 28,
    left: 28,
    pointerEvents: 'none',
  },
  toolbar: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    overflow: 'visible',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 18,
  },
  sourceSwitcher: {
    position: 'relative',
    width: 220,
    minWidth: 148,
    flex: '0 1 220px',
    pointerEvents: 'auto',
  },
  sourceTrigger: {
    display: 'grid',
    width: '100%',
    height: 36,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '24px minmax(0, 1fr) 16px',
    gap: 5,
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.68)',
      '@media (prefers-contrast: more)': 'rgba(49, 54, 63, 0.5)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 18,
    paddingRight: 8,
    paddingLeft: 6,
    backgroundColor: {
      'default': 'rgba(246, 248, 251, 0.56)',
      ':hover': 'rgba(250, 251, 253, 0.68)',
      ':active': 'rgba(226, 230, 237, 0.66)',
      '@media (prefers-contrast: more)': 'rgba(250, 250, 251, 0.96)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(245, 246, 248)',
    },
    backdropFilter: {
      'default': 'blur(24px) saturate(175%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    color: shelfTheme.text,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': '0 5px 14px rgba(27, 34, 44, 0.11), 0 1px 3px rgba(27, 34, 44, 0.07), inset 0 1px rgba(255, 255, 255, 0.82)',
      ':focus-visible': `0 0 0 2px ${shelfTheme.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.985)',
    },
    transitionDuration: controlTransition,
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  sourceTriggerIcon: {
    display: 'grid',
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyItems: 'center',
    color: shelfTheme.accent,
  },
  sourceTriggerLabel: {
    overflow: 'hidden',
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '18px',
    textAlign: 'left',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  searchBox: {
    display: 'grid',
    height: 34,
    width: 'clamp(160px, 24vw, 260px)',
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '18px minmax(0, 1fr) 22px',
    gap: 4,
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.62)',
      ':focus-within': 'rgba(0, 113, 227, 0.28)',
      '@media (prefers-contrast: more)': 'rgba(49, 54, 63, 0.5)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 17,
    paddingRight: 5,
    paddingLeft: 9,
    backgroundColor: {
      'default': 'rgba(239, 242, 246, 0.58)',
      ':focus-within': 'rgba(250, 251, 253, 0.72)',
      '@media (prefers-contrast: more)': 'rgba(250, 250, 251, 0.96)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(239, 240, 243)',
    },
    backdropFilter: {
      'default': 'blur(24px) saturate(175%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    color: shelfTheme.textQuiet,
    boxShadow: {
      'default': '0 5px 14px rgba(27, 34, 44, 0.1), 0 1px 3px rgba(27, 34, 44, 0.06), inset 0 1px rgba(255, 255, 255, 0.78)',
      ':focus-within': '0 0 0 3px rgba(0, 113, 227, 0.16), 0 5px 14px rgba(27, 34, 44, 0.1), inset 0 1px rgba(255, 255, 255, 0.86)',
    },
  },
  searchInput: {
    width: '100%',
    minWidth: 0,
    height: 30,
    borderWidth: 0,
    padding: 0,
    backgroundColor: 'transparent',
    color: shelfTheme.text,
    fontSize: 13,
    lineHeight: '18px',
    outline: 'none',
  },
  clearSearch: {
    display: 'grid',
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyItems: 'center',
    borderWidth: 0,
    borderRadius: 10,
    padding: 0,
    backgroundColor: 'rgba(61, 67, 77, 0.14)',
    color: shelfTheme.textMuted,
    cursor: 'default',
  },
  toolbarTrailing: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 8,
    pointerEvents: 'auto',
  },
  loadMoreFooter: {
    display: 'flex',
    justifyContent: 'center',
    paddingTop: 4,
    paddingBottom: 22,
  },
  scrollViewport: {
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflowX: 'hidden',
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    paddingRight: 28,
    paddingBottom: 52,
    paddingLeft: 28,
  },
  scrollViewportWithToolbar: {
    paddingTop: 112,
    scrollPaddingTop: 112,
  },
  scrollViewportEmpty: {
    paddingTop: 54,
    scrollPaddingTop: 54,
  },
  loadingState: {
    display: 'flex',
    minHeight: 'calc(100vh - 230px)',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    gap: 10,
    color: shelfTheme.textQuiet,
    fontSize: 13,
  },
  emptyState: {
    display: 'flex',
    minHeight: 'calc(100vh - 230px)',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    paddingBottom: 36,
    textAlign: 'center',
  },
  emptyIcon: {
    width: 28,
    height: 28,
    marginBottom: 12,
    color: 'rgba(39, 72, 118, 0.62)',
  },
  emptyTitle: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 5,
    marginLeft: 0,
    fontSize: 17,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '22px',
  },
  emptyText: {
    maxWidth: 320,
    marginTop: 0,
    marginRight: 0,
    marginBottom: 16,
    marginLeft: 0,
    color: shelfTheme.textMuted,
    fontSize: 12,
    lineHeight: '17px',
  },
  selectedSourceIssue: {
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    borderColor: 'rgba(166, 98, 24, 0.16)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    marginBottom: 12,
    paddingTop: 8,
    paddingRight: 10,
    paddingBottom: 8,
    paddingLeft: 10,
    backgroundColor: 'rgba(232, 153, 58, 0.08)',
    color: 'rgb(145, 79, 10)',
    fontSize: 12,
  },
})
