import * as stylex from '@stylexjs/stylex'

const colors = {
  focus: 'rgba(41, 97, 194, 0.84)',
  textMuted: 'rgba(46, 48, 54, 0.64)',
  textQuiet: 'rgba(55, 57, 63, 0.46)',
} as const

export const shelfBookReadingStyles = stylex.create({
  readingActions: {
    display: 'flex',
    minHeight: 36,
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 9,
    marginTop: 24,
  },
  readControl: {
    display: 'inline-flex',
    height: 36,
    overflow: 'hidden',
    alignItems: 'stretch',
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.62)',
      '@media (prefers-contrast: more)': 'rgba(0, 67, 151, 0.7)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 11,
    backgroundColor: {
      'default': 'rgba(0, 105, 220, 0.82)',
      '@media (prefers-contrast: more)': 'rgb(0, 101, 211)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(0, 113, 227)',
    },
    backdropFilter: {
      'default': 'blur(18px) saturate(180%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': '0 6px 16px rgba(0, 72, 159, 0.2), 0 1px 3px rgba(0, 61, 134, 0.14), inset 0 1px rgba(255, 255, 255, 0.42)',
      ':focus-within': `0 0 0 2px ${colors.focus}, 0 6px 16px rgba(0, 72, 159, 0.2)`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.975)',
    },
    transitionDuration: {
      'default': '90ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'transform, opacity',
    transitionTimingFunction: 'ease-out',
  },
  readControlDisabled: {
    opacity: 0.76,
  },
  readButton: {
    display: 'inline-flex',
    minWidth: 86,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderWidth: 0,
    paddingRight: 13,
    paddingLeft: 12,
    backgroundColor: 'transparent',
    color: {
      'default': 'white',
      ':disabled': 'rgba(255, 255, 255, 0.58)',
    },
    cursor: 'default',
    fontFamily: 'inherit',
    fontSize: 13,
    fontWeight: 650,
    letterSpacing: 0,
    outline: 'none',
  },
  formatPicker: {
    position: 'relative',
    display: 'inline-flex',
    minWidth: 68,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderLeftColor: 'rgba(255, 255, 255, 0.28)',
    borderLeftStyle: 'solid',
    borderLeftWidth: 1,
    paddingRight: 9,
    paddingLeft: 10,
    color: 'white',
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: 0,
  },
  formatSelect: {
    position: 'absolute',
    zIndex: 1,
    inset: 0,
    width: '100%',
    height: '100%',
    borderWidth: 0,
    opacity: 0,
    cursor: 'default',
  },
  onlineReadingOption: {
    display: 'inline-flex',
    minHeight: 30,
    alignItems: 'center',
    gap: 6,
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 12,
    fontWeight: 530,
    lineHeight: '17px',
    userSelect: 'none',
  },
  onlineReadingCheckbox: {
    width: 15,
    height: 15,
    flexShrink: 0,
    margin: 0,
    accentColor: 'rgb(0, 113, 227)',
  },
  readingHelp: {
    display: 'grid',
    width: 24,
    height: 28,
    alignItems: 'center',
    justifyItems: 'center',
    borderRadius: 7,
    color: colors.textQuiet,
    cursor: 'help',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  deleteReadingButton: {
    display: 'grid',
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyItems: 'center',
    borderColor: 'rgba(255, 255, 255, 0.6)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    padding: 0,
    backgroundColor: {
      'default': 'rgba(246, 248, 251, 0.46)',
      ':hover': 'rgba(255, 255, 255, 0.62)',
      ':active': 'rgba(210, 214, 221, 0.58)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(239, 241, 244)',
    },
    backdropFilter: {
      'default': 'blur(16px) saturate(170%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    color: 'rgb(177, 45, 43)',
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': '0 3px 9px rgba(35, 42, 52, 0.08), inset 0 1px rgba(255, 255, 255, 0.72)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.95)',
    },
  },
  readingError: {
    marginTop: 10,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: 'rgb(166, 42, 40)',
    fontSize: 11,
    lineHeight: '16px',
  },
})
