import * as stylex from '@stylexjs/stylex'

export const shelfTheme = {
  accent: 'var(--ui-accent, rgb(0, 113, 227))',
  accentForeground: 'var(--ui-accent-foreground, rgb(0, 113, 227))',
  accentHover: 'var(--ui-accent-hover, rgb(0, 105, 211))',
  accentPressed: 'var(--ui-accent-pressed, rgb(0, 91, 187))',
  canvas: 'var(--ui-canvas, rgb(250, 250, 249))',
  controlDuration: '110ms',
  controlHover: 'var(--ui-control-hover, rgba(76, 84, 96, 0.07))',
  controlPressed: 'var(--ui-control-pressed, rgba(80, 91, 108, 0.14))',
  controlRadius: 'var(--ui-control-radius, 9px)',
  controlShadow: 'var(--ui-control-shadow, 0 1px 2px rgba(35, 42, 52, 0.08))',
  controlStroke: 'var(--ui-control-stroke, 1px)',
  danger: 'var(--ui-danger, rgb(198, 48, 48))',
  fieldBorder: 'var(--ui-field-border, rgba(71, 76, 86, 0.2))',
  focus: 'var(--ui-focus, rgba(41, 97, 194, 0.84))',
  materialFilter: 'var(--ui-material-filter, blur(20px) saturate(170%))',
  onAccent: 'var(--ui-on-accent, white)',
  shadowRaised: 'var(--ui-shadow-raised, 0 8px 20px rgba(0, 0, 0, 0.14))',
  shadowSubtle: 'var(--ui-shadow-subtle, 0 2px 6px rgba(0, 0, 0, 0.1))',
  surface: 'var(--ui-surface, rgb(255, 255, 255))',
  surfaceRaised: 'var(--ui-surface-raised, rgb(255, 255, 255))',
  surfaceTranslucent: 'var(--ui-surface-translucent, rgba(244, 246, 249, 0.5))',
  text: 'var(--ui-text, rgba(27, 28, 31, 0.92))',
  textMuted: 'var(--ui-text-muted, rgba(46, 48, 54, 0.64))',
  textQuiet: 'var(--ui-text-quiet, rgba(55, 57, 63, 0.46))',
} as const
const controlTransition = {
  'default': shelfTheme.controlDuration,
  '@media (prefers-reduced-motion: reduce)': '0ms',
} as const

export const shelfSharedStyles = stylex.create({
  iconButton: {
    display: 'grid',
    width: 34,
    height: 34,
    flex: '0 0 34px',
    alignItems: 'center',
    justifyItems: 'center',
    borderColor: shelfTheme.fieldBorder,
    borderStyle: 'solid',
    borderWidth: shelfTheme.controlStroke,
    borderRadius: shelfTheme.controlRadius,
    padding: 0,
    backgroundColor: {
      'default': shelfTheme.surfaceTranslucent,
      ':hover': shelfTheme.controlHover,
      ':active': shelfTheme.controlPressed,
      ':disabled': shelfTheme.surfaceTranslucent,
      '@media (prefers-reduced-transparency: reduce)': 'rgb(245, 246, 248)',
    },
    backdropFilter: {
      'default': shelfTheme.materialFilter,
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    color: {
      'default': shelfTheme.textMuted,
      ':disabled': 'rgba(46, 48, 54, 0.25)',
    },
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': shelfTheme.shadowSubtle,
      ':focus-visible': `0 0 0 2px ${shelfTheme.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
      ':disabled': 'scale(1)',
    },
    transitionDuration: controlTransition,
    transitionProperty: 'background-color, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  spinner: {
    animationDuration: {
      'default': '850ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    animationIterationCount: 'infinite',
    animationName: stylex.keyframes({
      to: { transform: 'rotate(360deg)' },
    }),
    animationTimingFunction: 'linear',
  },
  primaryButton: {
    display: 'inline-flex',
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderColor: shelfTheme.fieldBorder,
    borderStyle: 'solid',
    borderWidth: shelfTheme.controlStroke,
    borderRadius: shelfTheme.controlRadius,
    paddingRight: 14,
    paddingLeft: 12,
    backgroundColor: {
      'default': shelfTheme.accent,
      ':hover': shelfTheme.accentHover,
      ':active': shelfTheme.accentPressed,
      ':disabled': 'rgba(0, 113, 227, 0.48)',
    },
    color: shelfTheme.onAccent,
    cursor: 'default',
    fontSize: 13,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': shelfTheme.controlShadow,
      ':focus-visible': `0 0 0 2px ${shelfTheme.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.975)',
    },
    transitionDuration: controlTransition,
    transitionProperty: 'background-color, transform',
  },
  secondaryButton: {
    display: 'inline-flex',
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: shelfTheme.fieldBorder,
    borderStyle: 'solid',
    borderWidth: shelfTheme.controlStroke,
    borderRadius: shelfTheme.controlRadius,
    paddingRight: 14,
    paddingLeft: 14,
    backgroundColor: {
      'default': shelfTheme.surfaceTranslucent,
      ':hover': shelfTheme.controlHover,
      ':active': shelfTheme.controlPressed,
      ':disabled': shelfTheme.surfaceTranslucent,
    },
    color: shelfTheme.text,
    cursor: 'default',
    fontSize: 13,
    fontWeight: 550,
    outline: 'none',
    boxShadow: {
      'default': shelfTheme.controlShadow,
      ':focus-visible': `0 0 0 2px ${shelfTheme.focus}`,
    },
  },
})
