import * as stylex from '@stylexjs/stylex'

const colors = {
  canvas: 'rgba(248, 249, 250, 0.88)',
  focus: 'rgba(41, 97, 194, 0.84)',
  text: 'rgba(27, 28, 31, 0.92)',
  textMuted: 'rgba(46, 48, 54, 0.64)',
  textQuiet: 'rgba(55, 57, 63, 0.46)',
} as const

export const shelfBookShellStyles = stylex.create({
  page: {
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    backgroundColor: {
      'default': colors.canvas,
      '@media (prefers-reduced-transparency: reduce)': 'rgb(248, 249, 250)',
      '@media (prefers-contrast: more)': 'rgb(250, 250, 251)',
    },
    color: colors.text,
  },
  scrollViewport: {
    width: '100%',
    height: '100%',
    overflowX: 'hidden',
    overflowY: 'auto',
    paddingTop: 88,
    paddingRight: {
      'default': 44,
      '@media (max-width: 900px)': 28,
    },
    paddingBottom: 64,
    paddingLeft: {
      'default': 44,
      '@media (max-width: 900px)': 28,
    },
    scrollPaddingTop: 88,
  },
  content: {
    width: '100%',
    maxWidth: 860,
    marginRight: 'auto',
    marginLeft: 'auto',
  },
  overview: {
    display: 'grid',
    minWidth: 0,
    alignItems: 'start',
    gridTemplateColumns: {
      'default': '180px minmax(0, 1fr)',
      '@media (max-width: 900px)': '150px minmax(0, 1fr)',
      '@media (max-width: 680px)': '1fr',
    },
    gridTemplateAreas: {
      'default': '"cover information" "cover description" ". inspector" ". technical"',
      '@media (max-width: 900px)': '"cover information" "description description" "inspector inspector" "technical technical"',
      '@media (max-width: 680px)': '"cover information" "description description" "inspector inspector" "technical technical"',
    },
    gap: {
      'default': '24px 36px',
      '@media (max-width: 900px)': '30px 28px',
      '@media (max-width: 680px)': '28px 22px',
    },
  },
  coverColumn: {
    gridArea: 'cover',
    width: {
      'default': 180,
      '@media (max-width: 900px)': 150,
      '@media (max-width: 680px)': 128,
    },
    minWidth: 0,
    marginRight: 0,
    marginLeft: 0,
  },
  information: {
    gridArea: 'information',
    minWidth: 0,
    paddingTop: 7,
  },
  title: {
    maxWidth: 680,
    margin: 0,
    fontSize: {
      'default': 28,
      '@media (max-width: 680px)': 24,
    },
    fontWeight: 720,
    letterSpacing: 0,
    lineHeight: {
      'default': '35px',
      '@media (max-width: 680px)': '30px',
    },
    overflowWrap: 'anywhere',
  },
  subtitle: {
    maxWidth: 680,
    marginTop: 7,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: '21px',
  },
  authors: {
    maxWidth: 680,
    marginTop: 10,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: colors.textMuted,
    fontSize: 14,
    fontWeight: 560,
    lineHeight: '20px',
  },
  headlineFacts: {
    display: 'flex',
    flexWrap: 'wrap',
    marginTop: 18,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: colors.textQuiet,
    fontSize: 12,
    fontWeight: 520,
    lineHeight: '17px',
  },
  headlineFact: {
    display: 'inline-flex',
    alignItems: 'center',
  },
  factSeparator: {
    marginRight: 7,
    marginLeft: 7,
    color: 'rgba(55, 57, 63, 0.28)',
  },
  status: {
    display: 'flex',
    minHeight: 'calc(100vh - 150px)',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    gap: 10,
    color: colors.textQuiet,
    fontSize: 13,
    textAlign: 'center',
  },
  statusTitle: {
    margin: 0,
    color: colors.text,
    fontSize: 17,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '22px',
  },
  statusText: {
    maxWidth: 360,
    margin: 0,
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: '17px',
  },
  shelfLink: {
    display: 'inline-flex',
    height: 30,
    alignItems: 'center',
    borderRadius: 7,
    marginTop: 4,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: 'rgba(118, 118, 128, 0.09)',
    color: colors.text,
    cursor: 'default',
    fontSize: 12,
    fontWeight: 600,
    outline: 'none',
    textDecoration: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    opacity: {
      'default': 1,
      ':active': 0.58,
    },
  },
  spinner: {
    animationDuration: {
      'default': '850ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    animationIterationCount: 'infinite',
    animationName: stylex.keyframes({
      to: { transform: 'rotate(360deg)' },
    }),
    animationTimingFunction: 'linear',
  },
})
