import * as stylex from '@stylexjs/stylex'

const colors = {
  focus: 'rgba(41, 97, 194, 0.84)',
  text: 'rgba(27, 28, 31, 0.92)',
  textMuted: 'rgba(46, 48, 54, 0.64)',
  textQuiet: 'rgba(55, 57, 63, 0.46)',
} as const

export const shelfBookDetailsStyles = stylex.create({
  metadataInspector: {
    gridArea: 'inspector',
    width: '100%',
    minWidth: 0,
    borderTopColor: 'rgba(67, 70, 76, 0.11)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 21,
  },
  inspectorTitle: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 15,
    marginLeft: 0,
    color: colors.text,
    fontSize: 15,
    fontWeight: 680,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  metadataGrid: {
    display: 'grid',
    gridTemplateColumns: {
      'default': 'repeat(2, minmax(0, 1fr))',
      '@media (max-width: 680px)': 'minmax(0, 1fr)',
    },
    columnGap: 40,
    rowGap: 17,
    margin: 0,
  },
  metadataItem: {
    minWidth: 0,
  },
  metadataTerm: {
    color: colors.textQuiet,
    fontSize: 11,
    fontWeight: 580,
    letterSpacing: 0,
    lineHeight: '17px',
  },
  metadataValue: {
    marginTop: 2,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: colors.text,
    fontSize: 13,
    lineHeight: '19px',
    overflowWrap: 'anywhere',
  },
  description: {
    gridArea: 'description',
    minWidth: 0,
    borderTopColor: 'rgba(67, 70, 76, 0.11)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 24,
  },
  sectionTitle: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 10,
    marginLeft: 0,
    fontSize: 15,
    fontWeight: 680,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  descriptionText: {
    margin: 0,
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: '22px',
    whiteSpace: 'pre-line',
  },
  descriptionUnavailable: {
    margin: 0,
    color: colors.textQuiet,
    fontSize: 13,
    fontStyle: 'italic',
    lineHeight: '20px',
  },
  technicalSection: {
    gridArea: 'technical',
    minWidth: 0,
    borderTopColor: 'rgba(67, 70, 76, 0.11)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 8,
  },
  disclosureButton: {
    display: 'flex',
    width: '100%',
    minHeight: 32,
    alignItems: 'center',
    borderWidth: 0,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    backgroundColor: 'transparent',
    color: colors.text,
    cursor: 'default',
    fontFamily: 'inherit',
    fontSize: 13,
    fontWeight: 610,
    letterSpacing: 0,
    lineHeight: '18px',
    outline: 'none',
    opacity: {
      'default': 1,
      ':active': 0.55,
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  disclosureIcon: {
    flexShrink: 0,
    marginRight: 5,
    color: colors.textQuiet,
    transform: 'rotate(0deg)',
    transitionDuration: {
      'default': '160ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'transform',
    transitionTimingFunction: 'ease-out',
  },
  disclosureIconOpen: {
    transform: 'rotate(90deg)',
  },
  technicalMetadata: {
    marginTop: 5,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 20,
  },
  technicalRow: {
    display: 'grid',
    gridTemplateColumns: {
      'default': '120px minmax(0, 1fr)',
      '@media (max-width: 680px)': '96px minmax(0, 1fr)',
    },
    columnGap: 18,
    borderTopColor: 'rgba(67, 70, 76, 0.09)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 8,
    paddingBottom: 8,
  },
})
