import * as stylex from '@stylexjs/stylex'
import { editorColors } from '../../common/editor-theme.stylex'

export const contextMenuStyles = stylex.create({
  popup: {
    position: 'fixed',
    zIndex: 100,
    boxSizing: 'border-box',
    display: 'flex',
    width: 232,
    maxHeight: 'calc(100vh - 16px)',
    overflowY: 'auto',
    flexDirection: 'column',
    borderRadius: 10,
    padding: 5,
    color: editorColors.gray900,
    fontSize: 13,
    outline: 'none',
    userSelect: 'none',
  },
  item: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    minHeight: 32,
    gap: 16,
    borderWidth: 0,
    borderRadius: 6,
    paddingBlock: 6,
    paddingInline: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': editorColors.gray100,
      ':focus-visible': editorColors.gray100,
    },
    color: {
      'default': editorColors.gray900,
      ':disabled': editorColors.gray400,
    },
    cursor: 'default',
    fontSize: 13,
    outline: 'none',
    textAlign: 'left',
  },
  itemOpen: {
    backgroundColor: editorColors.gray100,
  },
  itemLabel: {
    display: 'flex',
    alignItems: 'center',
    minWidth: 0,
    gap: 9,
  },
  icon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 17,
    height: 17,
    color: editorColors.gray500,
  },
  trailing: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    minWidth: 18,
    color: editorColors.gray400,
  },
  shortcut: {
    color: editorColors.gray400,
    fontSize: 12,
    letterSpacing: 0,
  },
  separator: {
    height: 1,
    marginBlock: 4,
    marginInline: 7,
    backgroundColor: editorColors.gray200,
  },
  submenuPopup: {
    zIndex: 101,
  },
  overlay: {
    position: 'fixed',
    zIndex: 100,
    inset: 0,
    backgroundColor: 'transparent',
  },
  imagePanel: {
    position: 'fixed',
    zIndex: 101,
    boxSizing: 'border-box',
    width: 'min(384px, calc(100vw - 16px))',
    borderRadius: 12,
    padding: 20,
    color: editorColors.gray900,
    fontSize: 14,
  },
  imageHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  imageClose: {
    'display': 'flex',
    'alignItems': 'center',
    'justifyContent': 'center',
    'width': 28,
    'height': 28,
    'borderWidth': 0,
    'borderRadius': 6,
    'padding': 0,
    'backgroundColor': {
      'default': 'transparent',
      ':hover': editorColors.gray100,
    },
    'color': editorColors.gray500,
    'cursor': 'pointer',
    'outline': 'none',
    ':focus-visible': {
      boxShadow: `0 0 0 2px ${editorColors.gray900}`,
    },
  },
})
