export { readerAnnotationLabel } from './internal/annotation-label'
export { Reader, WindowReader } from './reader'
export { prepareReaderAnnotationDeletion } from './reader-annotation-deletion'
export type {
  ReaderAnchor,
  ReaderAnnotation,
  ReaderAnnotationColor,
  ReaderAnnotationCopyFormat,
  ReaderAnnotationDependents,
  ReaderAnnotationEditorRenderInput,
  ReaderAnnotationStyle,
  ReaderAnnotationTopicCreateInput,
  ReaderAuxiliarySidebar,
  ReaderAuxiliarySidebarController,
  ReaderCapabilities,
  ReaderClientRect,
  ReaderComicRegionAnchor,
  ReaderDataSource,
  ReaderEpubLocator,
  ReaderEpubRegionAnchor,
  ReaderEpubTextAnchor,
  ReaderFormat,
  ReaderHighlight,
  ReaderImageOcclusionBoundsShape,
  ReaderImageOcclusionBrushShape,
  ReaderImageOcclusionOverlay,
  ReaderImageOcclusionShape,
  ReaderLocation,
  ReaderNormalizedRect,
  ReaderNote,
  ReaderOcrProvider,
  ReaderOcrRequest,
  ReaderOcrResult,
  ReaderOcrStatus,
  ReaderOcrTextItem,
  ReaderOutlineItem,
  ReaderPdfRegionAnchor,
  ReaderPdfTextAnchor,
  ReaderPosition,
  ReaderPresentationMode,
  ReaderProps,
  ReaderRandomAccessSource,
  ReaderRegionAnchor,
  ReaderRegionSelection,
  ReaderScaleCapability,
  ReaderScaleKind,
  ReaderSelection,
  ReaderSource,
  ReaderSourceData,
  ReaderTextAnchor,
  ReaderTextLayerKind,
  ReaderTextQuote,
  ReaderTextSelection,
  ReaderTxtRegionAnchor,
  ReaderTxtTextAnchor,
} from './types'
