import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'rgb(0, 113, 227)',
  canvas: 'rgb(238, 239, 242)',
  chrome: 'rgba(255, 255, 255, 0.88)',
  focus: 'rgba(41, 97, 194, 0.85)',
  separator: 'rgba(49, 48, 53, 0.13)',
  text: 'rgba(27, 27, 30, 0.9)',
  textMuted: 'rgba(48, 46, 51, 0.62)',
} as const

const materializeAbove = stylex.keyframes({
  from: {
    opacity: 0.72,
    transform: 'translate(-50%, -100%) translateY(4px) scale(0.96)',
  },
  to: {
    opacity: 1,
    transform: 'translate(-50%, -100%) translateY(0) scale(1)',
  },
})

const materializeBelow = stylex.keyframes({
  from: {
    opacity: 0.72,
    transform: 'translate(-50%, 0) translateY(-4px) scale(0.96)',
  },
  to: {
    opacity: 1,
    transform: 'translate(-50%, 0) translateY(0) scale(1)',
  },
})

export const readerStyles = stylex.create({
  root: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flex: 1,
    flexDirection: 'column',
    borderColor: colors.separator,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 14,
    backgroundColor: colors.canvas,
    color: colors.text,
    outline: 'none',
    boxShadow: {
      'default': '0 1px 2px rgba(31, 38, 48, 0.04)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  rootWindow: {
    overflow: 'visible',
    borderWidth: 0,
    borderRadius: 0,
    paddingTop: 56,
    backgroundColor: 'rgb(255, 255, 255)',
    boxShadow: 'none',
  },
  toolbar: {
    position: 'relative',
    zIndex: 2,
    display: 'grid',
    minHeight: 52,
    alignItems: 'center',
    gridTemplateColumns: 'minmax(140px, 1fr) auto minmax(140px, 1fr)',
    gap: 12,
    borderBottomColor: colors.separator,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingRight: 12,
    paddingLeft: 14,
    backgroundColor: {
      'default': colors.chrome,
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 250, 251)',
    },
    backdropFilter: {
      'default': 'blur(22px) saturate(160%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
  },
  toolbarWindow: {
    position: 'fixed',
    zIndex: 22,
    top: 10,
    right: 14,
    left: 'var(--reader-leading-offset, 270px)',
    display: 'block',
    minHeight: 36,
    borderBottomWidth: 0,
    paddingRight: 0,
    paddingLeft: 0,
    backgroundColor: 'transparent',
    backdropFilter: 'none',
    pointerEvents: 'none',
    transitionDuration: {
      'default': '300ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'left',
    transitionTimingFunction: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
  },
  titleGroup: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 8,
  },
  title: {
    overflow: 'hidden',
    margin: 0,
    fontSize: 13,
    fontWeight: 600,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  format: {
    flexShrink: 0,
    borderRadius: 5,
    paddingTop: 2,
    paddingRight: 5,
    paddingBottom: 2,
    paddingLeft: 5,
    backgroundColor: 'rgba(73, 72, 77, 0.08)',
    color: colors.textMuted,
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: '0.04em',
    lineHeight: '13px',
    textTransform: 'uppercase',
  },
  navigation: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  navigationWindow: {
    position: 'absolute',
    top: 0,
    left: 0,
    pointerEvents: 'auto',
  },
  actions: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 6,
  },
  actionsWindow: {
    position: 'absolute',
    top: 0,
    right: 0,
    pointerEvents: 'auto',
  },
  windowControlGroup: {
    height: 36,
    gap: 0,
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.82)',
      '@media (prefers-contrast: more)': 'rgba(35, 39, 46, 0.82)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 18,
    padding: 1,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.08)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(240, 242, 246)',
      '@media (prefers-contrast: more)': 'rgb(248, 249, 251)',
    },
    backgroundImage: 'linear-gradient(145deg, rgba(255, 255, 255, 0.34) 0%, rgba(255, 255, 255, 0.04) 38%, rgba(156, 166, 182, 0.08) 68%, rgba(255, 255, 255, 0.14) 100%)',
    backdropFilter: {
      'default': 'blur(16px) saturate(180%) brightness(1.03)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': '0 4px 12px rgba(24, 30, 40, 0.10), 0 0 0 0.5px rgba(56, 64, 77, 0.16), inset 0 1px rgba(255, 255, 255, 0.90), inset 0 -1px rgba(70, 79, 93, 0.16), inset 1px 0 rgba(255, 255, 255, 0.42), inset -1px 0 rgba(70, 79, 93, 0.08)',
      '@media (prefers-contrast: more)': '0 4px 12px rgba(22, 27, 35, 0.16), 0 0 0 1px rgba(35, 39, 46, 0.48), inset 0 1px rgba(255, 255, 255, 0.92)',
    },
  },
  button: {
    position: 'relative',
    display: 'grid',
    width: 30,
    height: 30,
    flexShrink: 0,
    alignItems: 'center',
    justifyItems: 'center',
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(69, 72, 79, 0.08)',
      ':active': 'rgba(69, 72, 79, 0.14)',
      ':disabled': 'transparent',
    },
    color: {
      'default': colors.text,
      ':disabled': 'rgba(48, 46, 51, 0.28)',
    },
    cursor: {
      'default': 'default',
      ':disabled': 'not-allowed',
    },
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
      ':disabled': 'none',
    },
    transitionDuration: {
      'default': '90ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  buttonActive: {
    backgroundColor: 'rgba(0, 113, 227, 0.12)',
    color: colors.accent,
  },
  buttonWindow: {
    width: 32,
    height: 32,
    borderColor: 'transparent',
    borderRadius: 16,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.30)',
      ':active': 'rgba(58, 66, 78, 0.14)',
      ':disabled': 'transparent',
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  statusChip: {
    flexShrink: 0,
    borderRadius: 999,
    paddingTop: 2,
    paddingRight: 6,
    paddingBottom: 2,
    paddingLeft: 6,
    backgroundColor: 'rgba(0, 113, 227, 0.09)',
    color: 'rgb(0, 92, 190)',
    fontSize: 9,
    fontWeight: 600,
    lineHeight: '13px',
  },
  location: {
    minWidth: 80,
    color: colors.textMuted,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    textAlign: 'center',
  },
  viewport: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flex: 1,
  },
  enginePane: {
    position: 'relative',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflow: 'hidden',
  },
  engine: {
    position: 'absolute',
    inset: 0,
    overflow: 'hidden',
  },
  overlay: {
    position: 'absolute',
    zIndex: 3,
    inset: 0,
    display: 'grid',
    alignItems: 'center',
    justifyItems: 'center',
    padding: 24,
    backgroundColor: colors.canvas,
    color: colors.textMuted,
    fontSize: 13,
    textAlign: 'center',
  },
  error: {
    color: 'rgb(176, 39, 49)',
  },
  annotationBadge: {
    position: 'absolute',
    top: -3,
    right: -4,
    display: 'grid',
    minWidth: 14,
    height: 14,
    alignItems: 'center',
    justifyItems: 'center',
    borderColor: colors.chrome,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 999,
    paddingRight: 3,
    paddingLeft: 3,
    backgroundColor: colors.accent,
    color: 'white',
    fontSize: 8,
    fontWeight: 700,
    lineHeight: '12px',
  },
  annotationPanel: {
    position: 'absolute',
    zIndex: 8,
    top: 0,
    right: 0,
    bottom: 0,
    display: 'flex',
    width: 304,
    maxWidth: 'min(304px, calc(100% - 44px))',
    minHeight: 0,
    flexDirection: 'column',
    borderLeftColor: colors.separator,
    borderLeftStyle: 'solid',
    borderLeftWidth: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.96)',
    boxShadow: '-10px 0 28px rgba(25, 31, 41, 0.08), -1px 0 rgba(255, 255, 255, 0.72)',
    opacity: 1,
    transform: 'translateX(0)',
    transitionDuration: {
      'default': '220ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'transform, opacity',
    transitionTimingFunction: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
    willChange: 'transform, opacity',
  },
  annotationPanelClosed: {
    opacity: 0,
    pointerEvents: 'none',
    transform: 'translateX(calc(100% + 12px))',
  },
  panelHeader: {
    display: 'flex',
    minHeight: 48,
    alignItems: 'center',
    borderBottomColor: colors.separator,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    gap: 2,
    padding: 7,
    backgroundColor: 'rgba(255, 255, 255, 0.78)',
  },
  sidebarTab: {
    display: 'flex',
    height: 32,
    minWidth: 0,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 7,
    paddingRight: 8,
    paddingLeft: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(71, 76, 86, 0.07)',
      ':active': 'rgba(71, 76, 86, 0.12)',
    },
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 11,
    fontWeight: 560,
    letterSpacing: 0,
    outline: 'none',
  },
  sidebarTabActive: {
    borderColor: 'rgba(42, 48, 58, 0.10)',
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    color: colors.text,
    boxShadow: '0 1px 3px rgba(24, 30, 40, 0.09), inset 0 1px rgba(255, 255, 255, 0.88)',
  },
  tabCount: {
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    paddingRight: 4,
    paddingLeft: 4,
    backgroundColor: 'rgba(69, 74, 84, 0.10)',
    color: colors.textMuted,
    fontSize: 9,
    fontVariantNumeric: 'tabular-nums',
    lineHeight: '16px',
    textAlign: 'center',
  },
  panelContent: {
    minHeight: 0,
    overflow: 'hidden',
    flex: 1,
  },
  annotationList: {
    minHeight: 0,
    overflowY: 'auto',
    flex: 1,
    padding: 10,
  },
  emptyAnnotations: {
    paddingTop: 34,
    paddingRight: 18,
    paddingBottom: 34,
    paddingLeft: 18,
    color: colors.textMuted,
    fontSize: 11,
    lineHeight: '17px',
    textAlign: 'center',
  },
  annotationItem: {
    position: 'relative',
    marginBottom: 8,
    borderColor: colors.separator,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 9,
    paddingLeft: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
    boxShadow: '0 1px 2px rgba(31, 38, 48, 0.035)',
    contentVisibility: 'auto',
    containIntrinsicSize: '92px',
  },
  outlineList: {
    position: 'relative',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflowY: 'auto',
    contain: 'strict',
  },
  outlineSpacer: {
    position: 'relative',
    width: '100%',
  },
  outlineVirtualRow: {
    position: 'absolute',
    right: 6,
    left: 6,
    height: 29,
  },
  outlineRow: {
    display: 'flex',
    height: 29,
    alignItems: 'center',
    borderRadius: 6,
    paddingRight: 6,
    color: colors.textMuted,
  },
  outlineRowActive: {
    backgroundColor: 'rgba(0, 113, 227, 0.11)',
    color: 'rgb(0, 92, 190)',
  },
  outlineDisclosure: {
    display: 'grid',
    width: 22,
    height: 26,
    flexShrink: 0,
    alignItems: 'center',
    justifyItems: 'center',
    borderWidth: 0,
    borderRadius: 5,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(67, 72, 82, 0.08)',
      ':active': 'rgba(67, 72, 82, 0.14)',
    },
    color: 'inherit',
    cursor: 'default',
  },
  outlineDisclosureSpacer: {
    width: 22,
    height: 1,
    flexShrink: 0,
  },
  outlineTarget: {
    overflow: 'hidden',
    minWidth: 0,
    minHeight: 27,
    flex: 1,
    borderWidth: 0,
    padding: 0,
    backgroundColor: 'transparent',
    color: 'inherit',
    cursor: 'default',
    fontSize: 11,
    fontWeight: 450,
    letterSpacing: 0,
    lineHeight: '15px',
    outline: 'none',
    textAlign: 'left',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  outlineLabel: {
    overflow: 'hidden',
    minWidth: 0,
    flex: 1,
    fontSize: 11,
    fontWeight: 580,
    lineHeight: '15px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  annotationItemActive: {
    borderColor: 'rgba(0, 113, 227, 0.42)',
    boxShadow: '0 0 0 2px rgba(0, 113, 227, 0.08)',
  },
  annotationTarget: {
    display: 'flex',
    width: '100%',
    alignItems: 'center',
    gap: 7,
    borderWidth: 0,
    padding: 0,
    backgroundColor: 'transparent',
    color: colors.textMuted,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
  },
  annotationDot: {
    width: 8,
    height: 8,
    flexShrink: 0,
    borderRadius: 999,
    boxShadow: '0 0 0 1px rgba(40, 37, 30, 0.12) inset',
  },
  annotationMeta: {
    overflow: 'hidden',
    flex: 1,
    fontSize: 9,
    fontWeight: 600,
    lineHeight: '13px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  annotationQuote: {
    display: '-webkit-box',
    overflow: 'hidden',
    marginTop: 8,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingLeft: 8,
    borderLeftColor: 'rgba(48, 46, 51, 0.18)',
    borderLeftStyle: 'solid',
    borderLeftWidth: 2,
    color: colors.textMuted,
    fontSize: 10,
    fontStyle: 'normal',
    lineHeight: '15px',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: 3,
  },
  annotationBody: {
    marginTop: 8,
    marginBottom: 0,
    color: colors.text,
    fontSize: 11,
    lineHeight: '17px',
    overflowWrap: 'anywhere',
    whiteSpace: 'pre-wrap',
  },
  annotationActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 3,
    marginTop: 7,
  },
  itemButton: {
    display: 'grid',
    width: 25,
    height: 25,
    alignItems: 'center',
    justifyItems: 'center',
    borderWidth: 0,
    borderRadius: 6,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(69, 72, 79, 0.08)',
      ':active': 'rgba(69, 72, 79, 0.14)',
    },
    color: colors.textMuted,
    cursor: 'default',
    outline: 'none',
  },
  deleteButton: {
    color: 'rgb(176, 39, 49)',
  },
  panelEditor: {
    marginTop: 8,
  },
  panelTextarea: {
    width: '100%',
    resize: 'vertical',
    borderColor: 'rgba(49, 48, 53, 0.2)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 7,
    padding: 7,
    backgroundColor: 'white',
    color: colors.text,
    fontFamily: 'inherit',
    fontSize: 11,
    lineHeight: '16px',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus': `0 0 0 2px ${colors.focus}`,
    },
  },
  panelEditorActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 6,
    marginTop: 7,
  },
  textButton: {
    minHeight: 27,
    borderWidth: 0,
    borderRadius: 7,
    paddingRight: 9,
    paddingLeft: 9,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(69, 72, 79, 0.08)',
      ':active': 'rgba(69, 72, 79, 0.14)',
    },
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 10,
    fontWeight: 600,
  },
  primaryTextButton: {
    display: 'flex',
    minHeight: 27,
    alignItems: 'center',
    gap: 5,
    borderWidth: 0,
    borderRadius: 7,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: {
      'default': colors.accent,
      ':hover': 'rgb(0, 103, 211)',
      ':active': 'rgb(0, 92, 192)',
      ':disabled': 'rgba(0, 113, 227, 0.34)',
    },
    color: 'white',
    cursor: {
      'default': 'default',
      ':disabled': 'not-allowed',
    },
    fontSize: 10,
    fontWeight: 650,
    outline: 'none',
  },
  glassPopover: {
    position: 'fixed',
    zIndex: 40,
    maxWidth: 'calc(100vw - 24px)',
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.82)',
      '@media (prefers-contrast: more)': 'rgba(35, 39, 46, 0.82)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.08)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(240, 242, 246)',
      '@media (prefers-contrast: more)': 'rgb(248, 249, 251)',
    },
    backgroundImage: 'linear-gradient(145deg, rgba(255, 255, 255, 0.34) 0%, rgba(255, 255, 255, 0.04) 38%, rgba(156, 166, 182, 0.08) 68%, rgba(255, 255, 255, 0.14) 100%)',
    color: 'rgba(27, 31, 38, 0.92)',
    backdropFilter: {
      'default': 'blur(12px) saturate(180%) brightness(1.03)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': '0 4px 12px rgba(24, 30, 40, 0.10), 0 0 0 0.5px rgba(56, 64, 77, 0.16), inset 0 1px rgba(255, 255, 255, 0.90), inset 0 -1px rgba(70, 79, 93, 0.16), inset 1px 0 rgba(255, 255, 255, 0.42), inset -1px 0 rgba(70, 79, 93, 0.08)',
      '@media (prefers-contrast: more)': '0 4px 12px rgba(22, 27, 35, 0.16), 0 0 0 1px rgba(35, 39, 46, 0.48), inset 0 1px rgba(255, 255, 255, 0.92)',
    },
    isolation: 'isolate',
    animationDuration: {
      'default': '180ms',
      '@media (prefers-reduced-motion: reduce)': '100ms',
    },
    animationFillMode: 'backwards',
    animationTimingFunction: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
    willChange: 'transform, opacity',
  },
  popoverAbove: {
    transform: 'translate(-50%, -100%)',
    transformOrigin: '50% calc(100% + 10px)',
    animationName: {
      'default': materializeAbove,
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
  },
  popoverBelow: {
    transform: 'translate(-50%, 0)',
    transformOrigin: '50% -10px',
    animationName: {
      'default': materializeBelow,
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
  },
  selectionToolbar: {
    width: 234,
    height: 44,
    boxSizing: 'border-box',
    overflow: 'hidden',
    borderRadius: 22,
    padding: 0,
  },
  selectionToolbarRegion: {
    width: 188,
  },
  paletteTool: {
    position: 'absolute',
    display: 'grid',
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyItems: 'center',
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 16,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.30)',
      ':active': 'rgba(58, 66, 78, 0.14)',
      '@media (prefers-contrast: more)': 'rgba(255, 255, 255, 0.44)',
    },
    color: 'rgba(29, 34, 42, 0.88)',
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  paletteClose: {
    top: 6,
    left: 6,
  },
  paletteCopy: {
    top: 6,
    left: 52,
  },
  paletteColor: {
    top: 6,
    left: 98,
  },
  paletteColorRegion: {
    left: 52,
  },
  paletteHighlight: {
    top: 6,
    left: 144,
  },
  paletteHighlightRegion: {
    left: 98,
  },
  paletteAnnotate: {
    top: 6,
    left: 190,
  },
  paletteAnnotateRegion: {
    left: 144,
  },
  paletteColorTool: {
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.30)',
      ':active': 'rgba(58, 66, 78, 0.14)',
    },
  },
  paletteCurrentColor: {
    width: 22,
    height: 22,
    borderColor: 'rgba(255, 255, 255, 0.92)',
    borderStyle: 'solid',
    borderWidth: 2,
    borderRadius: 11,
    boxShadow: '0 0 0 1px rgba(38, 44, 54, 0.42)',
  },
  paletteSwatch: {
    position: 'absolute',
    width: 26,
    height: 26,
    borderColor: 'rgba(255, 255, 255, 0.86)',
    borderStyle: 'solid',
    borderWidth: 2,
    borderRadius: 13,
    padding: 0,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': '0 0 0 1px rgba(38, 44, 54, 0.18)',
      ':hover': '0 0 0 2px rgba(255, 255, 255, 0.90), 0 0 0 3px rgba(38, 44, 54, 0.28)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.92)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  paletteColorYellow: {
    top: 9,
    left: 48,
  },
  paletteColorGreen: {
    top: 9,
    left: 85,
  },
  paletteColorBlue: {
    top: 9,
    left: 122,
  },
  paletteColorPink: {
    top: 9,
    left: 159,
  },
  paletteColorPurple: {
    top: 9,
    left: 196,
  },
  colorGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    paddingRight: 3,
    paddingLeft: 3,
  },
  colorButton: {
    width: 20,
    height: 20,
    flexShrink: 0,
    borderColor: 'rgba(39, 44, 52, 0.16)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 999,
    padding: 0,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'inset 0 1px rgba(255, 255, 255, 0.5), 0 1px 2px rgba(27, 32, 40, 0.12)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.88)',
    },
    transitionDuration: {
      'default': '90ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'transform, box-shadow',
    transitionTimingFunction: 'ease-out',
  },
  colorButtonSelected: {
    boxShadow: '0 0 0 2px rgba(246, 248, 252, 0.96), 0 0 0 3px rgba(40, 47, 58, 0.52), inset 0 1px rgba(255, 255, 255, 0.5)',
  },
  colorYellow: {
    backgroundColor: 'rgb(255, 205, 31)',
  },
  colorGreen: {
    backgroundColor: 'rgb(63, 190, 108)',
  },
  colorBlue: {
    backgroundColor: 'rgb(64, 148, 255)',
  },
  colorPink: {
    backgroundColor: 'rgb(255, 83, 139)',
  },
  colorPurple: {
    backgroundColor: 'rgb(140, 98, 255)',
  },
  selectionClose: {
    display: 'grid',
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyItems: 'center',
    borderWidth: 0,
    borderRadius: 17,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.30)',
      ':active': 'rgba(58, 66, 78, 0.14)',
    },
    color: 'inherit',
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  noteComposer: {
    zIndex: 41,
    display: 'flex',
    width: 320,
    flexDirection: 'column',
    borderRadius: 18,
    padding: 12,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.98)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(240, 242, 246)',
      '@media (prefers-contrast: more)': 'rgb(248, 249, 251)',
    },
    backdropFilter: {
      'default': 'blur(16px) saturate(180%) brightness(1.03)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': '0 10px 28px rgba(25, 32, 43, 0.16), 0 2px 7px rgba(25, 32, 43, 0.08), inset 0 1px rgba(255, 255, 255, 0.92), inset 0 -1px rgba(70, 82, 101, 0.12)',
      '@media (prefers-contrast: more)': '0 10px 28px rgba(24, 30, 40, 0.22), 0 0 0 1px rgba(34, 41, 52, 0.30), inset 0 1px rgba(255, 255, 255, 0.96)',
    },
  },
  composerHeader: {
    display: 'flex',
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: 2,
  },
  composerTitle: {
    fontSize: 12,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '17px',
  },
  composerQuote: {
    display: '-webkit-box',
    overflow: 'hidden',
    marginBottom: 7,
    borderLeftColor: 'rgba(48, 56, 68, 0.22)',
    borderLeftStyle: 'solid',
    borderLeftWidth: 2,
    paddingTop: 4,
    paddingRight: 6,
    paddingBottom: 4,
    paddingLeft: 9,
    color: 'rgba(42, 48, 58, 0.72)',
    fontSize: 10,
    lineHeight: '15px',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: 2,
  },
  composerTextarea: {
    width: '100%',
    resize: 'none',
    borderColor: 'rgba(45, 53, 66, 0.16)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 12,
    padding: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.86)',
    color: 'rgba(27, 31, 38, 0.92)',
    fontFamily: 'inherit',
    fontSize: 12,
    lineHeight: '17px',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus': `0 0 0 2px ${colors.focus}, inset 0 1px rgba(255, 255, 255, 0.72)`,
    },
  },
  composerFooter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  footer: {
    position: 'relative',
    zIndex: 2,
    height: 3,
    flexShrink: 0,
    backgroundColor: 'rgba(48, 46, 51, 0.10)',
  },
  progress: {
    height: '100%',
    backgroundColor: colors.accent,
    transitionDuration: {
      'default': '160ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'width',
    transitionTimingFunction: 'ease-out',
  },
})
