import * as stylex from '@stylexjs/stylex'
import { readerTheme } from './reader-theme.stylex'

export const readerShellStyles = stylex.create({
  root: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flex: 1,
    flexDirection: 'column',
    borderColor: readerTheme.separator,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 14,
    backgroundColor: readerTheme.canvas,
    color: readerTheme.text,
    outline: 'none',
    boxShadow: {
      'default': '0 1px 2px rgba(31, 38, 48, 0.04)',
      ':focus-visible': `0 0 0 2px ${readerTheme.focus}`,
    },
  },
  rootWindow: {
    overflow: 'visible',
    borderWidth: 0,
    borderRadius: 0,
    paddingTop: 56,
    backgroundColor: 'rgb(255, 255, 255)',
    boxShadow: 'none',
  },
  toolbar: {
    position: 'relative',
    zIndex: 2,
    display: 'grid',
    minHeight: 52,
    alignItems: 'center',
    gridTemplateColumns: 'minmax(140px, 1fr) auto minmax(140px, 1fr)',
    gap: 12,
    borderBottomColor: readerTheme.separator,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingRight: 12,
    paddingLeft: 14,
    backgroundColor: {
      'default': readerTheme.chrome,
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 250, 251)',
    },
    backdropFilter: {
      'default': 'blur(22px) saturate(160%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
  },
  toolbarWindow: {
    position: 'fixed',
    zIndex: 22,
    top: 10,
    right: 14,
    left: 'var(--reader-leading-offset, 270px)',
    display: 'block',
    minHeight: 36,
    borderBottomWidth: 0,
    paddingRight: 0,
    paddingLeft: 0,
    backgroundColor: 'transparent',
    backdropFilter: 'none',
    pointerEvents: 'none',
    transitionDuration: {
      'default': '300ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'left',
    transitionTimingFunction: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
  },
  titleGroup: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 8,
  },
  titleGroupWindow: {
    position: 'absolute',
    top: 0,
    right: 160,
    left: 160,
    height: 36,
    justifyContent: 'center',
    pointerEvents: 'none',
  },
  title: {
    overflow: 'hidden',
    margin: 0,
    fontSize: 13,
    fontWeight: 600,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  format: {
    flexShrink: 0,
    borderRadius: 5,
    paddingTop: 2,
    paddingRight: 5,
    paddingBottom: 2,
    paddingLeft: 5,
    backgroundColor: 'rgba(73, 72, 77, 0.08)',
    color: readerTheme.textMuted,
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: '0.04em',
    lineHeight: '13px',
    textTransform: 'uppercase',
  },
  navigation: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  navigationWindow: {
    position: 'absolute',
    top: 0,
    left: 0,
    pointerEvents: 'auto',
  },
  actions: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 6,
  },
  actionsWindow: {
    position: 'absolute',
    top: 0,
    right: 0,
    pointerEvents: 'auto',
  },
  actionsWindowWithSidebarActions: {
    right: 44,
  },
  sidebarActions: {
    display: 'flex',
    alignItems: 'center',
  },
  sidebarActionsWindow: {
    position: 'fixed',
    zIndex: 24,
    top: 10,
    right: 14,
    pointerEvents: 'auto',
  },
  windowControlGroup: {
    height: 36,
    gap: 0,
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.82)',
      '@media (prefers-contrast: more)': 'rgba(35, 39, 46, 0.82)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 18,
    padding: 1,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.08)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(240, 242, 246)',
      '@media (prefers-contrast: more)': 'rgb(248, 249, 251)',
    },
    backgroundImage: 'linear-gradient(145deg, rgba(255, 255, 255, 0.34) 0%, rgba(255, 255, 255, 0.04) 38%, rgba(156, 166, 182, 0.08) 68%, rgba(255, 255, 255, 0.14) 100%)',
    backdropFilter: {
      'default': 'blur(16px) saturate(180%) brightness(1.03)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': '0 4px 12px rgba(24, 30, 40, 0.10), 0 0 0 0.5px rgba(56, 64, 77, 0.16), inset 0 1px rgba(255, 255, 255, 0.90), inset 0 -1px rgba(70, 79, 93, 0.16), inset 1px 0 rgba(255, 255, 255, 0.42), inset -1px 0 rgba(70, 79, 93, 0.08)',
      '@media (prefers-contrast: more)': '0 4px 12px rgba(22, 27, 35, 0.16), 0 0 0 1px rgba(35, 39, 46, 0.48), inset 0 1px rgba(255, 255, 255, 0.92)',
    },
  },
  button: {
    position: 'relative',
    display: 'grid',
    width: 30,
    height: 30,
    flexShrink: 0,
    alignItems: 'center',
    justifyItems: 'center',
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(69, 72, 79, 0.08)',
      ':active': 'rgba(69, 72, 79, 0.14)',
      ':disabled': 'transparent',
    },
    color: {
      'default': readerTheme.text,
      ':disabled': 'rgba(48, 46, 51, 0.28)',
    },
    cursor: {
      'default': 'default',
      ':disabled': 'not-allowed',
    },
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${readerTheme.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
      ':disabled': 'none',
    },
    transitionDuration: {
      'default': '90ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  buttonActive: {
    backgroundColor: 'rgba(0, 113, 227, 0.12)',
    color: readerTheme.accent,
  },
  buttonWindow: {
    width: 32,
    height: 32,
    borderColor: 'transparent',
    borderRadius: 16,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.30)',
      ':active': 'rgba(58, 66, 78, 0.14)',
      ':disabled': 'transparent',
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${readerTheme.focus}`,
    },
  },
  statusChip: {
    flexShrink: 0,
    borderRadius: 999,
    paddingTop: 2,
    paddingRight: 6,
    paddingBottom: 2,
    paddingLeft: 6,
    backgroundColor: 'rgba(0, 113, 227, 0.09)',
    color: 'rgb(0, 92, 190)',
    fontSize: 9,
    fontWeight: 600,
    lineHeight: '13px',
  },
  location: {
    minWidth: 80,
    color: readerTheme.textMuted,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    textAlign: 'center',
  },
  viewport: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flex: 1,
  },
  enginePane: {
    position: 'relative',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflow: 'hidden',
  },
  engine: {
    position: 'absolute',
    inset: 0,
    overflow: 'hidden',
  },
  overlay: {
    position: 'absolute',
    zIndex: 3,
    inset: 0,
    display: 'grid',
    alignItems: 'center',
    justifyItems: 'center',
    padding: 24,
    backgroundColor: readerTheme.canvas,
    color: readerTheme.textMuted,
    fontSize: 13,
    textAlign: 'center',
  },
  error: {
    color: 'rgb(176, 39, 49)',
  },
  annotationBadge: {
    position: 'absolute',
    top: -3,
    right: -4,
    display: 'grid',
    minWidth: 14,
    height: 14,
    alignItems: 'center',
    justifyItems: 'center',
    borderColor: readerTheme.chrome,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 999,
    paddingRight: 3,
    paddingLeft: 3,
    backgroundColor: readerTheme.accent,
    color: 'white',
    fontSize: 8,
    fontWeight: 700,
    lineHeight: '12px',
  },
  footer: {
    position: 'relative',
    zIndex: 2,
    height: 3,
    flexShrink: 0,
    backgroundColor: 'rgba(48, 46, 51, 0.10)',
  },
  progress: {
    height: '100%',
    backgroundColor: readerTheme.accent,
    transitionDuration: {
      'default': '160ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'width',
    transitionTimingFunction: 'ease-out',
  },
  dialog: {
    'width': 'min(420px, calc(100vw - 40px))',
    'maxWidth': 'none',
    'overflow': 'hidden',
    'borderColor': 'rgba(255, 255, 255, 0.78)',
    'borderStyle': 'solid',
    'borderWidth': 1,
    'borderRadius': 8,
    'padding': 18,
    'backgroundColor': 'rgb(250, 250, 251)',
    'boxShadow': '0 18px 50px rgba(20, 25, 34, 0.22), 0 2px 8px rgba(20, 25, 34, 0.12)',
    'color': readerTheme.text,
    'outline': 'none',
    '::backdrop': {
      backgroundColor: 'rgba(24, 28, 35, 0.24)',
      backdropFilter: {
        'default': 'blur(3px)',
        '@media (prefers-reduced-transparency: reduce)': 'none',
      },
    },
  },
  dialogTitle: {
    margin: 0,
    color: readerTheme.text,
    fontSize: 15,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '21px',
  },
  dialogDescription: {
    marginTop: 8,
    marginBottom: 18,
    color: readerTheme.textMuted,
    fontSize: 12,
    lineHeight: '18px',
  },
  dialogActions: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: 7,
  },
  dialogButton: {
    minHeight: 32,
    borderColor: readerTheme.separator,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 7,
    paddingRight: 11,
    paddingLeft: 11,
    backgroundColor: {
      'default': 'rgb(255, 255, 255)',
      ':hover': 'rgb(245, 246, 248)',
      ':active': 'rgb(238, 240, 243)',
      ':disabled': 'rgb(245, 246, 248)',
    },
    color: readerTheme.text,
    cursor: {
      'default': 'default',
      ':disabled': 'not-allowed',
    },
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${readerTheme.focus}`,
    },
  },
  dialogPrimaryButton: {
    borderColor: 'rgb(0, 100, 210)',
    backgroundColor: {
      'default': readerTheme.accent,
      ':hover': 'rgb(0, 101, 212)',
      ':active': 'rgb(0, 88, 186)',
      ':disabled': 'rgba(0, 113, 227, 0.46)',
    },
    color: 'white',
  },
})
