import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'rgb(0, 113, 227)',
  canvas: 'rgb(238, 239, 242)',
  chrome: 'rgba(255, 255, 255, 0.88)',
  focus: 'rgba(41, 97, 194, 0.85)',
  separator: 'rgba(49, 48, 53, 0.13)',
  text: 'rgba(27, 27, 30, 0.9)',
  textMuted: 'rgba(48, 46, 51, 0.62)',
} as const

const materializeAbove = stylex.keyframes({
  from: {
    opacity: 0.78,
    transform: 'translate(-50%, -100%) translateY(5px) scale(0.94)',
    backdropFilter: 'blur(4px) saturate(135%) brightness(1.12)',
  },
  to: {
    opacity: 1,
    transform: 'translate(-50%, -100%) translateY(0) scale(1)',
    backdropFilter: 'blur(14px) saturate(165%) brightness(1.06)',
  },
})

const materializeBelow = stylex.keyframes({
  from: {
    opacity: 0.78,
    transform: 'translate(-50%, 0) translateY(-5px) scale(0.94)',
    backdropFilter: 'blur(4px) saturate(135%) brightness(1.12)',
  },
  to: {
    opacity: 1,
    transform: 'translate(-50%, 0) translateY(0) scale(1)',
    backdropFilter: 'blur(14px) saturate(165%) brightness(1.06)',
  },
})

export const readerStyles = stylex.create({
  root: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flex: 1,
    flexDirection: 'column',
    borderColor: colors.separator,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 14,
    backgroundColor: colors.canvas,
    color: colors.text,
    outline: 'none',
    boxShadow: {
      'default': '0 1px 2px rgba(31, 38, 48, 0.04)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  toolbar: {
    position: 'relative',
    zIndex: 2,
    display: 'grid',
    minHeight: 52,
    alignItems: 'center',
    gridTemplateColumns: 'minmax(140px, 1fr) auto minmax(140px, 1fr)',
    gap: 12,
    borderBottomColor: colors.separator,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingRight: 12,
    paddingLeft: 14,
    backgroundColor: {
      'default': colors.chrome,
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 250, 251)',
    },
    backdropFilter: {
      'default': 'blur(22px) saturate(160%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
  },
  titleGroup: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 8,
  },
  title: {
    overflow: 'hidden',
    margin: 0,
    fontSize: 13,
    fontWeight: 600,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  format: {
    flexShrink: 0,
    borderRadius: 5,
    paddingTop: 2,
    paddingRight: 5,
    paddingBottom: 2,
    paddingLeft: 5,
    backgroundColor: 'rgba(73, 72, 77, 0.08)',
    color: colors.textMuted,
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: '0.04em',
    lineHeight: '13px',
    textTransform: 'uppercase',
  },
  navigation: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  actions: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 6,
  },
  button: {
    position: 'relative',
    display: 'grid',
    width: 30,
    height: 30,
    flexShrink: 0,
    alignItems: 'center',
    justifyItems: 'center',
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(69, 72, 79, 0.08)',
      ':active': 'rgba(69, 72, 79, 0.14)',
      ':disabled': 'transparent',
    },
    color: {
      'default': colors.text,
      ':disabled': 'rgba(48, 46, 51, 0.28)',
    },
    cursor: {
      'default': 'default',
      ':disabled': 'not-allowed',
    },
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
      ':disabled': 'none',
    },
    transitionDuration: {
      'default': '90ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  buttonActive: {
    backgroundColor: 'rgba(0, 113, 227, 0.12)',
    color: colors.accent,
  },
  statusChip: {
    flexShrink: 0,
    borderRadius: 999,
    paddingTop: 2,
    paddingRight: 6,
    paddingBottom: 2,
    paddingLeft: 6,
    backgroundColor: 'rgba(0, 113, 227, 0.09)',
    color: 'rgb(0, 92, 190)',
    fontSize: 9,
    fontWeight: 600,
    lineHeight: '13px',
  },
  location: {
    minWidth: 80,
    color: colors.textMuted,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    textAlign: 'center',
  },
  modeGroup: {
    display: 'flex',
    overflow: 'hidden',
    flexShrink: 0,
    borderColor: colors.separator,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    padding: 2,
    backgroundColor: 'rgba(69, 72, 79, 0.05)',
  },
  modeButton: {
    height: 24,
    borderWidth: 0,
    borderRadius: 6,
    paddingRight: 8,
    paddingLeft: 8,
    backgroundColor: 'transparent',
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 10,
    fontWeight: 550,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  modeButtonActive: {
    backgroundColor: 'rgb(255, 255, 255)',
    color: colors.text,
    boxShadow: '0 1px 3px rgba(31, 38, 48, 0.14)',
  },
  modeButtonDisabled: {
    color: 'rgba(48, 46, 51, 0.3)',
    cursor: 'not-allowed',
  },
  viewport: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flex: 1,
  },
  enginePane: {
    position: 'relative',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflow: 'hidden',
  },
  engine: {
    position: 'absolute',
    inset: 0,
    overflow: 'hidden',
  },
  overlay: {
    position: 'absolute',
    zIndex: 3,
    inset: 0,
    display: 'grid',
    alignItems: 'center',
    justifyItems: 'center',
    padding: 24,
    backgroundColor: colors.canvas,
    color: colors.textMuted,
    fontSize: 13,
    textAlign: 'center',
  },
  error: {
    color: 'rgb(176, 39, 49)',
  },
  annotationBadge: {
    position: 'absolute',
    top: -3,
    right: -4,
    display: 'grid',
    minWidth: 14,
    height: 14,
    alignItems: 'center',
    justifyItems: 'center',
    borderColor: colors.chrome,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 999,
    paddingRight: 3,
    paddingLeft: 3,
    backgroundColor: colors.accent,
    color: 'white',
    fontSize: 8,
    fontWeight: 700,
    lineHeight: '12px',
  },
  annotationPanel: {
    display: 'flex',
    width: 292,
    minWidth: 240,
    minHeight: 0,
    flexDirection: 'column',
    borderLeftColor: colors.separator,
    borderLeftStyle: 'solid',
    borderLeftWidth: 1,
    backgroundColor: {
      'default': 'rgba(250, 250, 251, 0.92)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 250, 251)',
    },
    backdropFilter: {
      'default': 'blur(24px) saturate(150%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
  },
  panelHeader: {
    display: 'flex',
    minHeight: 56,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomColor: colors.separator,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingRight: 10,
    paddingLeft: 14,
  },
  panelTitle: {
    margin: 0,
    fontSize: 13,
    fontWeight: 650,
    lineHeight: '18px',
  },
  panelSubtitle: {
    margin: 0,
    color: colors.textMuted,
    fontSize: 9,
    lineHeight: '13px',
  },
  annotationList: {
    minHeight: 0,
    overflowY: 'auto',
    flex: 1,
    padding: 10,
  },
  emptyAnnotations: {
    paddingTop: 34,
    paddingRight: 18,
    paddingBottom: 34,
    paddingLeft: 18,
    color: colors.textMuted,
    fontSize: 11,
    lineHeight: '17px',
    textAlign: 'center',
  },
  annotationItem: {
    position: 'relative',
    marginBottom: 8,
    borderColor: colors.separator,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 9,
    paddingLeft: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
    boxShadow: '0 1px 2px rgba(31, 38, 48, 0.035)',
  },
  annotationItemActive: {
    borderColor: 'rgba(0, 113, 227, 0.42)',
    boxShadow: '0 0 0 2px rgba(0, 113, 227, 0.08)',
  },
  annotationTarget: {
    display: 'flex',
    width: '100%',
    alignItems: 'center',
    gap: 7,
    borderWidth: 0,
    padding: 0,
    backgroundColor: 'transparent',
    color: colors.textMuted,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
  },
  annotationDot: {
    width: 8,
    height: 8,
    flexShrink: 0,
    borderRadius: 999,
    boxShadow: '0 0 0 1px rgba(40, 37, 30, 0.12) inset',
  },
  annotationMeta: {
    overflow: 'hidden',
    flex: 1,
    fontSize: 9,
    fontWeight: 600,
    lineHeight: '13px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  annotationQuote: {
    display: '-webkit-box',
    overflow: 'hidden',
    marginTop: 8,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingLeft: 8,
    borderLeftColor: 'rgba(48, 46, 51, 0.18)',
    borderLeftStyle: 'solid',
    borderLeftWidth: 2,
    color: colors.textMuted,
    fontSize: 10,
    fontStyle: 'normal',
    lineHeight: '15px',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: 3,
  },
  annotationBody: {
    marginTop: 8,
    marginBottom: 0,
    color: colors.text,
    fontSize: 11,
    lineHeight: '17px',
    overflowWrap: 'anywhere',
    whiteSpace: 'pre-wrap',
  },
  annotationActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 3,
    marginTop: 7,
  },
  itemButton: {
    display: 'grid',
    width: 25,
    height: 25,
    alignItems: 'center',
    justifyItems: 'center',
    borderWidth: 0,
    borderRadius: 6,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(69, 72, 79, 0.08)',
      ':active': 'rgba(69, 72, 79, 0.14)',
    },
    color: colors.textMuted,
    cursor: 'default',
    outline: 'none',
  },
  deleteButton: {
    color: 'rgb(176, 39, 49)',
  },
  panelEditor: {
    marginTop: 8,
  },
  panelTextarea: {
    width: '100%',
    resize: 'vertical',
    borderColor: 'rgba(49, 48, 53, 0.2)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 7,
    padding: 7,
    backgroundColor: 'white',
    color: colors.text,
    fontFamily: 'inherit',
    fontSize: 11,
    lineHeight: '16px',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus': `0 0 0 2px ${colors.focus}`,
    },
  },
  panelEditorActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 6,
    marginTop: 7,
  },
  textButton: {
    minHeight: 27,
    borderWidth: 0,
    borderRadius: 7,
    paddingRight: 9,
    paddingLeft: 9,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(69, 72, 79, 0.08)',
      ':active': 'rgba(69, 72, 79, 0.14)',
    },
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 10,
    fontWeight: 600,
  },
  primaryTextButton: {
    display: 'flex',
    minHeight: 27,
    alignItems: 'center',
    gap: 5,
    borderWidth: 0,
    borderRadius: 7,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: {
      'default': colors.accent,
      ':hover': 'rgb(0, 103, 211)',
      ':active': 'rgb(0, 92, 192)',
      ':disabled': 'rgba(0, 113, 227, 0.34)',
    },
    color: 'white',
    cursor: {
      'default': 'default',
      ':disabled': 'not-allowed',
    },
    fontSize: 10,
    fontWeight: 650,
    outline: 'none',
  },
  glassPopover: {
    position: 'fixed',
    zIndex: 40,
    maxWidth: 'calc(100vw - 24px)',
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.84)',
      '@media (prefers-contrast: more)': 'rgba(34, 41, 52, 0.68)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    backgroundColor: {
      'default': 'rgba(236, 240, 247, 0.58)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(246, 247, 250)',
      '@media (prefers-contrast: more)': 'rgba(250, 251, 253, 0.98)',
    },
    backgroundImage: {
      'default': 'linear-gradient(180deg, rgba(255, 255, 255, 0.42) 0%, rgba(255, 255, 255, 0.12) 48%, rgba(105, 119, 140, 0.08) 100%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    color: 'rgba(27, 31, 38, 0.92)',
    backdropFilter: {
      'default': 'blur(14px) saturate(165%) brightness(1.06)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': '0 11px 28px rgba(27, 35, 48, 0.16), 0 2px 7px rgba(27, 35, 48, 0.08), inset 0 1px rgba(255, 255, 255, 0.96), inset 0 -1px rgba(65, 78, 98, 0.18), inset 1px 0 rgba(255, 255, 255, 0.54), inset -1px 0 rgba(65, 78, 98, 0.10)',
      '@media (prefers-contrast: more)': '0 12px 34px rgba(24, 30, 40, 0.22), 0 0 0 1px rgba(34, 41, 52, 0.28), inset 0 1px rgba(255, 255, 255, 0.96)',
    },
    isolation: 'isolate',
    animationDuration: {
      'default': '180ms',
      '@media (prefers-reduced-motion: reduce)': '100ms',
    },
    animationFillMode: 'backwards',
    animationTimingFunction: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
    willChange: 'transform, opacity, backdrop-filter',
  },
  popoverAbove: {
    transform: 'translate(-50%, -100%)',
    transformOrigin: '50% calc(100% + 10px)',
    animationName: {
      'default': materializeAbove,
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
  },
  popoverBelow: {
    transform: 'translate(-50%, 0)',
    transformOrigin: '50% -10px',
    animationName: {
      'default': materializeBelow,
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
  },
  selectionToolbar: {
    width: 270,
    height: 52,
    boxSizing: 'border-box',
    overflow: 'hidden',
    borderRadius: 26,
    padding: 0,
  },
  selectionToolbarRegion: {
    width: 220,
  },
  paletteTool: {
    position: 'absolute',
    display: 'grid',
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyItems: 'center',
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 17,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.54)',
      ':active': 'rgba(75, 85, 101, 0.18)',
      '@media (prefers-contrast: more)': 'rgba(255, 255, 255, 0.42)',
    },
    color: 'rgba(29, 34, 42, 0.88)',
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':hover': 'inset 0 1px rgba(255, 255, 255, 0.76), 0 2px 6px rgba(31, 39, 51, 0.08)',
      ':active': 'inset 0 1px rgba(255, 255, 255, 0.94), 0 0 9px rgba(255, 255, 255, 0.52)',
      ':focus-visible': `0 0 0 2px ${colors.focus}, inset 0 1px rgba(255, 255, 255, 0.72)`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.9)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  paletteClose: {
    top: 9,
    left: 9,
  },
  paletteCopy: {
    top: 9,
    left: 59,
  },
  paletteColor: {
    top: 9,
    left: 109,
  },
  paletteColorRegion: {
    left: 59,
  },
  paletteHighlight: {
    top: 9,
    left: 159,
  },
  paletteHighlightRegion: {
    left: 109,
  },
  paletteAnnotate: {
    top: 9,
    left: 209,
  },
  paletteAnnotateRegion: {
    left: 159,
  },
  paletteColorTool: {
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.54)',
      ':active': 'rgba(75, 85, 101, 0.18)',
    },
  },
  paletteCurrentColor: {
    width: 24,
    height: 24,
    borderColor: 'rgba(255, 255, 255, 0.92)',
    borderStyle: 'solid',
    borderWidth: 3,
    borderRadius: 12,
    boxShadow: '0 0 0 1px rgba(38, 44, 54, 0.50), 0 1px 3px rgba(25, 31, 41, 0.16)',
  },
  paletteSwatch: {
    position: 'absolute',
    width: 30,
    height: 30,
    borderColor: 'rgba(255, 255, 255, 0.86)',
    borderStyle: 'solid',
    borderWidth: 3,
    borderRadius: 15,
    padding: 0,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': '0 0 0 1px rgba(38, 44, 54, 0.22), 0 2px 5px rgba(25, 31, 41, 0.12)',
      ':hover': '0 0 0 2px rgba(255, 255, 255, 0.96), 0 0 0 3px rgba(38, 44, 54, 0.32), 0 3px 7px rgba(25, 31, 41, 0.14)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.88)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  paletteColorYellow: {
    top: 11,
    left: 55,
  },
  paletteColorGreen: {
    top: 11,
    left: 96,
  },
  paletteColorBlue: {
    top: 11,
    left: 137,
  },
  paletteColorPink: {
    top: 11,
    left: 178,
  },
  paletteColorPurple: {
    top: 11,
    left: 219,
  },
  colorGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    paddingRight: 3,
    paddingLeft: 3,
  },
  colorButton: {
    width: 20,
    height: 20,
    flexShrink: 0,
    borderColor: 'rgba(39, 44, 52, 0.16)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 999,
    padding: 0,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'inset 0 1px rgba(255, 255, 255, 0.5), 0 1px 2px rgba(27, 32, 40, 0.12)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.88)',
    },
    transitionDuration: {
      'default': '90ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'transform, box-shadow',
    transitionTimingFunction: 'ease-out',
  },
  colorButtonSelected: {
    boxShadow: '0 0 0 2px rgba(246, 248, 252, 0.96), 0 0 0 3px rgba(40, 47, 58, 0.52), inset 0 1px rgba(255, 255, 255, 0.5)',
  },
  colorYellow: {
    backgroundColor: 'rgb(255, 205, 31)',
  },
  colorGreen: {
    backgroundColor: 'rgb(63, 190, 108)',
  },
  colorBlue: {
    backgroundColor: 'rgb(64, 148, 255)',
  },
  colorPink: {
    backgroundColor: 'rgb(255, 83, 139)',
  },
  colorPurple: {
    backgroundColor: 'rgb(140, 98, 255)',
  },
  selectionClose: {
    display: 'grid',
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyItems: 'center',
    borderWidth: 0,
    borderRadius: 17,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.46)',
      ':active': 'rgba(72, 82, 97, 0.16)',
    },
    color: 'inherit',
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  noteComposer: {
    zIndex: 41,
    display: 'flex',
    width: 320,
    flexDirection: 'column',
    borderRadius: 22,
    padding: 12,
    backgroundColor: {
      'default': 'rgba(244, 247, 251, 0.86)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(246, 247, 250)',
      '@media (prefers-contrast: more)': 'rgb(250, 251, 253)',
    },
    backdropFilter: {
      'default': 'blur(24px) saturate(160%) brightness(1.04)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': '0 18px 46px rgba(25, 32, 43, 0.22), 0 3px 10px rgba(25, 32, 43, 0.10), inset 0 1px rgba(255, 255, 255, 0.96), inset 0 -1px rgba(70, 82, 101, 0.14)',
      '@media (prefers-contrast: more)': '0 18px 46px rgba(24, 30, 40, 0.26), 0 0 0 1px rgba(34, 41, 52, 0.30), inset 0 1px rgba(255, 255, 255, 0.98)',
    },
  },
  composerHeader: {
    display: 'flex',
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: 2,
  },
  composerTitle: {
    fontSize: 12,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '17px',
  },
  composerQuote: {
    display: '-webkit-box',
    overflow: 'hidden',
    marginBottom: 7,
    borderLeftColor: 'rgba(48, 56, 68, 0.22)',
    borderLeftStyle: 'solid',
    borderLeftWidth: 2,
    paddingTop: 4,
    paddingRight: 6,
    paddingBottom: 4,
    paddingLeft: 9,
    color: 'rgba(42, 48, 58, 0.64)',
    fontSize: 10,
    lineHeight: '15px',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: 2,
  },
  composerTextarea: {
    width: '100%',
    resize: 'none',
    borderColor: 'rgba(45, 53, 66, 0.16)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 12,
    padding: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.76)',
    color: 'rgba(27, 31, 38, 0.92)',
    fontFamily: 'inherit',
    fontSize: 12,
    lineHeight: '17px',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus': `0 0 0 2px ${colors.focus}, inset 0 1px rgba(255, 255, 255, 0.72)`,
    },
  },
  composerFooter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  footer: {
    position: 'relative',
    zIndex: 2,
    height: 3,
    flexShrink: 0,
    backgroundColor: 'rgba(48, 46, 51, 0.10)',
  },
  progress: {
    height: '100%',
    backgroundColor: colors.accent,
    transitionDuration: {
      'default': '160ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'width',
    transitionTimingFunction: 'ease-out',
  },
})
