import * as stylex from '@stylexjs/stylex'
import { readerTheme } from './reader-theme.stylex'

export const readerOutlineStyles = stylex.create({
  outlineList: {
    position: 'relative',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflowY: 'auto',
    contain: 'strict',
  },
  outlineSpacer: {
    position: 'relative',
    width: '100%',
  },
  outlineVirtualRow: {
    position: 'absolute',
    right: 6,
    left: 6,
    height: 29,
  },
  outlineRow: {
    display: 'flex',
    height: 29,
    alignItems: 'center',
    borderRadius: 6,
    paddingRight: 6,
    color: readerTheme.textMuted,
  },
  outlineRowActive: {
    backgroundColor: 'rgba(0, 113, 227, 0.11)',
    color: 'rgb(0, 92, 190)',
  },
  outlineDisclosure: {
    display: 'grid',
    width: 22,
    height: 26,
    flexShrink: 0,
    alignItems: 'center',
    justifyItems: 'center',
    borderWidth: 0,
    borderRadius: 5,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(67, 72, 82, 0.08)',
      ':active': 'rgba(67, 72, 82, 0.14)',
    },
    color: 'inherit',
    cursor: 'default',
  },
  outlineDisclosureSpacer: {
    width: 22,
    height: 1,
    flexShrink: 0,
  },
  outlineTarget: {
    overflow: 'hidden',
    minWidth: 0,
    minHeight: 27,
    flex: 1,
    borderWidth: 0,
    padding: 0,
    backgroundColor: 'transparent',
    color: 'inherit',
    cursor: 'default',
    fontSize: 11,
    fontWeight: 450,
    letterSpacing: 0,
    lineHeight: '15px',
    outline: 'none',
    textAlign: 'left',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  outlineLabel: {
    overflow: 'hidden',
    minWidth: 0,
    flex: 1,
    fontSize: 11,
    fontWeight: 580,
    lineHeight: '15px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
})
