import * as stylex from '@stylexjs/stylex'
import { readerTheme } from './reader-theme.stylex'

export const readerSidebarStyles = stylex.create({
  annotationPanel: {
    position: 'relative',
    zIndex: 8,
    display: 'flex',
    width: 360,
    maxWidth: 'min(360px, calc(100% - 44px))',
    minHeight: 0,
    flexShrink: 0,
    flexDirection: 'column',
    borderLeftColor: readerTheme.separator,
    borderLeftStyle: 'solid',
    borderLeftWidth: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.96)',
    boxShadow: '-10px 0 28px rgba(25, 31, 41, 0.08), -1px 0 rgba(255, 255, 255, 0.72)',
    opacity: 1,
    overflow: 'hidden',
    transitionDuration: {
      'default': '220ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'width, opacity',
    transitionTimingFunction: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
    willChange: 'width, opacity',
  },
  annotationPanelClosed: {
    width: 0,
    maxWidth: 0,
    borderLeftWidth: 0,
    opacity: 0,
    pointerEvents: 'none',
  },
  panelHeader: {
    display: 'flex',
    minHeight: 48,
    alignItems: 'center',
    borderBottomColor: readerTheme.separator,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    gap: 2,
    padding: 7,
    backgroundColor: 'rgba(255, 255, 255, 0.78)',
  },
  sidebarTab: {
    display: 'flex',
    height: 32,
    minWidth: 0,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 7,
    paddingRight: 8,
    paddingLeft: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(71, 76, 86, 0.07)',
      ':active': 'rgba(71, 76, 86, 0.12)',
    },
    color: readerTheme.textMuted,
    cursor: 'default',
    fontSize: 11,
    fontWeight: 560,
    letterSpacing: 0,
    outline: 'none',
  },
  sidebarTabActive: {
    borderColor: 'rgba(42, 48, 58, 0.10)',
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    color: readerTheme.text,
    boxShadow: '0 1px 3px rgba(24, 30, 40, 0.09), inset 0 1px rgba(255, 255, 255, 0.88)',
  },
  tabCount: {
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    paddingRight: 4,
    paddingLeft: 4,
    backgroundColor: 'rgba(69, 74, 84, 0.10)',
    color: readerTheme.textMuted,
    fontSize: 9,
    fontVariantNumeric: 'tabular-nums',
    lineHeight: '16px',
    textAlign: 'center',
  },
  panelContent: {
    minHeight: 0,
    overflow: 'hidden',
    flex: 1,
  },
  auxiliaryPanel: {
    display: 'flex',
    flexDirection: 'column',
  },
  annotationList: {
    minHeight: 0,
    overflowY: 'auto',
    flex: 1,
    padding: 10,
  },
  emptyAnnotations: {
    paddingTop: 34,
    paddingRight: 18,
    paddingBottom: 34,
    paddingLeft: 18,
    color: readerTheme.textMuted,
    fontSize: 11,
    lineHeight: '17px',
    textAlign: 'center',
  },
  annotationItem: {
    position: 'relative',
    marginBottom: 8,
    borderColor: readerTheme.separator,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
    boxShadow: '0 1px 2px rgba(31, 38, 48, 0.035)',
    contentVisibility: 'auto',
    containIntrinsicSize: '92px',
  },
  annotationItemActive: {
    borderColor: 'rgba(0, 113, 227, 0.42)',
    boxShadow: '0 0 0 2px rgba(0, 113, 227, 0.08)',
  },
  annotationTarget: {
    display: 'flex',
    width: '100%',
    alignItems: 'center',
    gap: 7,
    borderWidth: 0,
    padding: 0,
    backgroundColor: 'transparent',
    color: readerTheme.textMuted,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
  },
  annotationDot: {
    width: 8,
    height: 8,
    flexShrink: 0,
    borderRadius: 999,
    boxShadow: '0 0 0 1px rgba(40, 37, 30, 0.12) inset',
  },
  annotationMeta: {
    overflow: 'hidden',
    flex: 1,
    fontSize: 9,
    fontWeight: 600,
    lineHeight: '13px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  annotationQuote: {
    display: '-webkit-box',
    overflow: 'hidden',
    marginTop: 8,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingLeft: 8,
    borderLeftColor: 'rgba(48, 46, 51, 0.18)',
    borderLeftStyle: 'solid',
    borderLeftWidth: 2,
    color: readerTheme.textMuted,
    fontSize: 10,
    fontStyle: 'normal',
    lineHeight: '15px',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: 3,
  },
  annotationEditor: {
    marginTop: 8,
    minHeight: 120,
    overflow: 'hidden',
    borderTopColor: readerTheme.separator,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 4,
  },
})
