import * as stylex from '@stylexjs/stylex'

const colors = {
  focus: 'rgba(0, 122, 255, 0.72)',
  separator: 'rgba(60, 60, 67, 0.12)',
  text: 'rgba(28, 28, 30, 0.94)',
  textMuted: 'rgba(60, 60, 67, 0.64)',
  textQuiet: 'rgba(60, 60, 67, 0.46)',
} as const

const loadingRotation = stylex.keyframes({
  to: { transform: 'rotate(360deg)' },
})

export const todoListViewStyles = stylex.create({
  root: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    gap: 0,
    overflow: 'hidden',
    padding: '0 18px',
    boxSizing: 'border-box',
  },
  viewport: {
    width: '100%',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflowX: 'auto',
    overflowY: 'auto',
    overscrollBehavior: 'contain',
  },
  list: {
    position: 'relative',
    width: '100%',
    margin: 0,
    padding: 0,
    listStyle: 'none',
  },
  row: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: 58,
    borderBottomColor: colors.separator,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
  },
  rowShell: {
    display: 'flex',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    gap: 4,
  },
  treeToggle: {
    display: 'grid',
    width: 28,
    height: 36,
    flex: '0 0 28px',
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 7,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(118, 118, 128, 0.07)',
      ':active': 'rgba(118, 118, 128, 0.12)',
    },
    color: colors.textQuiet,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `inset 0 0 0 2px ${colors.focus}`,
    },
    transitionDuration: {
      'default': '90ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow',
    transitionTimingFunction: 'ease-out',
  },
  treeTogglePlaceholder: {
    display: 'block',
    width: 28,
    flex: '0 0 28px',
  },
  rowShellSelected: {
    borderRadius: 5,
    backgroundColor: 'rgba(0, 122, 255, 0.09)',
    boxShadow: 'inset 2px 0 rgba(0, 122, 255, 0.58)',
  },
  rowButton: {
    display: 'grid',
    width: 'auto',
    height: '100%',
    flex: 1,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '28px minmax(0, 1fr)',
    gap: 10,
    borderWidth: 0,
    borderRadius: 5,
    paddingRight: 14,
    paddingLeft: 12,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(118, 118, 128, 0.07)',
      ':active': 'rgba(118, 118, 128, 0.12)',
    },
    color: colors.text,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `inset 0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.995)',
    },
    transitionDuration: {
      'default': '90ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  rowButtonSelected: {
    backgroundColor: 'transparent',
    boxShadow: 'none',
  },
  calendarEventButton: {
    color: colors.text,
  },
  calendarEventDot: {
    width: 9,
    height: 9,
    justifySelf: 'center',
    borderRadius: 5,
    backgroundColor: 'var(--todo-calendar-color)',
  },
  statusIcon: {
    width: 19,
    height: 19,
    justifySelf: 'center',
    color: colors.textQuiet,
  },
  statusDoing: {
    color: 'rgb(214, 127, 16)',
  },
  statusDone: {
    color: 'rgb(42, 145, 87)',
  },
  taskContent: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    gap: 3,
  },
  taskText: {
    overflow: 'hidden',
    color: colors.text,
    fontSize: 13,
    fontWeight: 540,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  taskDone: {
    color: colors.textMuted,
    textDecorationLine: 'line-through',
  },
  source: {
    overflow: 'hidden',
    color: colors.textQuiet,
    fontSize: 11,
    fontWeight: 450,
    lineHeight: '15px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  retryButton: {
    height: 28,
    borderColor: 'rgba(0, 100, 210, 0.25)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 5,
    paddingRight: 12,
    paddingLeft: 12,
    backgroundColor: 'rgba(0, 122, 255, 0.1)',
    color: colors.text,
    cursor: 'default',
    fontSize: 12,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  loadingMore: {
    display: 'flex',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    color: colors.textQuiet,
    fontSize: 11,
    fontWeight: 500,
  },
  loadingMoreIcon: {
    width: 14,
    height: 14,
  },
  loadingIcon: {
    'animationDuration': '850ms',
    'animationIterationCount': 'infinite',
    'animationName': loadingRotation,
    'animationTimingFunction': 'linear',
    '@media (prefers-reduced-motion: reduce)': {
      animationName: 'none',
    },
  },
})
