import * as stylex from '@stylexjs/stylex'

const colors = {
  border: 'rgba(72, 72, 74, 0.12)',
  panelSolid: 'rgb(250, 250, 251)',
  text: 'rgba(25, 27, 31, 0.9)',
  textMuted: 'rgba(48, 52, 59, 0.62)',
  textQuiet: 'rgba(48, 52, 59, 0.46)',
} as const

export const todoPlanningViewStyles = stylex.create({
  root: {
    display: 'flex',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    gap: 12,
    overflow: 'auto',
    padding: 14,
    boxSizing: 'border-box',
  },
  toolbar: {
    display: 'flex',
    minHeight: 32,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  toolbarTitle: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'baseline',
    gap: 8,
  },
  title: {
    overflow: 'hidden',
    color: colors.text,
    fontSize: 15,
    fontWeight: 650,
    lineHeight: '20px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  subtitle: {
    overflow: 'hidden',
    color: colors.textQuiet,
    fontSize: 11,
    lineHeight: '16px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  toolbarActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  periodControl: {
    display: 'flex',
    height: 30,
    alignItems: 'center',
    gap: 2,
    borderColor: colors.border,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    paddingRight: 3,
    paddingLeft: 3,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.42)',
      '@media (prefers-reduced-transparency: reduce)': colors.panelSolid,
      '@media (prefers-contrast: more)': 'rgb(248, 249, 251)',
    },
    backdropFilter: {
      'default': 'blur(28px) saturate(130%) brightness(1.02)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 4px 14px rgba(28, 28, 30, 0.075), 0 0 0 0.5px rgba(255, 255, 255, 0.58), inset 0 1px rgba(255, 255, 255, 0.9)',
  },
  iconButton: {
    display: 'grid',
    width: 26,
    height: 26,
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 7,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.62)',
      ':active': 'rgba(118, 118, 128, 0.12)',
      ':disabled': 'transparent',
    },
    color: {
      'default': colors.textMuted,
      ':disabled': colors.textQuiet,
    },
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgba(41, 97, 194, 0.85)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  todayButton: {
    height: 26,
    borderColor: 'rgba(72, 72, 74, 0.1)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 7,
    paddingRight: 9,
    paddingLeft: 9,
    backgroundColor: 'rgba(255, 255, 255, 0.58)',
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': '0 1px 4px rgba(28, 28, 30, 0.1), 0 0 0 0.5px rgba(255, 255, 255, 0.6), inset 0 1px rgba(255, 255, 255, 0.94)',
      ':focus-visible': '0 0 0 2px rgba(41, 97, 194, 0.85)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.97)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  periodLabel: {
    minWidth: 116,
    paddingRight: 6,
    paddingLeft: 6,
    color: colors.text,
    fontSize: 12,
    fontWeight: 650,
    lineHeight: '20px',
    textAlign: 'center',
    whiteSpace: 'nowrap',
  },
  empty: {
    display: 'grid',
    minHeight: 180,
    placeItems: 'center',
    color: colors.textQuiet,
    fontSize: 12,
    textAlign: 'center',
  },
})
