import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'rgb(0, 122, 255)',
  border: 'rgba(60, 60, 67, 0.12)',
  panelSolid: 'rgb(255, 255, 255)',
  text: 'rgba(28, 28, 30, 0.94)',
  textMuted: 'rgba(60, 60, 67, 0.64)',
  textQuiet: 'rgba(60, 60, 67, 0.46)',
} as const

export const todoPlanningViewStyles = stylex.create({
  root: {
    display: 'flex',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    gap: 0,
    overflow: 'auto',
    padding: 0,
    boxSizing: 'border-box',
  },
  toolbar: {
    display: 'flex',
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    borderBottomColor: 'rgba(60, 60, 67, 0.11)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingRight: 16,
    paddingLeft: 16,
  },
  toolbarTitle: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'baseline',
    gap: 8,
  },
  title: {
    overflow: 'hidden',
    color: colors.accent,
    fontSize: 15,
    fontWeight: 650,
    lineHeight: '20px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  subtitle: {
    overflow: 'hidden',
    color: colors.textQuiet,
    fontSize: 11,
    lineHeight: '16px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  toolbarActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  periodControl: {
    display: 'flex',
    height: 30,
    alignItems: 'center',
    gap: 2,
    borderColor: colors.border,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 16,
    paddingRight: 2,
    paddingLeft: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.46)',
    backgroundImage: 'linear-gradient(145deg, rgba(255, 255, 255, 0.98), rgba(255, 255, 255, 0.36) 62%, rgba(174, 215, 255, 0.16))',
    boxShadow: '0 7px 20px rgba(28, 28, 30, 0.13), inset 0 1px rgba(255, 255, 255, 1), inset 0 -1px rgba(0, 96, 204, 0.18)',
  },
  iconButton: {
    display: 'grid',
    width: 26,
    height: 26,
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 13,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.68)',
      ':active': 'rgba(0, 122, 255, 0.14)',
      ':disabled': 'transparent',
    },
    color: {
      'default': colors.textMuted,
      ':disabled': colors.textQuiet,
    },
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgba(0, 122, 255, 0.72)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  todayButton: {
    height: 26,
    borderColor: 'rgba(72, 72, 74, 0.1)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 13,
    paddingRight: 9,
    paddingLeft: 9,
    backgroundColor: 'rgb(0, 122, 255)',
    backgroundImage: 'linear-gradient(180deg, rgb(34, 144, 255), rgb(0, 122, 255))',
    color: 'rgb(255, 255, 255)',
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': '0 4px 10px rgba(0, 92, 196, 0.3), inset 0 1px rgba(255, 255, 255, 0.32)',
      ':focus-visible': '0 0 0 2px rgba(0, 122, 255, 0.72)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.97)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  periodLabel: {
    minWidth: 116,
    paddingRight: 6,
    paddingLeft: 6,
    color: colors.text,
    fontSize: 12,
    fontWeight: 650,
    lineHeight: '20px',
    textAlign: 'center',
    whiteSpace: 'nowrap',
  },
  empty: {
    display: 'grid',
    minHeight: 180,
    placeItems: 'center',
    color: colors.textQuiet,
    fontSize: 12,
    textAlign: 'center',
  },
})
