import * as stylex from '@stylexjs/stylex'

const colors = {
  panelSolid: 'rgb(250, 250, 251)',
  text: 'rgba(25, 27, 31, 0.9)',
  textMuted: 'rgba(48, 52, 59, 0.62)',
  textQuiet: 'rgba(48, 52, 59, 0.46)',
} as const

export const todoCalendarViewStyles = stylex.create({
  toolbar: {
    display: 'flex',
    minHeight: 40,
    alignItems: 'center',
    gap: 16,
  },
  toolbarLeading: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 8,
  },
  monthTitle: {
    minWidth: 0,
    overflow: 'hidden',
    margin: 0,
    color: 'rgba(20, 20, 22, 0.94)',
    fontSize: 22,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: '30px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  navigationControl: {
    display: 'flex',
    height: 30,
    alignItems: 'center',
    gap: 0,
    borderColor: 'rgba(72, 72, 74, 0.12)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    paddingRight: 2,
    paddingLeft: 2,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.5)',
      '@media (prefers-reduced-transparency: reduce)': colors.panelSolid,
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    backdropFilter: {
      'default': 'blur(28px) saturate(135%) brightness(1.02)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 4px 14px rgba(28, 28, 30, 0.075), 0 0 0 0.5px rgba(255, 255, 255, 0.58), inset 0 1px rgba(255, 255, 255, 0.92)',
  },
  todayButton: {
    height: 30,
    borderColor: 'rgba(72, 72, 74, 0.12)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    paddingRight: 11,
    paddingLeft: 11,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.5)',
      ':hover': 'rgba(255, 255, 255, 0.72)',
      ':active': 'rgba(118, 118, 128, 0.12)',
      '@media (prefers-reduced-transparency: reduce)': colors.panelSolid,
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    backdropFilter: {
      'default': 'blur(28px) saturate(135%) brightness(1.02)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': '0 4px 14px rgba(28, 28, 30, 0.075), 0 0 0 0.5px rgba(255, 255, 255, 0.58), inset 0 1px rgba(255, 255, 255, 0.92)',
      ':focus-visible': '0 0 0 2px rgba(41, 97, 194, 0.85)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.97)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  layout: {
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
  },
  surface: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflow: 'visible',
  },
  root: {
    display: 'flex',
    width: '100%',
    height: '100%',
    minHeight: 0,
    flexDirection: 'column',
    color: colors.text,
    fontFamily: 'inherit',
  },
  grid: {
    display: 'grid',
    minHeight: 510,
    flex: 1,
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    gridTemplateRows: 'repeat(6, minmax(96px, 1fr))',
    gap: 1,
    overflow: 'visible',
    backgroundColor: 'rgba(72, 72, 74, 0.105)',
    boxShadow: '0 0 0 0.5px rgba(72, 72, 74, 0.1)',
  },
  weekdays: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    borderBottomColor: 'rgba(72, 72, 74, 0.12)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
  },
  weekday: {
    minWidth: 0,
    paddingTop: 4,
    paddingRight: 9,
    paddingBottom: 7,
    color: colors.textQuiet,
    fontSize: 10,
    fontWeight: 650,
    lineHeight: '15px',
    textAlign: 'right',
  },
  cell: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 82,
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 3,
    paddingTop: 5,
    paddingRight: 5,
    paddingBottom: 5,
    paddingLeft: 5,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.72)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(255, 255, 255)',
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    zIndex: {
      'default': 0,
      ':focus-within': 3,
    },
  },
  spanSegment: {
    position: 'relative',
    zIndex: 2,
    width: 'auto',
    height: 20,
    minWidth: 0,
    alignSelf: 'start',
    marginRight: 5,
    marginLeft: 5,
  },
  cellNeighbor: {
    backgroundColor: 'rgba(247, 247, 248, 0.72)',
  },
  dayButton: {
    display: 'grid',
    width: 24,
    height: 24,
    flex: '0 0 auto',
    alignSelf: 'flex-end',
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 12,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(118, 118, 128, 0.1)',
      ':active': 'rgba(118, 118, 128, 0.16)',
    },
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 650,
    lineHeight: '24px',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgba(41, 97, 194, 0.85)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  dayButtonNeighbor: {
    color: 'rgba(48, 52, 59, 0.34)',
  },
  dayButtonSelected: {
    backgroundColor: 'rgba(118, 118, 128, 0.14)',
    color: colors.text,
  },
  dayButtonToday: {
    backgroundColor: 'rgb(255, 59, 48)',
    color: 'rgb(255, 255, 255)',
    boxShadow: '0 1px 4px rgba(184, 28, 21, 0.2)',
  },
  taskList: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    gap: 2,
    overflow: 'visible',
  },
  taskShell: {
    position: 'relative',
    minWidth: 0,
    height: 20,
  },
  taskButton: {
    display: 'flex',
    width: '100%',
    height: 20,
    minWidth: 0,
    alignItems: 'center',
    gap: 5,
    overflow: 'hidden',
    borderWidth: 0,
    borderRadius: 4,
    paddingTop: 0,
    paddingRight: 20,
    paddingBottom: 0,
    paddingLeft: 5,
    backgroundColor: {
      'default': 'rgba(0, 122, 255, 0.09)',
      ':hover': 'rgba(0, 122, 255, 0.14)',
      ':active': 'rgba(0, 122, 255, 0.18)',
    },
    color: 'rgba(18, 64, 111, 0.88)',
    cursor: 'default',
    fontSize: 10,
    fontWeight: 550,
    lineHeight: '20px',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgba(41, 97, 194, 0.85)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow',
    transitionTimingFunction: 'ease-out',
  },
  taskStatus: {
    width: 6,
    height: 6,
    flex: '0 0 auto',
    borderRadius: 3,
    backgroundColor: 'rgb(0, 122, 255)',
  },
  taskStatusDoing: {
    backgroundColor: 'rgb(255, 159, 10)',
  },
  taskStatusDone: {
    backgroundColor: 'rgb(52, 199, 89)',
  },
  taskText: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  taskTextDone: {
    opacity: 0.58,
    textDecoration: 'line-through',
  },
  predictionShell: {
    position: 'relative',
    minWidth: 0,
    height: 20,
  },
  predictionPreview: {
    display: 'flex',
    width: '100%',
    height: 20,
    minWidth: 0,
    alignItems: 'center',
    gap: 5,
    overflow: 'hidden',
    borderRadius: 4,
    paddingInline: 5,
    backgroundColor: 'rgba(118, 118, 128, 0.07)',
    color: 'rgba(48, 52, 59, 0.5)',
    fontSize: 10,
    fontWeight: 500,
    lineHeight: '20px',
    opacity: 0.82,
  },
  predictionStatus: {
    width: 6,
    height: 6,
    flex: '0 0 auto',
    borderRadius: 3,
    backgroundColor: 'rgba(118, 118, 128, 0.62)',
  },
  predictionText: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  taskActions: {
    position: 'absolute',
    top: 0,
    right: 1,
    zIndex: 2,
    display: 'grid',
    width: 18,
    height: 20,
    placeItems: 'center',
    opacity: {
      'default': 0.42,
      ':hover': 1,
      ':focus-within': 1,
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'opacity',
    transitionTimingFunction: 'ease-out',
  },
  overflow: {
    position: 'relative',
    minWidth: 0,
  },
  taskMore: {
    width: 'fit-content',
    overflow: 'hidden',
    paddingRight: 3,
    paddingLeft: 3,
    color: colors.textQuiet,
    cursor: 'default',
    fontSize: 9,
    lineHeight: '15px',
    listStyle: 'none',
    outline: 'none',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  overflowPopover: {
    position: 'absolute',
    top: 19,
    left: '50%',
    zIndex: 8,
    display: 'flex',
    width: 260,
    maxHeight: 300,
    boxSizing: 'border-box',
    flexDirection: 'column',
    gap: 7,
    overflow: 'auto',
    borderColor: 'rgba(255, 255, 255, 0.82)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    padding: 9,
    backgroundColor: {
      'default': 'rgba(246, 247, 249, 0.9)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 250, 251)',
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    backdropFilter: {
      'default': 'blur(24px) saturate(145%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 14px 32px rgba(28, 28, 30, 0.18), 0 0 0 0.5px rgba(72, 72, 74, 0.08), inset 0 1px rgba(255, 255, 255, 0.92)',
    transform: 'translateX(-50%)',
  },
  overflowTitle: {
    color: colors.text,
    fontSize: 11,
    fontWeight: 650,
    lineHeight: '16px',
  },
  overflowList: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    gap: 3,
  },
})
