import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'var(--ui-accent, rgb(0, 122, 255))',
  divider: 'var(--ui-divider, rgba(72, 72, 74, 0.12))',
  focus: 'var(--ui-focus, rgba(0, 122, 255, 0.72))',
  onAccent: 'var(--ui-on-accent, rgb(255, 255, 255))',
  surface: 'var(--ui-surface, rgb(255, 255, 255))',
  text: 'var(--ui-text, rgba(28, 28, 30, 0.94))',
  textMuted: 'var(--ui-text-muted, rgba(60, 60, 67, 0.64))',
  textQuiet: 'var(--ui-text-quiet, rgba(60, 60, 67, 0.46))',
} as const

export const todoTimelineViewStyles = stylex.create({
  viewport: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    overflow: 'auto',
    padding: '18px 22px 24px',
    overscrollBehavior: 'contain',
  },
  group: {
    position: 'relative',
    display: 'grid',
    minWidth: 620,
    gridTemplateColumns: '104px minmax(0, 1fr)',
    gap: 18,
    paddingBottom: 12,
  },
  date: {
    display: 'flex',
    minHeight: 70,
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: 1,
    paddingTop: 4,
    paddingRight: 2,
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: 600,
    textAlign: 'right',
  },
  dateNumber: {
    color: colors.text,
    fontSize: 22,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 650,
    lineHeight: '25px',
  },
  dateWeekday: {
    color: colors.textMuted,
    fontSize: 11,
    lineHeight: '16px',
  },
  dateToday: {
    color: colors.accent,
  },
  entries: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    gap: 10,
    paddingLeft: 68,
  },
  dateRail: {
    position: 'absolute',
    top: 0,
    bottom: 4,
    left: 43,
    width: 1,
    backgroundColor: colors.divider,
  },
  entry: {
    position: 'relative',
    display: 'grid',
    minWidth: 0,
    gridTemplateColumns: '60px minmax(0, 1fr)',
    gap: 8,
    alignItems: 'start',
  },
  time: {
    overflow: 'hidden',
    paddingTop: 7,
    color: colors.textQuiet,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    lineHeight: '16px',
    textAlign: 'right',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  entryRail: {
    position: 'absolute',
    top: 7,
    left: -29,
    zIndex: 1,
    width: 9,
    height: 9,
    borderColor: colors.surface,
    borderStyle: 'solid',
    borderWidth: 2,
    borderRadius: 7,
    backgroundColor: colors.surface,
    boxSizing: 'border-box',
    boxShadow: `0 0 0 1px ${colors.divider}`,
  },
  entryDot: {
    display: 'block',
    width: '100%',
    height: '100%',
    borderRadius: 'inherit',
    backgroundColor: colors.accent,
    transform: 'scale(0.48)',
  },
  entryContent: {
    minWidth: 0,
  },
  unscheduled: {
    display: 'grid',
    minWidth: 620,
    gridTemplateColumns: '104px minmax(0, 1fr)',
    gap: 18,
    borderTopColor: colors.divider,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 16,
  },
  unscheduledLabel: {
    paddingRight: 2,
    color: colors.textQuiet,
    fontSize: 11,
    fontWeight: 600,
    textAlign: 'right',
  },
  loadingMore: {
    display: 'flex',
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    color: colors.textQuiet,
    fontSize: 11,
  },
  loadMoreButton: {
    alignSelf: 'center',
    height: 28,
    borderColor: colors.accent,
    borderStyle: 'solid',
    borderWidth: 'var(--ui-control-stroke, 1px)',
    borderRadius: 'var(--ui-control-radius, 7px)',
    paddingRight: 12,
    paddingLeft: 12,
    backgroundColor: colors.accent,
    backgroundImage: 'var(--todo-accent-background-image, linear-gradient(180deg, rgb(34, 144, 255), rgb(0, 122, 255)))',
    color: colors.onAccent,
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
    boxShadow: 'var(--ui-control-shadow, 0 4px 12px rgba(0, 92, 196, 0.24))',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.97)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
})
