import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'rgb(56, 108, 244)',
  text: 'rgba(25, 27, 31, 0.9)',
  textMuted: 'rgba(48, 52, 59, 0.62)',
  textQuiet: 'rgba(48, 52, 59, 0.46)',
} as const

export const todoTimelineViewStyles = stylex.create({
  viewport: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    overflow: 'auto',
    padding: '4px 4px 18px',
    overscrollBehavior: 'contain',
  },
  group: {
    position: 'relative',
    display: 'grid',
    minWidth: 620,
    gridTemplateColumns: '104px minmax(0, 1fr)',
    gap: 18,
    paddingBottom: 12,
  },
  date: {
    display: 'flex',
    minHeight: 70,
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: 1,
    paddingTop: 4,
    paddingRight: 2,
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: 600,
    textAlign: 'right',
  },
  dateNumber: {
    color: colors.text,
    fontSize: 22,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 650,
    lineHeight: '25px',
  },
  dateWeekday: {
    color: colors.textMuted,
    fontSize: 11,
    lineHeight: '16px',
  },
  dateToday: {
    color: colors.accent,
  },
  entries: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    gap: 10,
    paddingLeft: 68,
  },
  dateRail: {
    position: 'absolute',
    top: 0,
    bottom: 4,
    left: 43,
    width: 1,
    backgroundColor: 'rgba(72, 72, 74, 0.12)',
  },
  entry: {
    position: 'relative',
    display: 'grid',
    minWidth: 0,
    gridTemplateColumns: '60px minmax(0, 1fr)',
    gap: 8,
    alignItems: 'start',
  },
  time: {
    overflow: 'hidden',
    paddingTop: 7,
    color: colors.textQuiet,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    lineHeight: '16px',
    textAlign: 'right',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  entryRail: {
    position: 'absolute',
    top: 7,
    left: -29,
    zIndex: 1,
    width: 9,
    height: 9,
    borderColor: 'rgba(255, 255, 255, 0.96)',
    borderStyle: 'solid',
    borderWidth: 2,
    borderRadius: 7,
    backgroundColor: 'rgb(255, 255, 255)',
    boxSizing: 'border-box',
    boxShadow: '0 0 0 1px rgba(72, 72, 74, 0.32)',
  },
  entryDot: {
    display: 'block',
    width: '100%',
    height: '100%',
    borderRadius: 'inherit',
    backgroundColor: colors.accent,
    transform: 'scale(0.48)',
  },
  entryContent: {
    minWidth: 0,
  },
  unscheduled: {
    display: 'grid',
    minWidth: 620,
    gridTemplateColumns: '104px minmax(0, 1fr)',
    gap: 18,
    borderTopColor: 'rgba(72, 72, 74, 0.1)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 16,
  },
  unscheduledLabel: {
    paddingRight: 2,
    color: colors.textQuiet,
    fontSize: 11,
    fontWeight: 600,
    textAlign: 'right',
  },
  loadingMore: {
    display: 'flex',
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    color: colors.textQuiet,
    fontSize: 11,
  },
  loadMoreButton: {
    alignSelf: 'center',
    height: 28,
    borderColor: 'rgba(0, 100, 210, 0.25)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 7,
    paddingRight: 12,
    paddingLeft: 12,
    backgroundColor: 'rgba(0, 113, 227, 0.12)',
    color: 'rgb(0, 113, 227)',
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
  },
})
