import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'var(--ui-accent, rgb(0, 122, 255))',
  border: 'var(--ui-divider, rgba(60, 60, 67, 0.12))',
  controlHover: 'var(--ui-control-hover, rgba(255, 255, 255, 0.68))',
  controlPressed: 'var(--ui-control-pressed, rgba(0, 122, 255, 0.14))',
  focus: 'var(--ui-focus, rgba(0, 122, 255, 0.72))',
  onAccent: 'var(--ui-on-accent, rgb(255, 255, 255))',
  panel: 'var(--ui-surface-translucent, rgba(255, 255, 255, 0.46))',
  panelSolid: 'var(--ui-surface, rgb(255, 255, 255))',
  text: 'var(--ui-text, rgba(28, 28, 30, 0.94))',
  textMuted: 'var(--ui-text-muted, rgba(60, 60, 67, 0.64))',
  textQuiet: 'var(--ui-text-quiet, rgba(60, 60, 67, 0.46))',
} as const

export const todoPlanningViewStyles = stylex.create({
  root: {
    display: 'flex',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    gap: 0,
    overflow: 'auto',
    padding: 0,
    boxSizing: 'border-box',
  },
  toolbar: {
    display: 'flex',
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    borderBottomColor: colors.border,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingRight: 16,
    paddingLeft: 16,
  },
  toolbarTitle: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'baseline',
    gap: 8,
  },
  title: {
    overflow: 'hidden',
    color: colors.accent,
    fontSize: 15,
    fontWeight: 650,
    lineHeight: '20px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  subtitle: {
    overflow: 'hidden',
    color: colors.textQuiet,
    fontSize: 11,
    lineHeight: '16px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  toolbarActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  periodControl: {
    display: 'flex',
    height: 30,
    alignItems: 'center',
    gap: 2,
    borderColor: colors.border,
    borderStyle: 'solid',
    borderWidth: 'var(--ui-control-stroke, 1px)',
    borderRadius: 'var(--ui-control-radius, 16px)',
    paddingRight: 2,
    paddingLeft: 2,
    backgroundColor: colors.panel,
    backgroundImage: 'var(--todo-control-background-image, linear-gradient(145deg, rgba(255, 255, 255, 0.98), rgba(255, 255, 255, 0.36) 62%, rgba(174, 215, 255, 0.16)))',
    boxShadow: 'var(--ui-control-shadow, 0 7px 20px rgba(28, 28, 30, 0.13))',
  },
  iconButton: {
    display: 'grid',
    width: 26,
    height: 26,
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 'var(--ui-control-radius, 13px)',
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': colors.controlHover,
      ':active': colors.controlPressed,
      ':disabled': 'transparent',
    },
    color: {
      'default': colors.textMuted,
      ':disabled': colors.textQuiet,
    },
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  todayButton: {
    height: 26,
    borderColor: colors.border,
    borderStyle: 'solid',
    borderWidth: 'var(--ui-control-stroke, 1px)',
    borderRadius: 'var(--ui-control-radius, 13px)',
    paddingRight: 9,
    paddingLeft: 9,
    backgroundColor: colors.accent,
    backgroundImage: 'var(--todo-accent-background-image, linear-gradient(180deg, rgb(34, 144, 255), rgb(0, 122, 255)))',
    color: colors.onAccent,
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': 'var(--ui-control-shadow, 0 4px 10px rgba(0, 92, 196, 0.3))',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.97)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  periodLabel: {
    minWidth: 116,
    paddingRight: 6,
    paddingLeft: 6,
    color: colors.text,
    fontSize: 12,
    fontWeight: 650,
    lineHeight: '20px',
    textAlign: 'center',
    whiteSpace: 'nowrap',
  },
  empty: {
    display: 'grid',
    minHeight: 180,
    placeItems: 'center',
    color: colors.textQuiet,
    fontSize: 12,
    textAlign: 'center',
  },
})
