import * as stylex from '@stylexjs/stylex'

const colors = {
  focus: 'rgba(41, 97, 194, 0.85)',
  text: 'rgba(25, 27, 31, 0.9)',
  textMuted: 'rgba(48, 52, 59, 0.62)',
  textQuiet: 'rgba(48, 52, 59, 0.46)',
} as const

export const todoBoardViewStyles = stylex.create({
  viewport: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    gap: 12,
    overflowX: 'auto',
    overflowY: 'auto',
    padding: 14,
    overscrollBehavior: 'contain',
  },
  grid: {
    display: 'grid',
    minWidth: 780,
    minHeight: '100%',
    gridTemplateColumns: 'repeat(3, minmax(240px, 1fr))',
    alignItems: 'start',
    gap: 14,
  },
  column: {
    display: 'flex',
    minHeight: 'clamp(300px, 78vh, 760px)',
    flexDirection: 'column',
    overflow: 'hidden',
    borderColor: {
      'default': 'rgba(72, 72, 74, 0.09)',
      '@media (prefers-reduced-transparency: reduce)': 'rgba(72, 72, 74, 0.16)',
      '@media (prefers-contrast: more)': 'rgba(35, 35, 37, 0.42)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 12,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.2)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 250, 251)',
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    boxShadow: {
      'default': '0 1px 2px rgba(28, 28, 30, 0.025), inset 0 1px rgba(255, 255, 255, 0.66)',
      '@media (prefers-contrast: more)': '0 0 0 1px rgba(35, 35, 37, 0.28), inset 0 1px rgba(255, 255, 255, 0.92)',
    },
  },
  columnHeader: {
    display: 'flex',
    height: 42,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: 12,
    paddingLeft: 12,
    borderBottomColor: 'rgba(72, 72, 74, 0.085)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
  },
  columnTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    color: colors.text,
    fontSize: 12,
    fontWeight: 650,
  },
  columnCount: {
    minWidth: 22,
    height: 20,
    borderRadius: 10,
    paddingRight: 6,
    paddingLeft: 6,
    backgroundColor: 'rgba(118, 118, 128, 0.09)',
    borderColor: 'rgba(72, 72, 74, 0.07)',
    borderStyle: 'solid',
    borderWidth: 1,
    color: colors.textMuted,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 600,
    lineHeight: '20px',
    textAlign: 'center',
  },
  columnBody: {
    display: 'flex',
    minHeight: 168,
    flexDirection: 'column',
    gap: 8,
    padding: 10,
  },
  columnEmpty: {
    margin: 'auto',
    padding: 24,
    color: colors.textQuiet,
    fontSize: 12,
    textAlign: 'center',
  },
  columnLoading: {
    padding: 8,
    color: colors.textQuiet,
    fontSize: 11,
    textAlign: 'center',
  },
  card: {
    display: 'flex',
    width: '100%',
    minHeight: 86,
    minWidth: 0,
    boxSizing: 'border-box',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 6,
    borderColor: {
      'default': 'rgba(72, 72, 74, 0.12)',
      '@media (prefers-reduced-transparency: reduce)': 'rgba(72, 72, 74, 0.14)',
      '@media (prefers-contrast: more)': 'rgba(35, 35, 37, 0.34)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingTop: 10,
    paddingRight: 40,
    paddingBottom: 10,
    paddingLeft: 36,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.78)',
      ':hover': 'rgba(255, 255, 255, 0.94)',
      ':active': 'rgba(118, 118, 128, 0.1)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(255, 255, 255)',
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    color: colors.text,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': '0 2px 7px rgba(28, 28, 30, 0.07), 0 0 0 0.5px rgba(255, 255, 255, 0.7), inset 0 1px rgba(255, 255, 255, 0.92)',
      ':hover': '0 6px 16px rgba(28, 28, 30, 0.1), 0 0 0 0.5px rgba(255, 255, 255, 0.8), inset 0 1px rgba(255, 255, 255, 0.98)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'translateY(0) scale(1)',
      ':hover': 'translateY(-1px) scale(1.002)',
      ':active': 'translateY(1px) scale(0.985)',
    },
    transitionDuration: {
      'default': '110ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  cardShell: {
    position: 'relative',
    width: '100%',
    minWidth: 0,
  },
  cardActions: {
    position: 'absolute',
    top: 6,
    right: 6,
  },
  cardOccurrence: {
    position: 'absolute',
    zIndex: 1,
    top: 9,
    left: 8,
  },
  cardText: {
    overflow: 'hidden',
    fontSize: 13,
    fontWeight: 560,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  cardSource: {
    overflow: 'hidden',
    color: colors.textQuiet,
    fontSize: 11,
    lineHeight: '15px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  cardFooter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    color: colors.textMuted,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    lineHeight: '15px',
  },
  taskDone: {
    color: colors.textMuted,
    textDecorationLine: 'line-through',
  },
  statusIcon: {
    width: 19,
    height: 19,
    justifySelf: 'center',
    color: colors.textQuiet,
  },
  statusDoing: {
    color: 'rgb(214, 127, 16)',
  },
  statusDone: {
    color: 'rgb(42, 145, 87)',
  },
})
