import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'rgb(0, 113, 227)',
  text: 'rgba(25, 27, 31, 0.9)',
  textMuted: 'rgba(48, 52, 59, 0.62)',
  textQuiet: 'rgba(48, 52, 59, 0.46)',
} as const

export const todoTimelineViewStyles = stylex.create({
  viewport: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    gap: 14,
    overflow: 'auto',
    padding: 4,
  },
  group: {
    position: 'relative',
    display: 'grid',
    minWidth: 620,
    gridTemplateColumns: '132px minmax(0, 1fr)',
    gap: 18,
    paddingBottom: 4,
  },
  date: {
    position: 'relative',
    display: 'flex',
    minHeight: 64,
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: 2,
    paddingTop: 4,
    paddingRight: 18,
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: 600,
    textAlign: 'right',
  },
  dateNumber: {
    color: colors.text,
    fontSize: 18,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 650,
    lineHeight: '22px',
  },
  dateToday: {
    color: colors.accent,
  },
  rail: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: 1,
    backgroundColor: 'rgba(72, 72, 74, 0.11)',
  },
  dot: {
    position: 'absolute',
    top: 8,
    right: -4,
    zIndex: 1,
    width: 9,
    height: 9,
    borderColor: 'rgba(255, 255, 255, 0.92)',
    borderStyle: 'solid',
    borderWidth: 2,
    borderRadius: 6,
    backgroundColor: colors.accent,
    boxShadow: '0 2px 5px rgba(0, 90, 180, 0.26)',
  },
  items: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    gap: 7,
  },
  unscheduled: {
    display: 'grid',
    minWidth: 620,
    gridTemplateColumns: '132px minmax(0, 1fr)',
    gap: 18,
    borderTopColor: 'rgba(72, 72, 74, 0.1)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 14,
  },
  unscheduledLabel: {
    paddingRight: 18,
    color: colors.textQuiet,
    fontSize: 11,
    fontWeight: 600,
    textAlign: 'right',
  },
})
