import * as stylex from '@stylexjs/stylex'

const colors = {
  focus: 'rgba(0, 122, 255, 0.72)',
  text: 'rgba(28, 28, 30, 0.94)',
  textMuted: 'rgba(60, 60, 67, 0.64)',
  textQuiet: 'rgba(60, 60, 67, 0.46)',
} as const

export const todoBoardViewStyles = stylex.create({
  viewport: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    gap: 0,
    overflowX: 'auto',
    overflowY: 'auto',
    padding: 0,
    overscrollBehavior: 'contain',
  },
  grid: {
    display: 'grid',
    minWidth: 780,
    minHeight: '100%',
    gridTemplateColumns: 'repeat(3, minmax(240px, 1fr))',
    alignItems: 'stretch',
    gap: 0,
  },
  column: {
    display: 'flex',
    minHeight: '100%',
    flexDirection: 'column',
    overflow: 'hidden',
    borderRightColor: 'rgba(60, 60, 67, 0.11)',
    borderRightStyle: 'solid',
    borderRightWidth: 1,
    borderTopColor: 'transparent',
    borderTopStyle: 'solid',
    borderTopWidth: 3,
    backgroundColor: 'rgb(255, 255, 255)',
    boxShadow: 'none',
  },
  columnTodo: {
    borderTopColor: 'rgb(0, 122, 255)',
    backgroundImage: 'linear-gradient(180deg, rgba(0, 122, 255, 0.075), rgba(0, 122, 255, 0.018) 180px, transparent 420px)',
  },
  columnDoing: {
    borderTopColor: 'rgb(255, 149, 0)',
    backgroundImage: 'linear-gradient(180deg, rgba(255, 149, 0, 0.085), rgba(255, 149, 0, 0.018) 180px, transparent 420px)',
  },
  columnDone: {
    borderTopColor: 'rgb(52, 199, 89)',
    backgroundImage: 'linear-gradient(180deg, rgba(52, 199, 89, 0.08), rgba(52, 199, 89, 0.016) 180px, transparent 420px)',
  },
  columnHeader: {
    display: 'flex',
    height: 48,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: 16,
    paddingLeft: 16,
    borderBottomColor: 'rgba(60, 60, 67, 0.1)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
  },
  columnTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    color: colors.text,
    fontSize: 12,
    fontWeight: 650,
  },
  columnCount: {
    minWidth: 22,
    height: 20,
    borderRadius: 4,
    paddingRight: 6,
    paddingLeft: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.62)',
    borderWidth: 0,
    color: colors.textMuted,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 600,
    lineHeight: '20px',
    textAlign: 'center',
  },
  columnBody: {
    display: 'flex',
    minHeight: 168,
    flexDirection: 'column',
    gap: 7,
    padding: 10,
  },
  columnEmpty: {
    margin: 'auto',
    padding: 24,
    color: colors.textQuiet,
    fontSize: 12,
    textAlign: 'center',
  },
  columnLoading: {
    padding: 8,
    color: colors.textQuiet,
    fontSize: 11,
    textAlign: 'center',
  },
  card: {
    display: 'flex',
    width: '100%',
    minHeight: 86,
    minWidth: 0,
    boxSizing: 'border-box',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 6,
    borderColor: {
      'default': 'rgba(72, 72, 74, 0.12)',
      '@media (prefers-reduced-transparency: reduce)': 'rgba(72, 72, 74, 0.14)',
      '@media (prefers-contrast: more)': 'rgba(35, 35, 37, 0.34)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    paddingTop: 10,
    paddingRight: 40,
    paddingBottom: 10,
    paddingLeft: 36,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.82)',
      ':hover': 'rgb(255, 255, 255)',
      ':active': 'rgba(235, 232, 244, 0.88)',
    },
    backgroundImage: 'linear-gradient(145deg, rgba(255, 255, 255, 0.72), rgba(245, 248, 252, 0.28))',
    color: colors.text,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': '0 4px 14px rgba(49, 42, 72, 0.08), inset 0 1px rgba(255, 255, 255, 0.96)',
      ':hover': '0 7px 20px rgba(49, 42, 72, 0.12), inset 0 1px rgba(255, 255, 255, 1)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'translateY(0) scale(1)',
      ':hover': 'translateY(-1px) scale(1)',
      ':active': 'translateY(0) scale(0.985)',
    },
    transitionDuration: {
      'default': '110ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  cardSelected: {
    borderColor: 'rgba(0, 122, 255, 0.34)',
    backgroundColor: 'rgba(240, 247, 255, 0.94)',
    boxShadow: '0 0 0 1px rgba(0, 122, 255, 0.12), 0 7px 20px rgba(0, 92, 196, 0.14)',
  },
  cardShell: {
    position: 'relative',
    width: '100%',
    minWidth: 0,
  },
  cardActions: {
    position: 'absolute',
    top: 6,
    right: 6,
  },
  cardOccurrence: {
    position: 'absolute',
    zIndex: 1,
    top: 9,
    left: 8,
  },
  cardText: {
    overflow: 'hidden',
    fontSize: 13,
    fontWeight: 560,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  cardSource: {
    overflow: 'hidden',
    color: colors.textQuiet,
    fontSize: 11,
    lineHeight: '15px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  cardFooter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    color: colors.textMuted,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    lineHeight: '15px',
  },
  taskDone: {
    color: colors.textMuted,
    textDecorationLine: 'line-through',
  },
  statusIcon: {
    width: 19,
    height: 19,
    justifySelf: 'center',
    color: colors.textQuiet,
  },
  statusDoing: {
    color: 'rgb(214, 127, 16)',
  },
  statusDone: {
    color: 'rgb(42, 145, 87)',
  },
})
