import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'var(--ui-accent, rgb(0, 122, 255))',
  controlHover: 'var(--ui-control-hover, rgba(255, 255, 255, 0.96))',
  controlPressed: 'var(--ui-control-pressed, rgba(235, 232, 244, 0.88))',
  controlSelected: 'var(--ui-control-selected, rgba(240, 247, 255, 0.94))',
  focus: 'var(--ui-focus, rgba(0, 122, 255, 0.72))',
  surfaceRaised: 'var(--ui-surface-raised, rgba(255, 255, 255, 0.82))',
  text: 'var(--ui-text, rgba(28, 28, 30, 0.94))',
  textMuted: 'var(--ui-text-muted, rgba(60, 60, 67, 0.64))',
  textQuiet: 'var(--ui-text-quiet, rgba(60, 60, 67, 0.46))',
  warning: 'var(--ui-warning, rgb(214, 127, 16))',
  success: 'var(--ui-status-success, rgb(42, 145, 87))',
} as const

export const todoPlanningTaskStyles = stylex.create({
  task: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    minHeight: 62,
    alignItems: 'center',
    gap: 10,
    borderColor: {
      'default': 'var(--ui-border, rgba(72, 72, 74, 0.12))',
      '@media (prefers-reduced-transparency: reduce)': 'var(--ui-border-strong, rgba(72, 72, 74, 0.16))',
      '@media (prefers-contrast: more)': 'var(--ui-border-strong, rgba(35, 35, 37, 0.4))',
    },
    borderStyle: 'solid',
    borderWidth: 'var(--ui-surface-stroke, 1px)',
    borderRadius: 'var(--ui-surface-radius, 10px)',
    boxSizing: 'border-box',
    paddingTop: 9,
    paddingRight: 44,
    paddingBottom: 9,
    paddingLeft: 9,
    backgroundColor: {
      'default': colors.surfaceRaised,
      ':hover': colors.controlHover,
      ':active': colors.controlPressed,
    },
    backgroundImage: 'var(--todo-card-background-image, linear-gradient(145deg, rgba(255, 255, 255, 0.72), rgba(245, 248, 252, 0.28)))',
    color: colors.text,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': 'var(--ui-shadow-subtle, 0 4px 14px rgba(49, 42, 72, 0.08))',
      ':hover': 'var(--ui-shadow-raised, 0 7px 20px rgba(49, 42, 72, 0.12))',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'translateY(0) scale(1)',
      ':hover': 'translateY(-1px) scale(1)',
      ':active': 'translateY(0) scale(0.99)',
    },
    transitionDuration: {
      'default': '110ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
    contentVisibility: 'auto',
    containIntrinsicSize: '62px',
  },
  taskSelected: {
    borderColor: colors.accent,
    backgroundColor: colors.controlSelected,
    boxShadow: 'var(--ui-shadow-raised, 0 7px 20px rgba(0, 92, 196, 0.14))',
  },
  shell: {
    position: 'relative',
    width: '100%',
    minWidth: 0,
  },
  actions: {
    position: 'absolute',
    top: '50%',
    right: 6,
    transform: 'translateY(-50%)',
  },
  icon: {
    width: 18,
    height: 18,
    flex: '0 0 18px',
    color: colors.textQuiet,
  },
  doing: {
    color: colors.warning,
  },
  doneIcon: {
    color: colors.success,
  },
  content: {
    display: 'flex',
    minWidth: 0,
    flex: 1,
    flexDirection: 'column',
    gap: 3,
  },
  title: {
    overflow: 'hidden',
    color: colors.text,
    fontSize: 12,
    fontWeight: 600,
    lineHeight: '17px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  meta: {
    overflow: 'hidden',
    color: colors.textQuiet,
    fontSize: 10,
    lineHeight: '14px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  done: {
    color: colors.textMuted,
    textDecorationLine: 'line-through',
  },
})
