import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'var(--ui-accent, rgb(0, 122, 255))',
  border: 'var(--ui-divider, rgba(60, 60, 67, 0.13))',
  danger: 'var(--ui-danger, rgb(255, 59, 48))',
  panelSolid: 'var(--ui-surface, rgb(255, 255, 255))',
  text: 'var(--ui-text, rgba(28, 28, 30, 0.94))',
  textQuiet: 'var(--ui-text-quiet, rgba(60, 60, 67, 0.46))',
  warning: 'var(--ui-warning, rgb(255, 149, 0))',
} as const

export const todoQuadrantViewStyles = stylex.create({
  grid: {
    display: 'grid',
    minWidth: 820,
    minHeight: 0,
    flex: 1,
    gridTemplateColumns: 'repeat(2, minmax(320px, 1fr))',
    gridTemplateRows: 'repeat(2, minmax(220px, 1fr))',
    gap: 'var(--todo-quadrant-grid-gap, 1px)',
    overflow: 'hidden',
    backgroundColor: colors.border,
    boxShadow: 'none',
  },
  panel: {
    display: 'flex',
    minHeight: 0,
    flexDirection: 'column',
    overflow: 'hidden',
    backgroundColor: colors.panelSolid,
  },
  header: {
    display: 'flex',
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingTop: 8,
    paddingRight: 14,
    paddingBottom: 6,
    paddingLeft: 14,
  },
  title: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    color: colors.text,
    fontSize: 13,
    fontWeight: 650,
    lineHeight: '18px',
  },
  signal: {
    width: 6,
    height: 6,
    flex: '0 0 6px',
    borderRadius: 3,
    backgroundColor: colors.danger,
    boxShadow: 'none',
  },
  signalImportant: {
    backgroundColor: colors.warning,
    boxShadow: 'none',
  },
  signalUrgent: {
    backgroundColor: colors.accent,
    boxShadow: 'none',
  },
  signalQuiet: {
    backgroundColor: colors.textQuiet,
    boxShadow: 'none',
  },
  count: {
    minWidth: 16,
    color: colors.textQuiet,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 600,
    lineHeight: '16px',
    textAlign: 'right',
  },
  body: {
    display: 'flex',
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    gap: 8,
    overflow: 'auto',
    paddingTop: 4,
    paddingRight: 12,
    paddingBottom: 12,
    paddingLeft: 12,
  },
  empty: {
    display: 'grid',
    minHeight: 90,
    flex: 1,
    placeItems: 'center',
    color: colors.textQuiet,
    fontSize: 11,
  },
  rule: {
    color: colors.textQuiet,
    fontSize: 10,
    lineHeight: '14px',
  },
})
