import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'rgb(0, 122, 255)',
  focus: 'rgba(0, 122, 255, 0.72)',
  text: 'rgba(28, 28, 30, 0.94)',
  textMuted: 'rgba(60, 60, 67, 0.64)',
  panel: 'rgba(255, 255, 255, 0.5)',
  panelSolid: 'rgb(255, 255, 255)',
  border: 'rgba(60, 60, 67, 0.12)',
} as const

export const todoTimeGridViewStyles = stylex.create({
  root: {
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    flexDirection: 'column',
    color: colors.text,
  },
  toolbar: {
    'display': 'flex',
    'width': '100%',
    'minWidth': 0,
    'minHeight': 52,
    'flex': '0 0 auto',
    'alignItems': 'center',
    'justifyContent': 'space-between',
    'gap': 16,
    'borderBottomColor': colors.border,
    'borderBottomStyle': 'solid',
    'borderBottomWidth': 1,
    'paddingRight': 16,
    'paddingBottom': 0,
    'paddingLeft': 16,
    '@media (max-width: 900px)': {
      minHeight: 94,
      alignContent: 'center',
      flexWrap: 'wrap',
      gap: 6,
      paddingTop: 7,
      paddingBottom: 7,
    },
  },
  dateControls: {
    'display': 'flex',
    'minWidth': 0,
    'alignItems': 'center',
    'gap': 8,
    '@media (max-width: 900px)': {
      width: '100%',
    },
  },
  dateTitle: {
    overflow: 'hidden',
    margin: 0,
    color: colors.accent,
    fontSize: 17,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: '26px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  today: {
    height: 30,
    borderColor: colors.border,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 15,
    paddingRight: 11,
    paddingLeft: 11,
    backgroundColor: {
      'default': colors.panel,
      ':hover': 'rgb(255, 255, 255)',
      ':active': 'rgba(0, 122, 255, 0.16)',
    },
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': '0 5px 14px rgba(28, 28, 30, 0.11), inset 0 1px rgba(255, 255, 255, 1), inset 0 -1px rgba(0, 96, 204, 0.14)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.97)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  navigation: {
    display: 'flex',
    height: 30,
    alignItems: 'center',
    gap: 0,
    borderColor: colors.border,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 16,
    paddingRight: 2,
    paddingLeft: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.46)',
    backgroundImage: 'linear-gradient(145deg, rgba(255, 255, 255, 0.98), rgba(255, 255, 255, 0.36) 62%, rgba(174, 215, 255, 0.16))',
    boxShadow: '0 7px 20px rgba(28, 28, 30, 0.13), inset 0 1px rgba(255, 255, 255, 1), inset 0 -1px rgba(0, 96, 204, 0.18)',
  },
  navigationButton: {
    display: 'grid',
    width: 28,
    height: 26,
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 13,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.68)',
      ':active': 'rgba(0, 122, 255, 0.14)',
    },
    color: colors.textMuted,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  controls: {
    'display': 'flex',
    'minWidth': 0,
    'alignItems': 'center',
    'gap': 8,
    '@media (max-width: 900px)': {
      width: '100%',
    },
  },
  range: {
    'display': 'flex',
    'alignItems': 'center',
    'gap': 2,
    'borderColor': colors.border,
    'borderStyle': 'solid',
    'borderWidth': 1,
    'borderRadius': 16,
    'padding': 2,
    'backgroundColor': 'rgba(255, 255, 255, 0.46)',
    'backgroundImage': 'linear-gradient(145deg, rgba(255, 255, 255, 0.98), rgba(255, 255, 255, 0.36) 62%, rgba(174, 215, 255, 0.16))',
    'boxShadow': '0 7px 20px rgba(28, 28, 30, 0.13), inset 0 1px rgba(255, 255, 255, 1), inset 0 -1px rgba(0, 96, 204, 0.18)',
    '@media (max-width: 900px)': {
      flex: 1,
    },
  },
  rangeButton: {
    'height': 24,
    'borderWidth': 0,
    'borderRadius': 12,
    'paddingRight': 8,
    'paddingLeft': 8,
    'backgroundColor': {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.68)',
      ':active': 'rgba(0, 122, 255, 0.14)',
    },
    'color': colors.textMuted,
    'cursor': 'default',
    'fontSize': 11,
    'fontWeight': 600,
    'whiteSpace': 'nowrap',
    '@media (max-width: 900px)': {
      flex: 1,
    },
    'outline': 'none',
    'boxShadow': {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    'transform': {
      'default': 'scale(1)',
      ':active': 'scale(0.96)',
    },
    'transitionDuration': {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    'transitionProperty': 'background-color, box-shadow, color, transform',
    'transitionTimingFunction': 'ease-out',
  },
  rangeButtonSelected: {
    backgroundColor: 'rgb(0, 122, 255)',
    backgroundImage: 'linear-gradient(180deg, rgb(34, 144, 255), rgb(0, 122, 255))',
    boxShadow: '0 4px 10px rgba(0, 92, 196, 0.3), inset 0 1px rgba(255, 255, 255, 0.32)',
    color: 'rgb(255, 255, 255)',
  },
  spanSelect: {
    height: 24,
    borderColor: colors.border,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 12,
    paddingRight: 5,
    paddingLeft: 7,
    backgroundColor: 'rgba(255, 255, 255, 0.36)',
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  calendar: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflow: 'hidden',
  },
})
