import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'var(--ui-accent, rgb(0, 122, 255))',
  controlHover: 'var(--ui-control-hover, rgb(255, 255, 255))',
  controlPressed: 'var(--ui-control-pressed, rgba(235, 232, 244, 0.88))',
  controlSelected: 'var(--ui-control-selected, rgba(240, 247, 255, 0.94))',
  divider: 'var(--ui-divider, rgba(60, 60, 67, 0.11))',
  focus: 'var(--ui-focus, rgba(0, 122, 255, 0.72))',
  surface: 'var(--ui-surface, rgb(255, 255, 255))',
  surfaceRaised: 'var(--ui-surface-raised, rgba(255, 255, 255, 0.82))',
  text: 'var(--ui-text, rgba(28, 28, 30, 0.94))',
  textMuted: 'var(--ui-text-muted, rgba(60, 60, 67, 0.64))',
  textQuiet: 'var(--ui-text-quiet, rgba(60, 60, 67, 0.46))',
  warning: 'var(--ui-warning, rgb(214, 127, 16))',
  success: 'var(--ui-status-success, rgb(42, 145, 87))',
} as const

export const todoBoardViewStyles = stylex.create({
  viewport: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    gap: 0,
    overflowX: 'auto',
    overflowY: 'auto',
    padding: 0,
    overscrollBehavior: 'contain',
  },
  grid: {
    display: 'grid',
    minWidth: 780,
    minHeight: '100%',
    gridTemplateColumns: 'repeat(3, minmax(240px, 1fr))',
    alignItems: 'stretch',
    gap: 0,
  },
  column: {
    display: 'flex',
    minHeight: '100%',
    flexDirection: 'column',
    overflow: 'hidden',
    borderRightColor: colors.divider,
    borderRightStyle: 'solid',
    borderRightWidth: 'var(--ui-surface-stroke, 1px)',
    borderTopColor: 'transparent',
    borderTopStyle: 'solid',
    borderTopWidth: 3,
    backgroundColor: colors.surface,
    boxShadow: 'none',
  },
  columnTodo: {
    borderTopColor: colors.accent,
    backgroundImage: 'linear-gradient(180deg, rgba(0, 122, 255, 0.075), rgba(0, 122, 255, 0.018) 180px, transparent 420px)',
  },
  columnDoing: {
    borderTopColor: 'rgb(255, 149, 0)',
    backgroundImage: 'linear-gradient(180deg, rgba(255, 149, 0, 0.085), rgba(255, 149, 0, 0.018) 180px, transparent 420px)',
  },
  columnDone: {
    borderTopColor: 'rgb(52, 199, 89)',
    backgroundImage: 'linear-gradient(180deg, rgba(52, 199, 89, 0.08), rgba(52, 199, 89, 0.016) 180px, transparent 420px)',
  },
  columnHeader: {
    display: 'flex',
    height: 48,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: 16,
    paddingLeft: 16,
    borderBottomColor: colors.divider,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
  },
  columnTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    color: colors.text,
    fontSize: 12,
    fontWeight: 650,
  },
  columnCount: {
    minWidth: 22,
    height: 20,
    borderRadius: 'var(--ui-control-radius, 4px)',
    paddingRight: 6,
    paddingLeft: 6,
    backgroundColor: colors.surfaceRaised,
    borderWidth: 0,
    color: colors.textMuted,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 600,
    lineHeight: '20px',
    textAlign: 'center',
  },
  columnBody: {
    display: 'flex',
    minHeight: 168,
    flexDirection: 'column',
    gap: 7,
    padding: 10,
  },
  columnEmpty: {
    margin: 'auto',
    padding: 24,
    color: colors.textQuiet,
    fontSize: 12,
    textAlign: 'center',
  },
  columnLoading: {
    padding: 8,
    color: colors.textQuiet,
    fontSize: 11,
    textAlign: 'center',
  },
  card: {
    display: 'flex',
    width: '100%',
    minHeight: 86,
    minWidth: 0,
    boxSizing: 'border-box',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 6,
    borderColor: {
      'default': 'var(--ui-border, rgba(72, 72, 74, 0.12))',
      '@media (prefers-reduced-transparency: reduce)': 'var(--ui-border-strong, rgba(72, 72, 74, 0.14))',
      '@media (prefers-contrast: more)': 'var(--ui-border-strong, rgba(35, 35, 37, 0.34))',
    },
    borderStyle: 'solid',
    borderWidth: 'var(--ui-surface-stroke, 1px)',
    borderRadius: 'var(--ui-surface-radius, 10px)',
    paddingTop: 10,
    paddingRight: 40,
    paddingBottom: 10,
    paddingLeft: 36,
    backgroundColor: {
      'default': colors.surfaceRaised,
      ':hover': colors.controlHover,
      ':active': colors.controlPressed,
    },
    backgroundImage: 'var(--todo-card-background-image, linear-gradient(145deg, rgba(255, 255, 255, 0.72), rgba(245, 248, 252, 0.28)))',
    color: colors.text,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': 'var(--ui-shadow-subtle, 0 4px 14px rgba(49, 42, 72, 0.08))',
      ':hover': 'var(--ui-shadow-raised, 0 7px 20px rgba(49, 42, 72, 0.12))',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'translateY(0) scale(1)',
      ':hover': 'translateY(-1px) scale(1)',
      ':active': 'translateY(0) scale(0.985)',
    },
    transitionDuration: {
      'default': '110ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  cardSelected: {
    borderColor: colors.accent,
    backgroundColor: colors.controlSelected,
    boxShadow: 'var(--ui-shadow-raised, 0 7px 20px rgba(0, 92, 196, 0.14))',
  },
  cardShell: {
    position: 'relative',
    width: '100%',
    minWidth: 0,
  },
  cardActions: {
    position: 'absolute',
    top: 6,
    right: 6,
  },
  cardOccurrence: {
    position: 'absolute',
    zIndex: 1,
    top: 9,
    left: 8,
  },
  cardText: {
    overflow: 'hidden',
    fontSize: 13,
    fontWeight: 560,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  cardSource: {
    overflow: 'hidden',
    color: colors.textQuiet,
    fontSize: 11,
    lineHeight: '15px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  cardFooter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    color: colors.textMuted,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    lineHeight: '15px',
  },
  taskDone: {
    color: colors.textMuted,
    textDecorationLine: 'line-through',
  },
  statusIcon: {
    width: 19,
    height: 19,
    justifySelf: 'center',
    color: colors.textQuiet,
  },
  statusDoing: {
    color: colors.warning,
  },
  statusDone: {
    color: colors.success,
  },
})
