import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'var(--ui-accent, rgb(0, 122, 255))',
  accentSoft: 'var(--ui-accent-soft, rgba(0, 122, 255, 0.1))',
  border: 'var(--ui-divider, rgba(60, 60, 67, 0.12))',
  controlHover: 'var(--ui-control-hover, rgba(118, 118, 128, 0.1))',
  controlPressed: 'var(--ui-control-pressed, rgba(118, 118, 128, 0.16))',
  controlSelected: 'var(--ui-control-selected, rgba(118, 118, 128, 0.14))',
  focus: 'var(--ui-focus, rgba(0, 122, 255, 0.72))',
  onAccent: 'var(--ui-on-accent, rgb(255, 255, 255))',
  panel: 'var(--ui-surface-translucent, rgba(255, 255, 255, 0.46))',
  panelSolid: 'var(--ui-surface, rgb(255, 255, 255))',
  panelSunken: 'var(--ui-surface-sunken, rgb(248, 247, 252))',
  success: 'var(--ui-status-success, rgb(52, 199, 89))',
  text: 'var(--ui-text, rgba(28, 28, 30, 0.94))',
  textMuted: 'var(--ui-text-muted, rgba(60, 60, 67, 0.64))',
  textQuiet: 'var(--ui-text-quiet, rgba(60, 60, 67, 0.46))',
  warning: 'var(--ui-warning, rgb(255, 159, 10))',
} as const

export const todoCalendarViewStyles = stylex.create({
  toolbar: {
    display: 'flex',
    minHeight: 48,
    alignItems: 'center',
    gap: 16,
    borderBottomColor: colors.border,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingRight: 16,
    paddingLeft: 16,
  },
  toolbarLeading: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 8,
  },
  monthTitle: {
    minWidth: 0,
    overflow: 'hidden',
    margin: 0,
    color: colors.accent,
    fontSize: 18,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: '30px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  navigationControl: {
    display: 'flex',
    height: 30,
    alignItems: 'center',
    gap: 0,
    borderColor: colors.border,
    borderStyle: 'solid',
    borderWidth: 'var(--ui-control-stroke, 1px)',
    borderRadius: 'var(--ui-control-radius, 16px)',
    paddingRight: 2,
    paddingLeft: 2,
    backgroundColor: colors.panel,
    backgroundImage: 'var(--todo-control-background-image, linear-gradient(145deg, rgba(255, 255, 255, 0.98), rgba(255, 255, 255, 0.36) 62%, rgba(174, 215, 255, 0.16)))',
    boxShadow: 'var(--ui-control-shadow, 0 7px 20px rgba(28, 28, 30, 0.13))',
  },
  todayButton: {
    height: 30,
    borderColor: colors.border,
    borderStyle: 'solid',
    borderWidth: 'var(--ui-control-stroke, 1px)',
    borderRadius: 'var(--ui-control-radius, 15px)',
    paddingRight: 11,
    paddingLeft: 11,
    backgroundColor: {
      'default': colors.panelSolid,
      ':hover': colors.controlHover,
      ':active': colors.controlPressed,
    },
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': 'var(--ui-control-shadow, 0 5px 14px rgba(28, 28, 30, 0.11))',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.97)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  layout: {
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
  },
  surface: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    overflowX: 'hidden',
    overflowY: 'auto',
    overscrollBehaviorY: 'contain',
    scrollSnapType: 'y mandatory',
    scrollbarWidth: 'none',
    color: colors.text,
    fontFamily: 'inherit',
  },
  monthPanel: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    minHeight: '100%',
    flex: '0 0 100%',
    flexDirection: 'column',
    scrollSnapAlign: 'start',
    scrollSnapStop: 'always',
  },
  root: {
    display: 'flex',
    width: '100%',
    height: '100%',
    minHeight: 0,
    flexDirection: 'column',
    color: colors.text,
    fontFamily: 'inherit',
  },
  grid: {
    display: 'grid',
    minHeight: 510,
    flex: 1,
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    gridTemplateRows: 'repeat(6, minmax(96px, 1fr))',
    gap: 'var(--todo-calendar-grid-gap, 1px)',
    overflow: 'visible',
    backgroundColor: colors.border,
    boxShadow: 'none',
  },
  weekdays: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    borderBottomColor: colors.border,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
  },
  weekday: {
    minWidth: 0,
    paddingTop: 4,
    paddingRight: 9,
    paddingBottom: 7,
    color: colors.textQuiet,
    fontSize: 10,
    fontWeight: 650,
    lineHeight: '15px',
    textAlign: 'right',
  },
  cell: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 82,
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 3,
    paddingTop: 5,
    paddingRight: 5,
    paddingBottom: 5,
    paddingLeft: 5,
    backgroundColor: {
      'default': colors.panelSolid,
      '@media (prefers-reduced-transparency: reduce)': colors.panelSolid,
      '@media (prefers-contrast: more)': colors.panelSolid,
    },
    zIndex: {
      'default': 0,
      ':focus-within': 3,
    },
  },
  spanSegment: {
    position: 'relative',
    zIndex: 2,
    width: 'auto',
    height: 20,
    minWidth: 0,
    alignSelf: 'start',
    marginRight: 5,
    marginLeft: 5,
  },
  cellNeighbor: {
    backgroundColor: colors.panelSunken,
  },
  dayButton: {
    display: 'grid',
    width: 24,
    height: 24,
    flex: '0 0 auto',
    alignSelf: 'flex-end',
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 'var(--ui-control-radius, 12px)',
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': colors.controlHover,
      ':active': colors.controlPressed,
    },
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 650,
    lineHeight: '24px',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  dayButtonNeighbor: {
    color: colors.textQuiet,
  },
  dayButtonSelected: {
    backgroundColor: colors.controlSelected,
    color: colors.text,
  },
  dayButtonToday: {
    backgroundColor: colors.accent,
    color: colors.onAccent,
    boxShadow: 'var(--ui-control-shadow, 0 1px 4px rgba(0, 92, 196, 0.2))',
  },
  taskList: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    gap: 2,
    overflow: 'visible',
  },
  taskShell: {
    position: 'relative',
    minWidth: 0,
    height: 20,
  },
  taskButton: {
    display: 'flex',
    width: '100%',
    height: 20,
    minWidth: 0,
    alignItems: 'center',
    gap: 5,
    overflow: 'hidden',
    borderWidth: 0,
    borderRadius: 'var(--ui-control-radius, 4px)',
    paddingTop: 0,
    paddingRight: 20,
    paddingBottom: 0,
    paddingLeft: 5,
    backgroundColor: {
      'default': colors.accentSoft,
      ':hover': colors.controlHover,
      ':active': colors.controlPressed,
    },
    color: colors.text,
    cursor: 'default',
    fontSize: 10,
    fontWeight: 550,
    lineHeight: '20px',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow',
    transitionTimingFunction: 'ease-out',
  },
  taskButtonSelected: {
    backgroundColor: colors.controlSelected,
    boxShadow: `inset 2px 0 ${colors.accent}`,
  },
  taskStatus: {
    width: 6,
    height: 6,
    flex: '0 0 auto',
    borderRadius: 3,
    backgroundColor: colors.accent,
  },
  taskStatusDoing: {
    backgroundColor: colors.warning,
  },
  taskStatusDone: {
    backgroundColor: colors.success,
  },
  taskText: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  taskTextDone: {
    opacity: 0.58,
    textDecoration: 'line-through',
  },
  predictionShell: {
    position: 'relative',
    minWidth: 0,
    height: 20,
  },
  predictionPreview: {
    display: 'flex',
    width: '100%',
    height: 20,
    minWidth: 0,
    alignItems: 'center',
    gap: 5,
    overflow: 'hidden',
    borderRadius: 'var(--ui-control-radius, 4px)',
    paddingInline: 5,
    backgroundColor: colors.controlHover,
    color: colors.textQuiet,
    fontSize: 10,
    fontWeight: 500,
    lineHeight: '20px',
    opacity: 0.82,
  },
  predictionStatus: {
    width: 6,
    height: 6,
    flex: '0 0 auto',
    borderRadius: 3,
    backgroundColor: colors.textQuiet,
  },
  predictionText: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  taskActions: {
    position: 'absolute',
    top: 0,
    right: 1,
    zIndex: 2,
    display: 'grid',
    width: 18,
    height: 20,
    placeItems: 'center',
    opacity: {
      'default': 0.42,
      ':hover': 1,
      ':focus-within': 1,
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'opacity',
    transitionTimingFunction: 'ease-out',
  },
  overflow: {
    position: 'relative',
    minWidth: 0,
  },
  taskMore: {
    width: 'fit-content',
    overflow: 'hidden',
    paddingRight: 3,
    paddingLeft: 3,
    color: colors.textQuiet,
    cursor: 'default',
    fontSize: 9,
    lineHeight: '15px',
    listStyle: 'none',
    outline: 'none',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  overflowPopover: {
    position: 'absolute',
    top: 19,
    left: '50%',
    zIndex: 8,
    display: 'flex',
    width: 260,
    maxHeight: 300,
    boxSizing: 'border-box',
    flexDirection: 'column',
    gap: 7,
    overflow: 'auto',
    borderColor: 'var(--ui-border, rgba(72, 72, 74, 0.18))',
    borderStyle: 'solid',
    borderWidth: 'var(--ui-surface-stroke, 1px)',
    borderRadius: 'var(--ui-surface-radius, 10px)',
    padding: 9,
    backgroundColor: 'var(--ui-surface-raised, rgba(255, 255, 255, 0.96))',
    backgroundImage: 'var(--todo-card-background-image, linear-gradient(145deg, rgb(255, 255, 255), rgb(247, 250, 253)))',
    boxShadow: 'var(--ui-overlay-shadow, 0 18px 44px rgba(28, 28, 30, 0.2))',
    transform: 'translateX(-50%)',
  },
  overflowTitle: {
    color: colors.text,
    fontSize: 11,
    fontWeight: 650,
    lineHeight: '16px',
  },
  overflowList: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    gap: 3,
  },
})
