import * as stylex from '@stylexjs/stylex'

const colors = {
  focus: 'rgba(41, 97, 194, 0.85)',
  text: 'rgba(25, 27, 31, 0.9)',
  textMuted: 'rgba(48, 52, 59, 0.62)',
  panel: 'rgba(255, 255, 255, 0.5)',
  panelSolid: 'rgb(250, 250, 251)',
  border: 'rgba(72, 72, 74, 0.12)',
} as const

export const todoTimeGridViewStyles = stylex.create({
  root: {
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    flexDirection: 'column',
    color: colors.text,
  },
  toolbar: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    minHeight: 40,
    flex: '0 0 auto',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    paddingRight: 8,
    paddingBottom: 8,
    paddingLeft: 8,
  },
  dateControls: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 8,
  },
  dateTitle: {
    overflow: 'hidden',
    margin: 0,
    color: colors.text,
    fontSize: 18,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: '26px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  today: {
    height: 30,
    borderColor: colors.border,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    paddingRight: 11,
    paddingLeft: 11,
    backgroundColor: {
      'default': colors.panel,
      ':hover': 'rgba(255, 255, 255, 0.72)',
      ':active': 'rgba(118, 118, 128, 0.12)',
      '@media (prefers-reduced-transparency: reduce)': colors.panelSolid,
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    backdropFilter: {
      'default': 'blur(28px) saturate(135%) brightness(1.02)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': '0 4px 14px rgba(28, 28, 30, 0.075), 0 0 0 0.5px rgba(255, 255, 255, 0.58), inset 0 1px rgba(255, 255, 255, 0.92)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.97)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  navigation: {
    display: 'flex',
    height: 30,
    alignItems: 'center',
    gap: 0,
    borderColor: colors.border,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    paddingRight: 2,
    paddingLeft: 2,
    backgroundColor: {
      'default': colors.panel,
      '@media (prefers-reduced-transparency: reduce)': colors.panelSolid,
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    backdropFilter: {
      'default': 'blur(28px) saturate(135%) brightness(1.02)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 4px 14px rgba(28, 28, 30, 0.075), 0 0 0 0.5px rgba(255, 255, 255, 0.58), inset 0 1px rgba(255, 255, 255, 0.92)',
  },
  navigationButton: {
    display: 'grid',
    width: 28,
    height: 26,
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 7,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.56)',
      ':active': 'rgba(118, 118, 128, 0.12)',
    },
    color: colors.textMuted,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  controls: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 8,
  },
  range: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    borderColor: colors.border,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    padding: 2,
    backgroundColor: {
      'default': colors.panel,
      '@media (prefers-reduced-transparency: reduce)': colors.panelSolid,
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    backdropFilter: {
      'default': 'blur(28px) saturate(135%) brightness(1.02)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 4px 14px rgba(28, 28, 30, 0.075), 0 0 0 0.5px rgba(255, 255, 255, 0.58), inset 0 1px rgba(255, 255, 255, 0.92)',
  },
  rangeButton: {
    height: 24,
    borderWidth: 0,
    borderRadius: 7,
    paddingRight: 8,
    paddingLeft: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.56)',
      ':active': 'rgba(118, 118, 128, 0.12)',
    },
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.96)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  rangeButtonSelected: {
    backgroundColor: 'rgba(255, 255, 255, 0.74)',
    boxShadow: '0 1px 4px rgba(28, 28, 30, 0.12), 0 0 0 0.5px rgba(72, 72, 74, 0.08), inset 0 1px rgba(255, 255, 255, 0.96)',
    color: colors.text,
  },
  spanSelect: {
    height: 24,
    borderColor: colors.border,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 7,
    paddingRight: 5,
    paddingLeft: 7,
    backgroundColor: 'transparent',
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  calendar: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflow: 'hidden',
  },
})
