import * as stylex from '@stylexjs/stylex'

export const editorDomSurfaceStyles = stylex.create({
  alert: {
    flexShrink: 0,
    borderBottomColor: '#f0c7c2',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingBlock: 8,
    paddingInline: 12,
    backgroundColor: '#fff1f0',
    color: '#9f1c1c',
    fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
    fontSize: 13,
    lineHeight: '18px',
  },
  emptyTopic: {
    display: 'grid',
    minHeight: 0,
    flex: 1,
    placeItems: 'center',
    padding: 24,
    color: '#66706a',
    fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
    fontSize: 14,
    textAlign: 'center',
  },
  root: {
    display: 'flex',
    width: '100%',
    height: '100%',
    minHeight: 0,
    flexDirection: 'column',
    backgroundColor: '#ffffff',
  },
  topicButton: {
    maxWidth: 220,
    height: 32,
    overflow: 'hidden',
    flexShrink: 0,
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    paddingInline: 10,
    backgroundColor: {
      'default': 'transparent',
      ':active': '#dcebe2',
      ':hover': '#eef5f0',
    },
    color: '#52605a',
    cursor: 'default',
    fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: 0,
    outline: 'none',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  topicButtonSelected: {
    borderColor: '#c8dfd0',
    backgroundColor: '#e7f3ec',
    color: '#155d3b',
  },
  topicNavigation: {
    display: 'flex',
    minHeight: 44,
    overflowX: 'auto',
    flexShrink: 0,
    alignItems: 'center',
    gap: 6,
    borderBottomColor: '#e1e5e1',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingInline: 8,
    backgroundColor: '#f7f8f6',
    scrollbarWidth: 'none',
  },
  workspace: {
    display: 'flex',
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
  },
})
