import * as stylex from '@stylexjs/stylex'

export const learningCardDomStyles = stylex.create({
  actionError: {
    margin: 0,
    color: '#b42318',
    fontSize: 13,
    lineHeight: '18px',
    textAlign: 'center',
  },
  card: {
    display: 'flex',
    minHeight: 0,
    flex: 1,
    alignItems: 'stretch',
    justifyContent: 'center',
    padding: 12,
  },
  cardUnavailable: {
    display: 'grid',
    minHeight: 240,
    flex: 1,
    placeItems: 'center',
    color: '#66706a',
    fontSize: 14,
    textAlign: 'center',
  },
  completion: {
    display: 'grid',
    minHeight: 0,
    flex: 1,
    placeItems: 'center',
    padding: 24,
    textAlign: 'center',
  },
  completionTitle: {
    margin: 0,
    color: '#171a18',
    fontSize: 22,
    fontWeight: 700,
    letterSpacing: 0,
  },
  dock: {
    display: 'flex',
    flexShrink: 0,
    flexDirection: 'column',
    gap: 9,
    borderTopColor: '#d9ded9',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingBlock: 10,
    paddingInline: 12,
    backgroundColor: 'rgba(247, 248, 246, 0.97)',
  },
  header: {
    display: 'flex',
    minHeight: 48,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    borderBottomColor: '#d9ded9',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingInline: 12,
    backgroundColor: '#f7f8f6',
  },
  headerText: {
    minWidth: 0,
  },
  modeButton: {
    height: 30,
    borderWidth: 0,
    borderRadius: 6,
    paddingInline: 10,
    backgroundColor: {
      'default': 'transparent',
      ':active': '#dcebe2',
      ':hover': '#eef5f0',
    },
    color: '#52605a',
    cursor: 'default',
    fontSize: 12,
    fontWeight: 650,
    letterSpacing: 0,
  },
  modeButtonSelected: {
    backgroundColor: '#e7f3ec',
    color: '#155d3b',
  },
  modes: {
    display: 'flex',
    gap: 2,
  },
  noteTitle: {
    overflow: 'hidden',
    margin: 0,
    color: '#171a18',
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: 0,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  ratingButton: {
    display: 'flex',
    minWidth: 0,
    minHeight: 48,
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#d9ded9',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 7,
    padding: 5,
    backgroundColor: {
      'default': '#ffffff',
      ':active': '#eef5f0',
      ':disabled': '#f1f3f1',
    },
    color: '#171a18',
    cursor: 'default',
    font: 'inherit',
  },
  ratingGrid: {
    display: 'flex',
    gap: 7,
  },
  ratingInterval: {
    color: '#66706a',
    fontSize: 10,
    lineHeight: '14px',
  },
  ratingLabel: {
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: 0,
    textTransform: 'capitalize',
  },
  root: {
    display: 'flex',
    width: '100%',
    height: '100%',
    minHeight: 0,
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    color: '#171a18',
    fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
  },
  secondaryActions: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 8,
  },
  secondaryButton: {
    minHeight: 34,
    borderColor: '#d9ded9',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    paddingInline: 12,
    backgroundColor: {
      'default': '#ffffff',
      ':active': '#e7f3ec',
      ':disabled': '#f1f3f1',
    },
    color: '#52605a',
    cursor: 'default',
    fontSize: 12,
    fontWeight: 650,
    letterSpacing: 0,
  },
  showAnswerButton: {
    width: '100%',
    minHeight: 48,
    borderWidth: 0,
    borderRadius: 7,
    backgroundColor: {
      'default': '#177245',
      ':active': '#105c36',
      ':disabled': '#96b8a5',
    },
    color: '#ffffff',
    cursor: 'default',
    fontSize: 15,
    fontWeight: 750,
    letterSpacing: 0,
  },
  status: {
    display: 'grid',
    minHeight: 0,
    flex: 1,
    placeItems: 'center',
    padding: 24,
    color: '#66706a',
    fontSize: 14,
    textAlign: 'center',
  },
  topicTitle: {
    overflow: 'hidden',
    margin: 0,
    color: '#66706a',
    fontSize: 11,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
})
