import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: '#0071E3',
  accentActive: '#0058B0',
  accentSoft: 'rgba(0, 113, 227, 0.12)',
  background: '#FFFFFF',
  border: 'rgba(48, 46, 51, 0.13)',
  muted: 'rgba(48, 46, 51, 0.62)',
  surface: '#F8F9FB',
  surfacePressed: 'rgba(76, 84, 96, 0.10)',
  text: 'rgba(25, 27, 31, 0.90)',
} as const

export const learningCardDomStyles = stylex.create({
  actionError: {
    margin: 0,
    color: '#B3261E',
    fontSize: 13,
    lineHeight: '18px',
    textAlign: 'center',
  },
  card: {
    display: 'flex',
    minHeight: 0,
    flex: 1,
    alignItems: 'stretch',
    justifyContent: 'center',
    padding: 12,
  },
  cardUnavailable: {
    display: 'grid',
    minHeight: 240,
    flex: 1,
    placeItems: 'center',
    color: colors.muted,
    fontSize: 14,
    textAlign: 'center',
  },
  completion: {
    display: 'grid',
    minHeight: 0,
    flex: 1,
    placeItems: 'center',
    padding: 24,
    textAlign: 'center',
  },
  completionTitle: {
    margin: 0,
    color: colors.text,
    fontSize: 22,
    fontWeight: 700,
    letterSpacing: 0,
  },
  dock: {
    display: 'flex',
    flexShrink: 0,
    flexDirection: 'column',
    gap: 9,
    borderTopColor: colors.border,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingBlock: 10,
    paddingInline: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.90)',
  },
  header: {
    display: 'flex',
    minHeight: 48,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    borderBottomColor: colors.border,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingInline: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.86)',
  },
  headerText: {
    minWidth: 0,
  },
  modeButton: {
    height: 30,
    borderWidth: 0,
    borderRadius: 9,
    paddingInline: 10,
    backgroundColor: {
      'default': 'transparent',
      ':active': colors.surfacePressed,
      ':hover': colors.surface,
    },
    color: colors.muted,
    cursor: 'default',
    fontSize: 12,
    fontWeight: 650,
    letterSpacing: 0,
  },
  modeButtonSelected: {
    backgroundColor: colors.accentSoft,
    color: colors.accent,
  },
  modes: {
    display: 'flex',
    gap: 2,
  },
  noteTitle: {
    overflow: 'hidden',
    margin: 0,
    color: colors.text,
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: 0,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  ratingButton: {
    display: 'flex',
    minWidth: 0,
    minHeight: 48,
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: colors.border,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    padding: 5,
    backgroundColor: {
      'default': colors.surface,
      ':active': colors.surfacePressed,
      ':disabled': '#E3E6EB',
    },
    color: colors.text,
    cursor: 'default',
    font: 'inherit',
  },
  ratingGrid: {
    display: 'flex',
    gap: 7,
  },
  ratingInterval: {
    color: colors.muted,
    fontSize: 10,
    lineHeight: '14px',
  },
  ratingLabel: {
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: 0,
    textTransform: 'capitalize',
  },
  root: {
    display: 'flex',
    width: '100%',
    height: '100%',
    minHeight: 0,
    flexDirection: 'column',
    backgroundColor: colors.background,
    color: colors.text,
    fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
  },
  secondaryActions: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 8,
  },
  secondaryButton: {
    minHeight: 34,
    borderColor: colors.border,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    paddingInline: 12,
    backgroundColor: {
      'default': colors.surface,
      ':active': colors.accentSoft,
      ':disabled': '#E3E6EB',
    },
    color: colors.muted,
    cursor: 'default',
    fontSize: 12,
    fontWeight: 650,
    letterSpacing: 0,
  },
  showAnswerButton: {
    width: '100%',
    minHeight: 48,
    borderWidth: 0,
    borderRadius: 11,
    backgroundColor: {
      'default': colors.accent,
      ':active': colors.accentActive,
      ':disabled': '#9FC7EE',
    },
    color: '#ffffff',
    cursor: 'default',
    fontSize: 15,
    fontWeight: 750,
    letterSpacing: 0,
  },
  status: {
    display: 'grid',
    minHeight: 0,
    flex: 1,
    placeItems: 'center',
    padding: 24,
    color: colors.muted,
    fontSize: 14,
    textAlign: 'center',
  },
  topicTitle: {
    overflow: 'hidden',
    margin: 0,
    color: colors.muted,
    fontSize: 11,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
})
