import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'var(--ui-accent, rgb(28, 94, 196))',
  accentSoft: 'var(--ui-accent-soft, rgba(28, 94, 196, 0.1))',
  error: 'var(--ui-danger, rgb(170, 48, 48))',
  focus: 'var(--ui-focus, rgba(41, 97, 194, 0.82))',
  secondaryText: 'var(--ui-text-muted, rgba(50, 54, 62, 0.58))',
  text: 'var(--ui-text, rgba(24, 26, 31, 0.92))',
} as const

export const journalsPageStyles = stylex.create({
  page: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    backgroundColor: 'var(--ui-canvas, rgb(255, 255, 255))',
    color: colors.text,
  },
  scrollEdge: {
    position: 'absolute',
    zIndex: 10,
    top: 0,
    right: 0,
    left: 0,
    height: 60,
    pointerEvents: 'none',
    backgroundColor: {
      'default': 'var(--ui-surface-translucent, rgba(255, 255, 255, 0.94))',
      '@media (prefers-reduced-transparency: reduce)': 'var(--ui-surface, rgb(255, 255, 255))',
      '@media (prefers-contrast: more)': 'var(--ui-surface, rgb(255, 255, 255))',
    },
    backdropFilter: {
      'default': 'var(--ui-material-filter, blur(14px) saturate(150%))',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: 'var(--ui-shadow-subtle, 0 12px 18px 6px rgba(255, 255, 255, 0.94))',
  },
  viewport: {
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflowX: 'hidden',
    overflowY: 'auto',
    overscrollBehaviorY: 'contain',
    paddingTop: 72,
    scrollbarGutter: 'stable',
  },
  feed: {
    position: 'relative',
    width: 'min(100%, 940px)',
    marginRight: 'auto',
    marginLeft: 'auto',
  },
  feedHeight: (height: number) => ({
    height,
  }),
  virtualRow: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    paddingRight: {
      'default': 56,
      '@media (max-width: 900px)': 32,
    },
    paddingLeft: {
      'default': 56,
      '@media (max-width: 900px)': 32,
    },
  },
  virtualRowOffset: (offset: number) => ({
    transform: `translateY(${offset}px)`,
  }),
  day: {
    width: '100%',
    minHeight: 340,
    paddingTop: 28,
    paddingBottom: 64,
    borderTopColor: 'var(--ui-divider, rgba(75, 80, 90, 0.13))',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
  },
  firstDay: {
    paddingTop: 16,
    borderTopWidth: 0,
  },
  compactDay: {
    minHeight: 0,
    height: '100%',
    paddingTop: 0,
    paddingBottom: 0,
    borderTopWidth: 0,
  },
  dayHeader: {
    minWidth: 0,
    marginBottom: 4,
    paddingInlineStart: 'calc(max(4rem, calc(50% - 20rem)) + 1.5rem + 2px)',
  },
  compactDayHeader: {
    marginBottom: 2,
    paddingTop: 14,
    paddingRight: 22,
    paddingLeft: 22,
  },
  dayTitle: {
    minWidth: 0,
    margin: 0,
    color: colors.text,
    fontSize: 18,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '26px',
    textWrap: 'balance',
  },
  compactDayTitle: {
    fontSize: 15,
    lineHeight: '22px',
  },
  todayLabel: {
    display: 'inline-block',
    marginInlineStart: 8,
    color: colors.secondaryText,
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '18px',
    verticalAlign: 'baseline',
  },
  editorRegion: {
    minHeight: 230,
  },
  compactEditorRegion: {
    minHeight: 0,
    height: 'calc(100% - 38px)',
    overflowY: 'auto',
    overscrollBehaviorY: 'contain',
  },
  inlineStatus: {
    display: 'flex',
    minHeight: 230,
    alignItems: 'flex-start',
    gap: 8,
    paddingTop: 12,
    color: colors.secondaryText,
    fontSize: 13,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  inlineError: {
    color: colors.error,
  },
  validationError: {
    marginBottom: 14,
    paddingTop: 9,
    paddingRight: 12,
    paddingBottom: 9,
    paddingLeft: 12,
    borderLeftColor: colors.error,
    borderLeftStyle: 'solid',
    borderLeftWidth: 2,
    backgroundColor: 'color-mix(in srgb, var(--ui-danger, rgb(190, 52, 52)) 8%, transparent)',
    color: colors.error,
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: '18px',
  },
  feedStatus: {
    display: 'flex',
    height: 96,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    color: colors.secondaryText,
    fontSize: 13,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  initialStatus: {
    display: 'flex',
    width: '100%',
    minHeight: 0,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    color: colors.secondaryText,
    fontSize: 13,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  statusIcon: {
    width: 17,
    height: 17,
    flex: '0 0 17px',
  },
  loadingIcon: {
    animationDuration: '900ms',
    animationIterationCount: 'infinite',
    animationName: stylex.keyframes({
      to: { transform: 'rotate(360deg)' },
    }),
    animationTimingFunction: 'linear',
  },
  retryButton: {
    minHeight: 28,
    borderColor: 'var(--ui-border, rgba(72, 78, 89, 0.18))',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 'var(--ui-control-radius, 6px)',
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: {
      'default': 'var(--ui-surface-raised, rgba(248, 249, 251, 0.88))',
      ':hover': 'var(--ui-control-hover, rgb(241, 244, 248))',
      ':active': 'var(--ui-control-pressed, rgb(232, 236, 242))',
    },
    color: colors.text,
    cursor: 'default',
    fontSize: 12,
    fontWeight: 550,
    letterSpacing: 0,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
})
