import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'rgb(28, 94, 196)',
  accentSoft: 'rgba(28, 94, 196, 0.1)',
  error: 'rgb(170, 48, 48)',
  focus: 'rgba(41, 97, 194, 0.82)',
  secondaryText: 'rgba(50, 54, 62, 0.58)',
  text: 'rgba(24, 26, 31, 0.92)',
} as const

export const journalsPageStyles = stylex.create({
  page: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    backgroundColor: 'rgb(255, 255, 255)',
    color: colors.text,
  },
  scrollEdge: {
    position: 'absolute',
    zIndex: 10,
    top: 0,
    right: 0,
    left: 0,
    height: 60,
    pointerEvents: 'none',
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.94)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(255, 255, 255)',
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    backdropFilter: {
      'default': 'blur(14px) saturate(150%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 12px 18px 6px rgba(255, 255, 255, 0.94)',
  },
  viewport: {
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflowX: 'hidden',
    overflowY: 'auto',
    overscrollBehaviorY: 'contain',
    paddingTop: 72,
    scrollbarGutter: 'stable',
  },
  feed: {
    position: 'relative',
    width: 'min(100%, 940px)',
    marginRight: 'auto',
    marginLeft: 'auto',
  },
  feedHeight: (height: number) => ({
    height,
  }),
  virtualRow: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    paddingRight: {
      'default': 56,
      '@media (max-width: 900px)': 32,
    },
    paddingLeft: {
      'default': 56,
      '@media (max-width: 900px)': 32,
    },
  },
  virtualRowOffset: (offset: number) => ({
    transform: `translateY(${offset}px)`,
  }),
  day: {
    width: '100%',
    minHeight: 340,
    paddingTop: 28,
    paddingBottom: 64,
    borderTopColor: 'rgba(75, 80, 90, 0.13)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
  },
  firstDay: {
    paddingTop: 16,
    borderTopWidth: 0,
  },
  dayHeader: {
    minWidth: 0,
    marginBottom: 4,
    paddingInlineStart: 'calc(max(4rem, calc(50% - 20rem)) + 1.5rem + 2px)',
  },
  dayTitle: {
    minWidth: 0,
    margin: 0,
    color: colors.text,
    fontSize: 18,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '26px',
    textWrap: 'balance',
  },
  todayLabel: {
    display: 'inline-block',
    marginInlineStart: 8,
    color: colors.secondaryText,
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '18px',
    verticalAlign: 'baseline',
  },
  editorRegion: {
    minHeight: 230,
  },
  inlineStatus: {
    display: 'flex',
    minHeight: 230,
    alignItems: 'flex-start',
    gap: 8,
    paddingTop: 12,
    color: colors.secondaryText,
    fontSize: 13,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  inlineError: {
    color: colors.error,
  },
  validationError: {
    marginBottom: 14,
    paddingTop: 9,
    paddingRight: 12,
    paddingBottom: 9,
    paddingLeft: 12,
    borderLeftColor: colors.error,
    borderLeftStyle: 'solid',
    borderLeftWidth: 2,
    backgroundColor: 'rgba(190, 52, 52, 0.06)',
    color: colors.error,
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: '18px',
  },
  feedStatus: {
    display: 'flex',
    height: 96,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    color: colors.secondaryText,
    fontSize: 13,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  initialStatus: {
    display: 'flex',
    width: '100%',
    minHeight: 0,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    color: colors.secondaryText,
    fontSize: 13,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  statusIcon: {
    width: 17,
    height: 17,
    flex: '0 0 17px',
  },
  loadingIcon: {
    animationDuration: '900ms',
    animationIterationCount: 'infinite',
    animationName: stylex.keyframes({
      to: { transform: 'rotate(360deg)' },
    }),
    animationTimingFunction: 'linear',
  },
  retryButton: {
    minHeight: 28,
    borderColor: 'rgba(72, 78, 89, 0.18)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: {
      'default': 'rgba(248, 249, 251, 0.88)',
      ':hover': 'rgb(241, 244, 248)',
      ':active': 'rgb(232, 236, 242)',
    },
    color: colors.text,
    cursor: 'default',
    fontSize: 12,
    fontWeight: 550,
    letterSpacing: 0,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
})
