import * as stylex from '@stylexjs/stylex'

const text = 'rgba(24, 26, 31, 0.92)'

export const journalCalendarStyles = stylex.create({
  navigation: {
    display: 'grid',
    height: 34,
    gridTemplateColumns: '32px minmax(0, 1fr) 32px',
    alignItems: 'center',
    gap: 4,
    marginBottom: 8,
  },
  navigationButton: {
    display: 'grid',
    width: 32,
    height: 32,
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 16,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(52, 52, 54, 0.06)',
      ':active': 'rgba(52, 52, 54, 0.11)',
      ':disabled': 'transparent',
    },
    color: {
      'default': 'rgba(27, 31, 38, 0.84)',
      ':disabled': 'rgba(42, 47, 56, 0.2)',
    },
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgba(44, 44, 46, 0.68)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.96)',
      ':disabled': 'scale(1)',
    },
    transitionDuration: {
      'default': '110ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  monthLabel: {
    overflow: 'hidden',
    color: 'rgba(27, 31, 38, 0.9)',
    fontSize: 13,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '20px',
    textAlign: 'center',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  weekdays: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    marginBottom: 2,
  },
  weekday: {
    paddingTop: 5,
    paddingBottom: 7,
    color: 'rgba(47, 53, 62, 0.48)',
    fontSize: 10,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '12px',
    textAlign: 'center',
  },
  calendar: {
    width: '100%',
    maxWidth: '100%',
    borderWidth: 0,
    backgroundColor: 'transparent',
    color: text,
    fontFamily: 'inherit',
    fontSize: 0,
    lineHeight: 1,
  },
  tile: {
    position: 'relative',
    display: 'grid',
    height: 38,
    minWidth: 0,
    placeItems: 'center',
    appearance: 'none',
    borderWidth: 0,
    borderRadius: 19,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(52, 52, 54, 0.06)',
      ':active': 'rgba(52, 52, 54, 0.11)',
    },
    color: 'rgba(29, 33, 40, 0.88)',
    cursor: 'default',
    fontFamily: 'inherit',
    fontSize: 12,
    fontWeight: 520,
    letterSpacing: 0,
    lineHeight: '16px',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':hover': 'inset 0 1px rgba(255, 255, 255, 0.86)',
      ':focus-visible': '0 0 0 2px rgba(44, 44, 46, 0.68)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.93)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  tileHidden: {
    visibility: 'hidden',
    pointerEvents: 'none',
  },
  tileDisabled: {
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'transparent',
      ':active': 'transparent',
    },
    color: 'rgba(42, 47, 56, 0.2)',
    boxShadow: 'none',
    transform: 'none',
  },
  tileToday: {
    backgroundColor: 'rgba(255, 255, 255, 0.34)',
    color: 'rgba(24, 28, 34, 0.94)',
    fontWeight: 650,
    boxShadow: {
      'default': 'inset 0 0 0 1px rgba(34, 39, 47, 0.2), inset 0 1px 1px rgba(255, 255, 255, 0.9)',
      '@media (prefers-contrast: more)': 'inset 0 0 0 2px rgb(34, 39, 47)',
    },
  },
  tileSelected: {
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.58)',
      ':hover': 'rgba(255, 255, 255, 0.68)',
      ':active': 'rgba(52, 52, 54, 0.12)',
    },
    color: 'rgba(20, 24, 30, 0.96)',
    boxShadow: '0 4px 10px rgba(28, 28, 30, 0.11), 0 0 0 0.5px rgba(72, 72, 74, 0.24), inset 0 1px rgba(255, 255, 255, 0.98), inset 0 -1px rgba(72, 72, 74, 0.14)',
  },
  presence: {
    position: 'absolute',
    bottom: 3,
    left: '50%',
    width: 3,
    height: 3,
    borderRadius: '50%',
    backgroundColor: 'rgba(35, 40, 48, 0.56)',
    transform: 'translateX(-50%)',
  },
  presenceSelected: {
    backgroundColor: 'rgba(25, 29, 36, 0.72)',
  },
})
