import * as stylex from '@stylexjs/stylex'
import { shelfTheme } from '../shelf-shared.stylex'

const controlTransition = {
  'default': shelfTheme.controlDuration,
  '@media (prefers-reduced-motion: reduce)': '0ms',
} as const

export const shelfSourceManagerStyles = stylex.create({
  sheet: {
    position: 'relative',
    display: 'flex',
    width: 'min(480px, calc(100vw - 48px))',
    maxHeight: 'calc(100vh - 72px)',
    overflow: 'hidden',
    flexDirection: 'column',
  },
  sheetHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 20,
    paddingTop: 24,
    paddingRight: 20,
    paddingBottom: 18,
    paddingLeft: 24,
  },
  managerHeading: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'flex-start',
    gap: 8,
  },
  managerBody: {
    display: 'flex',
    minHeight: 260,
    overflow: 'hidden',
    flexDirection: 'column',
  },
  managerList: {
    display: 'flex',
    minHeight: 0,
    overflowY: 'auto',
    flex: 1,
    flexDirection: 'column',
    gap: 2,
    paddingRight: 16,
    paddingBottom: 10,
    paddingLeft: 16,
  },
  managerSourceRow: {
    display: 'grid',
    minHeight: 58,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '32px minmax(0, 1fr) 34px 34px',
    gap: 4,
    borderRadius: 10,
    paddingRight: 7,
    paddingLeft: 9,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(77, 84, 94, 0.06)',
    },
  },
  managerSourceIcon: {
    display: 'grid',
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyItems: 'center',
    borderRadius: 8,
    backgroundColor: 'rgba(0, 113, 227, 0.09)',
    color: shelfTheme.accent,
  },
  managerSourceDetails: {
    display: 'flex',
    minWidth: 0,
    overflow: 'hidden',
    alignItems: 'flex-start',
    flexDirection: 'column',
    gap: 2,
    borderWidth: 0,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    backgroundColor: 'transparent',
    color: shelfTheme.text,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  managerRemoveButton: {
    display: 'grid',
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyItems: 'center',
    borderWidth: 0,
    borderRadius: 9,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(198, 48, 48, 0.1)',
      ':active': 'rgba(198, 48, 48, 0.16)',
    },
    color: {
      'default': shelfTheme.textQuiet,
      ':hover': shelfTheme.danger,
    },
    cursor: 'default',
    outline: 'none',
  },
  managerActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    borderTopColor: 'rgba(255, 255, 255, 0.36)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 14,
    paddingRight: 20,
    paddingBottom: 18,
    paddingLeft: 20,
  },
  sheetTitle: {
    margin: 0,
    fontSize: 21,
    fontWeight: 690,
    letterSpacing: 0,
    lineHeight: '26px',
  },
  sheetSubtitle: {
    maxWidth: 370,
    marginTop: 5,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: shelfTheme.textMuted,
    fontSize: 12,
    lineHeight: '17px',
  },
  sourceForm: {
    display: 'flex',
    minHeight: 0,
    overflowY: 'auto',
    flexDirection: 'column',
    gap: 15,
    paddingRight: 24,
    paddingBottom: 22,
    paddingLeft: 24,
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    color: shelfTheme.textMuted,
    fontSize: 11,
    fontWeight: 600,
  },
  fieldOptional: {
    marginLeft: 5,
    color: shelfTheme.textQuiet,
    fontSize: 10,
    fontWeight: 500,
  },
  textInput: {
    width: '100%',
    height: 36,
    borderColor: {
      'default': 'rgba(60, 60, 67, 0.16)',
      ':focus': 'rgba(0, 113, 227, 0.72)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: {
      'default': 'rgba(92, 92, 100, 0.1)',
      ':focus': 'rgba(255, 255, 255, 0.82)',
      '@media (prefers-contrast: more)': 'rgba(255, 255, 255, 0.9)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(235, 235, 237)',
    },
    caretColor: shelfTheme.accent,
    color: shelfTheme.text,
    fontSize: 13,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus': '0 0 0 3px rgba(0, 113, 227, 0.18)',
    },
    transitionDuration: controlTransition,
    transitionProperty: 'background-color, border-color, box-shadow',
    transitionTimingFunction: 'ease-out',
  },
  accountDisclosure: {
    display: 'flex',
    width: '100%',
    height: 34,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderColor: 'rgba(52, 59, 70, 0.08)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    paddingRight: 8,
    paddingLeft: 8,
    backgroundColor: {
      'default': 'rgba(42, 49, 61, 0.035)',
      ':hover': 'rgba(42, 49, 61, 0.07)',
      ':active': 'rgba(70, 78, 90, 0.1)',
    },
    color: shelfTheme.textMuted,
    cursor: 'default',
    fontSize: 12,
    outline: 'none',
    boxShadow: 'inset 0 1px rgba(255, 255, 255, 0.2)',
  },
  accountLabel: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
  },
  accountFields: {
    display: 'flex',
    overflow: 'hidden',
    flexDirection: 'column',
    gap: 12,
  },
  privacyNote: {
    margin: 0,
    color: shelfTheme.textQuiet,
    fontSize: 10,
    lineHeight: '15px',
  },
  formError: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 7,
    borderRadius: 9,
    paddingTop: 9,
    paddingRight: 10,
    paddingBottom: 9,
    paddingLeft: 10,
    backgroundColor: 'rgba(198, 48, 48, 0.09)',
    color: 'rgb(158, 38, 38)',
    fontSize: 11,
    lineHeight: '16px',
  },
  sheetActions: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
    borderTopColor: 'rgba(255, 255, 255, 0.36)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    marginTop: 2,
    paddingTop: 16,
  },
})
