import * as stylex from '@stylexjs/stylex'
import { shelfTheme } from '../shelf-shared.stylex'

export const shelfSourceMenuStyles = stylex.create({
  sourceMenu: {
    position: 'absolute',
    zIndex: 40,
    top: 44,
    left: 0,
    display: 'flex',
    width: 286,
    maxHeight: 390,
    minHeight: 0,
    overflow: 'hidden',
    flexDirection: 'column',
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.82)',
      '@media (prefers-contrast: more)': 'rgba(35, 39, 46, 0.62)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 15,
    padding: 5,
    backgroundColor: {
      'default': 'rgba(244, 246, 249, 0.5)',
      '@media (prefers-contrast: more)': 'rgba(250, 250, 251, 0.96)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(248, 249, 251)',
    },
    backgroundImage: 'linear-gradient(145deg, rgba(255, 255, 255, 0.34), rgba(255, 255, 255, 0.04))',
    backdropFilter: {
      'default': 'blur(20px) saturate(185%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 20px 48px rgba(26, 32, 42, 0.22), 0 4px 12px rgba(26, 32, 42, 0.1), inset 0 1px rgba(255, 255, 255, 0.94)',
    transformOrigin: 'top left',
  },
  sourceMenuScroll: {
    minHeight: 0,
    maxHeight: 270,
    overflowY: 'auto',
    overscrollBehavior: 'contain',
  },
  sourceMenuItem: {
    display: 'grid',
    width: '100%',
    minHeight: 38,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '18px minmax(0, 1fr) 18px',
    gap: 7,
    borderWidth: 0,
    borderRadius: 9,
    paddingTop: 5,
    paddingRight: 8,
    paddingBottom: 5,
    paddingLeft: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(62, 72, 87, 0.08)',
      ':active': 'rgba(62, 72, 87, 0.14)',
    },
    color: shelfTheme.text,
    cursor: 'default',
    fontSize: 13,
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `inset 0 0 0 2px ${shelfTheme.focus}`,
    },
  },
  sourceMenuItemSelected: {
    backgroundColor: 'rgba(0, 113, 227, 0.1)',
    color: 'rgb(0, 94, 190)',
  },
  sourceMenuLabel: {
    display: 'flex',
    minWidth: 0,
    overflow: 'hidden',
    flexDirection: 'column',
    lineHeight: '17px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  menuSeparator: {
    height: 1,
    flex: '0 0 1px',
    marginTop: 4,
    marginRight: 7,
    marginBottom: 4,
    marginLeft: 7,
    backgroundColor: 'rgba(72, 80, 93, 0.12)',
  },
})
