import * as stylex from '@stylexjs/stylex'
import { uiColors, uiMotion } from '../theme.stylex'

export const buttonStyles = stylex.create({
  base: {
    'display': 'inline-flex',
    'minWidth': 0,
    'alignItems': 'center',
    'justifyContent': 'center',
    'gap': 6,
    'borderStyle': 'solid',
    'borderWidth': 1,
    'outline': 'none',
    'cursor': 'default',
    'textDecoration': 'none',
    'transitionDuration': uiMotion.duration,
    'transitionProperty': 'background-color, border-color, box-shadow, color, transform',
    'transitionTimingFunction': uiMotion.easing,
    ':focus-visible': {
      boxShadow: `0 0 0 2px ${uiColors.focus}`,
    },
    ':disabled': {
      cursor: 'default',
      opacity: 0.48,
      pointerEvents: 'none',
    },
  },
  plain: {
    minHeight: 34,
    borderColor: 'transparent',
    borderRadius: 9,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.32)',
      ':active': 'rgba(80, 91, 108, 0.14)',
    },
    color: uiColors.text,
    fontSize: 13,
    fontWeight: 500,
  },
  titlebar: {
    width: 32,
    height: 32,
    flex: '0 0 32px',
    borderColor: 'transparent',
    borderWidth: 0,
    borderRadius: 16,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.3)',
      ':active': 'rgba(58, 66, 78, 0.14)',
      ':disabled': 'transparent',
    },
    color: {
      'default': 'rgba(31, 35, 42, 0.82)',
      ':hover': 'rgba(22, 25, 31, 0.94)',
      ':disabled': 'rgba(44, 49, 58, 0.28)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.96)',
      ':disabled': 'scale(1)',
    },
  },
  toolbar: {
    width: 32,
    height: 32,
    flex: '0 0 32px',
    borderColor: 'transparent',
    borderWidth: 0,
    borderRadius: 7,
    padding: 4,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(71, 76, 86, 0.1)',
      ':active': 'rgba(71, 76, 86, 0.16)',
    },
    color: uiColors.text,
    fontSize: 13,
    fontWeight: 550,
  },
  primary: {
    minHeight: 36,
    borderColor: 'rgba(0, 83, 170, 0.16)',
    borderRadius: 11,
    paddingRight: 14,
    paddingLeft: 12,
    backgroundColor: {
      'default': uiColors.accent,
      ':hover': 'rgb(0, 105, 211)',
      ':active': uiColors.accentPressed,
    },
    color: 'white',
    fontSize: 13,
    fontWeight: 600,
    boxShadow: '0 4px 11px rgba(0, 86, 178, 0.2), inset 0 1px rgba(255, 255, 255, 0.24)',
  },
  secondary: {
    minHeight: 36,
    borderColor: 'rgba(255, 255, 255, 0.42)',
    borderRadius: 11,
    paddingRight: 14,
    paddingLeft: 14,
    backgroundColor: {
      'default': 'rgba(235, 240, 247, 0.18)',
      ':hover': 'rgba(255, 255, 255, 0.38)',
      ':active': 'rgba(71, 79, 91, 0.1)',
    },
    color: uiColors.text,
    fontSize: 13,
    fontWeight: 550,
    boxShadow: 'inset 0 1px rgba(255, 255, 255, 0.54), 0 1px 2px rgba(35, 42, 52, 0.06)',
  },
  menu: {
    minHeight: 38,
    width: '100%',
    justifyContent: 'flex-start',
    borderColor: 'transparent',
    borderRadius: 9,
    paddingTop: 5,
    paddingRight: 8,
    paddingBottom: 5,
    paddingLeft: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(62, 72, 87, 0.08)',
      ':active': 'rgba(62, 72, 87, 0.14)',
    },
    color: uiColors.text,
    fontSize: 13,
    fontWeight: 400,
  },
  icon: {
    minWidth: 36,
    minHeight: 36,
    borderColor: 'transparent',
    borderWidth: 0,
    borderRadius: 6,
    padding: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(243, 244, 246, 1)',
      ':active': 'rgba(229, 231, 235, 1)',
    },
    color: 'rgba(17, 24, 39, 1)',
    fontSize: 14,
    fontWeight: 500,
  },
  pressed: {
    backgroundColor: 'rgba(82, 86, 94, 0.16)',
  },
})
