import * as stylex from '@stylexjs/stylex'
import { uiColors, uiMotion } from '../theme.stylex'

export const buttonStyles = stylex.create({
  base: {
    'display': 'inline-flex',
    'minWidth': 0,
    'alignItems': 'center',
    'justifyContent': 'center',
    'gap': 6,
    'borderStyle': 'solid',
    'borderWidth': uiColors.controlStroke,
    'outline': 'none',
    'cursor': 'default',
    'textDecoration': 'none',
    'transitionDuration': uiMotion.duration,
    'transitionProperty': 'background-color, border-color, box-shadow, color, transform',
    'transitionTimingFunction': uiMotion.easing,
    ':focus-visible': {
      boxShadow: `0 0 0 2px ${uiColors.focus}`,
    },
    ':disabled': {
      cursor: 'default',
      opacity: 0.48,
      pointerEvents: 'none',
    },
  },
  plain: {
    minHeight: 34,
    borderColor: 'transparent',
    borderRadius: uiColors.controlRadius,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: {
      'default': 'transparent',
      ':hover': uiColors.controlHover,
      ':active': uiColors.controlPressed,
    },
    color: uiColors.text,
    fontSize: 13,
    fontWeight: 500,
  },
  titlebar: {
    width: 32,
    height: 32,
    flex: '0 0 32px',
    borderColor: 'transparent',
    borderWidth: 0,
    borderRadius: uiColors.pillRadius,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': uiColors.controlHover,
      ':active': uiColors.controlPressed,
      ':disabled': 'transparent',
    },
    color: {
      'default': uiColors.text,
      ':hover': uiColors.text,
      ':disabled': uiColors.textQuiet,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.96)',
      ':disabled': 'scale(1)',
    },
  },
  toolbar: {
    width: 32,
    height: 32,
    flex: '0 0 32px',
    borderColor: 'transparent',
    borderWidth: 0,
    borderRadius: uiColors.controlRadius,
    padding: 4,
    backgroundColor: {
      'default': 'transparent',
      ':hover': uiColors.controlHover,
      ':active': uiColors.controlPressed,
    },
    color: uiColors.text,
    fontSize: 13,
    fontWeight: 550,
  },
  primary: {
    minHeight: 36,
    borderColor: uiColors.accentSoft,
    borderRadius: uiColors.controlRadius,
    paddingRight: 14,
    paddingLeft: 12,
    backgroundColor: {
      'default': uiColors.accent,
      ':hover': uiColors.accentHover,
      ':active': uiColors.accentPressed,
    },
    color: uiColors.onAccent,
    fontSize: 13,
    fontWeight: 600,
    boxShadow: uiColors.controlShadow,
  },
  secondary: {
    minHeight: 36,
    borderColor: uiColors.fieldBorder,
    borderRadius: uiColors.controlRadius,
    paddingRight: 14,
    paddingLeft: 14,
    backgroundColor: {
      'default': uiColors.surfaceTranslucent,
      ':hover': uiColors.controlHover,
      ':active': uiColors.controlPressed,
    },
    color: uiColors.text,
    fontSize: 13,
    fontWeight: 550,
    boxShadow: uiColors.controlShadow,
  },
  menu: {
    minHeight: 38,
    width: '100%',
    justifyContent: 'flex-start',
    borderColor: 'transparent',
    borderRadius: uiColors.controlRadius,
    paddingTop: 5,
    paddingRight: 8,
    paddingBottom: 5,
    paddingLeft: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': uiColors.controlHover,
      ':active': uiColors.controlPressed,
    },
    color: uiColors.text,
    fontSize: 13,
    fontWeight: 400,
  },
  icon: {
    minWidth: 36,
    minHeight: 36,
    borderColor: 'transparent',
    borderWidth: 0,
    borderRadius: uiColors.controlRadius,
    padding: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': uiColors.controlHover,
      ':active': uiColors.controlPressed,
    },
    color: uiColors.text,
    fontSize: 14,
    fontWeight: 500,
  },
  pressed: {
    backgroundColor: uiColors.controlPressed,
  },
  danger: {
    minHeight: 36,
    borderColor: 'transparent',
    borderRadius: uiColors.controlRadius,
    paddingRight: 14,
    paddingLeft: 14,
    backgroundColor: {
      'default': uiColors.danger,
      ':hover': `color-mix(in srgb, ${uiColors.danger} 88%, black)`,
      ':active': `color-mix(in srgb, ${uiColors.danger} 78%, black)`,
    },
    color: uiColors.onAccent,
    fontSize: 13,
    fontWeight: 600,
  },
})
