import * as stylex from '@stylexjs/stylex'
import { uiColors, uiMotion } from '../theme.stylex'

export const dialogStyles = stylex.create({
  overlay: {
    position: 'fixed',
    zIndex: 100,
    inset: 0,
    display: 'grid',
    placeItems: 'center',
    padding: 24,
  },
  defaultOverlay: {
    backgroundColor: {
      'default': uiColors.overlay,
      '@media (prefers-reduced-transparency: reduce)': 'rgba(28, 31, 38, 0.28)',
    },
    backdropFilter: {
      'default': 'saturate(115%) brightness(0.98)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
  },
  noteOverlay: {
    position: 'fixed',
    zIndex: 60,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    display: 'grid',
    alignItems: 'center',
    justifyItems: 'center',
    padding: 24,
    backgroundColor: uiColors.overlay,
    backdropFilter: uiColors.materialFilter,
  },
  sheetOverlay: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    borderWidth: 0,
    padding: 0,
    backgroundColor: uiColors.overlay,
  },
  content: {
    position: 'fixed',
    zIndex: 101,
    top: '50%',
    left: '50%',
    display: 'flex',
    width: 'min(410px, calc(100vw - 40px))',
    maxHeight: 'calc(100vh - 48px)',
    overflow: 'hidden',
    flexDirection: 'column',
    borderColor: {
      'default': uiColors.fieldBorder,
      '@media (prefers-contrast: more)': 'rgba(46, 51, 59, 0.5)',
    },
    borderStyle: 'solid',
    borderWidth: uiColors.surfaceStroke,
    borderRadius: uiColors.surfaceRadius,
    backgroundColor: {
      'default': uiColors.surfaceTranslucent,
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 250, 251)',
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    backdropFilter: {
      'default': uiColors.materialFilter,
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: uiColors.overlayShadow,
    color: uiColors.text,
    outline: 'none',
    translate: '-50% -50%',
    transformOrigin: '50% 35%',
    transitionDuration: uiMotion.duration,
    transitionProperty: 'opacity, transform',
    transitionTimingFunction: uiMotion.easing,
  },
  alertContent: {
    display: 'flex',
    width: 'min(390px, calc(100vw - 48px))',
    alignItems: 'center',
    flexDirection: 'column',
    borderColor: uiColors.fieldBorder,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: uiColors.surfaceRadius,
    paddingTop: 25,
    paddingRight: 25,
    paddingBottom: 22,
    paddingLeft: 25,
    backgroundColor: {
      'default': uiColors.surfaceTranslucent,
      '@media (prefers-reduced-transparency: reduce)': 'rgb(249, 249, 250)',
    },
    backdropFilter: {
      'default': uiColors.materialFilter,
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: uiColors.overlayShadow,
    textAlign: 'center',
  },
  commandContent: {
    borderColor: uiColors.fieldBorder,
    borderStyle: 'solid',
    borderWidth: uiColors.surfaceStroke,
    borderRadius: uiColors.surfaceRadius,
    backgroundColor: {
      'default': uiColors.surfaceTranslucent,
      '@media (prefers-reduced-transparency: reduce)': 'rgb(248, 248, 249)',
      '@media (prefers-contrast: more)': 'rgb(252, 252, 253)',
    },
    backdropFilter: {
      'default': uiColors.materialFilter,
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: uiColors.overlayShadow,
  },
  compactContent: {
    borderColor: 'rgba(50, 55, 64, 0.18)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: uiColors.surfaceRadius,
    backgroundColor: {
      'default': uiColors.surfaceRaised,
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 251, 253)',
    },
    boxShadow: uiColors.overlayShadow,
  },
  wideContent: {
    borderColor: 'rgba(50, 55, 64, 0.18)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: uiColors.surfaceRadius,
    backgroundColor: {
      'default': uiColors.surfaceRaised,
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 251, 253)',
    },
    boxShadow: uiColors.overlayShadow,
  },
  sheetContent: {
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.78)',
      '@media (prefers-contrast: more)': 'rgba(33, 37, 44, 0.64)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: uiColors.surfaceRadius,
    backgroundColor: {
      'default': uiColors.surfaceTranslucent,
      '@media (prefers-contrast: more)': 'rgba(249, 249, 250, 0.96)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(249, 249, 250)',
    },
    backdropFilter: {
      'default': uiColors.materialFilter,
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: uiColors.overlayShadow,
  },
  customContent: {
    position: 'static',
    top: 'auto',
    left: 'auto',
    width: 'auto',
    maxHeight: 'none',
    transform: 'none',
    translate: 'none',
  },
  header: {
    display: 'flex',
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingRight: 14,
    paddingLeft: 18,
  },
  title: {
    margin: 0,
    color: uiColors.text,
    fontSize: 14,
    fontWeight: 660,
    lineHeight: '20px',
  },
  description: {
    margin: 0,
    color: uiColors.textMuted,
    fontSize: 12,
    lineHeight: '18px',
  },
  body: {
    display: 'flex',
    minHeight: 0,
    flexDirection: 'column',
    gap: 13,
    overflowY: 'auto',
    paddingTop: 2,
    paddingRight: 18,
    paddingBottom: 18,
    paddingLeft: 18,
  },
  footer: {
    display: 'flex',
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 7,
    borderTopColor: uiColors.divider,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingRight: 14,
    paddingLeft: 14,
    backgroundColor: uiColors.surfaceSunken,
  },
  close: {
    display: 'grid',
    width: 26,
    height: 26,
    flex: '0 0 26px',
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: uiColors.controlRadius,
    padding: 0,
    backgroundColor: {
      'default': 'rgba(67, 72, 81, 0.07)',
      ':hover': 'rgba(67, 72, 81, 0.12)',
      ':active': 'rgba(67, 72, 81, 0.17)',
    },
    color: uiColors.textMuted,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${uiColors.focus}`,
    },
  },
})
