import * as stylex from '@stylexjs/stylex'
import { uiColors, uiMotion } from '../theme.stylex'

export const editableTitleStyles = stylex.create({
  trigger: {
    display: 'flex',
    minWidth: 0,
    maxWidth: '100%',
    height: 32,
    alignItems: 'center',
    gap: 6,
    borderWidth: 0,
    borderRadius: uiColors.controlRadius,
    paddingRight: 8,
    paddingLeft: 10,
    backgroundColor: {
      'default': 'transparent',
      ':hover': uiColors.controlHover,
      ':active': uiColors.controlPressed,
    },
    color: uiColors.text,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${uiColors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.985)',
    },
    transitionDuration: uiMotion.duration,
    transitionProperty: 'background-color, transform, box-shadow',
    transitionTimingFunction: uiMotion.easing,
  },
  text: {
    overflow: 'hidden',
    minWidth: 0,
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  icon: {
    width: 12,
    height: 12,
    flex: '0 0 12px',
    color: 'rgba(48, 46, 51, 0.42)',
  },
  input: {
    width: 'clamp(160px, 28vw, 320px)',
    height: 34,
    borderColor: {
      'default': uiColors.fieldBorder,
      ':focus': uiColors.focus,
      ':invalid': 'rgba(184, 62, 62, 0.74)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: uiColors.controlRadius,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: {
      'default': uiColors.fieldBackground,
      '@media (prefers-reduced-transparency: reduce)': 'rgb(255, 255, 255)',
    },
    backdropFilter: {
      'default': uiColors.materialFilter,
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    color: uiColors.text,
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '18px',
    outline: 'none',
    boxShadow: {
      'default': uiColors.controlShadow,
      ':focus': `0 0 0 2px ${uiColors.focus}`,
    },
    textAlign: 'center',
  },
  error: {
    position: 'absolute',
    width: 1,
    height: 1,
    overflow: 'hidden',
    margin: -1,
    borderWidth: 0,
    padding: 0,
    clip: 'rect(0, 0, 0, 0)',
    clipPath: 'inset(50%)',
    whiteSpace: 'nowrap',
  },
})
