import * as stylex from '@stylexjs/stylex'
import { uiColors } from '../theme.stylex'

export const menuStyles = stylex.create({
  content: {
    position: 'fixed',
    zIndex: 100,
    boxSizing: 'border-box',
    display: 'flex',
    maxHeight: 'calc(100vh - 16px)',
    minHeight: 0,
    overflowY: 'auto',
    flexDirection: 'column',
    borderStyle: 'solid',
    borderWidth: 1,
    color: uiColors.text,
    outline: 'none',
    userSelect: 'none',
  },
  defaultContent: {
    minWidth: 180,
    borderColor: {
      'default': uiColors.fieldBorder,
      '@media (prefers-contrast: more)': uiColors.borderStrong,
    },
    borderRadius: uiColors.surfaceRadius,
    padding: 5,
    backgroundColor: {
      'default': uiColors.surfaceTranslucent,
      '@media (prefers-contrast: more)': uiColors.surfaceOpaque,
      '@media (prefers-reduced-transparency: reduce)': uiColors.surfaceOpaque,
    },
    backdropFilter: {
      'default': uiColors.materialFilter,
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: uiColors.overlayShadow,
    transformOrigin: 'top left',
  },
  contextContent: {
    width: 232,
    borderColor: uiColors.fieldBorder,
    borderRadius: uiColors.controlRadius,
    padding: 5,
    backgroundColor: uiColors.surfaceRaised,
    boxShadow: uiColors.overlayShadow,
    color: uiColors.text,
    fontSize: 13,
  },
  editorContent: {
    borderColor: uiColors.fieldBorder,
    borderRadius: uiColors.controlRadius,
    padding: 4,
    backgroundColor: uiColors.surfaceRaised,
    boxShadow: uiColors.overlayShadow,
  },
  noteContent: {
    borderColor: uiColors.fieldBorder,
    borderRadius: uiColors.controlRadius,
    padding: 4,
    backgroundColor: {
      'default': uiColors.surfaceRaised,
      '@media (prefers-reduced-transparency: reduce)': uiColors.surfaceOpaque,
    },
    backdropFilter: {
      'default': uiColors.materialFilter,
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: uiColors.overlayShadow,
  },
  item: {
    display: 'flex',
    width: '100%',
    minHeight: 32,
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 9,
    borderWidth: 0,
    borderRadius: uiColors.controlRadius,
    paddingTop: 6,
    paddingRight: 8,
    paddingBottom: 6,
    paddingLeft: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': uiColors.controlHover,
      ':active': uiColors.controlPressed,
      ':focus-visible': uiColors.controlHover,
      ':is([data-state="checked"])': uiColors.accentSoft,
    },
    color: {
      'default': uiColors.text,
      ':disabled': uiColors.textQuiet,
      ':is([data-state="checked"])': uiColors.accent,
    },
    cursor: 'default',
    fontSize: 13,
    outline: 'none',
    textAlign: 'left',
  },
  separator: {
    height: 1,
    flex: '0 0 1px',
    marginTop: 4,
    marginRight: 7,
    marginBottom: 4,
    marginLeft: 7,
    backgroundColor: uiColors.divider,
  },
})
