import * as stylex from '@stylexjs/stylex'
import { uiColors, uiMotion } from '../theme.stylex'

const sharedSidebarSurface = {
  position: 'relative',
  zIndex: 2,
  display: 'flex',
  minWidth: 0,
  minHeight: 0,
  overflow: 'hidden',
  flexDirection: 'column',
  marginTop: uiColors.sidebarInsetBlock,
  marginBottom: uiColors.sidebarInsetBlock,
  marginLeft: uiColors.sidebarInsetInlineStart,
  borderColor: {
    'default': uiColors.fieldBorder,
    '@media (prefers-contrast: more)': 'rgba(0, 0, 0, 0.42)',
  },
  borderStyle: 'solid',
  borderTopWidth: uiColors.sidebarBorderTopWidth,
  borderRightWidth: uiColors.sidebarBorderRightWidth,
  borderBottomWidth: uiColors.sidebarBorderBottomWidth,
  borderLeftWidth: uiColors.sidebarBorderLeftWidth,
  borderRadius: uiColors.sidebarRadius,
  backgroundColor: {
    'default': uiColors.sidebarBackground,
    '@media (prefers-reduced-transparency: reduce)': 'rgb(255, 255, 255)',
    '@media (prefers-contrast: more)': 'rgba(248, 249, 251, 0.96)',
  },
  backdropFilter: {
    'default': uiColors.materialFilter,
    '@media (prefers-reduced-transparency: reduce)': 'none',
  },
  boxShadow: uiColors.sidebarShadow,
} as const

export const sidebarStyles = stylex.create({
  root: sharedSidebarSurface,
  workspaceRoot: {},
  settingsRoot: {
    width: 204,
    borderColor: uiColors.fieldBorder,
    backgroundColor: uiColors.sidebarBackground,
  },
  workspaceHeader: {
    marginTop: 0,
    marginRight: 8,
    marginBottom: 6,
    marginLeft: 8,
    color: uiColors.textMuted,
    fontSize: 11,
    fontWeight: 600,
    lineHeight: '20px',
  },
  settingsHeader: {
    display: 'flex',
    height: 72,
    alignItems: 'flex-end',
    paddingRight: 18,
    paddingBottom: 13,
    paddingLeft: 18,
    color: uiColors.textMuted,
    fontSize: 12,
    fontWeight: 650,
    lineHeight: '18px',
  },
  workspaceNavigation: {
    minHeight: 0,
    overflowY: 'auto',
    paddingTop: 64,
    paddingRight: 10,
    paddingBottom: 20,
    paddingLeft: 10,
  },
  settingsNavigation: {
    display: 'flex',
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    gap: 3,
    paddingRight: 10,
    paddingLeft: 10,
  },
  group: {
    marginBottom: 17,
  },
  item: {
    width: '100%',
    minWidth: 0,
    alignItems: 'center',
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderLeftWidth: 'var(--ui-nav-selected-indicator-width, 0px)',
    backgroundColor: 'transparent',
    color: uiColors.text,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
    textDecoration: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${uiColors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.985)',
    },
    transitionDuration: uiMotion.duration,
    transitionProperty: 'background-color, border-color, color, transform, box-shadow',
    transitionTimingFunction: uiMotion.easing,
  },
  workspaceItem: {
    display: 'grid',
    height: 31,
    gridTemplateColumns: '20px minmax(0, 1fr)',
    gap: 7,
    borderRadius: uiColors.controlRadius,
    paddingRight: 9,
    paddingLeft: 8,
    backgroundColor: {
      'default': 'transparent',
      ':not([data-state="active"]):hover': uiColors.controlHover,
      ':not([data-state="active"]):active': uiColors.controlPressed,
      ':is([data-state="active"])': uiColors.navSelectedBackground,
      ':is([data-state="active"]):hover': uiColors.controlSelectedHover,
      ':is([data-state="active"]):active': uiColors.controlSelectedPressed,
    },
    borderLeftColor: {
      'default': 'transparent',
      ':is([data-state="active"])': uiColors.navSelectedIndicator,
    },
    borderColor: {
      'default': 'transparent',
      ':is([data-state="active"])': uiColors.navSelectedIndicator,
    },
    color: {
      'default': uiColors.text,
      ':is([data-state="active"])': uiColors.controlSelectedText,
    },
    fontWeight: {
      'default': 400,
      ':is([data-state="active"])': 550,
    },
    fontSize: 13,
    lineHeight: '18px',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${uiColors.focus}`,
      ':is([data-state="active"])': uiColors.controlShadow,
    },
  },
  settingsItem: {
    display: 'flex',
    minHeight: 34,
    gap: 10,
    borderRadius: uiColors.controlRadius,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: {
      'default': 'transparent',
      ':hover': uiColors.controlHover,
      ':active': uiColors.controlPressed,
      ':is([data-state="active"])': uiColors.navSelectedBackground,
      ':is([data-state="active"]):hover': uiColors.controlSelectedHover,
      ':is([data-state="active"]):active': uiColors.controlSelectedPressed,
    },
    borderColor: {
      'default': 'transparent',
      ':is([data-state="active"])': uiColors.navSelectedIndicator,
    },
    color: {
      'default': uiColors.text,
      ':is([data-state="active"])': uiColors.controlSelectedText,
    },
    fontWeight: {
      'default': 500,
      ':is([data-state="active"])': 600,
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${uiColors.focus}`,
      ':is([data-state="active"])': uiColors.controlShadow,
    },
    fontSize: 13,
    lineHeight: '18px',
  },
  icon: {
    display: 'grid',
    flex: '0 0 auto',
    placeItems: 'center',
    color: uiColors.textMuted,
  },
  workspaceIcon: {
    width: 17,
    height: 17,
    justifySelf: 'center',
  },
  settingsIcon: {
    flex: '0 0 auto',
  },
  iconActiveWorkspace: {
    color: uiColors.controlSelectedText,
  },
  iconActiveSettings: {
    color: uiColors.controlSelectedText,
  },
  label: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  workspaceLabel: {},
  settingsLabel: {},
  labelActiveWorkspace: {
    color: uiColors.controlSelectedText,
  },
  labelActiveSettings: {
    color: uiColors.controlSelectedText,
  },
})
