// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Return the UUID of the root folder.
 * 
 * This returns a static string slice representing the application's root
 * folder UUID.
 */
async getRootFolderUuid() : Promise<string> {
    return await TAURI_INVOKE("get_root_folder_uuid");
},
/**
 * Check whether a folder node exists by UUID.
 * 
 * Arguments:
 * - `state`: Shared database state provided by Tauri.
 * - `uuid`: The UUID of the folder node to check.
 * 
 * Returns `Ok(true)` if the folder node exists, `Ok(false)` if not,
 * or an error on failure.
 */
async isFolderNodeExist(uuid: string) : Promise<Result<boolean, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_folder_node_exist", { uuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieve a folder node by UUID.
 * 
 * Arguments:
 * - `state`: Shared database state provided by Tauri.
 * - `uuid`: The UUID of the folder node to retrieve.
 * 
 * Returns the `FolderNode` on success or an error if not found.
 */
async getFolderNode(uuid: string) : Promise<Result<FolderNode, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_folder_node", { uuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get immediate children of a folder node.
 * 
 * Arguments:
 * - `state`: Shared database state provided by Tauri.
 * - `parent_uuid`: UUID of the parent folder node.
 * 
 * Returns a vector of `FolderNode` representing the children.
 */
async getFolderNodeChildren(parentUuid: string) : Promise<Result<FolderNode[], Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_folder_node_children", { parentUuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new folder node.
 * 
 * Arguments:
 * - `state`: Shared database state provided by Tauri.
 * - `parent_uuid`: UUID of the parent folder under which to create the node.
 * - `uuid`: UUID for the new folder node.
 * - `typ`: The `FolderNodeType` describing the node type.
 * - `name`: Display name for the folder node.
 * - `reference`: Optional reference string associated with the node.
 * 
 * Returns `Ok(())` on success or an error on failure.
 */
async createFolderNode(parentUuid: string, uuid: string, typ: FolderNodeType, name: string, reference: string | null) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_folder_node", { parentUuid, uuid, typ, name, reference }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename an existing folder node.
 * 
 * Arguments:
 * - `state`: Shared database state provided by Tauri.
 * - `uuid`: UUID of the folder node to rename.
 * - `new_name`: The new display name for the node.
 * 
 * Returns `Ok(())` on success or an error on failure.
 */
async renameFolderNode(uuid: string, newName: string) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_folder_node", { uuid, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a folder node and return its parent's UUID.
 * 
 * Arguments:
 * - `state`: Shared database state provided by Tauri.
 * - `uuid`: UUID of the folder node to delete.
 * 
 * Returns `Ok(Some(parent_uuid))` if the deleted node had a parent,
 * `Ok(None)` if it had no parent, or an error on failure.
 */
async deleteFolderNodeRetParent(uuid: string) : Promise<Result<string | null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_folder_node_ret_parent", { uuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the parent folder node UUID for a given child UUID.
 * 
 * Arguments:
 * - `state`: Shared database state provided by Tauri.
 * - `child_uuid`: UUID of the child node to query.
 * 
 * Returns `Ok(Some(parent_uuid))` if the parent exists, `Ok(None)` if the
 * node has no parent, or an error on failure.
 */
async getParentFolderNodeUuid(childUuid: string) : Promise<Result<string | null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_parent_folder_node_uuid", { childUuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readSettings() : Promise<Result<string, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSettings(content: string) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_settings", { content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSettings() : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Error = { _tag: ErrorKind; message: string; inner_message: string }
export type ErrorKind = "DatabaseError" | "IoError" | "SerializationError"
/**
 * Represents a folder node with all its properties.
 */
export type FolderNode = { uuid: string; typ: FolderNodeType; name: string; ref: string | null; createdAt: string; childrenUpdatedAt: string; hasChildren: boolean }
/**
 * Represents the type of a folder node in the hierarchy.
 */
export type FolderNodeType = "Folder" | "Topic" | "Highlight" | "Item"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
