import * as stylex from '@stylexjs/stylex'

const colors = {
  ink: 'rgb(26 31 38 / 94%)',
  muted: 'rgb(76 85 96 / 65%)',
  faint: 'rgb(86 96 109 / 42%)',
  line: 'rgb(65 78 94 / 12%)',
  gridLine: 'rgb(64 77 94 / 13%)',
  canvas: 'rgb(248 249 251)',
  canvasDeep: 'rgb(241 243 246)',
  blue: 'rgb(0 113 227)',
  blueSoft: 'rgb(0 113 227 / 10%)',
} as const

const glassShadow = '0 9px 24px -18px rgb(22 35 52 / 46%), 0 2px 7px rgb(22 35 52 / 9%), 0 0 0 0.5px rgb(37 53 72 / 14%), inset 0 1px rgb(255 255 255 / 84%), inset 0 -1px rgb(64 79 98 / 9%)'

export const spreadsheetStyles = stylex.create({
  root: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 320,
    overflow: 'hidden',
    flexDirection: 'column',
    backgroundColor: colors.canvas,
    color: colors.ink,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
    fontSize: 12,
  },
  gridScroller: {
    position: 'absolute',
    inset: 0,
    overflow: 'auto',
    overscrollBehavior: 'contain',
    paddingTop: {
      'default': 94,
      '@media (max-width: 560px)': 90,
    },
    paddingBottom: 54,
    backgroundColor: colors.canvas,
  },
  grid: {
    display: 'grid',
    width: 'max-content',
    minWidth: '100%',
    gridAutoRows: 30,
    borderTopColor: colors.gridLine,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    borderLeftColor: colors.gridLine,
    borderLeftStyle: 'solid',
    borderLeftWidth: 1,
    backgroundColor: 'white',
  },
  cornerCell: {
    position: 'sticky',
    zIndex: 2,
    top: 0,
    left: 0,
    width: 40,
    height: 30,
    borderRightColor: colors.gridLine,
    borderRightStyle: 'solid',
    borderRightWidth: 1,
    borderBottomColor: colors.gridLine,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    backgroundColor: colors.canvasDeep,
  },
  columnHeader: {
    position: 'sticky',
    zIndex: 1,
    top: 0,
    display: 'flex',
    width: 100,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightColor: colors.gridLine,
    borderRightStyle: 'solid',
    borderRightWidth: 1,
    borderBottomColor: colors.gridLine,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    backgroundColor: colors.canvasDeep,
    color: colors.muted,
    fontSize: 11,
    fontWeight: 650,
    letterSpacing: 0,
    userSelect: 'none',
  },
  rowHeader: {
    position: 'sticky',
    zIndex: 1,
    left: 0,
    display: 'flex',
    width: 40,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightColor: colors.gridLine,
    borderRightStyle: 'solid',
    borderRightWidth: 1,
    borderBottomColor: colors.gridLine,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    backgroundColor: colors.canvasDeep,
    color: colors.muted,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    userSelect: 'none',
  },
  cell: {
    position: 'relative',
    display: 'flex',
    width: 100,
    height: 30,
    alignItems: 'center',
    overflow: 'hidden',
    borderRightColor: colors.gridLine,
    borderRightStyle: 'solid',
    borderRightWidth: 1,
    borderBottomColor: colors.gridLine,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingRight: 8,
    paddingLeft: 8,
    backgroundColor: 'white',
    color: colors.ink,
    fontSize: 12,
    lineHeight: '18px',
    outline: 'none',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    userSelect: 'none',
  },
  cellSelected: {
    zIndex: 1,
    boxShadow: `inset 0 0 0 2px ${colors.blue}`,
    backgroundColor: 'rgb(239 247 255)',
  },
  cellBold: {
    fontWeight: 700,
  },
  cellItalic: {
    fontStyle: 'italic',
  },
  cellUnderline: {
    textDecorationLine: 'underline',
  },
  cellAlignLeft: {
    justifyContent: 'flex-start',
  },
  cellAlignCenter: {
    justifyContent: 'center',
  },
  cellAlignRight: {
    justifyContent: 'flex-end',
  },
  columnHeaderSelected: {
    backgroundColor: 'rgb(229 240 253)',
    color: colors.blue,
  },
  rowHeaderSelected: {
    backgroundColor: 'rgb(229 240 253)',
    color: colors.blue,
    fontWeight: 650,
  },
  cellCurrency: {
    justifyContent: 'flex-end',
    fontVariantNumeric: 'tabular-nums',
  },
  cellNumber: {
    justifyContent: 'flex-end',
    fontVariantNumeric: 'tabular-nums',
  },
  cellEditor: {
    width: '100%',
    minWidth: 0,
    borderWidth: 0,
    padding: 0,
    backgroundColor: 'transparent',
    color: 'inherit',
    font: 'inherit',
    lineHeight: 'inherit',
    outline: 'none',
  },
  topControlLayer: {
    position: 'absolute',
    zIndex: 4,
    top: {
      'default': 10,
      '@media (max-width: 560px)': 10,
    },
    right: {
      'default': 14,
      '@media (max-width: 560px)': 10,
    },
    left: {
      'default': 14,
      '@media (max-width: 560px)': 10,
    },
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: {
      'default': 6,
      '@media (max-width: 560px)': 5,
    },
    pointerEvents: 'none',
  },
  bottomControlLayer: {
    position: 'absolute',
    zIndex: 4,
    right: {
      'default': 14,
      '@media (max-width: 560px)': 10,
    },
    bottom: {
      'default': 10,
      '@media (max-width: 560px)': 10,
    },
    left: {
      'default': 14,
      '@media (max-width: 560px)': 10,
    },
    display: 'flex',
    justifyContent: 'flex-start',
    pointerEvents: 'none',
  },
  glassMaterial: {
    borderColor: {
      'default': 'rgb(255 255 255 / 72%)',
      '@media (prefers-contrast: more)': 'rgb(28 40 55 / 45%)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    backgroundColor: {
      'default': 'rgb(248 250 253 / 58%)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(248 250 253)',
      '@media (prefers-contrast: more)': 'rgb(248 250 253)',
    },
    backgroundImage: 'linear-gradient(145deg, rgb(255 255 255 / 58%), rgb(255 255 255 / 6%) 46%, rgb(171 188 209 / 10%))',
    backdropFilter: {
      'default': 'blur(18px) saturate(175%) brightness(1.03)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': glassShadow,
      '@media (prefers-contrast: more)': '0 4px 12px rgb(22 27 35 / 18%), 0 0 0 1px rgb(28 40 55 / 48%), inset 0 1px rgb(255 255 255 / 92%)',
    },
  },
  toolbarIsland: {
    display: 'flex',
    width: 'max-content',
    maxWidth: '100%',
    height: 36,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    gap: {
      'default': 3,
      '@media (max-width: 560px)': 2,
    },
    borderRadius: 18,
    paddingRight: {
      'default': 3,
      '@media (max-width: 560px)': 3,
    },
    paddingLeft: {
      'default': 3,
      '@media (max-width: 560px)': 3,
    },
    pointerEvents: 'auto',
  },
  toolbarGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: {
      'default': 1,
      '@media (max-width: 560px)': 0,
    },
  },
  segmentedGroup: {
    borderRadius: 10,
    backgroundColor: 'rgb(74 88 107 / 5%)',
    padding: 1,
  },
  toolbarDivider: {
    width: 1,
    height: 20,
    marginRight: {
      'default': 2,
      '@media (max-width: 560px)': 1,
    },
    marginLeft: {
      'default': 2,
      '@media (max-width: 560px)': 1,
    },
    backgroundColor: colors.line,
  },
  iconButton: {
    position: 'relative',
    display: 'grid',
    width: {
      'default': 30,
      '@media (max-width: 560px)': 30,
    },
    height: 30,
    flexShrink: 0,
    placeItems: 'center',
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgb(255 255 255 / 64%)',
      ':active': 'rgb(216 227 241 / 62%)',
      ':disabled': 'transparent',
    },
    color: {
      'default': colors.ink,
      ':disabled': colors.faint,
    },
    cursor: {
      'default': 'pointer',
      ':disabled': 'not-allowed',
    },
    outline: 'none',
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, border-color, transform',
    transitionTimingFunction: 'ease-out',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgb(0 113 227 / 22%)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
  },
  iconButtonPressed: {
    backgroundColor: colors.blueSoft,
    color: colors.blue,
  },
  formulaIsland: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    height: 34,
    flexShrink: 0,
    alignItems: 'center',
    gap: {
      'default': 7,
      '@media (max-width: 560px)': 6,
    },
    borderRadius: 11,
    paddingRight: {
      'default': 7,
      '@media (max-width: 560px)': 7,
    },
    paddingLeft: {
      'default': 7,
      '@media (max-width: 560px)': 7,
    },
    pointerEvents: 'auto',
  },
  formulaMaterial: {
    backgroundColor: {
      'default': 'rgb(248 250 253 / 50%)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(248 250 253)',
    },
    boxShadow: '0 5px 16px -12px rgb(22 35 52 / 38%), 0 1px 5px rgb(22 35 52 / 7%), 0 0 0 0.5px rgb(37 53 72 / 12%), inset 0 1px rgb(255 255 255 / 76%)',
  },
  cellAddress: {
    display: 'inline-flex',
    width: 38,
    flexShrink: 0,
    justifyContent: 'center',
    borderRadius: 5,
    paddingTop: 2,
    paddingBottom: 2,
    backgroundColor: 'rgb(86 96 109 / 6%)',
    color: colors.muted,
    fontSize: 10,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 680,
    letterSpacing: 0,
  },
  formulaDivider: {
    width: 1,
    height: 16,
    backgroundColor: colors.line,
  },
  formulaIcon: {
    flexShrink: 0,
    color: colors.blue,
    fontFamily: 'Georgia, serif',
    fontSize: 13,
    fontStyle: 'italic',
    fontWeight: 700,
  },
  formulaInput: {
    width: '100%',
    height: 28,
    minWidth: 0,
    borderWidth: 0,
    borderRadius: 6,
    paddingRight: 6,
    paddingLeft: 6,
    backgroundColor: {
      'default': 'transparent',
      ':focus': 'rgb(255 255 255 / 44%)',
    },
    color: colors.ink,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 11,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': 'inset 0 0 0 1px rgb(0 113 227 / 22%)',
    },
  },
  sheetIsland: {
    display: 'flex',
    maxWidth: '100%',
    height: 36,
    alignItems: 'center',
    borderRadius: 12,
    paddingRight: 4,
    paddingLeft: 4,
    pointerEvents: 'auto',
  },
  addSheetButton: {
    display: 'grid',
    width: 28,
    height: 28,
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgb(255 255 255 / 70%)',
    },
    color: {
      'default': colors.muted,
      ':hover': colors.ink,
    },
    cursor: 'pointer',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgb(0 113 227 / 22%)',
    },
  },
  sheetDivider: {
    width: 1,
    height: 20,
    marginRight: 5,
    marginLeft: 5,
    backgroundColor: colors.line,
  },
  sheetTabs: {
    display: 'flex',
    maxWidth: 'calc(100vw - 120px)',
    alignItems: 'center',
    gap: 2,
    overflowX: 'auto',
    scrollbarWidth: 'none',
  },
  sheetTab: {
    height: 28,
    flexShrink: 0,
    borderWidth: 0,
    borderRadius: 8,
    paddingRight: 11,
    paddingLeft: 11,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgb(255 255 255 / 62%)',
    },
    color: {
      'default': colors.muted,
      ':hover': colors.ink,
    },
    cursor: 'pointer',
    fontSize: 10,
    fontWeight: 620,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgb(0 113 227 / 22%)',
    },
  },
  sheetTabActive: {
    backgroundColor: 'rgb(255 255 255 / 78%)',
    boxShadow: '0 1px 5px rgb(30 44 62 / 10%), inset 0 1px rgb(255 255 255 / 86%)',
    color: colors.ink,
  },
})
