import * as stylex from '@stylexjs/stylex'

const colors = {
  ink: 'rgb(26 31 38 / 94%)',
  muted: 'rgb(76 85 96 / 65%)',
  faint: 'rgb(86 96 109 / 42%)',
  line: 'rgb(65 78 94 / 12%)',
  gridLine: 'rgb(64 77 94 / 13%)',
  canvas: 'rgb(248 249 251)',
  canvasDeep: 'rgb(241 243 246)',
  blue: 'rgb(0 113 227)',
  blueSoft: 'rgb(0 113 227 / 10%)',
} as const

const glassShadow = '0 14px 35px -24px rgb(22 35 52 / 52%), 0 3px 9px rgb(22 35 52 / 10%), 0 0 0 0.5px rgb(37 53 72 / 15%), inset 0 1px rgb(255 255 255 / 88%), inset 0 -1px rgb(64 79 98 / 10%)'

export const spreadsheetStyles = stylex.create({
  root: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 420,
    overflow: 'hidden',
    flexDirection: 'column',
    backgroundColor: colors.canvas,
    color: colors.ink,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
    fontSize: 12,
  },
  gridScroller: {
    position: 'absolute',
    inset: 0,
    overflow: 'auto',
    overscrollBehavior: 'contain',
    paddingTop: {
      'default': 110,
      '@media (max-width: 560px)': 101,
    },
    paddingBottom: 62,
    backgroundColor: colors.canvas,
  },
  grid: {
    display: 'grid',
    width: 'max-content',
    minWidth: '100%',
    gridAutoRows: 34,
    borderTopColor: colors.gridLine,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    borderLeftColor: colors.gridLine,
    borderLeftStyle: 'solid',
    borderLeftWidth: 1,
    backgroundColor: 'white',
  },
  cornerCell: {
    position: 'sticky',
    zIndex: 2,
    top: 0,
    left: 0,
    width: 44,
    height: 34,
    borderRightColor: colors.gridLine,
    borderRightStyle: 'solid',
    borderRightWidth: 1,
    borderBottomColor: colors.gridLine,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    backgroundColor: colors.canvasDeep,
  },
  columnHeader: {
    position: 'sticky',
    zIndex: 1,
    top: 0,
    display: 'flex',
    width: 112,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightColor: colors.gridLine,
    borderRightStyle: 'solid',
    borderRightWidth: 1,
    borderBottomColor: colors.gridLine,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    backgroundColor: colors.canvasDeep,
    color: colors.muted,
    fontSize: 10,
    fontWeight: 650,
    letterSpacing: '0.04em',
    userSelect: 'none',
  },
  rowHeader: {
    position: 'sticky',
    zIndex: 1,
    left: 0,
    display: 'flex',
    width: 44,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightColor: colors.gridLine,
    borderRightStyle: 'solid',
    borderRightWidth: 1,
    borderBottomColor: colors.gridLine,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    backgroundColor: colors.canvasDeep,
    color: colors.muted,
    fontSize: 10,
    fontVariantNumeric: 'tabular-nums',
    userSelect: 'none',
  },
  cell: {
    position: 'relative',
    display: 'flex',
    width: 112,
    height: 34,
    alignItems: 'center',
    overflow: 'hidden',
    borderRightColor: colors.gridLine,
    borderRightStyle: 'solid',
    borderRightWidth: 1,
    borderBottomColor: colors.gridLine,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: 'white',
    color: colors.ink,
    fontSize: 12,
    lineHeight: '18px',
    outline: 'none',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    userSelect: 'none',
  },
  cellSelected: {
    zIndex: 1,
    boxShadow: `inset 0 0 0 2px ${colors.blue}`,
    backgroundColor: 'rgb(239 247 255)',
  },
  cellCurrency: {
    justifyContent: 'flex-end',
    fontVariantNumeric: 'tabular-nums',
  },
  cellNumber: {
    justifyContent: 'flex-end',
    fontVariantNumeric: 'tabular-nums',
  },
  cellEditor: {
    width: '100%',
    minWidth: 0,
    borderWidth: 0,
    padding: 0,
    backgroundColor: 'transparent',
    color: 'inherit',
    font: 'inherit',
    lineHeight: 'inherit',
    outline: 'none',
  },
  topControlLayer: {
    position: 'absolute',
    zIndex: 4,
    top: {
      'default': 14,
      '@media (max-width: 560px)': 10,
    },
    right: {
      'default': 18,
      '@media (max-width: 560px)': 10,
    },
    left: {
      'default': 18,
      '@media (max-width: 560px)': 10,
    },
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: {
      'default': 10,
      '@media (max-width: 560px)': 7,
    },
    pointerEvents: 'none',
  },
  bottomControlLayer: {
    position: 'absolute',
    zIndex: 4,
    right: {
      'default': 18,
      '@media (max-width: 560px)': 10,
    },
    bottom: {
      'default': 14,
      '@media (max-width: 560px)': 10,
    },
    left: {
      'default': 18,
      '@media (max-width: 560px)': 10,
    },
    display: 'flex',
    justifyContent: 'center',
    pointerEvents: 'none',
  },
  glassMaterial: {
    borderColor: {
      'default': 'rgb(255 255 255 / 72%)',
      '@media (prefers-contrast: more)': 'rgb(28 40 55 / 45%)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    backgroundColor: {
      'default': 'rgb(248 250 253 / 76%)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(248 250 253)',
      '@media (prefers-contrast: more)': 'rgb(248 250 253)',
    },
    backgroundImage: 'linear-gradient(145deg, rgb(255 255 255 / 62%), rgb(255 255 255 / 8%) 45%, rgb(185 198 214 / 12%))',
    backdropFilter: {
      'default': 'blur(22px) saturate(165%) brightness(1.03)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': glassShadow,
      '@media (prefers-contrast: more)': '0 4px 12px rgb(22 27 35 / 18%), 0 0 0 1px rgb(28 40 55 / 48%), inset 0 1px rgb(255 255 255 / 92%)',
    },
  },
  toolbarIsland: {
    display: 'flex',
    maxWidth: '100%',
    height: 42,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    gap: {
      'default': 5,
      '@media (max-width: 560px)': 1,
    },
    borderRadius: 15,
    paddingRight: {
      'default': 7,
      '@media (max-width: 560px)': 4,
    },
    paddingLeft: {
      'default': 7,
      '@media (max-width: 560px)': 4,
    },
    pointerEvents: 'auto',
  },
  toolbarGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: {
      'default': 2,
      '@media (max-width: 560px)': 0,
    },
  },
  wideToolbarGroup: {
    display: {
      'default': 'flex',
      '@media (max-width: 860px)': 'none',
    },
  },
  toolbarDivider: {
    width: 1,
    height: 20,
    marginRight: {
      'default': 2,
      '@media (max-width: 860px)': 0,
    },
    marginLeft: {
      'default': 2,
      '@media (max-width: 860px)': 0,
    },
    backgroundColor: colors.line,
  },
  compactToolbarHidden: {
    display: {
      'default': 'block',
      '@media (max-width: 560px)': 'none',
    },
  },
  iconButton: {
    position: 'relative',
    display: 'grid',
    width: {
      'default': 29,
      '@media (max-width: 560px)': 28,
    },
    height: 29,
    flexShrink: 0,
    placeItems: 'center',
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgb(255 255 255 / 64%)',
      ':active': 'rgb(216 227 241 / 62%)',
      ':disabled': 'transparent',
    },
    color: {
      'default': colors.ink,
      ':disabled': colors.faint,
    },
    cursor: {
      'default': 'pointer',
      ':disabled': 'not-allowed',
    },
    outline: 'none',
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, border-color, transform',
    transitionTimingFunction: 'ease-out',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgb(0 113 227 / 22%)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
  },
  iconButtonPressed: {
    backgroundColor: colors.blueSoft,
    color: colors.blue,
  },
  menuButton: {
    display: {
      'default': 'flex',
      '@media (max-width: 560px)': 'none',
    },
    height: 29,
    alignItems: 'center',
    gap: 4,
    borderWidth: 0,
    borderRadius: 8,
    paddingRight: 7,
    paddingLeft: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgb(255 255 255 / 64%)',
      ':disabled': 'transparent',
    },
    color: {
      'default': colors.ink,
      ':disabled': colors.faint,
    },
    cursor: {
      'default': 'pointer',
      ':disabled': 'not-allowed',
    },
    fontSize: 11,
    fontWeight: 570,
    outline: 'none',
  },
  numberButton: {
    display: {
      'default': 'block',
      '@media (max-width: 560px)': 'none',
    },
    width: 29,
    height: 29,
    borderWidth: 0,
    borderRadius: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgb(255 255 255 / 64%)',
      ':disabled': 'transparent',
    },
    color: {
      'default': colors.ink,
      ':disabled': colors.faint,
    },
    cursor: {
      'default': 'pointer',
      ':disabled': 'not-allowed',
    },
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    outline: 'none',
  },
  colorSwatch: {
    position: 'absolute',
    right: 6,
    bottom: 5,
    width: 10,
    height: 2,
    borderRadius: 2,
    backgroundColor: colors.blue,
  },
  moreButton: {
    display: {
      'default': 'none',
      '@media (max-width: 860px)': 'grid',
    },
  },
  formulaIsland: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    height: 42,
    flexShrink: 0,
    alignItems: 'center',
    gap: {
      'default': 9,
      '@media (max-width: 560px)': 7,
    },
    borderRadius: 13,
    paddingRight: {
      'default': 12,
      '@media (max-width: 560px)': 9,
    },
    paddingLeft: {
      'default': 12,
      '@media (max-width: 560px)': 9,
    },
    pointerEvents: 'auto',
  },
  cellAddress: {
    display: 'inline-flex',
    width: 40,
    flexShrink: 0,
    justifyContent: 'center',
    borderRadius: 6,
    paddingTop: 3,
    paddingBottom: 3,
    backgroundColor: 'rgb(86 96 109 / 8%)',
    color: colors.muted,
    fontSize: 10,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 680,
    letterSpacing: '0.04em',
  },
  formulaDivider: {
    width: 1,
    height: 18,
    backgroundColor: colors.line,
  },
  formulaIcon: {
    flexShrink: 0,
    color: colors.blue,
    fontFamily: 'Georgia, serif',
    fontSize: 15,
    fontStyle: 'italic',
    fontWeight: 700,
  },
  formulaInput: {
    width: '100%',
    minWidth: 0,
    borderWidth: 0,
    padding: 0,
    backgroundColor: 'transparent',
    color: colors.ink,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 11,
    outline: 'none',
  },
  sheetIsland: {
    display: 'flex',
    maxWidth: '100%',
    height: 40,
    alignItems: 'center',
    borderRadius: 14,
    paddingRight: 6,
    paddingLeft: 6,
    pointerEvents: 'auto',
  },
  addSheetButton: {
    display: 'grid',
    width: 28,
    height: 28,
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgb(255 255 255 / 70%)',
    },
    color: {
      'default': colors.muted,
      ':hover': colors.ink,
    },
    cursor: 'pointer',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgb(0 113 227 / 22%)',
    },
  },
  sheetDivider: {
    width: 1,
    height: 20,
    marginRight: 5,
    marginLeft: 5,
    backgroundColor: colors.line,
  },
  sheetTabs: {
    display: 'flex',
    maxWidth: 'calc(100vw - 120px)',
    alignItems: 'center',
    gap: 2,
    overflowX: 'auto',
    scrollbarWidth: 'none',
  },
  sheetTab: {
    height: 28,
    flexShrink: 0,
    borderWidth: 0,
    borderRadius: 8,
    paddingRight: 11,
    paddingLeft: 11,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgb(255 255 255 / 62%)',
    },
    color: {
      'default': colors.muted,
      ':hover': colors.ink,
    },
    cursor: 'pointer',
    fontSize: 10,
    fontWeight: 620,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgb(0 113 227 / 22%)',
    },
  },
  sheetTabActive: {
    backgroundColor: 'rgb(255 255 255 / 78%)',
    boxShadow: '0 1px 5px rgb(30 44 62 / 10%), inset 0 1px rgb(255 255 255 / 86%)',
    color: colors.ink,
  },
})
