import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'rgb(0, 113, 227)',
  focus: 'rgba(0, 96, 204, 0.44)',
  muted: 'rgba(45, 50, 58, 0.56)',
  text: 'rgba(23, 27, 33, 0.94)',
} as const

const controlShadow = '0 2px 6px rgba(31, 38, 48, 0.08), 0 0 0 0.5px rgba(55, 63, 74, 0.08), inset 0 1px rgba(255, 255, 255, 0.98), inset 0 -1px rgba(72, 79, 90, 0.07)'

export const learningReviewTitlebarStyles = stylex.create({
  sessionBar: {
    display: 'grid',
    width: '100%',
    height: 36,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '30px minmax(0, 1fr) auto',
    gap: 8,
    borderColor: 'rgba(255, 255, 255, 0.9)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 18,
    paddingTop: 2,
    paddingRight: 3,
    paddingBottom: 2,
    paddingLeft: 3,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.74)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 251, 252)',
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    backdropFilter: {
      'default': 'blur(22px) saturate(160%) contrast(1.02)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: controlShadow,
  },
  iconButton: {
    display: 'grid',
    width: 30,
    height: 30,
    flex: '0 0 30px',
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 7,
    padding: 0,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.42)',
      ':hover': 'rgba(255, 255, 255, 0.82)',
      ':active': 'rgba(231, 234, 238, 0.72)',
      ':disabled': 'rgba(255, 255, 255, 0.2)',
    },
    boxShadow: {
      'default': controlShadow,
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
      ':disabled': 'none',
    },
    color: {
      'default': 'rgba(39, 44, 52, 0.67)',
      ':hover': 'rgba(25, 30, 37, 0.9)',
      ':disabled': 'rgba(39, 44, 52, 0.25)',
    },
    cursor: 'default',
    outline: 'none',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  iconButtonActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    boxShadow: '0 1px 2px rgba(31, 38, 48, 0.05), inset 0 1px 2px rgba(50, 58, 69, 0.1), inset 0 0 0 1px rgba(55, 63, 74, 0.09)',
    color: 'rgb(0, 94, 196)',
  },
  identity: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    justifyContent: 'center',
  },
  scopeLabel: {
    overflow: 'hidden',
    color: colors.text,
    fontSize: 12,
    fontWeight: 660,
    letterSpacing: 0,
    lineHeight: '16px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  location: {
    display: 'flex',
    overflow: 'hidden',
    minWidth: 0,
    alignItems: 'center',
    gap: 3,
    marginTop: 1,
    color: colors.muted,
    fontSize: 10,
    letterSpacing: 0,
    lineHeight: '14px',
    whiteSpace: 'nowrap',
  },
  locationText: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  locationChevron: {
    flex: '0 0 auto',
    opacity: 0.56,
  },
  sessionMeta: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 7,
  },
  cardPosition: {
    maxWidth: 128,
    overflow: 'hidden',
    color: colors.muted,
    fontSize: 10,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 560,
    letterSpacing: 0,
    lineHeight: '14px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  progressTrack: {
    position: 'relative',
    width: {
      'default': 76,
      '@media (max-width: 720px)': 48,
      '@media (max-width: 560px)': 0,
    },
    height: 3,
    overflow: 'hidden',
    borderRadius: 2,
    backgroundColor: 'rgba(54, 61, 71, 0.1)',
  },
  progressFill: {
    position: 'absolute',
    inset: 0,
    borderRadius: 2,
    backgroundColor: colors.accent,
    transformOrigin: 'left center',
  },
})
