import * as stylex from '@stylexjs/stylex'

export const learningReviewSpring = {
  bounce: 0,
  type: 'spring',
  visualDuration: 0.24,
} as const

const spin = stylex.keyframes({
  to: { transform: 'rotate(360deg)' },
})

const colors = {
  accent: 'rgb(0, 113, 227)',
  accentPressed: 'rgb(0, 91, 190)',
  error: 'rgb(176, 54, 50)',
  focus: 'rgba(0, 96, 204, 0.44)',
  muted: 'rgba(45, 50, 58, 0.56)',
  text: 'rgba(23, 27, 33, 0.94)',
} as const

const controlShadow = '0 2px 6px rgba(31, 38, 48, 0.08), 0 0 0 0.5px rgba(55, 63, 74, 0.08), inset 0 1px rgba(255, 255, 255, 0.98), inset 0 -1px rgba(72, 79, 90, 0.07)'

export const learningReviewPageStyles = stylex.create({
  page: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    paddingTop: 56,
    backgroundColor: 'rgb(255, 255, 255)',
    color: colors.text,
  },
  session: {
    display: 'grid',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    gridTemplateRows: 'minmax(0, 1fr) auto',
  },
  materialViewport: {
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    justifyContent: 'center',
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    paddingTop: 'clamp(30px, 7vh, 74px)',
    paddingRight: 'clamp(20px, 6vw, 72px)',
    paddingBottom: 36,
    paddingLeft: 'clamp(20px, 6vw, 72px)',
  },
  material: {
    width: 'min(760px, 100%)',
    minHeight: 240,
    alignSelf: 'flex-start',
    color: colors.text,
  },
  materialLoading: {
    display: 'grid',
    minHeight: 240,
    placeItems: 'center',
    color: colors.muted,
    fontSize: 12,
    letterSpacing: 0,
  },
  dockRegion: {
    zIndex: 4,
    display: 'flex',
    justifyContent: 'center',
    paddingTop: 8,
    paddingRight: 18,
    paddingBottom: 16,
    paddingLeft: 18,
    pointerEvents: 'none',
  },
  reviewDock: {
    position: 'relative',
    display: 'flex',
    width: 'min(720px, 100%)',
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    pointerEvents: 'auto',
  },
  showAnswerButton: {
    width: 'min(320px, 100%)',
    height: 42,
    borderWidth: 0,
    borderRadius: 7,
    paddingRight: 18,
    paddingLeft: 18,
    backgroundColor: {
      'default': colors.accent,
      ':hover': 'rgb(0, 103, 211)',
      ':active': colors.accentPressed,
    },
    boxShadow: {
      'default': '0 2px 6px rgba(0, 76, 158, 0.2), inset 0 1px rgba(255, 255, 255, 0.24)',
      ':focus-visible': `0 0 0 3px ${colors.focus}`,
    },
    color: 'rgb(255, 255, 255)',
    cursor: 'default',
    fontSize: 13,
    fontWeight: 650,
    letterSpacing: 0,
    outline: 'none',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.98)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  ratingGrid: {
    display: 'grid',
    width: '100%',
    gridTemplateColumns: {
      'default': 'repeat(4, minmax(0, 1fr))',
      '@media (max-width: 560px)': 'repeat(2, minmax(0, 1fr))',
    },
    gap: 7,
  },
  ratingButton: {
    display: 'flex',
    minWidth: 0,
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    gap: 0,
    borderColor: 'rgba(52, 59, 69, 0.12)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 7,
    paddingTop: 5,
    paddingRight: 7,
    paddingBottom: 5,
    paddingLeft: 7,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.68)',
      ':hover': 'rgba(255, 255, 255, 0.98)',
      ':active': 'rgba(235, 238, 242, 0.88)',
      ':disabled': 'rgba(250, 250, 250, 0.45)',
    },
    boxShadow: {
      'default': controlShadow,
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    color: colors.text,
    cursor: 'default',
    opacity: {
      'default': 1,
      ':disabled': 0.52,
    },
    outline: 'none',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.97)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, border-color, box-shadow, opacity, transform',
    transitionTimingFunction: 'ease-out',
  },
  rating_again: {
    color: 'rgb(174, 54, 50)',
  },
  rating_hard: {
    color: 'rgb(166, 100, 24)',
  },
  rating_good: {
    color: 'rgb(0, 94, 196)',
  },
  rating_easy: {
    color: 'rgb(41, 122, 75)',
  },
  ratingInterval: {
    overflow: 'hidden',
    maxWidth: '100%',
    color: 'rgba(43, 48, 56, 0.52)',
    fontSize: 9,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 520,
    letterSpacing: 0,
    lineHeight: '12px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  ratingLabel: {
    overflow: 'hidden',
    maxWidth: '100%',
    fontSize: 12,
    fontWeight: 660,
    letterSpacing: 0,
    lineHeight: '17px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  inlineError: {
    position: 'absolute',
    right: 8,
    bottom: 'calc(100% + 6px)',
    left: 8,
    overflow: 'hidden',
    margin: 0,
    borderRadius: 7,
    paddingTop: 6,
    paddingRight: 9,
    paddingBottom: 6,
    paddingLeft: 9,
    backgroundColor: 'rgba(255, 247, 246, 0.96)',
    boxShadow: '0 5px 16px rgba(88, 37, 34, 0.12), inset 0 0 0 1px rgba(176, 54, 50, 0.13)',
    color: colors.error,
    fontSize: 10,
    letterSpacing: 0,
    lineHeight: '15px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  dockSpinner: {
    position: 'absolute',
    top: 15,
    right: -22,
    color: colors.muted,
  },
  centeredStatus: {
    display: 'flex',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    gap: 9,
    padding: 28,
    color: colors.muted,
    fontSize: 12,
    letterSpacing: 0,
    textAlign: 'center',
  },
  errorStatus: {
    color: colors.text,
  },
  statusTitle: {
    margin: 0,
    fontSize: 17,
    fontWeight: 680,
    letterSpacing: 0,
    lineHeight: '23px',
  },
  statusMessage: {
    width: 'min(460px, 100%)',
    margin: 0,
    color: colors.muted,
    lineHeight: '18px',
  },
  statusActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
  },
  primaryButton: {
    display: 'inline-flex',
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    borderWidth: 0,
    borderRadius: 7,
    paddingRight: 13,
    paddingLeft: 13,
    backgroundColor: {
      'default': colors.accent,
      ':hover': 'rgb(0, 103, 211)',
      ':active': colors.accentPressed,
    },
    boxShadow: {
      'default': '0 2px 5px rgba(0, 76, 158, 0.18)',
      ':focus-visible': `0 0 0 3px ${colors.focus}`,
    },
    color: 'white',
    cursor: 'default',
    fontSize: 12,
    fontWeight: 640,
    letterSpacing: 0,
    outline: 'none',
    textDecoration: 'none',
  },
  secondaryButton: {
    display: 'inline-flex',
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    borderColor: 'rgba(52, 59, 69, 0.13)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 7,
    paddingRight: 13,
    paddingLeft: 13,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.74)',
      ':hover': 'rgb(255, 255, 255)',
      ':active': 'rgba(235, 238, 242, 0.88)',
    },
    boxShadow: {
      'default': controlShadow,
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    color: colors.text,
    cursor: 'default',
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: 0,
    outline: 'none',
    textDecoration: 'none',
  },
  completion: {
    display: 'flex',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    padding: 28,
    textAlign: 'center',
  },
  completionIcon: {
    display: 'grid',
    width: 52,
    height: 52,
    placeItems: 'center',
    borderRadius: 8,
    backgroundColor: 'rgba(0, 113, 227, 0.09)',
    boxShadow: 'inset 0 0 0 1px rgba(0, 96, 204, 0.12)',
    color: colors.accent,
  },
  completionTitle: {
    marginTop: 18,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    fontSize: 22,
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: '29px',
  },
  completionMessage: {
    width: 'min(430px, 100%)',
    marginTop: 6,
    marginRight: 0,
    marginBottom: 18,
    marginLeft: 0,
    color: colors.muted,
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: '18px',
  },
  spinner: {
    animationDuration: '800ms',
    animationIterationCount: 'infinite',
    animationName: spin,
    animationTimingFunction: 'linear',
  },
})
