import * as stylex from '@stylexjs/stylex'

export const learningReviewSourceStyles = stylex.create({
  readingPage: {
    width: '100%',
    height: '100%',
    overflowY: 'auto',
    paddingTop: 82,
    paddingRight: 32,
    paddingBottom: 28,
    paddingLeft: 32,
    backgroundColor: 'rgb(255, 255, 255)',
  },
  workspace: {
    position: 'relative',
    display: 'grid',
    width: '100%',
    minHeight: 360,
    gridTemplateColumns: {
      'default': 'minmax(0, 1fr) 232px',
      '@media (max-width: 760px)': 'minmax(0, 1fr)',
    },
    gap: 20,
  },
  canvas: {
    minWidth: 0,
  },
  readingCanvas: {
    minWidth: 0,
    minHeight: 360,
  },
  readingActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    justifyContent: 'flex-end',
    paddingTop: 16,
  },
  structure: {
    minWidth: 0,
    borderLeftColor: 'rgba(46, 52, 61, 0.1)',
    borderLeftStyle: 'solid',
    borderLeftWidth: {
      'default': 1,
      '@media (max-width: 760px)': 0,
    },
    borderTopColor: 'rgba(46, 52, 61, 0.1)',
    borderTopStyle: 'solid',
    borderTopWidth: {
      'default': 0,
      '@media (max-width: 760px)': 1,
    },
    paddingTop: {
      'default': 2,
      '@media (max-width: 760px)': 12,
    },
    paddingLeft: {
      'default': 12,
      '@media (max-width: 760px)': 0,
    },
  },
  structureMobile: {
    position: { '@media (max-width: 760px)': 'absolute' },
    zIndex: { '@media (max-width: 760px)': 3 },
    right: { '@media (max-width: 760px)': 0 },
    bottom: { '@media (max-width: 760px)': 0 },
    left: { '@media (max-width: 760px)': 0 },
    maxHeight: { '@media (max-width: 760px)': 'min(60vh, 460px)' },
    overflowY: { '@media (max-width: 760px)': 'auto' },
    borderTopWidth: { '@media (max-width: 760px)': 1 },
    borderTopColor: { '@media (max-width: 760px)': 'rgba(46, 52, 61, 0.14)' },
    backgroundColor: { '@media (max-width: 760px)': 'rgb(255, 255, 255)' },
    boxShadow: { '@media (max-width: 760px)': '0 -8px 24px rgba(31, 38, 48, 0.12)' },
  },
  structureClosed: {
    display: { '@media (max-width: 760px)': 'none' },
  },
  structureToggle: {
    display: {
      'default': 'none',
      '@media (max-width: 760px)': 'inline-flex',
    },
    alignItems: 'center',
    gap: 5,
    marginTop: 8,
    marginBottom: 4,
    borderWidth: 0,
    padding: 5,
    backgroundColor: 'transparent',
    color: 'rgba(35, 40, 48, 0.72)',
    fontSize: 11,
  },
  structureHeader: {
    paddingTop: 4,
    paddingRight: 8,
    paddingBottom: 8,
    paddingLeft: 8,
    color: 'rgba(34, 39, 47, 0.7)',
    fontSize: 11,
    fontWeight: 650,
    letterSpacing: 0,
  },
  structureTree: {
    display: 'grid',
    maxHeight: 460,
    overflowY: 'auto',
    gap: 1,
  },
  structureRow: {
    minWidth: 0,
  },
  disclosure: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    height: 30,
    alignItems: 'center',
    gap: 5,
    borderWidth: 0,
    borderRadius: 5,
    paddingRight: 7,
    paddingLeft: 4,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(41, 47, 56, 0.06)',
    },
    color: 'rgba(35, 40, 48, 0.76)',
    fontSize: 11,
    letterSpacing: 0,
    textAlign: 'left',
  },
  topicButton: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    height: 30,
    alignItems: 'center',
    gap: 6,
    borderWidth: 0,
    borderRadius: 5,
    paddingRight: 7,
    paddingLeft: 6,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(41, 47, 56, 0.06)',
      ':disabled': 'transparent',
    },
    color: 'rgba(35, 40, 48, 0.72)',
    fontSize: 11,
    letterSpacing: 0,
    opacity: {
      'default': 1,
      ':disabled': 0.48,
    },
    textAlign: 'left',
  },
  topicButtonActive: {
    backgroundColor: 'rgba(45, 51, 60, 0.09)',
    color: 'rgba(20, 24, 30, 0.94)',
  },
  topicLabel: {
    overflow: 'hidden',
    flex: 1,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  sourceMarker: {
    width: 5,
    height: 5,
    flex: '0 0 auto',
    borderRadius: '50%',
    backgroundColor: 'rgb(45, 128, 77)',
  },
  navigationError: {
    marginRight: 6,
    marginBottom: 6,
    marginLeft: 6,
    color: 'rgb(176, 54, 50)',
    fontSize: 10,
    letterSpacing: 0,
    lineHeight: '14px',
  },
  sourceStatus: {
    display: 'grid',
    width: '100%',
    minHeight: 280,
    placeItems: 'center',
    color: 'rgba(45, 50, 58, 0.56)',
    fontSize: 12,
    letterSpacing: 0,
  },
  sourceError: {
    color: 'rgb(176, 54, 50)',
  },
})
