import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'rgb(0, 113, 227)',
  focus: 'rgba(41, 97, 194, 0.85)',
  selected: 'rgba(73, 72, 77, 0.10)',
  selectedPressed: 'rgba(76, 84, 96, 0.15)',
  sidebar: 'rgba(255, 255, 255, 0.48)',
  text: 'rgba(30, 29, 32, 0.86)',
  textMuted: 'rgba(48, 46, 51, 0.66)',
  textQuiet: 'rgba(48, 46, 51, 0.5)',
} as const

export const workspaceSidebarStyles = stylex.create({
  sidebar: {
    position: 'relative',
    zIndex: 2,
    display: 'flex',
    width: 248,
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flexDirection: 'column',
    marginTop: 8,
    marginBottom: 8,
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.62)',
      '@media (prefers-contrast: more)': 'rgba(0, 0, 0, 0.42)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 18,
    backgroundColor: {
      'default': colors.sidebar,
      '@media (prefers-reduced-transparency: reduce)': 'rgb(255, 255, 255)',
      '@media (prefers-contrast: more)': 'rgba(248, 249, 251, 0.96)',
    },
    backdropFilter: {
      'default': 'blur(30px) saturate(170%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 12px 30px rgba(31, 38, 48, 0.13), 0 2px 7px rgba(31, 38, 48, 0.09), inset 0 1px rgba(255, 255, 255, 0.8), inset 1px 0 rgba(255, 255, 255, 0.48)',
  },
  content: {
    minHeight: 0,
    overflowY: 'auto',
    paddingTop: 64,
    paddingRight: 10,
    paddingBottom: 20,
    paddingLeft: 10,
  },
  toggle: {
    position: 'absolute',
    zIndex: 21,
    top: 14,
    display: 'grid',
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyItems: 'center',
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.38)',
      ':active': 'rgba(72, 70, 76, 0.13)',
    },
    color: colors.textMuted,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  sourceGroup: {
    marginBottom: 17,
  },
  navigationHeading: {
    marginTop: 0,
    marginRight: 8,
    marginBottom: 6,
    marginLeft: 8,
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  groupHeading: {
    display: 'flex',
    width: '100%',
    height: 28,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 0,
    paddingRight: 7,
    paddingLeft: 8,
    backgroundColor: 'transparent',
    color: colors.textMuted,
    cursor: 'pointer',
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `inset 0 0 0 2px ${colors.focus}`,
    },
  },
  disclosureIcon: {
    display: 'grid',
    width: 14,
    height: 14,
    alignItems: 'center',
    justifyItems: 'center',
    color: colors.textQuiet,
  },
  sourceList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
  animatedSourceList: {
    overflow: 'hidden',
  },
  virtualSourceViewport: {
    width: '100%',
    overflowX: 'hidden',
    overflowY: 'auto',
    overscrollBehavior: 'contain',
  },
  virtualSourceSizer: {
    position: 'relative',
    width: '100%',
  },
  virtualSourceItem: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: 33,
  },
  sourceItem: {
    display: 'grid',
    width: '100%',
    height: 31,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '20px minmax(0, 1fr)',
    gap: 7,
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 9,
    paddingLeft: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(76, 84, 96, 0.07)',
      ':active': colors.selectedPressed,
    },
    color: colors.text,
    cursor: 'default',
    fontSize: 13,
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: '18px',
    textDecoration: 'none',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.985)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, border-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  sourceItemSelected: {
    borderColor: {
      'default': 'rgba(70, 78, 90, 0.04)',
      '@media (prefers-contrast: more)': 'rgba(0, 0, 0, 0.5)',
    },
    backgroundColor: {
      'default': colors.selected,
      '@media (prefers-contrast: more)': 'rgba(55, 62, 72, 0.16)',
    },
    fontWeight: 550,
  },
  sourceIcon: {
    width: 17,
    height: 17,
    justifySelf: 'center',
    color: colors.textMuted,
  },
  sourceIconSelected: {
    color: colors.accent,
  },
  sourceLabel: {
    overflow: 'hidden',
    textAlign: 'left',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  sourceLabelSelected: {
    color: colors.accent,
  },
})
