import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'var(--ui-accent, #f5c542)',
  border: 'var(--ui-border-strong, #202020)',
  canvas: 'var(--ui-canvas, #fffaf0)',
  divider: 'var(--ui-divider, #202020)',
  muted: 'var(--ui-text-muted, #5b5548)',
  surface: 'var(--ui-surface, #fffdf6)',
  text: 'var(--ui-text, #202020)',
  success: '#bdebc9',
} as const

export const styles = stylex.create({
  appRoot: {
    minHeight: '100vh',
    backgroundColor: colors.canvas,
    color: colors.text,
    fontFamily: 'ui-sans-serif, system-ui, sans-serif',
  },
  body: {
    margin: 0,
    minWidth: 320,
  },
  authShell: {
    display: 'flex',
    minHeight: '100vh',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  loading: {
    display: 'grid',
    minHeight: '100vh',
    placeItems: 'center',
    fontSize: '1rem',
    fontWeight: 800,
  },
  authCard: {
    width: '100%',
    maxWidth: 440,
    padding: 34,
    backgroundColor: colors.surface,
    borderWidth: 3,
    borderStyle: 'solid',
    borderColor: colors.border,
    boxShadow: `8px 8px 0 ${colors.border}`,
  },
  authTitle: {
    marginBlock: 12,
    fontSize: '2rem',
    lineHeight: 1,
  },
  authDescription: {
    color: colors.muted,
    lineHeight: 1.5,
  },
  form: {
    display: 'grid',
    gap: 16,
    marginTop: 24,
  },
  field: {
    display: 'grid',
    gap: 7,
    fontWeight: 800,
  },
  input: {
    minHeight: 42,
    paddingBlock: 8,
    paddingInline: 10,
    font: 'inherit',
    borderWidth: 2,
    borderStyle: 'solid',
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
  },
  formMessage: {
    color: colors.muted,
    fontSize: '.9rem',
  },
  textButton: {
    padding: 0,
    border: 0,
    backgroundColor: 'transparent',
    color: colors.text,
    cursor: 'pointer',
    textAlign: 'left',
    textDecoration: 'underline',
  },
  brandMark: {
    display: 'inline-flex',
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 900,
    backgroundColor: colors.accent,
    borderWidth: 3,
    borderStyle: 'solid',
    borderColor: colors.border,
    boxShadow: `3px 3px 0 ${colors.border}`,
  },
  eyebrow: {
    fontSize: '.72rem',
    fontWeight: 900,
    letterSpacing: '.08em',
    textTransform: 'uppercase',
  },
  console: {
    'display': 'grid',
    'minHeight': '100vh',
    'gridTemplateColumns': '238px minmax(0, 1fr)',
    '@media (max-width: 650px)': {
      display: 'block',
    },
  },
  aside: {
    'display': 'flex',
    'flexDirection': 'column',
    'paddingBlock': 24,
    'paddingInline': 16,
    'borderRightWidth': 3,
    'borderRightStyle': 'solid',
    'borderRightColor': colors.border,
    '@media (max-width: 650px)': {
      alignItems: 'center',
      flexDirection: 'row',
      height: 64,
      paddingBlock: 8,
      paddingInline: 12,
      position: 'sticky',
      top: 0,
      zIndex: 2,
      borderRightWidth: 0,
      borderBottomWidth: 3,
      borderBottomStyle: 'solid',
      borderBottomColor: colors.border,
    },
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
  },
  mobileNavButton: {
    'display': 'none',
    '@media (max-width: 650px)': {
      display: 'inline-flex',
      marginLeft: 'auto',
    },
  },
  brandText: {
    display: 'block',
  },
  mutedSmall: {
    display: 'block',
    color: colors.muted,
    fontSize: '.75rem',
  },
  nav: {
    'display': 'grid',
    'gap': 5,
    'marginTop': 38,
    '@media (max-width: 650px)': {
      display: 'none',
      marginTop: 0,
    },
  },
  navOpen: {
    '@media (max-width: 650px)': {
      display: 'grid',
      position: 'absolute',
      top: 64,
      right: 0,
      left: 0,
      gap: 7,
      padding: 12,
      backgroundColor: colors.canvas,
      borderBottomWidth: 3,
      borderBottomStyle: 'solid',
      borderBottomColor: colors.border,
      boxShadow: `0 5px 0 ${colors.border}`,
    },
  },
  navItem: {
    'padding': 11,
    'borderWidth': 2,
    'borderStyle': 'solid',
    'borderColor': 'transparent',
    'backgroundColor': 'transparent',
    'color': colors.text,
    'cursor': 'pointer',
    'font': 'inherit',
    'fontWeight': 800,
    'textAlign': 'left',
    '@media (max-width: 650px)': {
      display: 'flex',
      width: '100%',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
  },
  navItemActive: {
    'backgroundColor': colors.accent,
    'borderColor': colors.border,
    'boxShadow': `3px 3px 0 ${colors.border}`,
    '@media (max-width: 650px)': {
      fontSize: '.8rem',
    },
  },
  account: {
    'display': 'grid',
    'gap': 6,
    'marginTop': 'auto',
    'paddingTop': 16,
    'borderTopWidth': 2,
    'borderTopStyle': 'solid',
    'borderTopColor': colors.divider,
    '@media (max-width: 650px)': {
      display: 'none',
    },
  },
  accountButton: {
    padding: 0,
    border: 0,
    backgroundColor: 'transparent',
    color: colors.text,
    cursor: 'pointer',
    textAlign: 'left',
    textDecoration: 'underline',
  },
  main: {
    minWidth: 0,
  },
  header: {
    'display': 'flex',
    'minHeight': 126,
    'alignItems': 'center',
    'justifyContent': 'space-between',
    'padding': 24,
    'paddingInline': 34,
    'borderBottomWidth': 3,
    'borderBottomStyle': 'solid',
    'borderBottomColor': colors.border,
    '@media (max-width: 650px)': {
      minHeight: 0,
      alignItems: 'flex-start',
      flexDirection: 'column',
      gap: 14,
      padding: 22,
      paddingInline: 16,
    },
  },
  pageTitle: {
    'margin': 0,
    'marginTop': 8,
    'fontSize': '2.6rem',
    '@media (max-width: 650px)': {
      fontSize: '2rem',
    },
  },
  mode: {
    paddingBlock: 8,
    paddingInline: 12,
    backgroundColor: colors.success,
    borderWidth: 2,
    borderStyle: 'solid',
    borderColor: colors.border,
    fontWeight: 900,
  },
  metrics: {
    'display': 'grid',
    'gridTemplateColumns': 'repeat(3, 1fr)',
    'borderBottomWidth': 3,
    'borderBottomStyle': 'solid',
    'borderBottomColor': colors.border,
    '@media (max-width: 650px)': {
      gridTemplateColumns: '1fr',
    },
  },
  metric: {
    'display': 'grid',
    'minHeight': 145,
    'gap': 7,
    'padding': 25,
    'paddingInline': 28,
    'borderRightWidth': 2,
    'borderRightStyle': 'solid',
    'borderRightColor': colors.divider,
    '@media (max-width: 650px)': {
      minHeight: 0,
      borderRightWidth: 0,
      borderBottomWidth: 2,
      borderBottomStyle: 'solid',
      borderBottomColor: colors.divider,
    },
  },
  metricLast: {
    borderRightWidth: 0,
  },
  metricLabel: {
    fontSize: '.8rem',
    fontWeight: 800,
  },
  metricValue: {
    fontSize: '1.8rem',
  },
  panel: {
    'maxWidth': 720,
    'margin': 34,
    '@media (max-width: 650px)': {
      margin: 24,
      marginInline: 16,
    },
  },
  panelTitle: {
    marginBlock: 10,
    fontSize: '1.8rem',
  },
  panelDescription: {
    color: colors.muted,
    lineHeight: 1.6,
  },
  warning: {
    padding: 14,
    backgroundColor: '#ffe3a3',
    borderWidth: 2,
    borderStyle: 'solid',
    borderColor: colors.border,
    color: colors.text,
    fontWeight: 750,
    lineHeight: 1.5,
  },
  policyConfirmation: {
    display: 'grid',
    gap: 14,
    marginTop: 24,
    padding: 18,
    backgroundColor: colors.surface,
    borderWidth: 3,
    borderStyle: 'solid',
    borderColor: colors.border,
    boxShadow: `5px 5px 0 ${colors.border}`,
  },
  deviceSection: {
    display: 'grid',
    gap: 12,
    marginTop: 30,
    paddingTop: 22,
    borderTopWidth: 2,
    borderTopStyle: 'solid',
    borderTopColor: colors.divider,
  },
  subheading: {
    margin: 0,
    fontSize: '1.15rem',
  },
  deviceRow: {
    'display': 'flex',
    'minWidth': 0,
    'alignItems': 'center',
    'justifyContent': 'space-between',
    'gap': 16,
    'padding': 14,
    'borderWidth': 2,
    'borderStyle': 'solid',
    'borderColor': colors.border,
    '@media (max-width: 650px)': {
      alignItems: 'stretch',
      flexDirection: 'column',
    },
  },
  deviceDetails: {
    display: 'grid',
    minWidth: 0,
    gap: 4,
  },
  deviceMetadata: {
    overflow: 'hidden',
    color: colors.muted,
    fontSize: '.75rem',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  actions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 22,
  },
})
