export { default as i18nCompleteness } from '@memorilo/vite-config/i18n-completeness'
export { customI18nHmrPlugin } from '@memorilo/vite-config/i18n-hmr'
export { spdxLicensePlugin } from '@memorilo/vite-config/licenses'
export { localesPlugin } from '@memorilo/vite-config/locales'
export { localesJsonPlugin } from '@memorilo/vite-config/locales-json'
