import * as stylex from '@stylexjs/stylex'
import { shelfTheme } from '../shelf-shared.stylex'

const controlTransition = {
  'default': shelfTheme.controlDuration,
  '@media (prefers-reduced-motion: reduce)': '0ms',
} as const

export const shelfPublicationStyles = stylex.create({
  virtualSizer: {
    position: 'relative',
    width: '100%',
    maxWidth: 1500,
    minHeight: 1,
    marginRight: 'auto',
    marginLeft: 'auto',
  },
  virtualRow: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
  },
  overviewCollection: {
    width: '100%',
    maxWidth: 1500,
    marginRight: 'auto',
    marginLeft: 'auto',
  },
  browserHeader: {
    paddingTop: 8,
    paddingRight: 2,
    paddingBottom: 18,
    paddingLeft: 2,
  },
  browserTitle: {
    margin: 0,
    fontSize: 24,
    fontWeight: 700,
    letterSpacing: '-0.018em',
    lineHeight: '30px',
  },
  browserSubtitle: {
    maxWidth: 720,
    marginTop: 4,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: shelfTheme.textMuted,
    fontSize: 12,
    lineHeight: '17px',
  },
  overviewSection: {
    minHeight: 118,
    paddingBottom: 18,
  },
  overviewHeader: {
    display: 'flex',
    minHeight: 48,
    alignItems: 'center',
    gap: 8,
    paddingRight: 2,
    paddingLeft: 2,
  },
  overviewHeadingAction: {
    display: 'inline-flex',
    maxWidth: '100%',
    minWidth: 0,
    alignItems: 'center',
    gap: 7,
    borderWidth: 0,
    borderRadius: 6,
    paddingTop: 4,
    paddingRight: 3,
    paddingBottom: 4,
    paddingLeft: 0,
    backgroundColor: 'transparent',
    color: shelfTheme.text,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${shelfTheme.focus}`,
    },
    opacity: {
      'default': 1,
      ':active': 0.62,
    },
  },
  overviewTitleStack: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    gap: 1,
  },
  overviewTitle: {
    overflow: 'hidden',
    margin: 0,
    fontSize: 15,
    fontWeight: 660,
    letterSpacing: 0,
    lineHeight: '20px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  overviewSubtitle: {
    overflow: 'hidden',
    color: shelfTheme.textQuiet,
    fontSize: 11,
    lineHeight: '15px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  catalogChevron: {
    flex: '0 0 auto',
    color: 'rgba(55, 57, 63, 0.34)',
  },
  catalogSectionHeader: {
    display: 'inline-grid',
    maxWidth: '100%',
    minHeight: 44,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: 'minmax(0, auto) 14px',
    gap: 5,
    borderWidth: 0,
    borderRadius: 6,
    paddingRight: 3,
    paddingLeft: 2,
    backgroundColor: 'transparent',
    color: shelfTheme.text,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${shelfTheme.focus}`,
    },
    opacity: {
      'default': 1,
      ':active': 0.62,
    },
  },
  previewState: {
    display: 'flex',
    minHeight: 76,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    color: shelfTheme.textQuiet,
    fontSize: 12,
  },
  horizontalShelfViewport: {
    width: '100%',
    minWidth: 0,
    overflowX: 'auto',
    overflowY: 'hidden',
    paddingTop: 14,
    paddingBottom: 22,
    outline: 'none',
    scrollbarWidth: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `inset 0 0 0 2px ${shelfTheme.focus}`,
    },
  },
  horizontalShelfSizer: {
    position: 'relative',
    height: 272,
    minWidth: '100%',
  },
  horizontalShelfItem: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 140,
  },
  horizontalShelfStatus: {
    display: 'flex',
    width: 140,
    height: 203,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    gap: 8,
    paddingRight: 10,
    paddingLeft: 10,
    color: shelfTheme.textQuiet,
    fontSize: 11,
    lineHeight: '15px',
    textAlign: 'center',
  },
  horizontalRetry: {
    borderWidth: 0,
    borderRadius: 5,
    paddingTop: 3,
    paddingRight: 5,
    paddingBottom: 3,
    paddingLeft: 5,
    backgroundColor: 'transparent',
    color: shelfTheme.accent,
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
    outline: 'none',
    opacity: {
      'default': 1,
      ':active': 0.58,
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${shelfTheme.focus}`,
    },
  },
  groupHeading: {
    display: 'flex',
    minHeight: 64,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 18,
    borderBottomColor: 'rgba(67, 70, 76, 0.11)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingRight: 2,
    paddingLeft: 2,
  },
  groupTitleLine: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 8,
  },
  sourceGlyph: {
    display: 'grid',
    width: 26,
    height: 26,
    flex: '0 0 26px',
    alignItems: 'center',
    justifyItems: 'center',
    color: shelfTheme.accent,
  },
  groupTitle: {
    overflow: 'hidden',
    margin: 0,
    fontSize: 15,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '20px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  groupCount: {
    flex: '0 0 auto',
    color: shelfTheme.textQuiet,
    fontSize: 12,
    fontVariantNumeric: 'tabular-nums',
  },
  inlineIssue: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 6,
    overflow: 'hidden',
    color: 'rgb(159, 88, 13)',
    fontSize: 12,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  publicationRow: {
    display: 'grid',
    width: '100%',
    gap: 24,
    paddingTop: 18,
    paddingBottom: 26,
  },
  publication: {
    minWidth: 0,
  },
  publicationLink: {
    display: 'block',
    minWidth: 0,
    borderRadius: 6,
    color: 'inherit',
    cursor: 'default',
    outline: 'none',
    textDecoration: 'none',
    WebkitTouchCallout: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 3px ${shelfTheme.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.985)',
    },
    transitionDuration: controlTransition,
    transitionProperty: 'box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  coverFrame: {
    position: 'relative',
    width: '100%',
    overflow: 'hidden',
    aspectRatio: '0.69',
    borderColor: 'rgba(54, 58, 65, 0.1)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: 'rgb(231, 229, 223)',
    boxShadow: '0 7px 16px rgba(31, 34, 39, 0.13), 0 1px 3px rgba(31, 34, 39, 0.08)',
  },
  coverImage: {
    display: 'block',
    width: '100%',
    height: '100%',
    animationDuration: {
      'default': '180ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    animationName: stylex.keyframes({
      from: { opacity: 0, transform: 'scale(1.01)' },
      to: { opacity: 1, transform: 'scale(1)' },
    }),
    animationTimingFunction: 'ease-out',
    objectFit: 'cover',
  },
  coverPlaceholder: {
    display: 'flex',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    gap: 12,
    paddingTop: 22,
    paddingRight: 18,
    paddingBottom: 22,
    paddingLeft: 18,
    backgroundColor: 'rgb(229, 226, 217)',
    color: 'rgba(74, 67, 57, 0.52)',
    textAlign: 'center',
  },
  coverPlaceholderLoading: {
    backgroundColor: 'rgb(232, 231, 226)',
    backgroundImage: 'linear-gradient(112deg, rgba(255, 255, 255, 0.08) 20%, rgba(255, 255, 255, 0.56) 42%, rgba(255, 255, 255, 0.08) 64%)',
    backgroundPositionX: '100%',
    backgroundSize: '220% 100%',
    animationDuration: {
      'default': '1500ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    animationIterationCount: 'infinite',
    animationName: stylex.keyframes({
      from: { backgroundPositionX: '100%' },
      to: { backgroundPositionX: '-100%' },
    }),
    animationTimingFunction: 'ease-in-out',
    color: 'rgba(62, 67, 76, 0.48)',
  },
  coverPlaceholderError: {
    backgroundColor: 'rgb(235, 226, 220)',
    color: 'rgba(132, 68, 49, 0.68)',
  },
  coverPlaceholderTitle: {
    display: '-webkit-box',
    overflow: 'hidden',
    maxWidth: '100%',
    color: 'inherit',
    fontFamily: 'ui-serif, "New York", Georgia, serif',
    fontSize: 'clamp(13px, 1.25vw, 18px)',
    fontWeight: 600,
    letterSpacing: '-0.01em',
    lineHeight: 1.28,
    overflowWrap: 'anywhere',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: 6,
  },
  coverPlaceholderStatus: {
    color: 'inherit',
    fontFamily: 'system-ui, sans-serif',
    fontSize: 10,
    fontWeight: 600,
    letterSpacing: '0.02em',
    lineHeight: '14px',
  },
  publicationText: {
    position: 'relative',
    paddingTop: 10,
    paddingRight: 2,
    paddingLeft: 2,
  },
  publicationTitle: {
    display: '-webkit-box',
    overflow: 'hidden',
    margin: 0,
    color: shelfTheme.text,
    fontSize: 13,
    fontWeight: 620,
    letterSpacing: 0,
    lineHeight: '17px',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: 2,
  },
  publicationAuthor: {
    overflow: 'hidden',
    marginTop: 4,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: shelfTheme.textMuted,
    fontSize: 11,
    lineHeight: '15px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  formatLabel: {
    position: 'absolute',
    top: -20,
    right: 6,
    display: 'inline-flex',
    height: 16,
    alignItems: 'center',
    borderRadius: 4,
    paddingRight: 4,
    paddingLeft: 4,
    backgroundColor: 'rgba(21, 24, 28, 0.72)',
    color: 'rgba(255, 255, 255, 0.92)',
    fontSize: 8,
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: '10px',
  },
})
