import * as stylex from '@stylexjs/stylex'

const spin = stylex.keyframes({
  to: { transform: 'rotate(360deg)' },
})

const colors = {
  secondaryText: 'var(--ui-text-muted, rgba(54, 55, 61, 0.4))',
  text: 'var(--ui-text, rgba(28, 29, 33, 0.9))',
} as const

export const commandPaletteStyles = stylex.create({
  overlay: {
    position: 'fixed',
    zIndex: 100,
    inset: 0,
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingTop: 'clamp(112px, 18vh, 220px)',
    paddingRight: 24,
    paddingLeft: 24,
    backgroundColor: 'transparent',
  },
  panel: {
    display: 'grid',
    width: 'min(642px, calc(100vw - 48px))',
    maxHeight: 'min(560px, calc(100vh - 240px))',
    minHeight: 0,
    overflow: 'hidden',
    gridTemplateRows: '56px minmax(0, 1fr)',
    color: colors.text,
  },
  searchRow: {
    position: 'relative',
    display: 'flex',
    minHeight: 56,
    alignItems: 'center',
    gap: 14,
    paddingRight: 18,
    paddingLeft: 20,
  },
  searchRowExpanded: {
    '::after': {
      position: 'absolute',
      right: 20,
      bottom: 0,
      left: 20,
      height: 1,
      backgroundColor: 'var(--ui-divider, rgba(74, 74, 80, 0.13))',
      content: '',
    },
  },
  searchIcon: {
    width: 25,
    height: 25,
    flex: '0 0 25px',
    color: 'var(--ui-text-muted, rgba(44, 45, 50, 0.58))',
  },
  searchInputCluster: {
    display: 'flex',
    minWidth: 0,
    flex: '1 1 auto',
    alignItems: 'center',
    gap: 10,
  },
  input: {
    'width': '100%',
    'height': 44,
    'minWidth': 0,
    'borderWidth': 0,
    'padding': 0,
    'backgroundColor': 'transparent',
    'color': colors.text,
    'fontSize': 24,
    'fontWeight': 430,
    'letterSpacing': '-0.014em',
    'lineHeight': '32px',
    'outline': 'none',
    '::placeholder': {
      color: 'rgba(50, 51, 56, 0.5)',
      opacity: 1,
    },
  },
  inputWithQuery: {
    width: 'auto',
    minWidth: '1ch',
    maxWidth: 'calc(100% - 100px)',
    fieldSizing: 'content',
  },
  searchIntent: {
    flex: '0 0 auto',
    borderRadius: 'var(--ui-control-radius, 9px)',
    paddingTop: 4,
    paddingRight: 10,
    paddingBottom: 4,
    paddingLeft: 10,
    backgroundColor: 'var(--ui-control-hover, rgba(255, 255, 255, 0.43))',
    color: 'var(--ui-text-muted, rgba(64, 65, 70, 0.34))',
    fontSize: 15,
    fontWeight: 510,
    letterSpacing: '-0.006em',
    lineHeight: '22px',
    whiteSpace: 'nowrap',
  },
  searchCommandIconFrame: {
    display: 'grid',
    width: 30,
    height: 30,
    flex: '0 0 30px',
    alignItems: 'center',
    justifyItems: 'center',
    borderRadius: 'var(--ui-control-radius, 9px)',
    boxShadow: 'var(--ui-control-shadow, 0 3px 8px rgba(24, 24, 28, 0.18))',
  },
  searchSpinner: {
    width: 21,
    height: 21,
    flex: '0 0 21px',
    animationDuration: '900ms',
    animationIterationCount: 'infinite',
    animationName: {
      'default': spin,
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
    animationTimingFunction: 'linear',
    color: 'var(--ui-text-muted, rgba(58, 59, 64, 0.42))',
  },
  resultsShell: {
    minHeight: 0,
    overflow: 'hidden',
  },
  resultsViewport: {
    height: '100%',
    minHeight: 0,
    overflowY: 'auto',
    paddingTop: 10,
    paddingRight: 9,
    paddingBottom: 9,
    paddingLeft: 9,
  },
  commandList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1,
    margin: 0,
    padding: 0,
    listStyle: 'none',
  },
  command: {
    display: 'grid',
    width: '100%',
    minHeight: 56,
    gridTemplateColumns: '34px minmax(0, 1fr)',
    alignItems: 'center',
    columnGap: 11,
    borderWidth: 0,
    borderRadius: 'var(--ui-control-radius, 9px)',
    paddingTop: 5,
    paddingRight: 12,
    paddingBottom: 5,
    paddingLeft: 11,
    backgroundColor: 'transparent',
    color: colors.text,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.994)',
    },
    transitionDuration: {
      'default': '80ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  commandSelected: {
    backgroundColor: 'var(--ui-control-pressed, rgba(73, 73, 79, 0.13))',
  },
  commandIconFrame: {
    display: 'grid',
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyItems: 'center',
    borderRadius: 'var(--ui-control-radius, 9px)',
    boxShadow: 'var(--ui-control-shadow, 0 3px 8px rgba(24, 24, 28, 0.16))',
  },
  commandIconBlue: {
    backgroundColor: '#147ce5',
    color: 'rgba(255, 255, 255, 0.96)',
  },
  commandIconViolet: {
    backgroundColor: '#7467d9',
    color: 'rgba(255, 255, 255, 0.96)',
  },
  commandIconGraphite: {
    backgroundColor: '#7c7d83',
    color: 'rgba(255, 255, 255, 0.96)',
  },
  commandIcon: {
    width: 18,
    height: 18,
  },
  commandText: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    gap: 1,
  },
  commandLabel: {
    overflow: 'hidden',
    fontSize: 17,
    fontWeight: 520,
    letterSpacing: '-0.008em',
    lineHeight: '22px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  commandDescription: {
    overflow: 'hidden',
    color: colors.secondaryText,
    fontSize: 14,
    fontWeight: 430,
    letterSpacing: 0,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  searchStatus: {
    display: 'grid',
    minHeight: 56,
    alignItems: 'center',
    justifyItems: 'center',
    paddingRight: 18,
    paddingLeft: 18,
    color: colors.secondaryText,
    fontSize: 14,
    fontWeight: 450,
    letterSpacing: 0,
    lineHeight: '20px',
    textAlign: 'center',
  },
  searchStatusError: {
    color: 'rgba(176, 48, 48, 0.78)',
  },
  visuallyHidden: {
    position: 'absolute',
    width: 1,
    height: 1,
    overflow: 'hidden',
    clip: 'rect(0 0 0 0)',
    clipPath: 'inset(50%)',
    whiteSpace: 'nowrap',
  },
})
