import * as stylex from '@stylexjs/stylex'
import { optimizerTheme } from './learning-optimizer-shared.stylex'

export const learningOptimizerEditorStyles = stylex.create({
  detail: {
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflow: 'hidden',
    backgroundColor: 'transparent',
  },
  detailScroll: {
    width: '100%',
    minHeight: 0,
    overflowY: 'auto',
    paddingTop: 18,
    paddingRight: 'clamp(20px, 5vw, 56px)',
    paddingBottom: 38,
    paddingLeft: 'clamp(20px, 5vw, 56px)',
  },
  detailContent: {
    width: 'min(760px, 100%)',
    marginRight: 'auto',
    marginLeft: 'auto',
  },
  detailHeader: {
    display: 'flex',
    minHeight: 66,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 20,
    paddingBottom: 18,
  },
  headingCopy: {
    minWidth: 0,
  },
  titleLine: {
    display: 'flex',
    minWidth: 0,
    height: 30,
    alignItems: 'center',
    gap: 8,
    color: 'rgba(43, 47, 54, 0.72)',
  },
  detailTitle: {
    overflow: 'hidden',
    margin: 0,
    color: optimizerTheme.text,
    fontSize: 18,
    fontWeight: 680,
    letterSpacing: 0,
    lineHeight: '24px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  nameInput: {
    width: 'min(360px, 100%)',
    height: 30,
    minWidth: 0,
    borderColor: {
      'default': 'transparent',
      ':hover': 'rgba(58, 63, 72, 0.14)',
      ':focus': 'rgba(58, 63, 72, 0.24)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    paddingRight: 7,
    paddingLeft: 7,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.54)',
      ':focus': 'rgba(255, 255, 255, 0.78)',
    },
    color: optimizerTheme.text,
    fontSize: 18,
    fontWeight: 680,
    letterSpacing: 0,
    lineHeight: '24px',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus': `0 0 0 2px ${optimizerTheme.focus}`,
    },
  },
  detailDescription: {
    marginTop: 5,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: optimizerTheme.muted,
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: '17px',
  },
  metadata: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 5,
    marginTop: 5,
    color: 'rgba(55, 60, 68, 0.46)',
    fontSize: 10,
    letterSpacing: 0,
    lineHeight: '15px',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
  },
  formSection: {
    display: 'grid',
    gridTemplateColumns: 'minmax(150px, 0.42fr) minmax(300px, 1fr)',
    gap: 30,
    borderTopColor: optimizerTheme.line,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 17,
    paddingBottom: 17,
  },
  sectionHeader: {
    minWidth: 0,
    paddingTop: 6,
  },
  sectionTitle: {
    margin: 0,
    color: optimizerTheme.text,
    fontSize: 13,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '18px',
  },
  sectionDescription: {
    marginTop: 4,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: optimizerTheme.muted,
    fontSize: 11,
    letterSpacing: 0,
    lineHeight: '16px',
  },
  settingList: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
  },
  settingRow: {
    display: 'grid',
    minHeight: 43,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(126px, 46%)',
    columnGap: 18,
    borderBottomColor: 'rgba(55, 61, 70, 0.075)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingTop: 6,
    paddingBottom: 6,
  },
  settingCopy: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
  },
  settingLabel: {
    color: optimizerTheme.text,
    fontSize: 12,
    fontWeight: 540,
    letterSpacing: 0,
    lineHeight: '17px',
  },
  settingDescription: {
    marginTop: 2,
    color: optimizerTheme.muted,
    fontSize: 10,
    letterSpacing: 0,
    lineHeight: '14px',
  },
  controlSlot: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  numberControl: {
    display: 'flex',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 7,
  },
  numberInput: {
    width: 82,
    textAlign: 'right',
  },
  unit: {
    flex: '0 0 auto',
    color: optimizerTheme.muted,
    fontSize: 10,
    letterSpacing: 0,
  },
  rangeControl: {
    display: 'flex',
    width: '100%',
    alignItems: 'center',
    gap: 9,
  },
  range: {
    width: '100%',
    height: 18,
    accentColor: optimizerTheme.accent,
  },
  valueLabel: {
    width: 34,
    flex: '0 0 34px',
    color: optimizerTheme.text,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    letterSpacing: 0,
    textAlign: 'right',
  },
  switch: {
    position: 'relative',
    width: 32,
    height: 18,
    flex: '0 0 32px',
    borderWidth: 0,
    borderRadius: 9,
    padding: 0,
    backgroundColor: 'rgba(78, 83, 92, 0.2)',
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'inset 0 0 0 1px rgba(35, 39, 46, 0.08)',
      ':focus-visible': `0 0 0 2px ${optimizerTheme.focus}`,
    },
    opacity: {
      'default': 1,
      ':disabled': 0.45,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '120ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  switchOn: {
    backgroundColor: optimizerTheme.accent,
  },
  switchThumb: {
    position: 'absolute',
    top: 2,
    left: 2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: 'white',
    boxShadow: '0 1px 3px rgba(24, 28, 35, 0.24)',
    transform: 'translateX(0)',
    transitionDuration: {
      'default': '140ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'transform',
    transitionTimingFunction: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
  },
  switchThumbOn: {
    transform: 'translateX(14px)',
  },
  inlineError: {
    marginTop: 5,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: optimizerTheme.danger,
    fontSize: 10,
    letterSpacing: 0,
    lineHeight: '14px',
  },
  parameters: {
    display: 'block',
    width: '100%',
    maxHeight: 48,
    overflow: 'auto',
    borderRadius: 5,
    paddingTop: 5,
    paddingRight: 7,
    paddingBottom: 5,
    paddingLeft: 7,
    backgroundColor: 'rgba(62, 68, 78, 0.055)',
    color: 'rgba(43, 48, 56, 0.66)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 9,
    letterSpacing: 0,
    lineHeight: '13px',
    whiteSpace: 'normal',
  },
  parametersControl: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    flexDirection: 'column',
    gap: 8,
  },
  parameterActions: {
    display: 'flex',
    justifyContent: 'flex-end',
  },
  formActions: {
    display: 'flex',
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    borderTopColor: optimizerTheme.line,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 12,
  },
  secondaryActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
  },
  saveCluster: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 10,
  },
  rescheduleControl: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 7,
    color: optimizerTheme.muted,
    cursor: 'default',
    fontSize: 10,
    letterSpacing: 0,
    lineHeight: '14px',
  },
  textButton: {
    display: 'inline-flex',
    height: 28,
    minHeight: 28,
    alignItems: 'center',
    gap: 5,
    borderWidth: 0,
    borderRadius: 5,
    paddingRight: 7,
    paddingLeft: 7,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(61, 67, 77, 0.07)',
      ':active': 'rgba(61, 67, 77, 0.12)',
    },
    color: optimizerTheme.muted,
    cursor: 'default',
    fontSize: 10,
    fontWeight: 540,
    letterSpacing: 0,
    lineHeight: '14px',
    outline: 'none',
    opacity: {
      'default': 1,
      ':disabled': 0.42,
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${optimizerTheme.focus}`,
    },
  },
  dangerButton: {
    color: optimizerTheme.danger,
  },
})
