import * as stylex from '@stylexjs/stylex'
import { optimizerTheme } from './learning-optimizer-shared.stylex'

export const learningOptimizerDetailStyles = stylex.create({
  workspace: {
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flexDirection: 'column',
  },
  detailPage: {
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    paddingTop: 56,
    backgroundColor: 'rgb(255, 255, 255)',
    color: optimizerTheme.text,
  },
  dialogDescription: {
    margin: 0,
    color: 'rgba(35, 39, 46, 0.76)',
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: '18px',
  },
  dialogNote: {
    margin: 0,
    borderRadius: 6,
    paddingTop: 8,
    paddingRight: 9,
    paddingBottom: 8,
    paddingLeft: 9,
    backgroundColor: 'rgba(62, 68, 78, 0.055)',
    color: optimizerTheme.muted,
    fontSize: 10,
    letterSpacing: 0,
    lineHeight: '15px',
  },
  dialogSwitchRow: {
    display: 'flex',
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 20,
    borderTopColor: optimizerTheme.line,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 11,
    color: optimizerTheme.text,
    cursor: 'default',
    fontSize: 11,
    letterSpacing: 0,
    lineHeight: '16px',
  },
})
