import * as stylex from '@stylexjs/stylex'

export const optimizerTheme = stylex.defineVars({
  accent: 'rgb(0, 113, 227)',
  danger: 'rgb(166, 53, 53)',
  focus: 'rgba(0, 96, 204, 0.72)',
  line: 'rgba(55, 61, 70, 0.11)',
  muted: 'rgba(48, 53, 61, 0.58)',
  text: 'rgba(24, 27, 32, 0.92)',
})

const spin = stylex.keyframes({
  to: { transform: 'rotate(360deg)' },
})
export const learningOptimizerSharedStyles = stylex.create({
  feedback: {
    display: 'flex',
    minHeight: 30,
    alignItems: 'center',
    gap: 7,
    marginBottom: 12,
    borderRadius: 6,
    paddingRight: 10,
    paddingLeft: 10,
    fontSize: 11,
    letterSpacing: 0,
    lineHeight: '16px',
  },
  feedbackSuccess: {
    backgroundColor: 'rgba(67, 107, 76, 0.08)',
    color: 'rgb(55, 92, 64)',
  },
  feedbackError: {
    backgroundColor: 'rgba(166, 53, 53, 0.08)',
    color: optimizerTheme.danger,
  },
  input: {
    width: '100%',
    height: 28,
    minWidth: 0,
    borderColor: {
      'default': 'rgba(62, 68, 78, 0.18)',
      ':focus': 'rgba(45, 49, 57, 0.52)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    paddingRight: 7,
    paddingLeft: 7,
    backgroundColor: 'rgba(255, 255, 255, 0.76)',
    color: optimizerTheme.text,
    fontSize: 11,
    letterSpacing: 0,
    lineHeight: '16px',
    outline: 'none',
    boxShadow: {
      'default': 'inset 0 1px 2px rgba(25, 30, 38, 0.04)',
      ':focus': `0 0 0 2px ${optimizerTheme.focus}`,
    },
  },
  actionButton: {
    display: 'inline-flex',
    minWidth: 0,
    height: 28,
    minHeight: 28,
    flex: '0 0 auto',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderColor: 'rgba(62, 68, 78, 0.16)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.7)',
      ':hover': 'rgba(255, 255, 255, 0.94)',
      ':active': 'rgba(232, 235, 240, 0.9)',
    },
    color: 'rgba(34, 38, 45, 0.82)',
    cursor: 'default',
    fontSize: 11,
    fontWeight: 590,
    letterSpacing: 0,
    lineHeight: '16px',
    outline: 'none',
    opacity: {
      'default': 1,
      ':disabled': 0.44,
    },
    boxShadow: {
      'default': '0 1px 2px rgba(31, 37, 47, 0.05), inset 0 1px rgba(255, 255, 255, 0.8)',
      ':focus-visible': `0 0 0 2px ${optimizerTheme.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.97)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, opacity, transform',
    transitionTimingFunction: 'ease-out',
  },
  actionButtonStrong: {
    borderColor: 'rgba(0, 87, 180, 0.82)',
    backgroundColor: {
      'default': optimizerTheme.accent,
      ':hover': 'rgb(0, 101, 204)',
      ':active': 'rgb(0, 91, 184)',
    },
    color: 'white',
    boxShadow: '0 1px 3px rgba(0, 72, 150, 0.28), inset 0 1px rgba(255, 255, 255, 0.24)',
  },
  actionButtonDanger: {
    borderColor: 'rgba(151, 43, 43, 0.72)',
    backgroundColor: {
      'default': 'rgb(166, 53, 53)',
      ':hover': 'rgb(148, 43, 43)',
      ':active': 'rgb(178, 65, 65)',
    },
    color: 'white',
  },
  spinner: {
    animationDuration: '800ms',
    animationIterationCount: 'infinite',
    animationName: spin,
    animationTimingFunction: 'linear',
  },
  status: {
    display: 'flex',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    color: optimizerTheme.muted,
    fontSize: 11,
    letterSpacing: 0,
  },
  dialogSurface: {
    overflow: 'hidden',
    transformOrigin: '50% 35%',
  },
  dialogHeader: {
    display: 'flex',
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: 14,
    paddingLeft: 18,
  },
  dialogTitle: {
    margin: 0,
    color: optimizerTheme.text,
    fontSize: 14,
    fontWeight: 660,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  dialogClose: {
    display: 'grid',
    width: 26,
    height: 26,
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: '50%',
    padding: 0,
    backgroundColor: {
      'default': 'rgba(67, 72, 81, 0.07)',
      ':hover': 'rgba(67, 72, 81, 0.12)',
      ':active': 'rgba(67, 72, 81, 0.17)',
    },
    color: optimizerTheme.muted,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${optimizerTheme.focus}`,
    },
  },
  dialogBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: 13,
    paddingTop: 2,
    paddingRight: 18,
    paddingBottom: 18,
    paddingLeft: 18,
  },
  dialogActions: {
    display: 'flex',
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 7,
    borderTopColor: optimizerTheme.line,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingRight: 14,
    paddingLeft: 14,
    backgroundColor: 'rgba(239, 241, 244, 0.5)',
  },
})
