import * as stylex from '@stylexjs/stylex'
import { optimizerTheme } from './learning-optimizer-shared.stylex'

export const learningOptimizerPanelStyles = stylex.create({
  listWorkspace: {
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
  },
  listScroll: {
    width: '100%',
    minHeight: 0,
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    paddingTop: 16,
    paddingRight: 'clamp(20px, 5vw, 54px)',
    paddingBottom: 36,
    paddingLeft: 'clamp(20px, 5vw, 54px)',
  },
  listContent: {
    width: 'min(820px, 100%)',
    marginRight: 'auto',
    marginLeft: 'auto',
  },
  listHeader: {
    display: 'flex',
    minHeight: 74,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 24,
    paddingRight: 4,
    paddingLeft: 4,
  },
  listHeading: {
    minWidth: 0,
  },
  listTitle: {
    overflow: 'hidden',
    margin: 0,
    color: optimizerTheme.text,
    fontSize: 20,
    fontWeight: 690,
    letterSpacing: 0,
    lineHeight: '27px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  listSummary: {
    marginTop: 3,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: optimizerTheme.muted,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    letterSpacing: 0,
    lineHeight: '16px',
  },
  liquidPrimaryButton: {
    display: 'inline-flex',
    height: 34,
    flex: '0 0 auto',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderColor: {
      'default': 'rgba(0, 79, 166, 0.32)',
      '@media (prefers-contrast: more)': 'rgb(0, 72, 153)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    paddingRight: 12,
    paddingLeft: 11,
    backgroundColor: {
      'default': optimizerTheme.accent,
      ':hover': 'rgb(0, 103, 212)',
      ':active': 'rgb(0, 91, 190)',
      '@media (prefers-reduced-transparency: reduce)': optimizerTheme.accent,
      '@media (prefers-contrast: more)': 'rgb(0, 92, 196)',
    },
    boxShadow: {
      'default': '0 2px 5px -2px rgba(0, 76, 166, 0.38)',
      ':focus-visible': `0 0 0 2px ${optimizerTheme.focus}`,
      '@media (prefers-contrast: more)': '0 0 0 1px rgb(0, 62, 133)',
    },
    color: 'white',
    cursor: 'default',
    fontSize: 11,
    fontWeight: 640,
    letterSpacing: 0,
    lineHeight: '16px',
    outline: 'none',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.965)',
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
    transitionDuration: {
      'default': '110ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  optimizerList: {
    display: 'flex',
    width: '100%',
    flexDirection: 'column',
    borderTopColor: 'rgba(55, 61, 70, 0.11)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    borderBottomColor: 'rgba(55, 61, 70, 0.11)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
  },
  optimizerListItem: {
    width: '100%',
  },
  optimizerRow: {
    display: 'grid',
    width: '100%',
    minHeight: 64,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: {
      'default': '42px minmax(0, 1fr) minmax(290px, auto) 20px',
      '@media (max-width: 760px)': '42px minmax(0, 1fr) 20px',
    },
    gap: 10,
    borderBottomColor: 'rgba(55, 61, 70, 0.08)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    borderRadius: {
      'default': 0,
      ':hover': 8,
      ':active': 8,
    },
    paddingRight: 10,
    paddingLeft: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(70, 79, 93, 0.05)',
      ':active': 'rgba(70, 79, 93, 0.085)',
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `inset 0 0 0 2px ${optimizerTheme.focus}`,
    },
    color: optimizerTheme.text,
    outline: 'none',
    textDecoration: 'none',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.995)',
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  optimizerIcon: {
    display: 'grid',
    width: 32,
    height: 32,
    placeItems: 'center',
    borderRadius: 8,
    backgroundColor: 'rgba(0, 113, 227, 0.1)',
    color: optimizerTheme.accent,
    boxShadow: 'inset 0 0 0 0.5px rgba(0, 88, 184, 0.12)',
  },
  optimizerIconGlobal: {
    backgroundColor: 'rgba(0, 113, 227, 0.16)',
  },
  optimizerIdentity: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
  },
  optimizerName: {
    overflow: 'hidden',
    color: optimizerTheme.text,
    fontSize: 13,
    fontWeight: 620,
    letterSpacing: 0,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  optimizerKind: {
    overflow: 'hidden',
    marginTop: 1,
    color: optimizerTheme.muted,
    fontSize: 10,
    letterSpacing: 0,
    lineHeight: '15px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  optimizerMetrics: {
    display: {
      'default': 'grid',
      '@media (max-width: 760px)': 'none',
    },
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '104px 98px minmax(112px, 1fr)',
    gap: 12,
    color: 'rgba(34, 66, 105, 0.58)',
    fontSize: 10,
    fontVariantNumeric: 'tabular-nums',
    letterSpacing: 0,
    lineHeight: '15px',
    textAlign: 'right',
  },
  optimizerChevron: {
    color: 'rgba(0, 91, 190, 0.52)',
  },
  dialogField: {
    display: 'grid',
    gridTemplateColumns: '110px minmax(0, 1fr)',
    alignItems: 'center',
    gap: 12,
    color: optimizerTheme.text,
    fontSize: 11,
    fontWeight: 540,
    letterSpacing: 0,
    lineHeight: '16px',
  },
})
