import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: '#0071E3',
  border: 'rgba(60, 60, 67, 0.14)',
  muted: 'rgba(60, 60, 67, 0.64)',
  pressed: 'rgba(60, 60, 67, 0.10)',
  selected: 'rgba(0, 113, 227, 0.11)',
  text: '#1D1D1F',
} as const

export const noteStructureInspectorStyles = stylex.create({
  content: {
    display: 'flex',
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    overflowY: 'auto',
    padding: 8,
  },
  disclosureButton: {
    display: 'inline-flex',
    width: 28,
    height: 32,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderStyle: 'none',
    borderRadius: 6,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(60, 60, 67, 0.06)',
      ':active': colors.pressed,
    },
    color: colors.muted,
    cursor: 'default',
  },
  disclosureIcon: {
    transitionDuration: '160ms',
    transitionProperty: 'transform',
    transitionTimingFunction: 'ease-out',
  },
  disclosureIconExpanded: {
    transform: 'rotate(90deg)',
  },
  disclosurePlaceholder: {
    width: 28,
    flexShrink: 0,
  },
  empty: {
    paddingBlock: 20,
    paddingInline: 12,
    color: colors.muted,
    fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
    fontSize: 12,
    lineHeight: '17px',
    textAlign: 'center',
  },
  entryButton: {
    display: 'flex',
    height: 32,
    minWidth: 0,
    flex: 1,
    alignItems: 'center',
    gap: 7,
    borderStyle: 'none',
    borderRadius: 7,
    paddingBlock: 0,
    paddingInline: 7,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(60, 60, 67, 0.06)',
      ':active': colors.pressed,
    },
    color: colors.text,
    cursor: 'default',
    fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
    fontSize: 12,
    textAlign: 'left',
  },
  entryButtonCurrent: {
    backgroundColor: colors.selected,
    color: colors.accent,
    fontWeight: 600,
  },
  entryIcon: {
    flexShrink: 0,
    color: 'currentColor',
  },
  entryLabel: {
    overflow: 'hidden',
    flex: 1,
    minWidth: 0,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  entryRow: (depth: number) => ({
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    paddingInlineStart: depth * 14,
  }),
  header: {
    display: 'flex',
    minHeight: 42,
    alignItems: 'center',
    gap: 8,
    borderBottomColor: colors.border,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingInline: 12,
  },
  learningLabel: {
    color: colors.text,
    fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
    fontSize: 12,
    fontWeight: 600,
  },
  learningRow: {
    display: 'flex',
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomColor: colors.border,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingInline: 12,
  },
  learningSwitch: {
    position: 'relative',
    width: 32,
    height: 20,
    borderStyle: 'none',
    borderRadius: 10,
    padding: 0,
    backgroundColor: 'rgba(120, 120, 128, 0.28)',
    cursor: 'default',
  },
  learningSwitchOn: {
    backgroundColor: '#34C759',
  },
  learningSwitchThumb: {
    position: 'absolute',
    top: 2,
    left: 2,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.20)',
    transitionDuration: '160ms',
    transitionProperty: 'transform',
    transitionTimingFunction: 'ease-out',
  },
  learningSwitchThumbOn: {
    transform: 'translateX(12px)',
  },
  root: {
    display: 'flex',
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
  },
  title: {
    overflow: 'hidden',
    margin: 0,
    color: colors.text,
    fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
    fontSize: 13,
    fontWeight: 700,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  titleCount: {
    color: colors.muted,
    fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
    fontSize: 11,
  },
})
