export { Reader } from '@memorilo/reader'
export type {
  ReaderAnchor,
  ReaderAnnotation,
  ReaderAnnotationColor,
  ReaderCapabilities,
  ReaderEpubLocator,
  ReaderEpubTextAnchor,
  ReaderFormat,
  ReaderHighlight,
  ReaderLocation,
  ReaderNormalizedRect,
  ReaderNote,
  ReaderOcrProvider,
  ReaderOcrRequest,
  ReaderOcrResult,
  ReaderOcrStatus,
  ReaderOcrTextItem,
  ReaderPdfRegionAnchor,
  ReaderPdfTextAnchor,
  ReaderPresentationMode,
  ReaderProps,
  ReaderRegionSelection,
  ReaderSelection,
  ReaderSource,
  ReaderSourceData,
  ReaderTextAnchor,
  ReaderTextLayerKind,
  ReaderTextQuote,
  ReaderTextSelection,
} from '@memorilo/reader'
