export type { DatabaseCommand, DatabaseValue, EditorStorageDatabase } from './database-driver'
export type {
  CheckpointNoteInput,
  CreateEditorStorageOptions,
  CreateNoteInput,
  EditorStorage,
  FolderProjection,
  GetNoteInput,
  GetTopicBlockInput,
  IndexPendingEmbeddingsInput,
  ListNotesInput,
  NoteEntryProjection,
  NotePage,
  NoteSearchHit,
  NoteSearchMatch,
  NoteSortDirection,
  NoteSortField,
  NoteSummary,
  NoteTitleSearchHit,
  NoteWriteReceipt,
  SaveNoteUpdatesInput,
  SearchNotesInput,
  SearchTopicBlocksInput,
  StoredNote,
  StoredNoteUpdate,
  StoredTopicBlock,
  TopicBlockProjection,
  TopicBlockSearchHit,
  TopicBlockSearchMode,
  TopicContentProjection,
  TopicEditorMode,
  TopicProjection,
  TopicSearchHit,
} from './editor-storage'
export { createEditorStorage, DuplicateNoteTitleError } from './editor-storage'
export type { EmbeddingModel } from './embedding-model'
