export type { DatabaseCommand, DatabaseValue, EditorStorageDatabase } from './database-driver'
export type {
  AssetReferenceProjection,
  AssetStatistics,
  CheckpointNoteInput,
  CreateEditorStorageOptions,
  CreateNoteInput,
  EditorStorage,
  FavoriteNoteItem,
  FolderProjection,
  GetNoteInput,
  GetTopicBlockInput,
  IndexPendingEmbeddingsInput,
  ListNoteActivityInput,
  ListNotesInput,
  NoteEntryProjection,
  NoteFavoriteState,
  NotePage,
  NoteSearchHit,
  NoteSearchMatch,
  NoteSortDirection,
  NoteSortField,
  NoteSummary,
  NoteTitleSearchHit,
  NoteWriteReceipt,
  RecentNoteItem,
  ReconcileNoteAssetReferencesInput,
  RecordNoteOpenedInput,
  RegisterAssetInput,
  SaveNoteUpdatesInput,
  SearchNotesInput,
  SearchTopicBlocksInput,
  SetNoteFavoriteInput,
  StoredAsset,
  StoredNote,
  StoredNoteUpdate,
  StoredTopicBlock,
  TopicBlockProjection,
  TopicBlockSearchHit,
  TopicBlockSearchMode,
  TopicContentProjection,
  TopicEditorMode,
  TopicProjection,
  TopicSearchHit,
} from './editor-storage'
export { createEditorStorage, DuplicateNoteTitleError } from './editor-storage'
export type { EmbeddingModel } from './embedding-model'
export type { CreateShelfImageCacheOptions } from './shelf-image-cache'
export { createShelfImageCache } from './shelf-image-cache'
export type { CreateShelfStorageOptions } from './shelf-storage'
export { createShelfStorage } from './shelf-storage'
