import * as stylex from '@stylexjs/stylex'

export const taskReminderPickerStyles = stylex.create({
  popover: {
    zIndex: 70,
    display: 'grid',
    width: 'min(284px, calc(100vw - 24px))',
    gap: 9,
    boxSizing: 'border-box',
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.86)',
      '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.16)',
      '@media (prefers-contrast: more)': 'currentColor',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    backgroundColor: {
      'default': 'rgba(249, 250, 253, 0.93)',
      '@media (prefers-color-scheme: dark)': 'rgba(31, 34, 41, 0.94)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(249, 250, 253)',
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    backdropFilter: {
      'default': 'blur(26px) saturate(150%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': '0 18px 48px rgba(31, 38, 48, 0.2), 0 3px 10px rgba(31, 38, 48, 0.1), inset 0 1px rgba(255, 255, 255, 0.9)',
      '@media (prefers-color-scheme: dark)': '0 20px 52px rgba(0, 0, 0, 0.46), 0 3px 12px rgba(0, 0, 0, 0.28), inset 0 1px rgba(255, 255, 255, 0.1)',
    },
    color: {
      'default': 'rgba(25, 27, 31, 0.92)',
      '@media (prefers-color-scheme: dark)': 'rgba(248, 249, 251, 0.94)',
    },
  },
  heading: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingInline: 4,
    fontSize: 12,
    fontWeight: 650,
  },
  iconButton: {
    minWidth: 28,
    minHeight: 28,
    padding: 5,
  },
  options: {
    display: 'grid',
    gap: 2,
  },
  option: {
    'display': 'grid',
    'gridTemplateColumns': '18px minmax(0, 1fr)',
    'alignItems': 'center',
    'minHeight': 32,
    'gap': 8,
    'borderWidth': 0,
    'borderRadius': 7,
    'paddingInline': 7,
    'backgroundColor': 'transparent',
    'color': 'inherit',
    'fontSize': 12,
    'fontWeight': 520,
    'textAlign': 'left',
    ':hover': { backgroundColor: 'rgba(128, 128, 128, 0.09)' },
    ':active': { transform: 'scale(0.985)' },
    ':disabled': { opacity: 0.46 },
    ':focus-visible': { boxShadow: '0 0 0 2px rgba(41, 97, 194, 0.62)' },
  },
  optionSelected: {
    color: {
      'default': 'rgb(42, 89, 220)',
      '@media (prefers-color-scheme: dark)': 'rgb(119, 164, 255)',
    },
  },
  checkmark: {
    display: 'grid',
    width: 16,
    height: 16,
    placeItems: 'center',
    borderColor: 'rgba(72, 77, 86, 0.22)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 5,
    color: 'white',
  },
  checkmarkSelected: {
    borderColor: 'rgb(67, 112, 255)',
    backgroundColor: 'rgb(67, 112, 255)',
    boxShadow: '0 2px 5px rgba(42, 88, 220, 0.22)',
  },
  customSection: {
    display: 'grid',
    gap: 7,
    borderTop: '1px solid rgba(128, 128, 128, 0.14)',
    paddingBlockStart: 9,
  },
  sectionLabel: {
    paddingInline: 4,
    color: {
      'default': 'rgba(48, 52, 59, 0.58)',
      '@media (prefers-color-scheme: dark)': 'rgba(235, 237, 242, 0.6)',
    },
    fontSize: 10,
    fontWeight: 650,
  },
  customInputRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) 32px',
    gap: 6,
  },
  timeInput: {
    width: '100%',
    height: 32,
    boxSizing: 'border-box',
    borderRadius: 7,
    paddingInline: 8,
    fontSize: 12,
    fontVariantNumeric: 'tabular-nums',
  },
  addButton: {
    width: 32,
    minWidth: 32,
    height: 32,
    padding: 0,
  },
  customList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 5,
  },
  customItem: {
    display: 'flex',
    height: 28,
    alignItems: 'center',
    gap: 4,
    borderRadius: 7,
    paddingInlineStart: 8,
    backgroundColor: {
      'default': 'rgba(67, 112, 255, 0.1)',
      '@media (prefers-color-scheme: dark)': 'rgba(110, 158, 255, 0.16)',
    },
    color: {
      'default': 'rgb(42, 89, 220)',
      '@media (prefers-color-scheme: dark)': 'rgb(135, 175, 255)',
    },
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 600,
  },
  removeButton: {
    width: 26,
    minWidth: 26,
    height: 26,
    padding: 0,
    color: 'inherit',
  },
  clearButton: {
    height: 30,
    borderRadius: 7,
    fontSize: 11,
  },
})
