import * as stylex from '@stylexjs/stylex'

export const taskRepeatPickerStyles = stylex.create({
  popover: {
    zIndex: 70,
    display: 'grid',
    width: 'min(300px, calc(100vw - 24px))',
    maxHeight: 'min(620px, calc(100vh - 24px))',
    boxSizing: 'border-box',
    gap: 10,
    overflowY: 'auto',
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.86)',
      '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.16)',
      '@media (prefers-contrast: more)': 'currentColor',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    backgroundColor: {
      'default': 'rgba(249, 250, 253, 0.93)',
      '@media (prefers-color-scheme: dark)': 'rgba(31, 34, 41, 0.94)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(249, 250, 253)',
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    backdropFilter: {
      'default': 'blur(26px) saturate(150%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': '0 18px 48px rgba(31, 38, 48, 0.2), 0 3px 10px rgba(31, 38, 48, 0.1), inset 0 1px rgba(255, 255, 255, 0.9)',
      '@media (prefers-color-scheme: dark)': '0 20px 52px rgba(0, 0, 0, 0.46), 0 3px 12px rgba(0, 0, 0, 0.28), inset 0 1px rgba(255, 255, 255, 0.1)',
    },
    color: {
      'default': 'rgba(25, 27, 31, 0.92)',
      '@media (prefers-color-scheme: dark)': 'rgba(248, 249, 251, 0.94)',
    },
  },
  customPopover: {
    width: 'min(372px, calc(100vw - 24px))',
    gridTemplateRows: 'auto minmax(0, 1fr) auto',
    minHeight: 0,
    overflow: 'hidden',
    overflowY: 'hidden',
  },
  content: {
    display: 'grid',
    minHeight: 0,
    gap: 10,
    alignContent: 'start',
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    paddingInlineEnd: 2,
    scrollbarGutter: 'stable',
  },
  presetList: {
    display: 'grid',
    gap: 3,
  },
  preset: {
    'display': 'flex',
    'minHeight': 32,
    'alignItems': 'center',
    'justifyContent': 'space-between',
    'gap': 8,
    'borderWidth': 0,
    'borderRadius': 7,
    'paddingInline': 9,
    'backgroundColor': 'transparent',
    'color': 'inherit',
    'fontSize': 12,
    'fontWeight': 550,
    'textAlign': 'left',
    ':hover': { backgroundColor: 'rgba(128, 128, 128, 0.1)' },
    ':active': { transform: 'scale(0.985)' },
    ':focus-visible': { boxShadow: '0 0 0 2px rgba(41, 97, 194, 0.64)' },
  },
  presetSummary: {
    overflow: 'hidden',
    color: {
      'default': 'rgba(48, 52, 59, 0.5)',
      '@media (prefers-color-scheme: dark)': 'rgba(235, 237, 242, 0.54)',
    },
    fontSize: 10,
    fontWeight: 500,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  heading: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingInline: 4,
    fontSize: 12,
    fontWeight: 650,
  },
  field: {
    display: 'grid',
    gap: 5,
    color: {
      'default': 'rgba(48, 52, 59, 0.58)',
      '@media (prefers-color-scheme: dark)': 'rgba(235, 237, 242, 0.6)',
    },
    fontSize: 10,
    fontWeight: 600,
  },
  selectRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)',
    gap: 6,
  },
  input: {
    'width': '100%',
    'minWidth': 0,
    'height': 30,
    'boxSizing': 'border-box',
    'borderColor': 'rgba(72, 77, 86, 0.12)',
    'borderStyle': 'solid',
    'borderWidth': 1,
    'borderRadius': 7,
    'paddingInline': 8,
    'backgroundColor': 'rgba(255, 255, 255, 0.64)',
    'color': 'inherit',
    'fontSize': 11,
    'outline': 'none',
    ':focus': { borderColor: 'rgba(67, 112, 255, 0.7)', boxShadow: '0 0 0 2px rgba(67, 112, 255, 0.15)' },
  },
  segmented: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    minHeight: 30,
    borderRadius: 7,
    padding: 2,
    backgroundColor: 'rgba(74, 79, 88, 0.08)',
  },
  segmentedTwo: {
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
  },
  segment: {
    'minWidth': 0,
    'borderWidth': 0,
    'borderRadius': 6,
    'paddingInline': 5,
    'backgroundColor': 'transparent',
    'color': 'rgba(48, 52, 59, 0.56)',
    'fontSize': 10,
    'fontWeight': 600,
    ':hover': { color: 'inherit' },
    ':focus-visible': { boxShadow: '0 0 0 2px rgba(41, 97, 194, 0.62)' },
  },
  segmentSelected: {
    backgroundColor: 'rgba(255, 255, 255, 0.86)',
    color: 'inherit',
    boxShadow: '0 1px 3px rgba(32, 38, 48, 0.12), inset 0 1px rgba(255, 255, 255, 0.84)',
  },
  weekdayRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    gap: 3,
  },
  weekday: {
    'display': 'grid',
    'minWidth': 0,
    'height': 29,
    'placeItems': 'center',
    'borderWidth': 0,
    'borderRadius': 7,
    'padding': 0,
    'backgroundColor': 'transparent',
    'color': 'rgba(48, 52, 59, 0.62)',
    'fontSize': 10,
    'fontWeight': 600,
    ':hover': { backgroundColor: 'rgba(128, 128, 128, 0.1)' },
    ':focus-visible': { boxShadow: '0 0 0 2px rgba(41, 97, 194, 0.62)' },
  },
  weekdaySelected: {
    backgroundColor: 'rgb(67, 112, 255)',
    color: 'white',
    boxShadow: '0 3px 8px rgba(42, 88, 220, 0.25)',
  },
  miniMonth: {
    display: 'grid',
    gap: 8,
    paddingBlock: 2,
  },
  miniMonthHeader: {
    display: 'grid',
    gridTemplateColumns: '28px minmax(0, 1fr) 28px',
    alignItems: 'center',
    minHeight: 28,
    fontSize: 11,
    fontWeight: 650,
    textAlign: 'center',
  },
  iconButton: {
    'display': 'grid',
    'width': 28,
    'height': 28,
    'placeItems': 'center',
    'borderWidth': 0,
    'borderRadius': 6,
    'padding': 0,
    'backgroundColor': 'transparent',
    'color': 'inherit',
    ':hover': { backgroundColor: 'rgba(128, 128, 128, 0.1)' },
    ':active': { transform: 'scale(0.94)' },
    ':focus-visible': { boxShadow: '0 0 0 2px rgba(41, 97, 194, 0.62)' },
  },
  miniWeekdays: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    color: 'rgba(48, 52, 59, 0.4)',
    fontSize: 9,
    fontWeight: 600,
    textAlign: 'center',
  },
  miniGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    gap: 2,
  },
  miniDay: {
    'display': 'grid',
    'height': 27,
    'placeItems': 'center',
    'borderWidth': 0,
    'borderRadius': '50%',
    'padding': 0,
    'backgroundColor': 'transparent',
    'color': 'inherit',
    'fontSize': 10,
    'fontVariantNumeric': 'tabular-nums',
    ':hover': { backgroundColor: 'rgba(128, 128, 128, 0.1)' },
    ':focus-visible': { boxShadow: '0 0 0 2px rgba(41, 97, 194, 0.62)' },
  },
  miniDayMuted: { color: 'rgba(48, 52, 59, 0.26)' },
  miniDaySelected: { backgroundColor: 'rgb(67, 112, 255)', color: 'white', boxShadow: '0 3px 8px rgba(42, 88, 220, 0.25)' },
  miniDayLast: { gridColumn: 'span 2', borderRadius: 14, paddingInline: 7, whiteSpace: 'nowrap' },
  miniDayPreview: {
    'position': 'relative',
    '::after': {
      position: 'absolute',
      bottom: 3,
      left: '50%',
      width: 4,
      height: 4,
      borderRadius: '50%',
      backgroundColor: {
        'default': 'rgb(67, 112, 255)',
        '@media (prefers-color-scheme: dark)': 'rgb(110, 158, 255)',
        '@media (prefers-contrast: more)': 'currentColor',
      },
      content: '',
      pointerEvents: 'none',
      transform: 'translateX(-50%)',
    },
  },
  anchorWeekdays: {
    fontSize: 10,
  },
  anchorGrid: {
    gridAutoRows: 36,
    gap: 2,
  },
  anchorDay: {
    width: 34,
    height: 34,
    placeSelf: 'center',
    fontSize: 11,
  },
  checkboxRow: {
    display: 'flex',
    minHeight: 28,
    alignItems: 'center',
    gap: 7,
    color: 'rgba(48, 52, 59, 0.72)',
    fontSize: 10,
    fontWeight: 500,
  },
  checkbox: { width: 14, height: 14, margin: 0, accentColor: 'rgb(67, 112, 255)' },
  footer: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)',
    gap: 7,
    paddingTop: 10,
    borderTop: '1px solid rgba(128, 128, 128, 0.14)',
  },
  footerButton: {
    height: 30,
    borderRadius: 7,
    fontSize: 11,
  },
  calendarSelect: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)',
    gap: 6,
  },
  note: {
    paddingInline: 4,
    color: 'rgba(48, 52, 59, 0.48)',
    fontSize: 10,
    lineHeight: '15px',
  },
})
