import * as stylex from '@stylexjs/stylex'

export const imageOcclusionEditorStyles = stylex.create({
  root: {
    display: 'grid',
    gridTemplateRows: 'auto minmax(0, 1fr)',
    width: '100%',
    height: '100%',
    minHeight: 0,
    backgroundColor: '#f4f5f7',
    color: '#1d2026',
  },
  toolbar: {
    zIndex: 2,
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    minHeight: 48,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'rgb(24 28 36 / 10%)',
    paddingBlock: 8,
    paddingInline: 12,
    backgroundColor: 'rgb(250 251 252 / 86%)',
    backdropFilter: 'blur(18px) saturate(135%)',
    overflowX: 'auto',
  },
  titleInput: {
    'flex': '0 1 220px',
    'minWidth': 120,
    'height': 30,
    'borderWidth': 1,
    'borderStyle': 'solid',
    'borderColor': 'transparent',
    'borderRadius': 5,
    'paddingInline': 8,
    'backgroundColor': 'transparent',
    'color': 'inherit',
    'fontFamily': 'inherit',
    'fontSize': 13,
    'fontWeight': 600,
    'outline': 'none',
    ':hover': {
      borderColor: 'rgb(24 28 36 / 12%)',
      backgroundColor: 'rgb(255 255 255 / 60%)',
    },
    ':focus': {
      borderColor: '#3b82f6',
      backgroundColor: '#ffffff',
      boxShadow: '0 0 0 2px rgb(59 130 246 / 14%)',
    },
  },
  separator: {
    flex: '0 0 1px',
    width: 1,
    height: 22,
    backgroundColor: 'rgb(24 28 36 / 12%)',
  },
  controlGroup: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 2,
    flexShrink: 0,
    borderRadius: 6,
    padding: 2,
    backgroundColor: 'rgb(24 28 36 / 6%)',
  },
  iconButton: {
    'display': 'inline-flex',
    'alignItems': 'center',
    'justifyContent': 'center',
    'width': 28,
    'height': 28,
    'borderWidth': 0,
    'borderRadius': 4,
    'padding': 0,
    'backgroundColor': 'transparent',
    'color': '#565d69',
    'cursor': 'pointer',
    ':hover': {
      backgroundColor: 'rgb(255 255 255 / 80%)',
      color: '#20242c',
    },
    ':active': {
      transform: 'scale(0.96)',
    },
    ':disabled': {
      color: 'rgb(86 93 105 / 32%)',
      cursor: 'default',
      transform: 'none',
    },
  },
  iconButtonActive: {
    backgroundColor: '#ffffff',
    color: '#1769e0',
    boxShadow: '0 1px 4px rgb(23 31 45 / 14%)',
  },
  modeButton: {
    'minWidth': 78,
    'height': 28,
    'borderWidth': 0,
    'borderRadius': 4,
    'paddingInline': 9,
    'backgroundColor': 'transparent',
    'color': '#565d69',
    'fontFamily': 'inherit',
    'fontSize': 12,
    'whiteSpace': 'nowrap',
    'cursor': 'pointer',
    ':hover': {
      color: '#20242c',
    },
  },
  modeButtonActive: {
    backgroundColor: '#ffffff',
    color: '#1769e0',
    boxShadow: '0 1px 4px rgb(23 31 45 / 14%)',
  },
  canvasShell: {
    position: 'relative',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    backgroundColor: '#e7e9ed',
  },
  canvasDraw: {
    cursor: 'crosshair',
  },
  status: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#626975',
    fontSize: 13,
  },
  spinner: {
    'animationName': stylex.keyframes({
      to: { transform: 'rotate(360deg)' },
    }),
    'animationDuration': '800ms',
    'animationIterationCount': 'infinite',
    'animationTimingFunction': 'linear',
    '@media (prefers-reduced-motion: reduce)': {
      animationName: 'none',
    },
  },
})
