import * as stylex from '@stylexjs/stylex'
import { noteTheme } from './note-shared.stylex'

export const noteEditorStyles = stylex.create({
  page: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    height: '100%',
    minHeight: 0,
    overflow: 'hidden',
    backgroundColor: noteTheme.canvas,
    color: noteTheme.chromeText,
  },
  workspace: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    overflow: 'hidden',
    marginLeft: -10,
    paddingTop: 56,
    paddingLeft: 10,
    backgroundColor: noteTheme.canvas,
  },
  topicLoading: {
    display: 'grid',
    width: '100%',
    height: '100%',
    minHeight: 0,
    placeItems: 'center',
    color: noteTheme.chromeTextMuted,
    fontSize: 12,
    letterSpacing: 0,
  },
  fullBleedWorkspace: {
    paddingTop: 0,
  },
  cardTopicToolbar: {
    display: 'flex',
    minHeight: 38,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'flex-end',
    borderBottomColor: 'rgba(48, 53, 61, 0.09)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingInline: 16,
  },
  cardTopicPreviewTrigger: {
    display: 'grid',
    width: 28,
    height: 28,
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 6,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(68, 73, 82, 0.08)',
      ':active': 'rgba(68, 73, 82, 0.14)',
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${noteTheme.focus}`,
    },
    color: noteTheme.chromeTextMuted,
    cursor: 'default',
    outline: 'none',
  },
  cardTopicPreviewOverlay: {
    position: 'absolute',
    zIndex: 10,
    inset: 0,
    display: 'grid',
    placeItems: 'center',
    padding: 24,
    backgroundColor: 'rgba(33, 37, 43, 0.18)',
    backdropFilter: 'blur(3px)',
  },
  cardTopicPreviewDialog: {
    display: 'flex',
    width: 'min(520px, 100%)',
    maxHeight: 'min(680px, 100%)',
    overflow: 'hidden',
    flexDirection: 'column',
    borderColor: 'rgba(45, 51, 59, 0.12)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: 'rgb(250, 251, 252)',
    boxShadow: '0 22px 60px rgba(22, 27, 34, 0.22)',
  },
  cardTopicPreviewHeader: {
    display: 'flex',
    minHeight: 42,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomColor: 'rgba(45, 51, 59, 0.1)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingInline: 12,
  },
  cardTopicPreviewTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    color: noteTheme.chromeText,
    fontSize: 12,
    fontWeight: 650,
    letterSpacing: 0,
  },
  cardTopicPreviewClose: {
    display: 'grid',
    width: 28,
    height: 28,
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 6,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(68, 73, 82, 0.08)',
      ':active': 'rgba(68, 73, 82, 0.14)',
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${noteTheme.focus}`,
    },
    color: noteTheme.chromeTextMuted,
    cursor: 'default',
    outline: 'none',
  },
  cardTopicPreviewSelector: {
    display: 'flex',
    flexShrink: 0,
    gap: 2,
    marginBlock: 8,
    marginInline: 12,
    borderRadius: 7,
    padding: 2,
    backgroundColor: 'rgba(68, 73, 82, 0.07)',
  },
  cardTopicPreviewOption: {
    flex: 1,
    minWidth: 0,
    height: 28,
    borderWidth: 0,
    borderRadius: 5,
    paddingInline: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.72)',
    },
    color: noteTheme.chromeText,
    cursor: 'default',
    font: 'inherit',
    fontSize: 11,
    fontWeight: 550,
    letterSpacing: 0,
    outline: 'none',
  },
  cardTopicPreviewOptionSelected: {
    backgroundColor: 'rgba(255, 255, 255, 0.96)',
    boxShadow: '0 1px 4px rgba(31, 38, 48, 0.12)',
  },
  cardTopicPreviewBody: {
    minHeight: 0,
    overflow: 'auto',
    padding: 12,
  },
  readerSourceHeader: {
    display: 'flex',
    minHeight: 64,
    flexShrink: 0,
    alignItems: 'center',
    gap: 8,
    borderBottomColor: 'rgba(48, 53, 61, 0.12)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingTop: 8,
    paddingRight: 18,
    paddingBottom: 8,
    paddingLeft: 18,
    backgroundColor: 'rgba(247, 248, 250, 0.92)',
  },
  readerSourceLink: {
    display: 'flex',
    minWidth: 0,
    flex: 1,
    alignItems: 'center',
    gap: 12,
    borderRadius: 6,
    padding: 4,
    color: noteTheme.chromeText,
    outline: 'none',
    textDecoration: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${noteTheme.focus}`,
    },
  },
  readerSourceSnapshot: {
    display: 'flex',
    minWidth: 0,
    flex: 1,
    alignItems: 'center',
    gap: 12,
    padding: 4,
  },
  readerSourceText: {
    display: '-webkit-box',
    minWidth: 0,
    overflow: 'hidden',
    flex: 1,
    margin: 0,
    color: noteTheme.chromeText,
    fontSize: 12,
    fontStyle: 'normal',
    lineHeight: '18px',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: 3,
  },
  readerSourceImage: {
    width: 132,
    height: 76,
    flexShrink: 0,
    borderColor: 'rgba(48, 53, 61, 0.16)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 5,
    objectFit: 'contain',
    backgroundColor: 'white',
  },
  readerSourceLocation: {
    maxWidth: 180,
    flexShrink: 0,
    color: noteTheme.chromeTextMuted,
    fontSize: 10,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '15px',
    textAlign: 'right',
  },
  readerSourceRemove: {
    display: 'grid',
    width: 28,
    height: 28,
    flexShrink: 0,
    alignItems: 'center',
    justifyItems: 'center',
    borderWidth: 0,
    borderRadius: 6,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(68, 73, 82, 0.08)',
      ':active': 'rgba(68, 73, 82, 0.14)',
    },
    color: noteTheme.chromeTextMuted,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${noteTheme.focus}`,
    },
  },
  alertStack: {
    position: 'absolute',
    zIndex: 2,
    top: 68,
    left: '50%',
    display: 'flex',
    width: 'min(620px, calc(100% - 32px))',
    flexDirection: 'column',
    gap: 8,
    transform: 'translateX(-50%)',
  },
  saveError: {
    maxWidth: '100%',
    borderRadius: 8,
    paddingBlock: 8,
    paddingInline: 12,
    backgroundColor: 'rgba(115, 28, 28, 0.9)',
    color: '#ffffff',
    fontSize: 12,
  },
  validationError: {
    display: 'flex',
    maxWidth: '100%',
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    borderRadius: 8,
    paddingBlock: 6,
    paddingRight: 7,
    paddingLeft: 12,
    backgroundColor: 'rgba(115, 28, 28, 0.94)',
    color: '#ffffff',
    fontSize: 12,
    lineHeight: 1.45,
  },
  validationErrorMessage: {
    minWidth: 0,
  },
  validationErrorActions: {
    display: 'flex',
    minWidth: 172,
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 7,
  },
  copyDiagnosticsButton: {
    display: 'inline-flex',
    height: 28,
    flexShrink: 0,
    alignItems: 'center',
    gap: 5,
    borderColor: 'rgba(255, 255, 255, 0.34)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    paddingInline: 8,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.12)',
      ':hover': 'rgba(255, 255, 255, 0.2)',
      ':active': 'rgba(255, 255, 255, 0.27)',
    },
    color: '#ffffff',
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '16px',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgba(255, 255, 255, 0.88)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.98)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  copyDiagnosticsStatus: {
    width: 54,
    flexShrink: 0,
    color: 'rgba(255, 255, 255, 0.86)',
    fontSize: 10,
    fontWeight: 550,
    letterSpacing: 0,
    lineHeight: '14px',
  },
})
