import * as stylex from '@stylexjs/stylex'
import { noteTheme } from './note-shared.stylex'

export const noteEditorStyles = stylex.create({
  page: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    height: '100%',
    minHeight: 0,
    overflow: 'hidden',
    backgroundColor: noteTheme.canvas,
    color: noteTheme.chromeText,
  },
  workspace: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflow: 'hidden',
    marginLeft: -10,
    paddingTop: 56,
    paddingLeft: 10,
    backgroundColor: noteTheme.canvas,
  },
  topicLoading: {
    display: 'grid',
    width: '100%',
    height: '100%',
    minHeight: 0,
    placeItems: 'center',
    color: noteTheme.chromeTextMuted,
    fontSize: 12,
    letterSpacing: 0,
  },
  whiteboardWorkspace: {
    paddingTop: 0,
  },
  alertStack: {
    position: 'absolute',
    zIndex: 2,
    top: 68,
    left: '50%',
    display: 'flex',
    width: 'min(620px, calc(100% - 32px))',
    flexDirection: 'column',
    gap: 8,
    transform: 'translateX(-50%)',
  },
  saveError: {
    maxWidth: '100%',
    borderRadius: 8,
    paddingBlock: 8,
    paddingInline: 12,
    backgroundColor: 'rgba(115, 28, 28, 0.9)',
    color: '#ffffff',
    fontSize: 12,
  },
  validationError: {
    display: 'flex',
    maxWidth: '100%',
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    borderRadius: 8,
    paddingBlock: 6,
    paddingRight: 7,
    paddingLeft: 12,
    backgroundColor: 'rgba(115, 28, 28, 0.94)',
    color: '#ffffff',
    fontSize: 12,
    lineHeight: 1.45,
  },
  validationErrorMessage: {
    minWidth: 0,
  },
  validationErrorActions: {
    display: 'flex',
    minWidth: 172,
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 7,
  },
  copyDiagnosticsButton: {
    display: 'inline-flex',
    height: 28,
    flexShrink: 0,
    alignItems: 'center',
    gap: 5,
    borderColor: 'rgba(255, 255, 255, 0.34)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    paddingInline: 8,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.12)',
      ':hover': 'rgba(255, 255, 255, 0.2)',
      ':active': 'rgba(255, 255, 255, 0.27)',
    },
    color: '#ffffff',
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '16px',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgba(255, 255, 255, 0.88)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.98)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  copyDiagnosticsStatus: {
    width: 54,
    flexShrink: 0,
    color: 'rgba(255, 255, 255, 0.86)',
    fontSize: 10,
    fontWeight: 550,
    letterSpacing: 0,
    lineHeight: '14px',
  },
})
