import * as stylex from '@stylexjs/stylex'
import { noteTheme } from './note-shared.stylex'

export const noteEditorDialogStyles = stylex.create({
  bookPickerOverlay: {
    position: 'fixed',
    zIndex: 60,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    display: 'grid',
    alignItems: 'center',
    justifyItems: 'center',
    padding: 24,
    backgroundColor: 'rgba(28, 31, 38, 0.24)',
    backdropFilter: 'blur(10px)',
  },
  entryCreationDialog: {
    display: 'flex',
    width: 'min(360px, 100%)',
    overflow: 'hidden',
    flexDirection: 'column',
    borderColor: 'rgba(50, 55, 64, 0.18)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 12,
    backgroundColor: {
      'default': 'rgba(250, 251, 253, 0.96)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 251, 253)',
    },
    boxShadow: '0 22px 56px rgba(29, 35, 45, 0.22), 0 2px 8px rgba(29, 35, 45, 0.1)',
  },
  entryCreationBody: {
    display: 'grid',
    gap: 8,
    paddingTop: 16,
    paddingRight: 18,
    paddingBottom: 18,
    paddingLeft: 18,
  },
  entryCreationField: {
    display: 'grid',
    gap: 6,
    color: noteTheme.chromeTextMuted,
    fontSize: 11,
    fontWeight: 550,
    letterSpacing: 0,
    lineHeight: '16px',
  },
  entryCreationInput: {
    width: '100%',
    height: 34,
    borderColor: 'rgba(49, 48, 53, 0.18)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.82)',
    color: noteTheme.chromeText,
    fontSize: 13,
    letterSpacing: 0,
    lineHeight: '18px',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus': '0 0 0 3px rgba(41, 97, 194, 0.2)',
    },
  },
  bookPickerDialog: {
    display: 'flex',
    width: 'min(620px, 100%)',
    maxHeight: 'min(720px, calc(100vh - 48px))',
    flexDirection: 'column',
    overflow: 'hidden',
    borderColor: 'rgba(50, 55, 64, 0.18)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 14,
    backgroundColor: {
      'default': 'rgba(250, 251, 253, 0.96)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 251, 253)',
    },
    boxShadow: '0 22px 56px rgba(29, 35, 45, 0.22), 0 2px 8px rgba(29, 35, 45, 0.1)',
  },
  bookPickerHeader: {
    display: 'flex',
    minHeight: 76,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    borderBottomColor: 'rgba(49, 48, 53, 0.12)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingTop: 15,
    paddingRight: 18,
    paddingBottom: 14,
    paddingLeft: 20,
  },
  bookPickerTitle: {
    margin: 0,
    color: noteTheme.chromeText,
    fontSize: 16,
    fontWeight: 650,
    lineHeight: '22px',
  },
  bookPickerDescription: {
    marginTop: 3,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: noteTheme.chromeTextMuted,
    fontSize: 12,
    lineHeight: '18px',
  },
  inspectorCloseButton: {
    display: 'grid',
    width: 30,
    height: 30,
    flexShrink: 0,
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 15,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(60, 65, 74, 0.08)',
      ':active': 'rgba(60, 65, 74, 0.14)',
    },
    color: noteTheme.chromeTextMuted,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      ':focus-visible': `0 0 0 2px ${noteTheme.focus}`,
    },
  },
  bookPickerBody: {
    display: 'grid',
    minHeight: 0,
    flex: 1,
    gridTemplateRows: 'auto minmax(96px, 1fr) auto auto',
    gap: 12,
    padding: 16,
  },
  bookPickerSearch: {
    display: 'flex',
    minHeight: 34,
    alignItems: 'center',
    gap: 8,
    borderColor: 'rgba(49, 48, 53, 0.16)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 9,
    paddingLeft: 9,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    color: noteTheme.chromeTextQuiet,
    boxShadow: {
      ':focus-within': '0 0 0 3px rgba(41, 97, 194, 0.2)',
    },
  },
  bookPickerSearchInput: {
    width: '100%',
    minWidth: 0,
    height: 30,
    borderWidth: 0,
    padding: 0,
    backgroundColor: 'transparent',
    color: noteTheme.chromeText,
    fontSize: 12,
    lineHeight: '18px',
    outline: 'none',
  },
  bookPickerList: {
    display: 'grid',
    minHeight: 96,
    overflowY: 'auto',
    alignContent: 'start',
    gap: 6,
  },
  bookPickerOption: {
    display: 'grid',
    minHeight: 54,
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: 12,
    borderColor: 'rgba(49, 48, 53, 0.11)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingTop: 9,
    paddingRight: 11,
    paddingBottom: 9,
    paddingLeft: 11,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.66)',
      ':hover': 'rgba(255, 255, 255, 0.96)',
      ':active': 'rgba(242, 245, 249, 0.96)',
    },
    color: noteTheme.chromeText,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      ':focus-visible': `0 0 0 2px ${noteTheme.focus}`,
    },
  },
  bookPickerOptionSelected: {
    borderColor: 'rgba(0, 113, 227, 0.42)',
    backgroundColor: 'rgba(0, 113, 227, 0.08)',
  },
  bookPickerOptionText: {
    display: 'grid',
    minWidth: 0,
    gap: 2,
  },
  bookPickerOptionTitle: {
    overflow: 'hidden',
    fontSize: 12,
    fontWeight: 600,
    lineHeight: '17px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  bookPickerOptionDetail: {
    overflow: 'hidden',
    color: noteTheme.chromeTextQuiet,
    fontSize: 10,
    lineHeight: '15px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  bookPickerFormatList: {
    color: noteTheme.chromeTextMuted,
    fontSize: 9,
    fontWeight: 650,
    lineHeight: '14px',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
  },
  bookPickerFormatField: {
    display: 'grid',
    gridTemplateColumns: 'auto minmax(140px, 220px)',
    alignItems: 'center',
    justifyContent: 'end',
    gap: 10,
    color: noteTheme.chromeTextMuted,
    fontSize: 11,
    fontWeight: 600,
  },
  bookPickerFormatSelect: {
    height: 32,
    borderColor: 'rgba(49, 48, 53, 0.16)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 8,
    paddingLeft: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.82)',
    color: noteTheme.chromeText,
    fontSize: 12,
    outline: 'none',
    boxShadow: {
      ':focus-visible': `0 0 0 2px ${noteTheme.focus}`,
    },
  },
  bookPickerStatus: {
    alignSelf: 'center',
    margin: 0,
    padding: 24,
    color: noteTheme.chromeTextMuted,
    fontSize: 12,
    lineHeight: '18px',
    textAlign: 'center',
  },
  bookPickerError: {
    margin: 0,
    color: 'rgb(151, 45, 45)',
    fontSize: 11,
    lineHeight: '17px',
  },
  bookPickerWarning: {
    margin: 0,
    borderRadius: 7,
    paddingTop: 8,
    paddingRight: 10,
    paddingBottom: 8,
    paddingLeft: 10,
    backgroundColor: 'rgba(198, 119, 28, 0.1)',
    color: 'rgb(133, 78, 18)',
    fontSize: 11,
    lineHeight: '17px',
  },
  bookPickerFooter: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 8,
    borderTopColor: 'rgba(49, 48, 53, 0.12)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 13,
    paddingRight: 18,
    paddingBottom: 15,
    paddingLeft: 18,
  },
  bookPickerCancel: {
    minHeight: 32,
    borderColor: 'rgba(49, 48, 53, 0.16)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 12,
    paddingLeft: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    color: noteTheme.chromeTextMuted,
    cursor: 'default',
    fontSize: 12,
    fontWeight: 550,
    outline: 'none',
    boxShadow: {
      ':focus-visible': `0 0 0 2px ${noteTheme.focus}`,
    },
  },
  bookPickerCreate: {
    minHeight: 32,
    borderColor: 'rgba(0, 90, 190, 0.22)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 13,
    paddingLeft: 13,
    backgroundColor: {
      'default': 'rgb(0, 113, 227)',
      ':hover': 'rgb(0, 103, 211)',
      ':active': 'rgb(0, 92, 192)',
      ':disabled': 'rgba(0, 113, 227, 0.44)',
    },
    color: 'white',
    cursor: 'default',
    fontSize: 12,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      ':focus-visible': '0 0 0 3px rgba(41, 97, 194, 0.38)',
    },
  },
})
