ALTER TABLE "sync_accounts" ALTER COLUMN "generation" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_accounts" ALTER COLUMN "membership_epoch" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_accounts" ALTER COLUMN "membership_epoch" SET DEFAULT 1;--> statement-breakpoint
ALTER TABLE "sync_accounts" ALTER COLUMN "next_receipt_sequence" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_accounts" ALTER COLUMN "next_receipt_sequence" SET DEFAULT 1;--> statement-breakpoint
ALTER TABLE "sync_accounts" ALTER COLUMN "policy_epoch" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_asset_manifests" ALTER COLUMN "generation" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_asset_manifests" ALTER COLUMN "sequence" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_asset_manifests" ALTER COLUMN "content_length" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_asset_manifests" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_asset_manifests" ALTER COLUMN "received_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_audit_events" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_changes" ALTER COLUMN "generation" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_changes" ALTER COLUMN "sequence" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_changes" ALTER COLUMN "receipt_sequence" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_changes" ALTER COLUMN "received_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_device_credentials" ALTER COLUMN "membership_epoch" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_device_credentials" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_device_credentials" ALTER COLUMN "expires_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_device_credentials" ALTER COLUMN "revoked_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_device_nonces" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_device_nonces" ALTER COLUMN "expires_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_invites" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_invites" ALTER COLUMN "expires_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_invites" ALTER COLUMN "revoked_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_invites" ALTER COLUMN "consumed_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_learning_entities" ALTER COLUMN "generation" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_learning_entities" ALTER COLUMN "source_sequence" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_learning_entities" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_learning_entities" ALTER COLUMN "updated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_learning_tombstones" ALTER COLUMN "generation" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_learning_tombstones" ALTER COLUMN "tombstone_generation" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_learning_tombstones" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_note_snapshots" ALTER COLUMN "generation" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_note_snapshots" ALTER COLUMN "updated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_objects" ALTER COLUMN "generation" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_objects" ALTER COLUMN "content_length" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_objects" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_pairing_sessions" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_pairing_sessions" ALTER COLUMN "expires_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_pairing_sessions" ALTER COLUMN "consumed_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_reset_jobs" ALTER COLUMN "generation" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_reset_jobs" ALTER COLUMN "attempts" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_reset_jobs" ALTER COLUMN "lease_expires_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_reset_jobs" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_reset_jobs" ALTER COLUMN "completed_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_sessions" ALTER COLUMN "expires_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_sessions" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sync_users" ALTER COLUMN "created_at" SET DATA TYPE bigint;