import * as stylex from '@stylexjs/stylex'
import { noteTheme } from './editor/note-shared.stylex'

export const noteInspectorStyles = stylex.create({
  inspector: {
    position: {
      'default': 'relative',
      '@media (max-width: 1024px)': 'absolute',
    },
    zIndex: 3,
    top: {
      'default': 'auto',
      '@media (max-width: 1024px)': 0,
    },
    right: {
      'default': 'auto',
      '@media (max-width: 1024px)': 0,
    },
    bottom: {
      'default': 'auto',
      '@media (max-width: 1024px)': 0,
    },
    display: 'flex',
    width: 292,
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flexDirection: 'column',
    paddingTop: 56,
    borderLeftColor: {
      'default': 'rgba(255, 255, 255, 0.54)',
      '@media (prefers-contrast: more)': 'rgba(0, 0, 0, 0.42)',
    },
    borderLeftStyle: 'solid',
    borderLeftWidth: 1,
    backgroundColor: {
      'default': noteTheme.inspector,
      '@media (prefers-reduced-transparency: reduce)': 'rgb(246, 247, 249)',
      '@media (prefers-contrast: more)': 'rgba(250, 251, 252, 0.98)',
    },
    backdropFilter: {
      'default': 'blur(24px) saturate(145%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': '-12px 0 28px rgba(31, 38, 48, 0.055), inset 1px 0 rgba(255, 255, 255, 0.74)',
      '@media (prefers-contrast: more)': '-1px 0 rgba(0, 0, 0, 0.18)',
    },
  },
  inspectorTitlebar: {
    display: 'flex',
    minHeight: 44,
    flex: '0 0 44px',
    alignItems: 'center',
    paddingRight: 17,
    paddingLeft: 17,
    userSelect: 'none',
  },
  inspectorTitleGroup: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 7,
  },
  inspectorTitle: {
    overflow: 'hidden',
    margin: 0,
    color: noteTheme.chromeText,
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  inspectorCount: {
    minWidth: 17,
    borderRadius: 6,
    paddingRight: 5,
    paddingLeft: 5,
    backgroundColor: 'rgba(61, 68, 78, 0.08)',
    color: noteTheme.chromeTextMuted,
    fontSize: 10,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 550,
    lineHeight: '17px',
    textAlign: 'center',
  },
  learningRow: {
    display: 'flex',
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'space-between',
    marginRight: 17,
    marginLeft: 17,
    borderBottomColor: 'rgba(48, 53, 61, 0.1)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingBottom: 9,
  },
  learningLabel: {
    color: noteTheme.chromeTextMuted,
    fontSize: 11,
    fontWeight: 550,
    letterSpacing: 0,
    lineHeight: '16px',
  },
  learningSwitch: {
    position: 'relative',
    width: 32,
    height: 18,
    flexShrink: 0,
    borderWidth: 0,
    borderRadius: 9,
    padding: 0,
    backgroundColor: 'rgba(78, 83, 92, 0.2)',
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'inset 0 0 0 1px rgba(35, 39, 46, 0.08)',
      ':focus-visible': `0 0 0 2px ${noteTheme.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '120ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  learningSwitchOn: {
    backgroundColor: noteTheme.success,
  },
  learningSwitchThumb: {
    position: 'absolute',
    top: 2,
    left: 2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: 'white',
    boxShadow: '0 1px 3px rgba(24, 28, 35, 0.24)',
    transform: 'translateX(0)',
    transitionDuration: {
      'default': '140ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'transform',
    transitionTimingFunction: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
  },
  learningSwitchThumbOn: {
    transform: 'translateX(14px)',
  },
  inspectorContent: {
    minHeight: 0,
    overflowY: 'auto',
    flex: 1,
    paddingTop: 8,
    paddingRight: 12,
    paddingBottom: 24,
    paddingLeft: 12,
  },
  inspectorSection: {
    marginBottom: 25,
  },
  topicTree: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1,
  },
  entryRow: (depth: number) => ({
    width: '100%',
    height: 31,
    minWidth: 0,
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 7,
    paddingLeft: 6 + depth * 16,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(70, 78, 90, 0.065)',
      ':active': noteTheme.selectedPressed,
    },
    color: noteTheme.chromeText,
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.99)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  }),
  entryRowCurrent: {
    backgroundColor: {
      'default': 'rgba(72, 80, 91, 0.095)',
      ':hover': 'rgba(72, 80, 91, 0.12)',
      '@media (prefers-contrast: more)': 'rgba(55, 62, 72, 0.17)',
    },
  },
  folderEntryButton: {
    display: 'grid',
    width: '100%',
    height: '100%',
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '18px 17px minmax(0, 1fr)',
    gap: 3,
    borderWidth: 0,
    borderRadius: 6,
    padding: 0,
    backgroundColor: 'transparent',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${noteTheme.focus}`,
    },
    color: noteTheme.chromeText,
    cursor: 'default',
    font: 'inherit',
    outline: 'none',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.99)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'transform',
    transitionTimingFunction: 'ease-out',
  },
  topicEntry: {
    display: 'grid',
    width: '100%',
    height: '100%',
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '18px 17px minmax(0, 1fr)',
    gap: 3,
  },
  entryDisclosure: {
    display: 'grid',
    width: 18,
    height: 28,
    alignItems: 'center',
    justifyItems: 'center',
    color: noteTheme.chromeTextQuiet,
  },
  entryDisclosureButton: {
    display: 'grid',
    width: 18,
    height: 28,
    alignItems: 'center',
    justifyItems: 'center',
    borderWidth: 0,
    borderRadius: 5,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(65, 72, 82, 0.09)',
      ':active': noteTheme.selectedPressed,
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${noteTheme.focus}`,
    },
    color: noteTheme.chromeTextQuiet,
    cursor: 'default',
    outline: 'none',
  },
  entryDisclosurePlaceholder: {
    width: 18,
    height: 28,
  },
  folderIcon: {
    color: noteTheme.chromeTextQuiet,
  },
  topicIcon: {
    color: noteTheme.chromeTextQuiet,
  },
  topicIconCurrent: {
    color: noteTheme.chromeTextQuiet,
  },
  cardTopicIcon: {
    position: 'relative',
    display: 'grid',
    width: 17,
    height: 18,
    alignItems: 'center',
    justifyItems: 'center',
    color: noteTheme.chromeTextQuiet,
  },
  topicIconGlyph: {
    gridArea: '1 / 1',
  },
  cardTopicSyncIcon: {
    position: 'absolute',
    right: -1,
    bottom: 1,
    padding: 1,
    backgroundColor: 'rgb(248, 249, 251)',
    color: noteTheme.chromeTextQuiet,
  },
  topicLink: {
    display: 'flex',
    height: '100%',
    minWidth: 0,
    alignItems: 'center',
    borderRadius: 5,
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${noteTheme.focus}`,
    },
    color: noteTheme.chromeText,
    fontSize: 12,
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: '17px',
    outline: 'none',
    textDecoration: 'none',
  },
  topicLinkCurrent: {
    color: noteTheme.chromeText,
    fontWeight: 550,
  },
  entryLabel: {
    overflow: 'hidden',
    minWidth: 0,
    fontSize: 12,
    fontWeight: 'inherit',
    letterSpacing: 0,
    lineHeight: '17px',
    textAlign: 'left',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
})
