import type { DesktopApi } from './contract'
import type { DesktopIpcClient } from './ipc-contract'

export function createDesktopApi(
  services: DesktopIpcClient,
  subscribeConfiguration: DesktopApi['subscribeConfiguration'],
  subscribeNoteSaveRequests: DesktopApi['subscribeNoteSaveRequests'],
  subscribeNoteUpdates: DesktopApi['subscribeNoteUpdates'],
  subscribeP2pStatus: DesktopApi['subscribeP2pStatus'] = () => () => undefined,
  subscribeLearningUpdates: DesktopApi['subscribeLearningUpdates'] = () => () => undefined,
  subscribeSyncServerEvents: DesktopApi['subscribeSyncServerEvents'] = () => () => undefined,
  deviceProvisioning: DesktopApi['deviceProvisioning'] = {
    cancelSelection: async () => undefined,
    clearLocalManagementToken: async () => undefined,
    deleteGalleryAsset: async () => undefined,
    generateLocalManagementToken: async () => { throw new Error('Device provisioning is unavailable') },
    hasLocalManagementToken: async () => false,
    loadGallery: async () => { throw new Error('Device gallery is unavailable') },
    loadTodos: async () => { throw new Error('Device TODO synchronization is unavailable') },
    loadTodoTarget: async () => ({ status: null, target: null }),
    pushTodos: async () => undefined,
    reorderGallery: async () => undefined,
    respondToPairing: async () => undefined,
    saveLocalManagementToken: async () => undefined,
    saveTodoTarget: async () => undefined,
    setGallerySlideshow: async () => undefined,
    selectDevice: async () => undefined,
    subscribeDevices: () => () => undefined,
    subscribePairing: () => () => undefined,
    uploadGalleryAsset: async () => undefined,
  },
): DesktopApi {
  const p2p = services.p2p ?? {
    approvePairing: async () => { throw new Error('P2P sync is unavailable') },
    acceptInvitation: async () => { throw new Error('P2P sync is unavailable') },
    confirmPairing: async () => { throw new Error('P2P sync is unavailable') },
    completePairing: async () => { throw new Error('P2P sync is unavailable') },
    createInvitation: async () => { throw new Error('P2P sync is unavailable') },
    enableDiscovery: async () => { throw new Error('P2P sync is unavailable') },
    getLocalDevice: async () => { throw new Error('P2P sync is unavailable') },
    getPairingRequests: async () => { throw new Error('P2P sync is unavailable') },
    getServerStatus: async () => { throw new Error('Sync Server is unavailable') },
    getStatus: async () => { throw new Error('P2P sync is unavailable') },
    installServerCredential: async () => { throw new Error('Sync Server is unavailable') },
    listDevices: async () => { throw new Error('P2P sync is unavailable') },
    listDiscoveredPeers: async () => { throw new Error('P2P sync is unavailable') },
    requestPairing: async () => { throw new Error('P2P sync is unavailable') },
    removeDevice: async () => { throw new Error('P2P sync is unavailable') },
    updateDeviceName: async () => { throw new Error('P2P sync is unavailable') },
  }
  return {
    deviceProvisioning,
    loadWhiteboardLibrary: () => services.whiteboardLibrary.load(),
    request: request => services.transport.fetch(request),
    saveWhiteboardLibrary: data => services.whiteboardLibrary.save(data),
    p2p,
    subscribeConfiguration,
    subscribeLearningUpdates,
    subscribeNoteSaveRequests,
    subscribeNoteUpdates,
    subscribeP2pStatus,
    subscribeSyncServerEvents,
  }
}
