import type {
  DesktopApi,
  DesktopLearningApi,
  DesktopNoteExternalUpdate,
} from './contract'
import type { DesktopIpcClient } from './ipc-contract'

function createDesktopLearningApi(service: DesktopIpcClient['learning']): DesktopLearningApi {
  return {
    archiveOptimizer: optimizerId => service.archiveOptimizer(optimizerId),
    assignNoteOptimizer: input => service.assignNoteOptimizer(input),
    createOptimizer: input => service.createOptimizer(input),
    getActivitySummary: input => service.getActivitySummary(input),
    getDailyProgress: now => service.getDailyProgress(now),
    getLearningState: targetId => service.getLearningState(targetId),
    getMaintenanceEstimate: () => service.getMaintenanceEstimate(),
    getNoteOptimizer: noteId => service.getNoteOptimizer(noteId),
    getOptimizer: optimizerId => service.getOptimizer(optimizerId),
    getOptimizerNoteCount: optimizerId => service.getOptimizerNoteCount(optimizerId),
    getNextItem: input => service.getNextItem(input),
    getNextNewItem: input => service.getNextNewItem(input),
    getNextReviewItem: input => service.getNextReviewItem(input),
    listNotesWithCards: () => service.listNotesWithCards(),
    listOptimizers: () => service.listOptimizers(),
    listQueue: input => service.listQueue(input),
    listTargets: cardId => service.listTargets(cardId),
    maintainDatabase: () => service.maintainDatabase(),
    optimizeOptimizer: input => service.optimizeOptimizer(input),
    prepareReview: input => service.prepareReview(input),
    rateMultiLineCard: input => service.rateMultiLineCard(input),
    rateTarget: input => service.rateTarget(input),
    resetOptimizerDefaults: (optimizerId, rescheduleNow) => (
      service.resetOptimizerDefaults(optimizerId, rescheduleNow)
    ),
    resetTarget: input => service.resetTarget(input),
    restoreReviewItem: input => service.restoreReviewItem(input),
    undoLastReview: input => service.undoLastReview(input),
    undoReviews: input => service.undoReviews(input),
    saveOptimizer: input => service.saveOptimizer(input),
  }
}

export function createDesktopApi(
  services: DesktopIpcClient,
  subscribeConfiguration: DesktopApi['subscribeConfiguration'],
  subscribeNoteSaveRequests: DesktopApi['subscribeNoteSaveRequests'],
  subscribeNoteUpdates: (listener: (update: DesktopNoteExternalUpdate) => void) => () => void,
): DesktopApi {
  return {
    addShelfSource: input => services.shelf.addSource(input),
    checkAssets: () => services.assets.check(),
    closeBookReadingSession: sessionId => services.books.closeReadingSession(sessionId),
    createBookContext: input => services.books.createContext(input),
    createNote: input => services.notes.createNote(input),
    deleteShelfReading: readingId => services.shelf.deleteReading(readingId),
    getCachedShelfView: input => services.shelf.getCachedView(input),
    getConfiguration: () => services.configuration.get(),
    getNote: input => services.notes.getNote(input),
    getRuntimeInfo: () => services.app.getRuntimeInfo(),
    getShelfAsset: input => services.shelf.getAsset(input),
    getShelfPublicationDetails: input => services.shelf.getPublicationDetails(input),
    getTopicBlock: input => services.notes.getTopicBlock(input),
    importNetworkImage: input => services.assets.importNetworkImage(input),
    isBookReadingAvailable: readingId => services.books.isReadingAvailable(readingId),
    listBookContexts: readingId => services.books.listContexts(readingId),
    listFavoriteNotes: input => services.notes.listFavoriteNotes(input),
    listJournalDates: input => services.journals.listJournalDates(input),
    listNotes: input => services.notes.listNotes(input),
    listPastJournals: input => services.journals.listPastJournals(input),
    listRecentNotes: input => services.notes.listRecentNotes(input),
    learning: createDesktopLearningApi(services.learning),
    listShelfSources: () => services.shelf.listSources(),
    openJournal: input => services.journals.openJournal(input),
    openMostRecentNote: () => services.notes.openMostRecentNote(),
    openShelfReading: input => services.shelf.openReading(input),
    prepareShelfReading: input => services.shelf.prepareReading(input),
    prunePastEmptyJournals: () => services.journals.prunePastEmptyJournals(),
    readShelfReadingRange: input => services.shelf.readReadingRange(input),
    reclaimAssets: input => services.assets.reclaim(input),
    rebindBookContext: input => services.books.rebindContext(input),
    recordNoteOpened: input => services.notes.recordNoteOpened(input),
    refreshShelfView: input => services.shelf.refreshView(input),
    removeShelfSource: sourceId => services.shelf.removeSource(sourceId),
    renameNote: input => services.notes.renameNote(input),
    saveImage: input => services.assets.saveImage(input),
    saveNoteUpdates: input => services.notes.saveNoteUpdates(input),
    searchNotes: input => services.notes.searchNotes(input),
    searchTopicBlocks: input => services.notes.searchTopicBlocks(input),
    setConfiguration: configuration => services.configuration.set(configuration),
    setConfigurationValue: (path, value) => services.configuration.setValue(path, value),
    setNoteFavorite: input => services.notes.setNoteFavorite(input),
    selectBookContext: input => services.books.selectContext(input),
    showColumnVisibilityMenu: input => services.window.showColumnVisibilityMenu(input),
    subscribeConfiguration,
    subscribeNoteSaveRequests,
    subscribeNoteUpdates,
    updateShelfSource: input => services.shelf.updateSource(input),
  }
}
