import * as stylex from '@stylexjs/stylex'

const colors = {
  canvas: '#ffffff',
  accent: 'rgb(0, 113, 227)',
  chromeText: 'rgba(30, 29, 32, 0.86)',
  chromeTextMuted: 'rgba(48, 46, 51, 0.66)',
  chromeTextQuiet: 'rgba(48, 46, 51, 0.5)',
  focus: 'rgba(41, 97, 194, 0.85)',
  selected: 'rgba(73, 72, 77, 0.10)',
  selectedPressed: 'rgba(76, 84, 96, 0.15)',
  sidebar: 'rgba(255, 255, 255, 0.48)',
} as const

export const editorRouteStyles = stylex.create({
  page: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    height: '100vh',
    minHeight: 0,
    overflow: 'hidden',
    backgroundColor: colors.canvas,
    color: colors.chromeText,
  },
  sidebar: {
    position: 'relative',
    zIndex: 2,
    display: 'flex',
    width: 248,
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flexDirection: 'column',
    marginTop: 8,
    marginBottom: 8,
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.62)',
      '@media (prefers-contrast: more)': 'rgba(0, 0, 0, 0.42)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 18,
    backgroundColor: {
      'default': colors.sidebar,
      '@media (prefers-reduced-transparency: reduce)': 'rgba(240, 242, 245, 0.98)',
      '@media (prefers-contrast: more)': 'rgba(248, 249, 251, 0.96)',
    },
    backdropFilter: {
      'default': 'blur(30px) saturate(170%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 12px 30px rgba(31, 38, 48, 0.13), 0 2px 7px rgba(31, 38, 48, 0.09), inset 0 1px rgba(255, 255, 255, 0.8), inset 1px 0 rgba(255, 255, 255, 0.48)',
  },
  sidebarTitlebar: {
    display: 'flex',
    minHeight: 40,
    alignItems: 'center',
    userSelect: 'none',
  },
  sidebarToggle: {
    position: 'absolute',
    zIndex: 4,
    top: 12,
    display: 'grid',
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyItems: 'center',
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.38)',
      ':active': 'rgba(72, 70, 76, 0.13)',
    },
    color: colors.chromeTextMuted,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  sidebarContent: {
    minHeight: 0,
    overflowY: 'auto',
    paddingTop: 20,
    paddingRight: 10,
    paddingBottom: 20,
    paddingLeft: 10,
  },
  sourceGroup: {
    marginBottom: 17,
  },
  navigationHeading: {
    marginTop: 0,
    marginRight: 8,
    marginBottom: 6,
    marginLeft: 8,
    color: colors.chromeTextMuted,
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  groupHeading: {
    display: 'flex',
    width: '100%',
    height: 28,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 0,
    paddingRight: 7,
    paddingLeft: 8,
    backgroundColor: 'transparent',
    color: colors.chromeTextMuted,
    cursor: 'pointer',
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `inset 0 0 0 2px ${colors.focus}`,
    },
  },
  disclosureIcon: {
    display: 'grid',
    width: 14,
    height: 14,
    alignItems: 'center',
    justifyItems: 'center',
    color: colors.chromeTextQuiet,
  },
  sourceList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
  animatedSourceList: {
    overflow: 'hidden',
  },
  sourceItem: {
    display: 'grid',
    width: '100%',
    height: 31,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '20px minmax(0, 1fr) auto',
    gap: 7,
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 9,
    paddingLeft: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(76, 84, 96, 0.07)',
      ':active': colors.selectedPressed,
    },
    color: colors.chromeText,
    cursor: 'default',
    fontSize: 13,
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: '18px',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.985)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, border-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  sourceItemSelected: {
    borderColor: {
      'default': 'rgba(70, 78, 90, 0.04)',
      '@media (prefers-contrast: more)': 'rgba(0, 0, 0, 0.5)',
    },
    backgroundColor: {
      'default': colors.selected,
      '@media (prefers-contrast: more)': 'rgba(55, 62, 72, 0.16)',
    },
    fontWeight: 550,
  },
  sourceIcon: {
    width: 17,
    height: 17,
    justifySelf: 'center',
    color: colors.chromeTextMuted,
  },
  sourceIconSelected: {
    color: colors.accent,
  },
  sourceLabel: {
    overflow: 'hidden',
    textAlign: 'left',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  sourceLabelSelected: {
    color: colors.accent,
  },
  sourceMeta: {
    minWidth: 18,
    borderRadius: 7,
    paddingRight: 5,
    paddingLeft: 5,
    backgroundColor: 'rgba(60, 68, 79, 0.09)',
    color: colors.chromeTextMuted,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    lineHeight: '18px',
    textAlign: 'center',
  },
  workspace: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflow: 'hidden',
    marginLeft: -10,
    paddingLeft: 10,
    backgroundColor: colors.canvas,
  },
  saveError: {
    position: 'absolute',
    zIndex: 2,
    top: 12,
    left: '50%',
    maxWidth: 'min(520px, calc(100% - 32px))',
    borderRadius: 8,
    paddingBlock: 8,
    paddingInline: 12,
    backgroundColor: 'rgba(115, 28, 28, 0.9)',
    color: '#ffffff',
    fontSize: 12,
    transform: 'translateX(-50%)',
  },
})
