import * as stylex from '@stylexjs/stylex'

const colors = {
  canvas: '#ffffff',
  accent: 'rgb(0, 113, 227)',
  chromeText: 'rgba(30, 29, 32, 0.86)',
  chromeTextMuted: 'rgba(48, 46, 51, 0.66)',
  chromeTextQuiet: 'rgba(48, 46, 51, 0.5)',
  focus: 'rgba(41, 97, 194, 0.85)',
  selected: 'rgba(73, 72, 77, 0.10)',
  selectedPressed: 'rgba(76, 84, 96, 0.15)',
  sidebar: 'rgba(255, 255, 255, 0.48)',
  inspector: 'rgba(248, 249, 251, 0.74)',
  success: 'rgb(52, 145, 80)',
  warning: 'rgb(198, 119, 28)',
} as const

export const editorRouteStyles = stylex.create({
  page: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    height: '100vh',
    minHeight: 0,
    overflow: 'hidden',
    backgroundColor: colors.canvas,
    color: colors.chromeText,
  },
  sidebar: {
    position: 'relative',
    zIndex: 2,
    display: 'flex',
    width: 248,
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flexDirection: 'column',
    marginTop: 8,
    marginBottom: 8,
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.62)',
      '@media (prefers-contrast: more)': 'rgba(0, 0, 0, 0.42)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 18,
    backgroundColor: {
      'default': colors.sidebar,
      '@media (prefers-reduced-transparency: reduce)': 'rgba(240, 242, 245, 0.98)',
      '@media (prefers-contrast: more)': 'rgba(248, 249, 251, 0.96)',
    },
    backdropFilter: {
      'default': 'blur(30px) saturate(170%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 12px 30px rgba(31, 38, 48, 0.13), 0 2px 7px rgba(31, 38, 48, 0.09), inset 0 1px rgba(255, 255, 255, 0.8), inset 1px 0 rgba(255, 255, 255, 0.48)',
  },
  sidebarTitlebar: {
    display: 'flex',
    minHeight: 40,
    alignItems: 'center',
    userSelect: 'none',
  },
  sidebarToggle: {
    position: 'absolute',
    zIndex: 4,
    top: 12,
    display: 'grid',
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyItems: 'center',
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.38)',
      ':active': 'rgba(72, 70, 76, 0.13)',
    },
    color: colors.chromeTextMuted,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  sidebarContent: {
    minHeight: 0,
    overflowY: 'auto',
    paddingTop: 20,
    paddingRight: 10,
    paddingBottom: 20,
    paddingLeft: 10,
  },
  sourceGroup: {
    marginBottom: 17,
  },
  navigationHeading: {
    marginTop: 0,
    marginRight: 8,
    marginBottom: 6,
    marginLeft: 8,
    color: colors.chromeTextMuted,
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  groupHeading: {
    display: 'flex',
    width: '100%',
    height: 28,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 0,
    paddingRight: 7,
    paddingLeft: 8,
    backgroundColor: 'transparent',
    color: colors.chromeTextMuted,
    cursor: 'pointer',
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `inset 0 0 0 2px ${colors.focus}`,
    },
  },
  disclosureIcon: {
    display: 'grid',
    width: 14,
    height: 14,
    alignItems: 'center',
    justifyItems: 'center',
    color: colors.chromeTextQuiet,
  },
  sourceList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
  animatedSourceList: {
    overflow: 'hidden',
  },
  sourceItem: {
    display: 'grid',
    width: '100%',
    height: 31,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '20px minmax(0, 1fr) auto',
    gap: 7,
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 9,
    paddingLeft: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(76, 84, 96, 0.07)',
      ':active': colors.selectedPressed,
    },
    color: colors.chromeText,
    cursor: 'default',
    fontSize: 13,
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: '18px',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.985)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, border-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  sourceItemSelected: {
    borderColor: {
      'default': 'rgba(70, 78, 90, 0.04)',
      '@media (prefers-contrast: more)': 'rgba(0, 0, 0, 0.5)',
    },
    backgroundColor: {
      'default': colors.selected,
      '@media (prefers-contrast: more)': 'rgba(55, 62, 72, 0.16)',
    },
    fontWeight: 550,
  },
  sourceIcon: {
    width: 17,
    height: 17,
    justifySelf: 'center',
    color: colors.chromeTextMuted,
  },
  sourceIconSelected: {
    color: colors.accent,
  },
  sourceLabel: {
    overflow: 'hidden',
    textAlign: 'left',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  sourceLabelSelected: {
    color: colors.accent,
  },
  sourceMeta: {
    minWidth: 18,
    borderRadius: 7,
    paddingRight: 5,
    paddingLeft: 5,
    backgroundColor: 'rgba(60, 68, 79, 0.09)',
    color: colors.chromeTextMuted,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    lineHeight: '18px',
    textAlign: 'center',
  },
  workspace: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflow: 'hidden',
    marginLeft: -10,
    paddingLeft: 10,
    backgroundColor: colors.canvas,
  },
  inspector: {
    position: {
      'default': 'relative',
      '@media (max-width: 1024px)': 'absolute',
    },
    zIndex: 3,
    top: {
      'default': 'auto',
      '@media (max-width: 1024px)': 0,
    },
    right: {
      'default': 'auto',
      '@media (max-width: 1024px)': 0,
    },
    bottom: {
      'default': 'auto',
      '@media (max-width: 1024px)': 0,
    },
    display: 'flex',
    width: 292,
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flexDirection: 'column',
    borderLeftColor: {
      'default': 'rgba(255, 255, 255, 0.54)',
      '@media (prefers-contrast: more)': 'rgba(0, 0, 0, 0.42)',
    },
    borderLeftStyle: 'solid',
    borderLeftWidth: 1,
    backgroundColor: {
      'default': colors.inspector,
      '@media (prefers-reduced-transparency: reduce)': 'rgb(246, 247, 249)',
      '@media (prefers-contrast: more)': 'rgba(250, 251, 252, 0.98)',
    },
    backdropFilter: {
      'default': 'blur(24px) saturate(145%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': '-12px 0 28px rgba(31, 38, 48, 0.055), inset 1px 0 rgba(255, 255, 255, 0.74)',
      '@media (prefers-contrast: more)': '-1px 0 rgba(0, 0, 0, 0.18)',
    },
  },
  inspectorTitlebar: {
    display: 'flex',
    minHeight: 52,
    flex: '0 0 52px',
    alignItems: 'center',
    paddingRight: 52,
    paddingLeft: 17,
    userSelect: 'none',
  },
  inspectorTitleGroup: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 7,
  },
  inspectorTitle: {
    overflow: 'hidden',
    margin: 0,
    color: colors.chromeText,
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  inspectorCount: {
    minWidth: 17,
    borderRadius: 6,
    paddingRight: 5,
    paddingLeft: 5,
    backgroundColor: 'rgba(61, 68, 78, 0.08)',
    color: colors.chromeTextMuted,
    fontSize: 10,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 550,
    lineHeight: '17px',
    textAlign: 'center',
  },
  inspectorContent: {
    minHeight: 0,
    overflowY: 'auto',
    paddingTop: 8,
    paddingRight: 12,
    paddingBottom: 24,
    paddingLeft: 12,
  },
  inspectorSection: {
    marginBottom: 25,
  },
  inspectorSectionHeading: {
    display: 'flex',
    height: 25,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: 7,
    paddingLeft: 7,
  },
  inspectorSectionTitle: {
    margin: 0,
    color: colors.chromeTextMuted,
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '16px',
  },
  inspectorSectionMeta: {
    color: colors.warning,
    fontSize: 10,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 550,
    lineHeight: '16px',
  },
  topicTree: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1,
  },
  topicRow: {
    display: 'grid',
    width: '100%',
    height: 31,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '14px minmax(0, 1fr) 16px',
    gap: 5,
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 7,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(70, 78, 90, 0.065)',
      ':active': colors.selectedPressed,
    },
    color: colors.chromeText,
    cursor: 'default',
    fontSize: 12,
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: '17px',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.99)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  topicRowSelected: {
    backgroundColor: {
      'default': 'rgba(72, 80, 91, 0.095)',
      ':hover': 'rgba(72, 80, 91, 0.12)',
      '@media (prefers-contrast: more)': 'rgba(55, 62, 72, 0.17)',
    },
    fontWeight: 550,
  },
  topicDepth0: {
    paddingLeft: 6,
  },
  topicDepth1: {
    paddingLeft: 22,
  },
  topicDepth2: {
    paddingLeft: 38,
  },
  topicDisclosure: {
    display: 'grid',
    width: 14,
    height: 14,
    alignItems: 'center',
    justifyItems: 'center',
    color: colors.chromeTextQuiet,
  },
  topicLeaf: {
    width: 3,
    height: 3,
    borderRadius: 99,
    backgroundColor: 'rgba(64, 69, 77, 0.28)',
  },
  topicLabel: {
    overflow: 'hidden',
    textAlign: 'left',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  topicStatus: {
    display: 'grid',
    width: 16,
    height: 16,
    alignItems: 'center',
    justifyItems: 'center',
    color: colors.chromeTextQuiet,
  },
  topicStatusCurrent: {
    color: colors.accent,
  },
  topicStatusDue: {
    color: colors.warning,
  },
  topicStatusLearned: {
    color: colors.success,
  },
  learningSection: {
    marginBottom: 0,
  },
  learningState: {
    display: 'flex',
    alignItems: 'center',
    gap: 5,
    color: colors.chromeTextMuted,
    fontSize: 10,
    fontWeight: 550,
    lineHeight: '16px',
  },
  learningStateDot: {
    width: 5,
    height: 5,
    borderRadius: 99,
    backgroundColor: colors.warning,
    boxShadow: '0 0 0 2px rgba(198, 119, 28, 0.12)',
  },
  learningDetails: {
    display: 'flex',
    marginTop: 7,
    marginRight: 7,
    marginBottom: 18,
    marginLeft: 7,
    flexDirection: 'column',
    gap: 9,
  },
  learningDetail: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 12,
  },
  learningTerm: {
    color: colors.chromeTextMuted,
    fontSize: 11,
    letterSpacing: 0,
    lineHeight: '17px',
  },
  learningValue: {
    margin: 0,
    color: colors.chromeText,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 550,
    lineHeight: '17px',
    textAlign: 'right',
  },
  learningValueDue: {
    color: colors.warning,
  },
  learningProgressHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginRight: 7,
    marginBottom: 7,
    marginLeft: 7,
    color: colors.chromeTextMuted,
    fontSize: 10,
    fontVariantNumeric: 'tabular-nums',
    lineHeight: '15px',
  },
  learningProgressTrack: {
    height: 3,
    overflow: 'hidden',
    marginRight: 7,
    marginLeft: 7,
    borderRadius: 99,
    backgroundColor: 'rgba(58, 67, 78, 0.11)',
  },
  learningProgressFill: {
    width: '50%',
    height: '100%',
    borderRadius: 99,
    backgroundColor: colors.success,
  },
  inspectorToggle: {
    position: 'absolute',
    zIndex: 5,
    top: 12,
    right: 12,
    display: 'grid',
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyItems: 'center',
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(76, 84, 96, 0.07)',
      ':active': 'rgba(72, 70, 76, 0.13)',
    },
    color: colors.chromeTextMuted,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  saveError: {
    position: 'absolute',
    zIndex: 2,
    top: 12,
    left: '50%',
    maxWidth: 'min(520px, calc(100% - 32px))',
    borderRadius: 8,
    paddingBlock: 8,
    paddingInline: 12,
    backgroundColor: 'rgba(115, 28, 28, 0.9)',
    color: '#ffffff',
    fontSize: 12,
    transform: 'translateX(-50%)',
  },
})
