import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'rgb(28, 94, 196)',
  accentSoft: 'rgba(28, 94, 196, 0.1)',
  error: 'rgb(170, 48, 48)',
  focus: 'rgba(41, 97, 194, 0.82)',
  secondaryText: 'rgba(50, 54, 62, 0.58)',
  text: 'rgba(24, 26, 31, 0.92)',
} as const

export const journalRouteStyles = stylex.create({
  page: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    backgroundColor: 'rgb(255, 255, 255)',
    color: colors.text,
  },
  scrollEdge: {
    position: 'absolute',
    zIndex: 10,
    top: 0,
    right: 0,
    left: 0,
    height: 60,
    pointerEvents: 'none',
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.94)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(255, 255, 255)',
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    backdropFilter: {
      'default': 'blur(14px) saturate(150%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 12px 18px 6px rgba(255, 255, 255, 0.94)',
  },
  viewport: {
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflowX: 'hidden',
    overflowY: 'auto',
    overscrollBehaviorY: 'contain',
    paddingTop: 72,
    scrollbarGutter: 'stable',
  },
  feed: {
    position: 'relative',
    width: 'min(100%, 940px)',
    marginRight: 'auto',
    marginLeft: 'auto',
  },
  feedHeight: (height: number) => ({
    height,
  }),
  virtualRow: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    paddingRight: {
      'default': 56,
      '@media (max-width: 900px)': 32,
    },
    paddingLeft: {
      'default': 56,
      '@media (max-width: 900px)': 32,
    },
  },
  virtualRowOffset: (offset: number) => ({
    transform: `translateY(${offset}px)`,
  }),
  day: {
    width: '100%',
    minHeight: 340,
    paddingTop: 28,
    paddingBottom: 64,
    borderTopColor: 'rgba(75, 80, 90, 0.13)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
  },
  firstDay: {
    paddingTop: 16,
    borderTopWidth: 0,
  },
  dayHeader: {
    minWidth: 0,
    marginBottom: 4,
    paddingInlineStart: 'calc(max(4rem, calc(50% - 20rem)) + 1.5rem + 2px)',
  },
  dayTitle: {
    minWidth: 0,
    margin: 0,
    color: colors.text,
    fontSize: 18,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '26px',
    textWrap: 'balance',
  },
  todayLabel: {
    display: 'inline-block',
    marginInlineStart: 8,
    color: colors.secondaryText,
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '18px',
    verticalAlign: 'baseline',
  },
  editorRegion: {
    minHeight: 230,
  },
  inlineStatus: {
    display: 'flex',
    minHeight: 230,
    alignItems: 'flex-start',
    gap: 8,
    paddingTop: 12,
    color: colors.secondaryText,
    fontSize: 13,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  inlineError: {
    color: colors.error,
  },
  validationError: {
    marginBottom: 14,
    paddingTop: 9,
    paddingRight: 12,
    paddingBottom: 9,
    paddingLeft: 12,
    borderLeftColor: colors.error,
    borderLeftStyle: 'solid',
    borderLeftWidth: 2,
    backgroundColor: 'rgba(190, 52, 52, 0.06)',
    color: colors.error,
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: '18px',
  },
  feedStatus: {
    display: 'flex',
    height: 96,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    color: colors.secondaryText,
    fontSize: 13,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  initialStatus: {
    display: 'flex',
    width: '100%',
    minHeight: 0,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    color: colors.secondaryText,
    fontSize: 13,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  statusIcon: {
    width: 17,
    height: 17,
    flex: '0 0 17px',
  },
  loadingIcon: {
    animationDuration: '900ms',
    animationIterationCount: 'infinite',
    animationName: stylex.keyframes({
      to: { transform: 'rotate(360deg)' },
    }),
    animationTimingFunction: 'linear',
  },
  retryButton: {
    minHeight: 28,
    borderColor: 'rgba(72, 78, 89, 0.18)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: {
      'default': 'rgba(248, 249, 251, 0.88)',
      ':hover': 'rgb(241, 244, 248)',
      ':active': 'rgb(232, 236, 242)',
    },
    color: colors.text,
    cursor: 'default',
    fontSize: 12,
    fontWeight: 550,
    letterSpacing: 0,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  calendarRoot: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
  },
  calendarButton: {
    display: 'grid',
    width: 32,
    height: 32,
    flex: '0 0 32px',
    alignItems: 'center',
    justifyItems: 'center',
    borderWidth: 0,
    borderRadius: 16,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(52, 52, 54, 0.06)',
      ':active': 'rgba(52, 52, 54, 0.12)',
    },
    color: {
      'default': 'rgba(31, 35, 42, 0.82)',
      ':hover': 'rgba(22, 25, 31, 0.94)',
    },
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgba(44, 44, 46, 0.68)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.96)',
    },
    transitionDuration: {
      'default': '110ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  calendarButtonOpen: {
    backgroundColor: 'rgba(255, 255, 255, 0.46)',
    boxShadow: '0 5px 14px rgba(28, 28, 30, 0.1), 0 0 0 0.5px rgba(72, 72, 74, 0.2), inset 0 1px rgba(255, 255, 255, 0.96), inset 0 -1px rgba(72, 72, 74, 0.14)',
  },
  calendarPopover: {
    position: 'absolute',
    zIndex: 40,
    top: 42,
    right: 0,
    width: 304,
    overflow: 'hidden',
    padding: 10,
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.94)',
      '@media (prefers-contrast: more)': 'rgba(28, 28, 30, 0.72)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 22,
    backgroundColor: {
      'default': 'rgba(246, 246, 246, 0.74)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 250, 250)',
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    backdropFilter: {
      'default': 'saturate(118%) contrast(1.045) brightness(1.015)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': '0 22px 48px rgba(28, 28, 30, 0.16), 0 5px 14px rgba(28, 28, 30, 0.09), 0 0 0 0.5px rgba(72, 72, 74, 0.18), inset 0 1px rgba(255, 255, 255, 0.98), inset 1px 0 rgba(255, 255, 255, 0.62), inset 0 -1px rgba(72, 72, 74, 0.16), inset -1px 0 rgba(72, 72, 74, 0.1)',
      '@media (prefers-contrast: more)': '0 18px 48px rgba(28, 28, 30, 0.24), 0 0 0 1px rgba(28, 28, 30, 0.36), inset 0 1px rgba(255, 255, 255, 0.98)',
    },
    transformOrigin: 'top right',
    willChange: 'opacity, transform',
  },
  calendarGlassHighlight: {
    position: 'absolute',
    zIndex: 0,
    top: 0,
    right: 8,
    left: 8,
    height: 92,
    borderRadius: '20px 20px 50% 50%',
    backgroundImage: {
      'default': 'radial-gradient(110% 86% at 18% 0%, rgba(255, 255, 255, 0.78) 0%, rgba(255, 255, 255, 0.2) 40%, rgba(255, 255, 255, 0) 72%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    pointerEvents: 'none',
  },
  calendarGlassEdge: {
    position: 'absolute',
    zIndex: 1,
    inset: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.86)',
    borderRightColor: 'rgba(72, 72, 74, 0.09)',
    borderBottomColor: 'rgba(72, 72, 74, 0.15)',
    borderLeftColor: 'rgba(255, 255, 255, 0.54)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 21,
    boxShadow: 'inset 0 2px 5px rgba(255, 255, 255, 0.22), inset 0 -2px 5px rgba(72, 72, 74, 0.035)',
    pointerEvents: 'none',
  },
  calendarContent: {
    position: 'relative',
    zIndex: 2,
  },
  calendarLoading: {
    opacity: 0.72,
  },
  visuallyHidden: {
    position: 'absolute',
    width: 1,
    height: 1,
    overflow: 'hidden',
    padding: 0,
    borderWidth: 0,
    clip: 'rect(0 0 0 0)',
    clipPath: 'inset(50%)',
    whiteSpace: 'nowrap',
  },
})

export const journalCalendarStyles = stylex.create({
  navigation: {
    display: 'grid',
    height: 34,
    gridTemplateColumns: '32px minmax(0, 1fr) 32px',
    alignItems: 'center',
    gap: 4,
    marginBottom: 8,
  },
  navigationButton: {
    display: 'grid',
    width: 32,
    height: 32,
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 16,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(52, 52, 54, 0.06)',
      ':active': 'rgba(52, 52, 54, 0.11)',
      ':disabled': 'transparent',
    },
    color: {
      'default': 'rgba(27, 31, 38, 0.84)',
      ':disabled': 'rgba(42, 47, 56, 0.2)',
    },
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgba(44, 44, 46, 0.68)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.96)',
      ':disabled': 'scale(1)',
    },
    transitionDuration: {
      'default': '110ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  monthLabel: {
    overflow: 'hidden',
    color: 'rgba(27, 31, 38, 0.9)',
    fontSize: 13,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '20px',
    textAlign: 'center',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  weekdays: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    marginBottom: 2,
  },
  weekday: {
    paddingTop: 5,
    paddingBottom: 7,
    color: 'rgba(47, 53, 62, 0.48)',
    fontSize: 10,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '12px',
    textAlign: 'center',
  },
  calendar: {
    width: '100%',
    maxWidth: '100%',
    borderWidth: 0,
    backgroundColor: 'transparent',
    color: colors.text,
    fontFamily: 'inherit',
    fontSize: 0,
    lineHeight: 1,
  },
  tile: {
    position: 'relative',
    display: 'grid',
    height: 38,
    minWidth: 0,
    placeItems: 'center',
    appearance: 'none',
    borderWidth: 0,
    borderRadius: 19,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(52, 52, 54, 0.06)',
      ':active': 'rgba(52, 52, 54, 0.11)',
    },
    color: 'rgba(29, 33, 40, 0.88)',
    cursor: 'default',
    fontFamily: 'inherit',
    fontSize: 12,
    fontWeight: 520,
    letterSpacing: 0,
    lineHeight: '16px',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':hover': 'inset 0 1px rgba(255, 255, 255, 0.86)',
      ':focus-visible': '0 0 0 2px rgba(44, 44, 46, 0.68)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.93)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  tileHidden: {
    visibility: 'hidden',
    pointerEvents: 'none',
  },
  tileDisabled: {
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'transparent',
      ':active': 'transparent',
    },
    color: 'rgba(42, 47, 56, 0.2)',
    boxShadow: 'none',
    transform: 'none',
  },
  tileToday: {
    backgroundColor: 'rgba(255, 255, 255, 0.34)',
    color: 'rgba(24, 28, 34, 0.94)',
    fontWeight: 650,
    boxShadow: {
      'default': 'inset 0 0 0 1px rgba(34, 39, 47, 0.2), inset 0 1px 1px rgba(255, 255, 255, 0.9)',
      '@media (prefers-contrast: more)': 'inset 0 0 0 2px rgb(34, 39, 47)',
    },
  },
  tileSelected: {
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.58)',
      ':hover': 'rgba(255, 255, 255, 0.68)',
      ':active': 'rgba(52, 52, 54, 0.12)',
    },
    color: 'rgba(20, 24, 30, 0.96)',
    boxShadow: '0 4px 10px rgba(28, 28, 30, 0.11), 0 0 0 0.5px rgba(72, 72, 74, 0.24), inset 0 1px rgba(255, 255, 255, 0.98), inset 0 -1px rgba(72, 72, 74, 0.14)',
  },
  presence: {
    position: 'absolute',
    bottom: 3,
    left: '50%',
    width: 3,
    height: 3,
    borderRadius: '50%',
    backgroundColor: 'rgba(35, 40, 48, 0.56)',
    transform: 'translateX(-50%)',
  },
  presenceSelected: {
    backgroundColor: 'rgba(25, 29, 36, 0.72)',
  },
})
