import * as stylex from '@stylexjs/stylex'

const colors = {
  focus: 'rgba(34, 38, 45, 0.72)',
  text: 'rgba(25, 28, 34, 0.9)',
  textMuted: 'rgba(49, 54, 63, 0.62)',
} as const

export const learningRouteStyles = stylex.create({
  page: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flexDirection: 'column',
    paddingTop: 56,
    backgroundColor: 'rgb(248, 249, 251)',
    color: colors.text,
  },
  tabRegion: {
    position: 'relative',
    zIndex: 2,
    display: 'flex',
    width: '100%',
    flex: '0 0 auto',
    justifyContent: 'center',
    paddingTop: 12,
    paddingRight: 20,
    paddingLeft: 20,
  },
  tabList: {
    position: 'relative',
    display: 'grid',
    width: 'min(196px, 100%)',
    height: 32,
    isolation: 'isolate',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 2,
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.88)',
      '@media (prefers-contrast: more)': 'rgba(39, 44, 52, 0.72)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    padding: 3,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.06)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(235, 239, 245)',
      '@media (prefers-contrast: more)': 'rgb(245, 247, 250)',
    },
    backgroundImage: {
      'default': 'radial-gradient(circle 72px at var(--learning-glass-light-x, 50%) var(--learning-glass-light-y, 0%), rgba(255, 255, 255, 0.82) 0%, rgba(255, 255, 255, 0.13) 36%, transparent 69%), linear-gradient(112deg, rgba(255, 255, 255, 0.24), rgba(255, 255, 255, 0.04) 52%, rgba(255, 255, 255, 0.2))',
      '@media (prefers-reduced-transparency: reduce)': 'none',
      '@media (prefers-contrast: more)': 'none',
    },
    backdropFilter: {
      'default': 'saturate(165%) contrast(1.045) brightness(1.015)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': '0 3px 8px rgba(32, 42, 58, 0.08), 0 1px 2px rgba(32, 42, 58, 0.06), inset 0 1px rgba(255, 255, 255, 0.78)',
      '@media (prefers-contrast: more)': '0 8px 20px rgba(31, 37, 47, 0.16), 0 0 0 1px rgba(39, 44, 52, 0.42), inset 0 1px rgba(255, 255, 255, 0.94)',
    },
    userSelect: 'none',
  },
  tab: {
    position: 'relative',
    zIndex: 3,
    display: 'grid',
    height: 24,
    minWidth: 0,
    alignItems: 'center',
    justifyItems: 'center',
    borderWidth: 0,
    borderRadius: 7,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: 'transparent',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    color: colors.textMuted,
    cursor: 'default',
    outline: 'none',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.975)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'color, transform',
    transitionTimingFunction: 'ease-out',
  },
  tabSelected: {
    color: colors.text,
  },
  selectionIndicator: {
    position: 'absolute',
    zIndex: 0,
    inset: 0,
    borderRadius: 7,
    backgroundColor: {
      'default': 'rgba(42, 47, 55, 0.075)',
      '@media (prefers-reduced-transparency: reduce)': 'rgba(42, 47, 55, 0.1)',
      '@media (prefers-contrast: more)': 'rgba(30, 34, 40, 0.16)',
    },
    pointerEvents: 'none',
    willChange: 'transform',
  },
  tabLabel: {
    position: 'relative',
    zIndex: 1,
    overflow: 'hidden',
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    textShadow: '0 1px rgba(255, 255, 255, 0.72)',
    whiteSpace: 'nowrap',
  },
  panelRegion: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
  },
  panel: {
    width: '100%',
    minWidth: 0,
    minHeight: 0,
  },
})
