import * as stylex from '@stylexjs/stylex'

const spin = stylex.keyframes({
  to: { transform: 'rotate(360deg)' },
})

const colors = {
  accent: 'rgb(0, 113, 227)',
  danger: 'rgb(166, 53, 53)',
  focus: 'rgba(0, 96, 204, 0.72)',
  line: 'rgba(55, 61, 70, 0.11)',
  muted: 'rgba(48, 53, 61, 0.58)',
  text: 'rgba(24, 27, 32, 0.92)',
} as const

export const learningOptimizerStyles = stylex.create({
  workspace: {
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flexDirection: 'column',
  },
  detailPage: {
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    paddingTop: 56,
    backgroundColor: 'rgb(255, 255, 255)',
    color: colors.text,
  },
  listWorkspace: {
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
  },
  listScroll: {
    width: '100%',
    minHeight: 0,
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    paddingTop: 16,
    paddingRight: 'clamp(20px, 5vw, 54px)',
    paddingBottom: 36,
    paddingLeft: 'clamp(20px, 5vw, 54px)',
  },
  listContent: {
    width: 'min(820px, 100%)',
    marginRight: 'auto',
    marginLeft: 'auto',
  },
  listHeader: {
    display: 'flex',
    minHeight: 74,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 24,
    paddingRight: 4,
    paddingLeft: 4,
  },
  listHeading: {
    minWidth: 0,
  },
  listTitle: {
    overflow: 'hidden',
    margin: 0,
    color: colors.text,
    fontSize: 20,
    fontWeight: 690,
    letterSpacing: 0,
    lineHeight: '27px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  listSummary: {
    marginTop: 3,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: colors.muted,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    letterSpacing: 0,
    lineHeight: '16px',
  },
  liquidPrimaryButton: {
    display: 'inline-flex',
    height: 34,
    flex: '0 0 auto',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderColor: {
      'default': 'rgba(0, 79, 166, 0.32)',
      '@media (prefers-contrast: more)': 'rgb(0, 72, 153)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    paddingRight: 12,
    paddingLeft: 11,
    backgroundColor: {
      'default': colors.accent,
      ':hover': 'rgb(0, 103, 212)',
      ':active': 'rgb(0, 91, 190)',
      '@media (prefers-reduced-transparency: reduce)': colors.accent,
      '@media (prefers-contrast: more)': 'rgb(0, 92, 196)',
    },
    boxShadow: {
      'default': '0 2px 5px -2px rgba(0, 76, 166, 0.38)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
      '@media (prefers-contrast: more)': '0 0 0 1px rgb(0, 62, 133)',
    },
    color: 'white',
    cursor: 'default',
    fontSize: 11,
    fontWeight: 640,
    letterSpacing: 0,
    lineHeight: '16px',
    outline: 'none',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.965)',
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
    transitionDuration: {
      'default': '110ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  optimizerList: {
    display: 'flex',
    width: '100%',
    flexDirection: 'column',
    borderTopColor: 'rgba(55, 61, 70, 0.11)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    borderBottomColor: 'rgba(55, 61, 70, 0.11)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
  },
  optimizerListItem: {
    width: '100%',
  },
  optimizerRow: {
    display: 'grid',
    width: '100%',
    minHeight: 64,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: {
      'default': '42px minmax(0, 1fr) minmax(290px, auto) 20px',
      '@media (max-width: 760px)': '42px minmax(0, 1fr) 20px',
    },
    gap: 10,
    borderBottomColor: 'rgba(55, 61, 70, 0.08)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    borderRadius: {
      'default': 0,
      ':hover': 8,
      ':active': 8,
    },
    paddingRight: 10,
    paddingLeft: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(70, 79, 93, 0.05)',
      ':active': 'rgba(70, 79, 93, 0.085)',
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `inset 0 0 0 2px ${colors.focus}`,
    },
    color: colors.text,
    outline: 'none',
    textDecoration: 'none',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.995)',
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  optimizerIcon: {
    display: 'grid',
    width: 32,
    height: 32,
    placeItems: 'center',
    borderRadius: 8,
    backgroundColor: 'rgba(0, 113, 227, 0.1)',
    color: colors.accent,
    boxShadow: 'inset 0 0 0 0.5px rgba(0, 88, 184, 0.12)',
  },
  optimizerIconGlobal: {
    backgroundColor: 'rgba(0, 113, 227, 0.16)',
  },
  optimizerIdentity: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
  },
  optimizerName: {
    overflow: 'hidden',
    color: colors.text,
    fontSize: 13,
    fontWeight: 620,
    letterSpacing: 0,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  optimizerKind: {
    overflow: 'hidden',
    marginTop: 1,
    color: colors.muted,
    fontSize: 10,
    letterSpacing: 0,
    lineHeight: '15px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  optimizerMetrics: {
    display: {
      'default': 'grid',
      '@media (max-width: 760px)': 'none',
    },
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '104px 98px minmax(112px, 1fr)',
    gap: 12,
    color: 'rgba(34, 66, 105, 0.58)',
    fontSize: 10,
    fontVariantNumeric: 'tabular-nums',
    letterSpacing: 0,
    lineHeight: '15px',
    textAlign: 'right',
  },
  optimizerChevron: {
    color: 'rgba(0, 91, 190, 0.52)',
  },
  detail: {
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflow: 'hidden',
    backgroundColor: 'transparent',
  },
  detailScroll: {
    width: '100%',
    minHeight: 0,
    overflowY: 'auto',
    paddingTop: 18,
    paddingRight: 'clamp(20px, 5vw, 56px)',
    paddingBottom: 38,
    paddingLeft: 'clamp(20px, 5vw, 56px)',
  },
  detailContent: {
    width: 'min(760px, 100%)',
    marginRight: 'auto',
    marginLeft: 'auto',
  },
  detailHeader: {
    display: 'flex',
    minHeight: 66,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 20,
    paddingBottom: 18,
  },
  headingCopy: {
    minWidth: 0,
  },
  titleLine: {
    display: 'flex',
    minWidth: 0,
    height: 30,
    alignItems: 'center',
    gap: 8,
    color: 'rgba(43, 47, 54, 0.72)',
  },
  detailTitle: {
    overflow: 'hidden',
    margin: 0,
    color: colors.text,
    fontSize: 18,
    fontWeight: 680,
    letterSpacing: 0,
    lineHeight: '24px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  nameInput: {
    width: 'min(360px, 100%)',
    height: 30,
    minWidth: 0,
    borderColor: {
      'default': 'transparent',
      ':hover': 'rgba(58, 63, 72, 0.14)',
      ':focus': 'rgba(58, 63, 72, 0.24)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    paddingRight: 7,
    paddingLeft: 7,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.54)',
      ':focus': 'rgba(255, 255, 255, 0.78)',
    },
    color: colors.text,
    fontSize: 18,
    fontWeight: 680,
    letterSpacing: 0,
    lineHeight: '24px',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus': `0 0 0 2px ${colors.focus}`,
    },
  },
  detailDescription: {
    marginTop: 5,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: colors.muted,
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: '17px',
  },
  metadata: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 5,
    marginTop: 5,
    color: 'rgba(55, 60, 68, 0.46)',
    fontSize: 10,
    letterSpacing: 0,
    lineHeight: '15px',
  },
  feedback: {
    display: 'flex',
    minHeight: 30,
    alignItems: 'center',
    gap: 7,
    marginBottom: 12,
    borderRadius: 6,
    paddingRight: 10,
    paddingLeft: 10,
    fontSize: 11,
    letterSpacing: 0,
    lineHeight: '16px',
  },
  feedbackSuccess: {
    backgroundColor: 'rgba(67, 107, 76, 0.08)',
    color: 'rgb(55, 92, 64)',
  },
  feedbackError: {
    backgroundColor: 'rgba(166, 53, 53, 0.08)',
    color: colors.danger,
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
  },
  formSection: {
    display: 'grid',
    gridTemplateColumns: 'minmax(150px, 0.42fr) minmax(300px, 1fr)',
    gap: 30,
    borderTopColor: colors.line,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 17,
    paddingBottom: 17,
  },
  sectionHeader: {
    minWidth: 0,
    paddingTop: 6,
  },
  sectionTitle: {
    margin: 0,
    color: colors.text,
    fontSize: 13,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '18px',
  },
  sectionDescription: {
    marginTop: 4,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: colors.muted,
    fontSize: 11,
    letterSpacing: 0,
    lineHeight: '16px',
  },
  settingList: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
  },
  settingRow: {
    display: 'grid',
    minHeight: 43,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(126px, 46%)',
    columnGap: 18,
    borderBottomColor: 'rgba(55, 61, 70, 0.075)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingTop: 6,
    paddingBottom: 6,
  },
  settingCopy: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
  },
  settingLabel: {
    color: colors.text,
    fontSize: 12,
    fontWeight: 540,
    letterSpacing: 0,
    lineHeight: '17px',
  },
  settingDescription: {
    marginTop: 2,
    color: colors.muted,
    fontSize: 10,
    letterSpacing: 0,
    lineHeight: '14px',
  },
  controlSlot: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  input: {
    width: '100%',
    height: 28,
    minWidth: 0,
    borderColor: {
      'default': 'rgba(62, 68, 78, 0.18)',
      ':focus': 'rgba(45, 49, 57, 0.52)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    paddingRight: 7,
    paddingLeft: 7,
    backgroundColor: 'rgba(255, 255, 255, 0.76)',
    color: colors.text,
    fontSize: 11,
    letterSpacing: 0,
    lineHeight: '16px',
    outline: 'none',
    boxShadow: {
      'default': 'inset 0 1px 2px rgba(25, 30, 38, 0.04)',
      ':focus': `0 0 0 2px ${colors.focus}`,
    },
  },
  numberControl: {
    display: 'flex',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 7,
  },
  numberInput: {
    width: 82,
    textAlign: 'right',
  },
  shortSelect: {
    width: 92,
  },
  unit: {
    flex: '0 0 auto',
    color: colors.muted,
    fontSize: 10,
    letterSpacing: 0,
  },
  rangeControl: {
    display: 'flex',
    width: '100%',
    alignItems: 'center',
    gap: 9,
  },
  range: {
    width: '100%',
    height: 18,
    accentColor: colors.accent,
  },
  valueLabel: {
    width: 34,
    flex: '0 0 34px',
    color: colors.text,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    letterSpacing: 0,
    textAlign: 'right',
  },
  switch: {
    position: 'relative',
    width: 32,
    height: 18,
    flex: '0 0 32px',
    borderWidth: 0,
    borderRadius: 9,
    padding: 0,
    backgroundColor: 'rgba(78, 83, 92, 0.2)',
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'inset 0 0 0 1px rgba(35, 39, 46, 0.08)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    opacity: {
      'default': 1,
      ':disabled': 0.45,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '120ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  switchOn: {
    backgroundColor: colors.accent,
  },
  switchThumb: {
    position: 'absolute',
    top: 2,
    left: 2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: 'white',
    boxShadow: '0 1px 3px rgba(24, 28, 35, 0.24)',
    transform: 'translateX(0)',
    transitionDuration: {
      'default': '140ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'transform',
    transitionTimingFunction: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
  },
  switchThumbOn: {
    transform: 'translateX(14px)',
  },
  inlineError: {
    marginTop: 5,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: colors.danger,
    fontSize: 10,
    letterSpacing: 0,
    lineHeight: '14px',
  },
  parameters: {
    display: 'block',
    width: '100%',
    maxHeight: 48,
    overflow: 'auto',
    borderRadius: 5,
    paddingTop: 5,
    paddingRight: 7,
    paddingBottom: 5,
    paddingLeft: 7,
    backgroundColor: 'rgba(62, 68, 78, 0.055)',
    color: 'rgba(43, 48, 56, 0.66)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 9,
    letterSpacing: 0,
    lineHeight: '13px',
    whiteSpace: 'normal',
  },
  parametersControl: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    flexDirection: 'column',
    gap: 8,
  },
  parameterActions: {
    display: 'flex',
    justifyContent: 'flex-end',
  },
  formActions: {
    display: 'flex',
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    borderTopColor: colors.line,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 12,
  },
  secondaryActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
  },
  saveCluster: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 10,
  },
  rescheduleControl: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 7,
    color: colors.muted,
    cursor: 'default',
    fontSize: 10,
    letterSpacing: 0,
    lineHeight: '14px',
  },
  actionButton: {
    display: 'inline-flex',
    minWidth: 0,
    height: 28,
    flex: '0 0 auto',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderColor: 'rgba(62, 68, 78, 0.16)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.7)',
      ':hover': 'rgba(255, 255, 255, 0.94)',
      ':active': 'rgba(232, 235, 240, 0.9)',
    },
    color: 'rgba(34, 38, 45, 0.82)',
    cursor: 'default',
    fontSize: 11,
    fontWeight: 590,
    letterSpacing: 0,
    lineHeight: '16px',
    outline: 'none',
    opacity: {
      'default': 1,
      ':disabled': 0.44,
    },
    boxShadow: {
      'default': '0 1px 2px rgba(31, 37, 47, 0.05), inset 0 1px rgba(255, 255, 255, 0.8)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.97)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, opacity, transform',
    transitionTimingFunction: 'ease-out',
  },
  actionButtonStrong: {
    borderColor: 'rgba(0, 87, 180, 0.82)',
    backgroundColor: {
      'default': colors.accent,
      ':hover': 'rgb(0, 101, 204)',
      ':active': 'rgb(0, 91, 184)',
    },
    color: 'white',
    boxShadow: '0 1px 3px rgba(0, 72, 150, 0.28), inset 0 1px rgba(255, 255, 255, 0.24)',
  },
  actionButtonDanger: {
    borderColor: 'rgba(151, 43, 43, 0.72)',
    backgroundColor: {
      'default': 'rgb(166, 53, 53)',
      ':hover': 'rgb(148, 43, 43)',
      ':active': 'rgb(178, 65, 65)',
    },
    color: 'white',
  },
  textButton: {
    display: 'inline-flex',
    height: 28,
    alignItems: 'center',
    gap: 5,
    borderWidth: 0,
    borderRadius: 5,
    paddingRight: 7,
    paddingLeft: 7,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(61, 67, 77, 0.07)',
      ':active': 'rgba(61, 67, 77, 0.12)',
    },
    color: colors.muted,
    cursor: 'default',
    fontSize: 10,
    fontWeight: 540,
    letterSpacing: 0,
    lineHeight: '14px',
    outline: 'none',
    opacity: {
      'default': 1,
      ':disabled': 0.42,
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  dangerButton: {
    color: colors.danger,
  },
  spinner: {
    animationDuration: '800ms',
    animationIterationCount: 'infinite',
    animationName: spin,
    animationTimingFunction: 'linear',
  },
  status: {
    display: 'flex',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    color: colors.muted,
    fontSize: 11,
    letterSpacing: 0,
  },
  dialog: {
    'width': 'min(410px, calc(100vw - 40px))',
    'maxWidth': 'none',
    'overflow': 'visible',
    'borderWidth': 0,
    'padding': 0,
    'backgroundColor': 'transparent',
    'color': colors.text,
    'outline': 'none',
    '::backdrop': {
      backgroundColor: 'rgba(29, 33, 40, 0.2)',
      backdropFilter: {
        'default': 'saturate(115%) brightness(0.98)',
        '@media (prefers-reduced-transparency: reduce)': 'none',
      },
    },
  },
  dialogSurface: {
    width: '100%',
    overflow: 'hidden',
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.82)',
      '@media (prefers-contrast: more)': 'rgba(46, 51, 59, 0.5)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 14,
    backgroundColor: {
      'default': 'rgba(250, 250, 251, 0.9)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 250, 251)',
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    backdropFilter: {
      'default': 'saturate(150%) contrast(1.035) brightness(1.015)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 22px 54px rgba(29, 35, 45, 0.2), 0 4px 12px rgba(29, 35, 45, 0.11), inset 0 1px rgba(255, 255, 255, 0.96)',
    transformOrigin: '50% 35%',
  },
  dialogHeader: {
    display: 'flex',
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: 14,
    paddingLeft: 18,
  },
  dialogTitle: {
    margin: 0,
    color: colors.text,
    fontSize: 14,
    fontWeight: 660,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  dialogClose: {
    display: 'grid',
    width: 26,
    height: 26,
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: '50%',
    padding: 0,
    backgroundColor: {
      'default': 'rgba(67, 72, 81, 0.07)',
      ':hover': 'rgba(67, 72, 81, 0.12)',
      ':active': 'rgba(67, 72, 81, 0.17)',
    },
    color: colors.muted,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  dialogBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: 13,
    paddingTop: 2,
    paddingRight: 18,
    paddingBottom: 18,
    paddingLeft: 18,
  },
  dialogField: {
    display: 'grid',
    gridTemplateColumns: '110px minmax(0, 1fr)',
    alignItems: 'center',
    gap: 12,
    color: colors.text,
    fontSize: 11,
    fontWeight: 540,
    letterSpacing: 0,
    lineHeight: '16px',
  },
  dialogDescription: {
    margin: 0,
    color: 'rgba(35, 39, 46, 0.76)',
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: '18px',
  },
  dialogNote: {
    margin: 0,
    borderRadius: 6,
    paddingTop: 8,
    paddingRight: 9,
    paddingBottom: 8,
    paddingLeft: 9,
    backgroundColor: 'rgba(62, 68, 78, 0.055)',
    color: colors.muted,
    fontSize: 10,
    letterSpacing: 0,
    lineHeight: '15px',
  },
  dialogSwitchRow: {
    display: 'flex',
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 20,
    borderTopColor: colors.line,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 11,
    color: colors.text,
    cursor: 'default',
    fontSize: 11,
    letterSpacing: 0,
    lineHeight: '16px',
  },
  dialogActions: {
    display: 'flex',
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 7,
    borderTopColor: colors.line,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingRight: 14,
    paddingLeft: 14,
    backgroundColor: 'rgba(239, 241, 244, 0.5)',
  },
})
