import * as stylex from '@stylexjs/stylex'

/** Styles shared by the Note route shell and its lazy editor wrapper. */

const colors = {
  canvas: '#ffffff',
  chromeText: 'rgba(30, 29, 32, 0.86)',
  chromeTextMuted: 'rgba(48, 46, 51, 0.66)',
  chromeTextQuiet: 'rgba(48, 46, 51, 0.5)',
  focus: 'rgba(41, 97, 194, 0.85)',
  selectedPressed: 'rgba(76, 84, 96, 0.15)',
  inspector: 'rgba(248, 249, 251, 0.74)',
  success: 'rgb(52, 145, 80)',
  warning: 'rgb(198, 119, 28)',
} as const

export const editorRouteStyles = stylex.create({
  titlebarActionButton: {
    display: 'grid',
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyItems: 'center',
    borderWidth: 0,
    borderRadius: 16,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.3)',
      ':active': 'rgba(58, 66, 78, 0.14)',
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    color: colors.chromeTextMuted,
    cursor: 'default',
    outline: 'none',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.95)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  titlebarFavoriteActive: {
    color: 'rgb(215, 151, 25)',
  },
  statusPage: {
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    boxSizing: 'border-box',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 56,
    backgroundColor: colors.canvas,
    color: colors.chromeText,
  },
  statusMessage: {
    margin: 0,
    color: colors.chromeTextMuted,
    fontSize: 13,
    fontWeight: 500,
    letterSpacing: 0,
    lineHeight: '18px',
  },
  errorMessage: {
    maxWidth: 'min(520px, calc(100% - 48px))',
    color: 'rgb(151, 45, 45)',
    textAlign: 'center',
  },
  page: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    height: '100%',
    minHeight: 0,
    overflow: 'hidden',
    backgroundColor: colors.canvas,
    color: colors.chromeText,
  },
  workspace: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflow: 'hidden',
    marginLeft: -10,
    paddingTop: 56,
    paddingLeft: 10,
    backgroundColor: colors.canvas,
  },
  inspector: {
    position: {
      'default': 'relative',
      '@media (max-width: 1024px)': 'absolute',
    },
    zIndex: 3,
    top: {
      'default': 'auto',
      '@media (max-width: 1024px)': 0,
    },
    right: {
      'default': 'auto',
      '@media (max-width: 1024px)': 0,
    },
    bottom: {
      'default': 'auto',
      '@media (max-width: 1024px)': 0,
    },
    display: 'flex',
    width: 292,
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flexDirection: 'column',
    paddingTop: 56,
    borderLeftColor: {
      'default': 'rgba(255, 255, 255, 0.54)',
      '@media (prefers-contrast: more)': 'rgba(0, 0, 0, 0.42)',
    },
    borderLeftStyle: 'solid',
    borderLeftWidth: 1,
    backgroundColor: {
      'default': colors.inspector,
      '@media (prefers-reduced-transparency: reduce)': 'rgb(246, 247, 249)',
      '@media (prefers-contrast: more)': 'rgba(250, 251, 252, 0.98)',
    },
    backdropFilter: {
      'default': 'blur(24px) saturate(145%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': '-12px 0 28px rgba(31, 38, 48, 0.055), inset 1px 0 rgba(255, 255, 255, 0.74)',
      '@media (prefers-contrast: more)': '-1px 0 rgba(0, 0, 0, 0.18)',
    },
  },
  inspectorTitlebar: {
    display: 'flex',
    minHeight: 44,
    flex: '0 0 44px',
    alignItems: 'center',
    paddingRight: 17,
    paddingLeft: 17,
    userSelect: 'none',
  },
  inspectorTitleGroup: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 7,
  },
  inspectorTitle: {
    overflow: 'hidden',
    margin: 0,
    color: colors.chromeText,
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  inspectorCount: {
    minWidth: 17,
    borderRadius: 6,
    paddingRight: 5,
    paddingLeft: 5,
    backgroundColor: 'rgba(61, 68, 78, 0.08)',
    color: colors.chromeTextMuted,
    fontSize: 10,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 550,
    lineHeight: '17px',
    textAlign: 'center',
  },
  inspectorContent: {
    minHeight: 0,
    overflowY: 'auto',
    paddingTop: 8,
    paddingRight: 12,
    paddingBottom: 24,
    paddingLeft: 12,
  },
  inspectorSection: {
    marginBottom: 25,
  },
  inspectorSectionHeading: {
    display: 'flex',
    height: 25,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: 7,
    paddingLeft: 7,
  },
  inspectorSectionTitle: {
    margin: 0,
    color: colors.chromeTextMuted,
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '16px',
  },
  inspectorSectionMeta: {
    color: colors.warning,
    fontSize: 10,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 550,
    lineHeight: '16px',
  },
  topicTree: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1,
  },
  entryRow: (depth: number) => ({
    width: '100%',
    height: 31,
    minWidth: 0,
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 7,
    paddingLeft: 6 + depth * 16,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(70, 78, 90, 0.065)',
      ':active': colors.selectedPressed,
    },
    color: colors.chromeText,
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.99)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  }),
  entryRowCurrent: {
    backgroundColor: {
      'default': 'rgba(72, 80, 91, 0.095)',
      ':hover': 'rgba(72, 80, 91, 0.12)',
      '@media (prefers-contrast: more)': 'rgba(55, 62, 72, 0.17)',
    },
  },
  folderEntryButton: {
    display: 'grid',
    width: '100%',
    height: '100%',
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '18px 17px minmax(0, 1fr)',
    gap: 3,
    borderWidth: 0,
    borderRadius: 6,
    padding: 0,
    backgroundColor: 'transparent',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    color: colors.chromeText,
    cursor: 'default',
    font: 'inherit',
    outline: 'none',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.99)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'transform',
    transitionTimingFunction: 'ease-out',
  },
  topicEntry: {
    display: 'grid',
    width: '100%',
    height: '100%',
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '18px 17px minmax(0, 1fr)',
    gap: 3,
  },
  entryDisclosure: {
    display: 'grid',
    width: 18,
    height: 28,
    alignItems: 'center',
    justifyItems: 'center',
    color: colors.chromeTextQuiet,
  },
  entryDisclosureButton: {
    display: 'grid',
    width: 18,
    height: 28,
    alignItems: 'center',
    justifyItems: 'center',
    borderWidth: 0,
    borderRadius: 5,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(65, 72, 82, 0.09)',
      ':active': colors.selectedPressed,
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    color: colors.chromeTextQuiet,
    cursor: 'default',
    outline: 'none',
  },
  entryDisclosurePlaceholder: {
    width: 18,
    height: 28,
  },
  folderIcon: {
    color: colors.chromeTextQuiet,
  },
  topicIcon: {
    color: colors.chromeTextQuiet,
  },
  topicIconCurrent: {
    color: colors.chromeTextQuiet,
  },
  topicLink: {
    display: 'flex',
    height: '100%',
    minWidth: 0,
    alignItems: 'center',
    borderRadius: 5,
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    color: colors.chromeText,
    fontSize: 12,
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: '17px',
    outline: 'none',
    textDecoration: 'none',
  },
  topicLinkCurrent: {
    color: colors.chromeText,
    fontWeight: 550,
  },
  entryLabel: {
    overflow: 'hidden',
    minWidth: 0,
    fontSize: 12,
    fontWeight: 'inherit',
    letterSpacing: 0,
    lineHeight: '17px',
    textAlign: 'left',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  learningSection: {
    marginBottom: 0,
  },
  learningState: {
    display: 'flex',
    alignItems: 'center',
    gap: 5,
    color: colors.chromeTextMuted,
    fontSize: 10,
    fontWeight: 550,
    lineHeight: '16px',
  },
  learningStateDot: {
    width: 5,
    height: 5,
    borderRadius: 99,
    backgroundColor: colors.warning,
    boxShadow: '0 0 0 2px rgba(198, 119, 28, 0.12)',
  },
  learningDetails: {
    display: 'flex',
    marginTop: 7,
    marginRight: 7,
    marginBottom: 18,
    marginLeft: 7,
    flexDirection: 'column',
    gap: 9,
  },
  learningDetail: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 12,
  },
  learningTerm: {
    color: colors.chromeTextMuted,
    fontSize: 11,
    letterSpacing: 0,
    lineHeight: '17px',
  },
  learningValue: {
    margin: 0,
    color: colors.chromeText,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 550,
    lineHeight: '17px',
    textAlign: 'right',
  },
  learningValueDue: {
    color: colors.warning,
  },
  learningProgressHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginRight: 7,
    marginBottom: 7,
    marginLeft: 7,
    color: colors.chromeTextMuted,
    fontSize: 10,
    fontVariantNumeric: 'tabular-nums',
    lineHeight: '15px',
  },
  learningProgressTrack: {
    height: 3,
    overflow: 'hidden',
    marginRight: 7,
    marginLeft: 7,
    borderRadius: 99,
    backgroundColor: 'rgba(58, 67, 78, 0.11)',
  },
  learningProgressFill: {
    width: '50%',
    height: '100%',
    borderRadius: 99,
    backgroundColor: colors.success,
  },
  saveError: {
    position: 'absolute',
    zIndex: 2,
    top: 68,
    left: '50%',
    maxWidth: 'min(520px, calc(100% - 32px))',
    borderRadius: 8,
    paddingBlock: 8,
    paddingInline: 12,
    backgroundColor: 'rgba(115, 28, 28, 0.9)',
    color: '#ffffff',
    fontSize: 12,
    transform: 'translateX(-50%)',
  },
})
