import * as stylex from '@stylexjs/stylex'

/** Styles shared by the Note route shell and its lazy editor wrapper. */

const colors = {
  canvas: '#ffffff',
  chromeText: 'rgba(30, 29, 32, 0.86)',
  chromeTextMuted: 'rgba(48, 46, 51, 0.66)',
  chromeTextQuiet: 'rgba(48, 46, 51, 0.5)',
  focus: 'rgba(41, 97, 194, 0.85)',
  selectedPressed: 'rgba(76, 84, 96, 0.15)',
  inspector: 'rgba(248, 249, 251, 0.74)',
  success: 'rgb(52, 145, 80)',
  warning: 'rgb(198, 119, 28)',
} as const

export const editorRouteStyles = stylex.create({
  whiteboard: {
    position: 'relative',
    width: '100%',
    minHeight: 0,
    flex: 1,
    overflow: 'hidden',
    backgroundColor: '#f7f8fa',
  },
  whiteboardTopRightControls: {
    display: 'flex',
    padding: 4,
    borderColor: 'rgba(255, 255, 255, 0.7)',
    borderRadius: 12,
    borderStyle: 'solid',
    borderWidth: 1,
    backgroundColor: 'rgba(246, 248, 252, 0.68)',
    backdropFilter: 'blur(18px) saturate(160%)',
    boxShadow: 'inset 0 1px 0 rgba(255, 255, 255, 0.82), 0 6px 18px rgba(39, 45, 58, 0.12)',
  },
  whiteboardInsertEditorButton: {
    display: 'grid',
    width: 36,
    height: 36,
    boxSizing: 'border-box',
    alignItems: 'center',
    justifyItems: 'center',
    borderWidth: 0,
    borderRadius: 8,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.62)',
      ':active': 'rgba(73, 82, 98, 0.16)',
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    color: colors.chromeText,
    cursor: 'default',
    outline: 'none',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.95)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  whiteboardEditorEmbed: {
    width: '100%',
    height: '100%',
    boxSizing: 'border-box',
    overflow: 'auto',
    borderRadius: 8,
    backgroundColor: '#ffffff',
    color: '#111318',
    overscrollBehavior: 'contain',
  },
  titlebarActionButton: {
    display: 'grid',
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyItems: 'center',
    borderWidth: 0,
    borderRadius: 16,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.3)',
      ':active': 'rgba(58, 66, 78, 0.14)',
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    color: colors.chromeTextMuted,
    cursor: 'default',
    outline: 'none',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.95)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  titlebarFavoriteActive: {
    color: 'rgb(215, 151, 25)',
  },
  statusPage: {
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    boxSizing: 'border-box',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 56,
    backgroundColor: colors.canvas,
    color: colors.chromeText,
  },
  statusMessage: {
    margin: 0,
    color: colors.chromeTextMuted,
    fontSize: 13,
    fontWeight: 500,
    letterSpacing: 0,
    lineHeight: '18px',
  },
  errorMessage: {
    maxWidth: 'min(520px, calc(100% - 48px))',
    color: 'rgb(151, 45, 45)',
    textAlign: 'center',
  },
  page: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    height: '100%',
    minHeight: 0,
    overflow: 'hidden',
    backgroundColor: colors.canvas,
    color: colors.chromeText,
  },
  workspace: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflow: 'hidden',
    marginLeft: -10,
    paddingTop: 56,
    paddingLeft: 10,
    backgroundColor: colors.canvas,
  },
  inspector: {
    position: {
      'default': 'relative',
      '@media (max-width: 1024px)': 'absolute',
    },
    zIndex: 3,
    top: {
      'default': 'auto',
      '@media (max-width: 1024px)': 0,
    },
    right: {
      'default': 'auto',
      '@media (max-width: 1024px)': 0,
    },
    bottom: {
      'default': 'auto',
      '@media (max-width: 1024px)': 0,
    },
    display: 'flex',
    width: 292,
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flexDirection: 'column',
    paddingTop: 56,
    borderLeftColor: {
      'default': 'rgba(255, 255, 255, 0.54)',
      '@media (prefers-contrast: more)': 'rgba(0, 0, 0, 0.42)',
    },
    borderLeftStyle: 'solid',
    borderLeftWidth: 1,
    backgroundColor: {
      'default': colors.inspector,
      '@media (prefers-reduced-transparency: reduce)': 'rgb(246, 247, 249)',
      '@media (prefers-contrast: more)': 'rgba(250, 251, 252, 0.98)',
    },
    backdropFilter: {
      'default': 'blur(24px) saturate(145%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': '-12px 0 28px rgba(31, 38, 48, 0.055), inset 1px 0 rgba(255, 255, 255, 0.74)',
      '@media (prefers-contrast: more)': '-1px 0 rgba(0, 0, 0, 0.18)',
    },
  },
  inspectorTitlebar: {
    display: 'flex',
    minHeight: 44,
    flex: '0 0 44px',
    alignItems: 'center',
    paddingRight: 17,
    paddingLeft: 17,
    userSelect: 'none',
  },
  inspectorTitleGroup: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 7,
  },
  inspectorTitle: {
    overflow: 'hidden',
    margin: 0,
    color: colors.chromeText,
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  inspectorCount: {
    minWidth: 17,
    borderRadius: 6,
    paddingRight: 5,
    paddingLeft: 5,
    backgroundColor: 'rgba(61, 68, 78, 0.08)',
    color: colors.chromeTextMuted,
    fontSize: 10,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 550,
    lineHeight: '17px',
    textAlign: 'center',
  },
  inspectorContent: {
    minHeight: 0,
    overflowY: 'auto',
    paddingTop: 8,
    paddingRight: 12,
    paddingBottom: 24,
    paddingLeft: 12,
  },
  inspectorSection: {
    marginBottom: 25,
  },
  inspectorSectionHeading: {
    display: 'flex',
    height: 25,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: 7,
    paddingLeft: 7,
  },
  inspectorSectionTitle: {
    margin: 0,
    color: colors.chromeTextMuted,
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '16px',
  },
  inspectorSectionMeta: {
    color: colors.warning,
    fontSize: 10,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 550,
    lineHeight: '16px',
  },
  topicTree: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1,
  },
  entryRow: (depth: number) => ({
    width: '100%',
    height: 31,
    minWidth: 0,
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 7,
    paddingLeft: 6 + depth * 16,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(70, 78, 90, 0.065)',
      ':active': colors.selectedPressed,
    },
    color: colors.chromeText,
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.99)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  }),
  entryRowCurrent: {
    backgroundColor: {
      'default': 'rgba(72, 80, 91, 0.095)',
      ':hover': 'rgba(72, 80, 91, 0.12)',
      '@media (prefers-contrast: more)': 'rgba(55, 62, 72, 0.17)',
    },
  },
  folderEntryButton: {
    display: 'grid',
    width: '100%',
    height: '100%',
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '18px 17px minmax(0, 1fr)',
    gap: 3,
    borderWidth: 0,
    borderRadius: 6,
    padding: 0,
    backgroundColor: 'transparent',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    color: colors.chromeText,
    cursor: 'default',
    font: 'inherit',
    outline: 'none',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.99)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'transform',
    transitionTimingFunction: 'ease-out',
  },
  topicEntry: {
    display: 'grid',
    width: '100%',
    height: '100%',
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '18px 17px minmax(0, 1fr)',
    gap: 3,
  },
  entryDisclosure: {
    display: 'grid',
    width: 18,
    height: 28,
    alignItems: 'center',
    justifyItems: 'center',
    color: colors.chromeTextQuiet,
  },
  entryDisclosureButton: {
    display: 'grid',
    width: 18,
    height: 28,
    alignItems: 'center',
    justifyItems: 'center',
    borderWidth: 0,
    borderRadius: 5,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(65, 72, 82, 0.09)',
      ':active': colors.selectedPressed,
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    color: colors.chromeTextQuiet,
    cursor: 'default',
    outline: 'none',
  },
  entryDisclosurePlaceholder: {
    width: 18,
    height: 28,
  },
  folderIcon: {
    color: colors.chromeTextQuiet,
  },
  topicIcon: {
    color: colors.chromeTextQuiet,
  },
  topicIconCurrent: {
    color: colors.chromeTextQuiet,
  },
  topicLink: {
    display: 'flex',
    height: '100%',
    minWidth: 0,
    alignItems: 'center',
    borderRadius: 5,
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    color: colors.chromeText,
    fontSize: 12,
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: '17px',
    outline: 'none',
    textDecoration: 'none',
  },
  topicLinkCurrent: {
    color: colors.chromeText,
    fontWeight: 550,
  },
  entryLabel: {
    overflow: 'hidden',
    minWidth: 0,
    fontSize: 12,
    fontWeight: 'inherit',
    letterSpacing: 0,
    lineHeight: '17px',
    textAlign: 'left',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  learningSection: {
    marginBottom: 0,
  },
  learningState: {
    display: 'flex',
    alignItems: 'center',
    gap: 5,
    color: colors.chromeTextMuted,
    fontSize: 10,
    fontWeight: 550,
    lineHeight: '16px',
  },
  learningStateDot: {
    width: 5,
    height: 5,
    borderRadius: 99,
    backgroundColor: colors.warning,
    boxShadow: '0 0 0 2px rgba(198, 119, 28, 0.12)',
  },
  learningDetails: {
    display: 'flex',
    marginTop: 7,
    marginRight: 7,
    marginBottom: 18,
    marginLeft: 7,
    flexDirection: 'column',
    gap: 9,
  },
  learningDetail: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 12,
  },
  learningTerm: {
    color: colors.chromeTextMuted,
    fontSize: 11,
    letterSpacing: 0,
    lineHeight: '17px',
  },
  learningValue: {
    margin: 0,
    color: colors.chromeText,
    fontSize: 11,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 550,
    lineHeight: '17px',
    textAlign: 'right',
  },
  learningValueDue: {
    color: colors.warning,
  },
  learningProgressHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginRight: 7,
    marginBottom: 7,
    marginLeft: 7,
    color: colors.chromeTextMuted,
    fontSize: 10,
    fontVariantNumeric: 'tabular-nums',
    lineHeight: '15px',
  },
  learningProgressTrack: {
    height: 3,
    overflow: 'hidden',
    marginRight: 7,
    marginLeft: 7,
    borderRadius: 99,
    backgroundColor: 'rgba(58, 67, 78, 0.11)',
  },
  learningProgressFill: {
    width: '50%',
    height: '100%',
    borderRadius: 99,
    backgroundColor: colors.success,
  },
  alertStack: {
    position: 'absolute',
    zIndex: 2,
    top: 68,
    left: '50%',
    display: 'flex',
    width: 'min(620px, calc(100% - 32px))',
    flexDirection: 'column',
    gap: 8,
    transform: 'translateX(-50%)',
  },
  saveError: {
    maxWidth: '100%',
    borderRadius: 8,
    paddingBlock: 8,
    paddingInline: 12,
    backgroundColor: 'rgba(115, 28, 28, 0.9)',
    color: '#ffffff',
    fontSize: 12,
  },
  validationError: {
    display: 'flex',
    maxWidth: '100%',
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    borderRadius: 8,
    paddingBlock: 6,
    paddingRight: 7,
    paddingLeft: 12,
    backgroundColor: 'rgba(115, 28, 28, 0.94)',
    color: '#ffffff',
    fontSize: 12,
    lineHeight: 1.45,
  },
  validationErrorMessage: {
    minWidth: 0,
  },
  validationErrorActions: {
    display: 'flex',
    minWidth: 172,
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 7,
  },
  copyDiagnosticsButton: {
    display: 'inline-flex',
    height: 28,
    flexShrink: 0,
    alignItems: 'center',
    gap: 5,
    borderColor: 'rgba(255, 255, 255, 0.34)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    paddingInline: 8,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.12)',
      ':hover': 'rgba(255, 255, 255, 0.2)',
      ':active': 'rgba(255, 255, 255, 0.27)',
    },
    color: '#ffffff',
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '16px',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgba(255, 255, 255, 0.88)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.98)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  copyDiagnosticsStatus: {
    width: 54,
    flexShrink: 0,
    color: 'rgba(255, 255, 255, 0.86)',
    fontSize: 10,
    fontWeight: 550,
    letterSpacing: 0,
    lineHeight: '14px',
  },
  entryContextMenu: {
    position: 'fixed',
    zIndex: 70,
    width: 168,
    borderColor: 'rgba(48, 51, 58, 0.16)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    padding: 4,
    backgroundColor: {
      'default': 'rgba(250, 251, 253, 0.94)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 251, 253)',
    },
    backdropFilter: {
      'default': 'blur(18px) saturate(160%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 12px 28px rgba(28, 34, 44, 0.18), 0 2px 6px rgba(28, 34, 44, 0.1)',
  },
  entryContextSubmenuTrigger: {
    position: 'relative',
  },
  entryContextSubmenu: {
    position: 'absolute',
    zIndex: 71,
    top: -4,
    left: 'calc(100% + 4px)',
    width: 168,
    borderColor: 'rgba(48, 51, 58, 0.16)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    padding: 4,
    backgroundColor: {
      'default': 'rgba(250, 251, 253, 0.94)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 251, 253)',
    },
    backdropFilter: {
      'default': 'blur(18px) saturate(160%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 12px 28px rgba(28, 34, 44, 0.18), 0 2px 6px rgba(28, 34, 44, 0.1)',
  },
  entryContextSubmenuLeft: {
    right: 'calc(100% + 4px)',
    left: 'auto',
  },
  entryContextMenuItem: {
    display: 'flex',
    width: '100%',
    height: 30,
    alignItems: 'center',
    gap: 8,
    borderWidth: 0,
    borderRadius: 5,
    paddingRight: 8,
    paddingLeft: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(0, 113, 227, 0.1)',
      ':active': 'rgba(0, 113, 227, 0.16)',
    },
    color: colors.chromeText,
    cursor: 'default',
    fontSize: 12,
    lineHeight: '17px',
    outline: 'none',
    textDecoration: 'none',
    boxShadow: {
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  entryContextMenuItemDisabled: {
    backgroundColor: {
      ':hover': 'transparent',
      ':active': 'transparent',
    },
    color: colors.chromeTextQuiet,
  },
  entryContextMenuItemTrailing: {
    marginLeft: 'auto',
  },
  bookPickerOverlay: {
    position: 'fixed',
    zIndex: 60,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    display: 'grid',
    alignItems: 'center',
    justifyItems: 'center',
    padding: 24,
    backgroundColor: 'rgba(28, 31, 38, 0.24)',
    backdropFilter: 'blur(10px)',
  },
  entryCreationDialog: {
    display: 'flex',
    width: 'min(360px, 100%)',
    overflow: 'hidden',
    flexDirection: 'column',
    borderColor: 'rgba(50, 55, 64, 0.18)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 12,
    backgroundColor: {
      'default': 'rgba(250, 251, 253, 0.96)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 251, 253)',
    },
    boxShadow: '0 22px 56px rgba(29, 35, 45, 0.22), 0 2px 8px rgba(29, 35, 45, 0.1)',
  },
  entryCreationBody: {
    display: 'grid',
    gap: 8,
    paddingTop: 16,
    paddingRight: 18,
    paddingBottom: 18,
    paddingLeft: 18,
  },
  entryCreationField: {
    display: 'grid',
    gap: 6,
    color: colors.chromeTextMuted,
    fontSize: 11,
    fontWeight: 550,
    letterSpacing: 0,
    lineHeight: '16px',
  },
  entryCreationInput: {
    width: '100%',
    height: 34,
    borderColor: 'rgba(49, 48, 53, 0.18)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.82)',
    color: colors.chromeText,
    fontSize: 13,
    letterSpacing: 0,
    lineHeight: '18px',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus': '0 0 0 3px rgba(41, 97, 194, 0.2)',
    },
  },
  bookPickerDialog: {
    display: 'flex',
    width: 'min(620px, 100%)',
    maxHeight: 'min(720px, calc(100vh - 48px))',
    flexDirection: 'column',
    overflow: 'hidden',
    borderColor: 'rgba(50, 55, 64, 0.18)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 14,
    backgroundColor: {
      'default': 'rgba(250, 251, 253, 0.96)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 251, 253)',
    },
    boxShadow: '0 22px 56px rgba(29, 35, 45, 0.22), 0 2px 8px rgba(29, 35, 45, 0.1)',
  },
  bookPickerHeader: {
    display: 'flex',
    minHeight: 76,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    borderBottomColor: 'rgba(49, 48, 53, 0.12)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingTop: 15,
    paddingRight: 18,
    paddingBottom: 14,
    paddingLeft: 20,
  },
  bookPickerTitle: {
    margin: 0,
    color: colors.chromeText,
    fontSize: 16,
    fontWeight: 650,
    lineHeight: '22px',
  },
  bookPickerDescription: {
    marginTop: 3,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: colors.chromeTextMuted,
    fontSize: 12,
    lineHeight: '18px',
  },
  inspectorCloseButton: {
    display: 'grid',
    width: 30,
    height: 30,
    flexShrink: 0,
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 15,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(60, 65, 74, 0.08)',
      ':active': 'rgba(60, 65, 74, 0.14)',
    },
    color: colors.chromeTextMuted,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  bookPickerBody: {
    display: 'grid',
    minHeight: 0,
    flex: 1,
    gridTemplateRows: 'auto minmax(96px, 1fr) auto auto',
    gap: 12,
    padding: 16,
  },
  bookPickerSearch: {
    display: 'flex',
    minHeight: 34,
    alignItems: 'center',
    gap: 8,
    borderColor: 'rgba(49, 48, 53, 0.16)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 9,
    paddingLeft: 9,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    color: colors.chromeTextQuiet,
    boxShadow: {
      ':focus-within': '0 0 0 3px rgba(41, 97, 194, 0.2)',
    },
  },
  bookPickerSearchInput: {
    width: '100%',
    minWidth: 0,
    height: 30,
    borderWidth: 0,
    padding: 0,
    backgroundColor: 'transparent',
    color: colors.chromeText,
    fontSize: 12,
    lineHeight: '18px',
    outline: 'none',
  },
  bookPickerList: {
    display: 'grid',
    minHeight: 96,
    overflowY: 'auto',
    alignContent: 'start',
    gap: 6,
  },
  bookPickerOption: {
    display: 'grid',
    minHeight: 54,
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: 12,
    borderColor: 'rgba(49, 48, 53, 0.11)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingTop: 9,
    paddingRight: 11,
    paddingBottom: 9,
    paddingLeft: 11,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.66)',
      ':hover': 'rgba(255, 255, 255, 0.96)',
      ':active': 'rgba(242, 245, 249, 0.96)',
    },
    color: colors.chromeText,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  bookPickerOptionSelected: {
    borderColor: 'rgba(0, 113, 227, 0.42)',
    backgroundColor: 'rgba(0, 113, 227, 0.08)',
  },
  bookPickerOptionText: {
    display: 'grid',
    minWidth: 0,
    gap: 2,
  },
  bookPickerOptionTitle: {
    overflow: 'hidden',
    fontSize: 12,
    fontWeight: 600,
    lineHeight: '17px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  bookPickerOptionDetail: {
    overflow: 'hidden',
    color: colors.chromeTextQuiet,
    fontSize: 10,
    lineHeight: '15px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  bookPickerFormatList: {
    color: colors.chromeTextMuted,
    fontSize: 9,
    fontWeight: 650,
    lineHeight: '14px',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
  },
  bookPickerFormatField: {
    display: 'grid',
    gridTemplateColumns: 'auto minmax(140px, 220px)',
    alignItems: 'center',
    justifyContent: 'end',
    gap: 10,
    color: colors.chromeTextMuted,
    fontSize: 11,
    fontWeight: 600,
  },
  bookPickerFormatSelect: {
    height: 32,
    borderColor: 'rgba(49, 48, 53, 0.16)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 8,
    paddingLeft: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.82)',
    color: colors.chromeText,
    fontSize: 12,
    outline: 'none',
    boxShadow: {
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  bookPickerStatus: {
    alignSelf: 'center',
    margin: 0,
    padding: 24,
    color: colors.chromeTextMuted,
    fontSize: 12,
    lineHeight: '18px',
    textAlign: 'center',
  },
  bookPickerError: {
    margin: 0,
    color: 'rgb(151, 45, 45)',
    fontSize: 11,
    lineHeight: '17px',
  },
  bookPickerWarning: {
    margin: 0,
    borderRadius: 7,
    paddingTop: 8,
    paddingRight: 10,
    paddingBottom: 8,
    paddingLeft: 10,
    backgroundColor: 'rgba(198, 119, 28, 0.1)',
    color: 'rgb(133, 78, 18)',
    fontSize: 11,
    lineHeight: '17px',
  },
  bookPickerFooter: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 8,
    borderTopColor: 'rgba(49, 48, 53, 0.12)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 13,
    paddingRight: 18,
    paddingBottom: 15,
    paddingLeft: 18,
  },
  bookPickerCancel: {
    minHeight: 32,
    borderColor: 'rgba(49, 48, 53, 0.16)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 12,
    paddingLeft: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    color: colors.chromeTextMuted,
    cursor: 'default',
    fontSize: 12,
    fontWeight: 550,
    outline: 'none',
    boxShadow: {
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  bookPickerCreate: {
    minHeight: 32,
    borderColor: 'rgba(0, 90, 190, 0.22)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 13,
    paddingLeft: 13,
    backgroundColor: {
      'default': 'rgb(0, 113, 227)',
      ':hover': 'rgb(0, 103, 211)',
      ':active': 'rgb(0, 92, 192)',
      ':disabled': 'rgba(0, 113, 227, 0.44)',
    },
    color: 'white',
    cursor: 'default',
    fontSize: 12,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      ':focus-visible': '0 0 0 3px rgba(41, 97, 194, 0.38)',
    },
  },
})
