import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'rgb(0, 113, 227)',
  canvas: '#ffffff',
  focus: 'rgba(41, 97, 194, 0.85)',
  separator: 'rgba(72, 77, 86, 0.1)',
  text: 'rgba(25, 27, 31, 0.9)',
  textMuted: 'rgba(48, 52, 59, 0.62)',
  textQuiet: 'rgba(48, 52, 59, 0.46)',
} as const

const loadingRotation = stylex.keyframes({
  to: { transform: 'rotate(360deg)' },
})

export const pagesRouteStyles = stylex.create({
  page: {
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    paddingTop: 56,
    backgroundColor: colors.canvas,
    color: colors.text,
  },
  content: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    paddingTop: 8,
    paddingRight: 18,
    paddingBottom: 12,
    paddingLeft: 18,
  },
  summary: {
    display: 'flex',
    height: 32,
    flex: '0 0 32px',
    alignItems: 'center',
    paddingLeft: 14,
    userSelect: 'none',
  },
  resultCount: {
    margin: 0,
    color: colors.textMuted,
    fontSize: 12,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 550,
    letterSpacing: 0,
    lineHeight: '18px',
  },
  tableRegion: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    flex: 1,
  },
  tableViewport: {
    width: '100%',
    minWidth: 0,
    minHeight: 0,
    overflowX: 'hidden',
    overflowY: 'auto',
    overscrollBehavior: 'contain',
  },
  table: {
    display: 'grid',
    width: '100%',
    minWidth: 0,
    borderCollapse: 'collapse',
  },
  tableHead: {
    position: 'sticky',
    zIndex: 2,
    top: 0,
    display: 'grid',
    width: '100%',
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.72)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(250, 250, 251)',
      '@media (prefers-contrast: more)': 'rgb(250, 251, 252)',
    },
    backdropFilter: {
      'default': 'blur(20px) saturate(140%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': '0 1px rgba(72, 77, 86, 0.12), 0 10px 18px -18px rgba(28, 35, 46, 0.34)',
      '@media (prefers-contrast: more)': '0 1px rgba(26, 30, 36, 0.56)',
    },
  },
  headerRow: {
    display: 'flex',
    width: '100%',
    height: 34,
    alignItems: 'center',
  },
  headerCell: {
    display: 'flex',
    height: '100%',
    minWidth: 0,
    alignItems: 'center',
    paddingRight: 0,
    paddingLeft: 0,
    color: 'rgba(35, 40, 48, 0.67)',
    fontSize: 11,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '16px',
    textAlign: 'left',
    textShadow: '0 1px rgba(255, 255, 255, 0.62)',
    userSelect: 'none',
  },
  headerButton: {
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 5,
    overflow: 'hidden',
    borderWidth: 0,
    paddingRight: 14,
    paddingLeft: 14,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(70, 79, 93, 0.055)',
      ':active': 'rgba(70, 79, 93, 0.09)',
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `inset 0 0 0 2px ${colors.focus}`,
    },
    color: 'inherit',
    cursor: 'default',
    font: 'inherit',
    outline: 'none',
    textAlign: 'left',
    transitionDuration: {
      'default': '90ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, color',
    transitionTimingFunction: 'ease-out',
    whiteSpace: 'nowrap',
  },
  headerButtonSorted: {
    color: 'rgba(25, 29, 36, 0.88)',
  },
  sortIcon: {
    width: 12,
    height: 12,
    flex: '0 0 12px',
  },
  tableBody: {
    position: 'relative',
    display: 'grid',
    width: '100%',
  },
  tableRow: {
    position: 'absolute',
    top: 0,
    left: 0,
    display: 'flex',
    width: '100%',
    height: 46,
    alignItems: 'center',
    borderBottomColor: colors.separator,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    borderRadius: {
      'default': 0,
      ':hover': 8,
      ':active': 8,
    },
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(70, 79, 93, 0.055)',
      ':active': 'rgba(70, 79, 93, 0.095)',
    },
    transitionDuration: {
      'default': '90ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  tableCell: {
    display: 'flex',
    height: '100%',
    minWidth: 0,
    alignItems: 'center',
    overflow: 'hidden',
    paddingRight: 14,
    paddingLeft: 14,
    color: colors.textMuted,
    fontSize: 12,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  titleCell: {
    color: colors.text,
    fontSize: 13,
    fontVariantNumeric: 'normal',
    fontWeight: 520,
  },
  titleCellControls: {
    display: 'grid',
    width: '100%',
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '28px minmax(0, 1fr) 28px',
    gap: 3,
  },
  titleOpenButton: {
    display: 'flex',
    height: 32,
    minWidth: 0,
    alignItems: 'center',
    overflow: 'hidden',
    borderWidth: 0,
    borderRadius: 6,
    paddingRight: 6,
    paddingLeft: 6,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(70, 79, 93, 0.06)',
      ':active': 'rgba(70, 79, 93, 0.1)',
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    color: 'inherit',
    cursor: 'default',
    font: 'inherit',
    outline: 'none',
    textAlign: 'left',
    textOverflow: 'ellipsis',
    transitionDuration: {
      'default': '90ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow',
    transitionTimingFunction: 'ease-out',
    whiteSpace: 'nowrap',
  },
  titleOpenLabel: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  titleIconButton: {
    display: 'grid',
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyItems: 'center',
    borderWidth: 0,
    borderRadius: 7,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(70, 79, 93, 0.075)',
      ':active': 'rgba(70, 79, 93, 0.13)',
      ':disabled': 'transparent',
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    color: {
      'default': colors.textQuiet,
      ':hover': colors.text,
      ':disabled': 'rgba(48, 52, 59, 0.25)',
    },
    cursor: 'default',
    outline: 'none',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  favoriteButtonActive: {
    color: 'rgb(215, 151, 25)',
  },
  titleEditor: {
    position: 'relative',
    width: '100%',
    minWidth: 0,
  },
  titleEditSpacer: {
    width: 28,
    height: 28,
  },
  titleInput: {
    width: '100%',
    height: 30,
    minWidth: 0,
    borderColor: {
      'default': 'rgba(104, 112, 125, 0.22)',
      ':focus': 'rgba(41, 97, 194, 0.72)',
      ':invalid': 'rgba(184, 62, 62, 0.74)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    paddingRight: 6,
    paddingLeft: 6,
    backgroundColor: 'rgba(246, 248, 251, 0.9)',
    boxShadow: {
      'default': 'inset 0 1px 2px rgba(35, 42, 53, 0.05)',
      ':focus': '0 0 0 2px rgba(41, 97, 194, 0.18), inset 0 1px 2px rgba(35, 42, 53, 0.05)',
    },
    color: colors.text,
    font: 'inherit',
    outline: 'none',
    opacity: {
      'default': 1,
      ':read-only': 0.62,
    },
  },
  visuallyHidden: {
    position: 'absolute',
    width: 1,
    height: 1,
    overflow: 'hidden',
    margin: -1,
    clip: 'rect(0 0 0 0)',
    clipPath: 'inset(50%)',
    whiteSpace: 'nowrap',
  },
  titleColumn: {
    minWidth: 180,
    flex: '1 1 100%',
  },
  createdColumn: {
    display: {
      'default': 'flex',
      '@media (max-width: 960px)': 'none',
    },
    width: 184,
    flex: '0 0 184px',
  },
  dateColumn: {
    width: 184,
    flex: '0 0 184px',
  },
  statusBody: {
    display: 'grid',
    width: '100%',
    height: 'clamp(240px, 52vh, 520px)',
    placeItems: 'center',
  },
  statusRow: {
    display: 'contents',
  },
  statusCell: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    gap: 8,
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: 500,
    letterSpacing: 0,
    lineHeight: '18px',
    textAlign: 'center',
  },
  statusIcon: {
    width: 22,
    height: 22,
    color: colors.textQuiet,
  },
  loadingIcon: {
    'animationDuration': '850ms',
    'animationIterationCount': 'infinite',
    'animationName': loadingRotation,
    'animationTimingFunction': 'linear',
    '@media (prefers-reduced-motion: reduce)': {
      animationName: 'none',
    },
  },
  errorIcon: {
    width: 22,
    height: 22,
    color: 'rgb(184, 83, 69)',
  },
  viewMenuRoot: {
    display: 'flex',
    height: 32,
    alignItems: 'center',
  },
  viewMenuButton: {
    display: 'flex',
    width: 62,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    borderWidth: 0,
    borderRadius: 16,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.3)',
      ':active': 'rgba(58, 66, 78, 0.14)',
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    color: 'rgba(31, 35, 42, 0.82)',
    cursor: 'default',
    outline: 'none',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.97)',
    },
    transitionDuration: {
      'default': '110ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  viewMenuChevron: {
    transform: 'rotate(0deg)',
    transitionDuration: {
      'default': '150ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'transform',
    transitionTimingFunction: 'ease-out',
  },
  viewMenuChevronOpen: {
    transform: 'rotate(180deg)',
  },
  retryButton: {
    height: 28,
    marginTop: 2,
    borderColor: 'rgba(0, 100, 210, 0.25)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 14,
    paddingRight: 12,
    paddingLeft: 12,
    backgroundColor: {
      'default': 'rgba(0, 113, 227, 0.12)',
      ':hover': 'rgba(0, 113, 227, 0.18)',
      ':active': 'rgba(0, 113, 227, 0.24)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(228, 240, 253)',
    },
    backgroundImage: 'linear-gradient(150deg, rgba(255, 255, 255, 0.48), rgba(0, 113, 227, 0.06))',
    backdropFilter: {
      'default': 'blur(14px) saturate(170%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': '0 3px 8px rgba(0, 72, 150, 0.12), inset 0 1px rgba(255, 255, 255, 0.72)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    color: colors.accent,
    cursor: 'default',
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: 0,
    outline: 'none',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.96)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  loadingRow: {
    position: 'absolute',
    top: 0,
    left: 8,
    display: 'flex',
    width: 'calc(100% - 16px)',
    height: 46,
    alignItems: 'center',
  },
  loadingCell: {
    display: 'flex',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    color: colors.textQuiet,
    fontSize: 11,
    fontWeight: 500,
    letterSpacing: 0,
    lineHeight: '16px',
  },
  loadingMoreIcon: {
    width: 14,
    height: 14,
  },
})
