import * as stylex from '@stylexjs/stylex'

export const readerRouteStyles = stylex.create({
  page: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    paddingTop: 56,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
  },
  pageOpen: {
    paddingTop: 0,
  },
  empty: {
    display: 'grid',
    minHeight: 0,
    flex: 1,
    alignContent: 'center',
    justifyItems: 'center',
    padding: 32,
    color: 'rgba(48, 46, 51, 0.62)',
  },
  emptyIcon: {
    width: 34,
    height: 34,
    marginBottom: 14,
    color: 'rgba(48, 46, 51, 0.42)',
  },
  emptyTitle: {
    marginTop: 0,
    marginBottom: 6,
    color: 'rgba(27, 27, 30, 0.9)',
    fontSize: 15,
    fontWeight: 600,
    lineHeight: '21px',
  },
  emptyDetail: {
    maxWidth: 360,
    marginTop: 0,
    marginBottom: 18,
    fontSize: 12,
    lineHeight: '18px',
    textAlign: 'center',
  },
  openButton: {
    display: 'flex',
    height: 32,
    alignItems: 'center',
    gap: 7,
    borderColor: 'rgba(0, 90, 190, 0.22)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 12,
    paddingLeft: 11,
    backgroundColor: {
      'default': 'rgb(0, 113, 227)',
      ':hover': 'rgb(0, 103, 211)',
      ':active': 'rgb(0, 92, 192)',
    },
    color: 'white',
    cursor: 'default',
    fontSize: 12,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': '0 1px 2px rgba(0, 64, 140, 0.18)',
      ':focus-visible': '0 0 0 3px rgba(41, 97, 194, 0.38)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.97)',
    },
    transitionDuration: {
      'default': '90ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  toolbarActionButton: {
    position: 'relative',
    display: 'grid',
    width: 30,
    height: 30,
    flexShrink: 0,
    alignItems: 'center',
    justifyItems: 'center',
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(69, 72, 79, 0.08)',
      ':active': 'rgba(69, 72, 79, 0.14)',
      ':focus-visible': 'rgba(69, 72, 79, 0.08)',
    },
    color: 'rgba(27, 27, 30, 0.9)',
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      ':focus-visible': '0 0 0 2px rgba(41, 97, 194, 0.72)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  fileInput: {
    position: 'absolute',
    width: 1,
    height: 1,
    overflow: 'hidden',
    clip: 'rect(0, 0, 0, 0)',
    whiteSpace: 'nowrap',
  },
  routeStatus: {
    display: 'flex',
    minHeight: 0,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    padding: 32,
    color: 'rgba(48, 46, 51, 0.58)',
    textAlign: 'center',
  },
  statusIcon: {
    marginBottom: 12,
    color: 'rgba(48, 46, 51, 0.42)',
  },
  statusTitle: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 6,
    marginLeft: 0,
    color: 'rgba(27, 27, 30, 0.9)',
    fontSize: 15,
    fontWeight: 620,
    letterSpacing: 0,
    lineHeight: '21px',
  },
  statusDetail: {
    maxWidth: 380,
    marginTop: 0,
    marginRight: 0,
    marginBottom: 18,
    marginLeft: 0,
    color: 'rgba(48, 46, 51, 0.62)',
    fontSize: 12,
    lineHeight: '18px',
  },
  backLink: {
    textDecoration: 'none',
  },
  spinner: {
    marginBottom: 12,
    animationDuration: {
      'default': '850ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    animationIterationCount: 'infinite',
    animationName: stylex.keyframes({
      to: { transform: 'rotate(360deg)' },
    }),
    animationTimingFunction: 'linear',
  },
  contextOverlay: {
    position: 'fixed',
    zIndex: 40,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    display: 'grid',
    alignItems: 'center',
    justifyItems: 'center',
    padding: 24,
    backgroundColor: 'rgba(28, 31, 38, 0.24)',
    backdropFilter: 'blur(10px)',
  },
  contextDialog: {
    display: 'flex',
    width: 'min(460px, 100%)',
    maxHeight: 'min(640px, calc(100vh - 48px))',
    flexDirection: 'column',
    overflow: 'hidden',
    borderColor: 'rgba(50, 55, 64, 0.18)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 14,
    backgroundColor: 'rgba(250, 251, 253, 0.96)',
    boxShadow: '0 22px 56px rgba(29, 35, 45, 0.22), 0 2px 8px rgba(29, 35, 45, 0.1)',
  },
  contextHeader: {
    display: 'grid',
    gap: 4,
    borderBottomColor: 'rgba(49, 48, 53, 0.12)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingTop: 20,
    paddingRight: 22,
    paddingBottom: 17,
    paddingLeft: 22,
  },
  contextTitle: {
    margin: 0,
    color: 'rgba(27, 27, 30, 0.92)',
    fontSize: 16,
    fontWeight: 650,
    lineHeight: '22px',
  },
  contextDescription: {
    margin: 0,
    color: 'rgba(48, 46, 51, 0.62)',
    fontSize: 12,
    lineHeight: '18px',
  },
  contextBody: {
    display: 'grid',
    minHeight: 0,
    gap: 8,
    overflowY: 'auto',
    padding: 14,
  },
  contextOption: {
    display: 'grid',
    minHeight: 58,
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: 14,
    borderColor: 'rgba(49, 48, 53, 0.12)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    paddingTop: 10,
    paddingRight: 13,
    paddingBottom: 10,
    paddingLeft: 13,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.72)',
      ':hover': 'rgba(255, 255, 255, 0.96)',
      ':active': 'rgba(242, 245, 249, 0.96)',
      ':focus-visible': 'rgba(255, 255, 255, 0.96)',
    },
    color: 'rgba(27, 27, 30, 0.9)',
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      ':focus-visible': '0 0 0 2px rgba(41, 97, 194, 0.72)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.99)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  contextOptionText: {
    display: 'grid',
    minWidth: 0,
    gap: 2,
  },
  contextOptionTitle: {
    overflow: 'hidden',
    color: 'rgba(27, 27, 30, 0.9)',
    fontSize: 13,
    fontWeight: 600,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  contextOptionDetail: {
    overflow: 'hidden',
    color: 'rgba(48, 46, 51, 0.58)',
    fontSize: 11,
    lineHeight: '16px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  contextOptionFormat: {
    flexShrink: 0,
    borderRadius: 5,
    paddingTop: 3,
    paddingRight: 6,
    paddingBottom: 3,
    paddingLeft: 6,
    backgroundColor: 'rgba(73, 72, 77, 0.08)',
    color: 'rgba(48, 46, 51, 0.62)',
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: '0.04em',
    lineHeight: '13px',
    textTransform: 'uppercase',
  },
  contextCreateButton: {
    display: 'flex',
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderColor: 'rgba(0, 90, 190, 0.22)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    paddingRight: 12,
    paddingLeft: 12,
    backgroundColor: {
      'default': 'rgba(0, 113, 227, 0.94)',
      ':hover': 'rgb(0, 103, 211)',
      ':active': 'rgb(0, 92, 192)',
      ':disabled': 'rgba(0, 113, 227, 0.48)',
    },
    color: 'white',
    cursor: 'default',
    fontSize: 12,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': '0 1px 2px rgba(0, 64, 140, 0.18)',
      ':focus-visible': '0 0 0 3px rgba(41, 97, 194, 0.38)',
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.98)',
    },
    transitionDuration: {
      'default': '90ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  contextEmpty: {
    paddingTop: 12,
    paddingRight: 8,
    paddingBottom: 12,
    paddingLeft: 8,
    color: 'rgba(48, 46, 51, 0.62)',
    fontSize: 12,
    lineHeight: '18px',
    textAlign: 'center',
  },
  contextForm: {
    display: 'grid',
    gap: 15,
    padding: 20,
  },
  contextField: {
    display: 'grid',
    gap: 6,
  },
  contextLabel: {
    color: 'rgba(48, 46, 51, 0.72)',
    fontSize: 11,
    fontWeight: 600,
    lineHeight: '16px',
  },
  contextInput: {
    width: '100%',
    minHeight: 34,
    borderColor: 'rgba(49, 48, 53, 0.18)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingTop: 7,
    paddingRight: 9,
    paddingBottom: 7,
    paddingLeft: 9,
    backgroundColor: 'rgba(255, 255, 255, 0.86)',
    color: 'rgba(27, 27, 30, 0.9)',
    fontSize: 13,
    lineHeight: '18px',
    outline: 'none',
    boxShadow: {
      ':focus': '0 0 0 3px rgba(41, 97, 194, 0.2)',
    },
  },
  contextFooter: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 8,
    borderTopColor: 'rgba(49, 48, 53, 0.12)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 13,
    paddingRight: 20,
    paddingBottom: 15,
    paddingLeft: 20,
  },
  contextCancelButton: {
    minHeight: 32,
    borderColor: 'rgba(49, 48, 53, 0.16)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 12,
    paddingLeft: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    color: 'rgba(48, 46, 51, 0.76)',
    cursor: 'default',
    fontSize: 12,
    fontWeight: 550,
    outline: 'none',
    boxShadow: {
      ':focus-visible': '0 0 0 3px rgba(41, 97, 194, 0.26)',
    },
  },
  contextError: {
    margin: 0,
    color: 'rgba(174, 56, 56, 0.92)',
    fontSize: 12,
    lineHeight: '18px',
  },
})
