import * as stylex from '@stylexjs/stylex'

const colors = {
  canvas: 'rgba(248, 249, 250, 0.88)',
  focus: 'rgba(41, 97, 194, 0.84)',
  text: 'rgba(27, 28, 31, 0.92)',
  textMuted: 'rgba(46, 48, 54, 0.64)',
  textQuiet: 'rgba(55, 57, 63, 0.46)',
} as const

export const shelfBookStyles = stylex.create({
  page: {
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    backgroundColor: {
      'default': colors.canvas,
      '@media (prefers-reduced-transparency: reduce)': 'rgb(248, 249, 250)',
      '@media (prefers-contrast: more)': 'rgb(250, 250, 251)',
    },
    color: colors.text,
  },
  scrollViewport: {
    width: '100%',
    height: '100%',
    overflowX: 'hidden',
    overflowY: 'auto',
    paddingTop: 88,
    paddingRight: {
      'default': 44,
      '@media (max-width: 900px)': 28,
    },
    paddingBottom: 64,
    paddingLeft: {
      'default': 44,
      '@media (max-width: 900px)': 28,
    },
    scrollPaddingTop: 88,
  },
  content: {
    width: '100%',
    maxWidth: 860,
    marginRight: 'auto',
    marginLeft: 'auto',
  },
  overview: {
    display: 'grid',
    minWidth: 0,
    alignItems: 'start',
    gridTemplateColumns: {
      'default': '180px minmax(0, 1fr)',
      '@media (max-width: 900px)': '150px minmax(0, 1fr)',
      '@media (max-width: 680px)': '1fr',
    },
    gridTemplateAreas: {
      'default': '"cover information" "cover description" ". inspector" ". technical"',
      '@media (max-width: 900px)': '"cover information" "description description" "inspector inspector" "technical technical"',
      '@media (max-width: 680px)': '"cover information" "description description" "inspector inspector" "technical technical"',
    },
    gap: {
      'default': '24px 36px',
      '@media (max-width: 900px)': '30px 28px',
      '@media (max-width: 680px)': '28px 22px',
    },
  },
  coverColumn: {
    gridArea: 'cover',
    width: {
      'default': 180,
      '@media (max-width: 900px)': 150,
      '@media (max-width: 680px)': 128,
    },
    minWidth: 0,
    marginRight: 0,
    marginLeft: 0,
  },
  coverFrame: {
    position: 'relative',
    width: '100%',
    overflow: 'hidden',
    aspectRatio: '0.69',
    borderColor: 'rgba(54, 58, 65, 0.1)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    backgroundColor: 'rgb(231, 229, 223)',
    boxShadow: '0 12px 27px rgba(31, 34, 39, 0.16), 0 2px 5px rgba(31, 34, 39, 0.09)',
  },
  coverImage: {
    display: 'block',
    width: '100%',
    height: '100%',
    animationDuration: {
      'default': '180ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    animationName: stylex.keyframes({
      from: { opacity: 0 },
      to: { opacity: 1 },
    }),
    animationTimingFunction: 'ease-out',
    objectFit: 'cover',
  },
  coverPlaceholder: {
    display: 'flex',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    gap: 14,
    paddingTop: 24,
    paddingRight: 20,
    paddingBottom: 24,
    paddingLeft: 20,
    backgroundColor: 'rgb(229, 226, 217)',
    color: 'rgba(74, 67, 57, 0.54)',
    textAlign: 'center',
  },
  coverPlaceholderLoading: {
    backgroundColor: 'rgb(232, 231, 226)',
    color: 'rgba(62, 67, 76, 0.48)',
  },
  coverPlaceholderError: {
    backgroundColor: 'rgb(235, 226, 220)',
    color: 'rgba(132, 68, 49, 0.68)',
  },
  placeholderTitle: {
    display: '-webkit-box',
    overflow: 'hidden',
    maxWidth: '100%',
    fontFamily: 'ui-serif, "New York", Georgia, serif',
    fontSize: 17,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: 1.3,
    overflowWrap: 'anywhere',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: 7,
  },
  information: {
    gridArea: 'information',
    minWidth: 0,
    paddingTop: 7,
  },
  title: {
    maxWidth: 680,
    margin: 0,
    fontSize: {
      'default': 28,
      '@media (max-width: 680px)': 24,
    },
    fontWeight: 720,
    letterSpacing: 0,
    lineHeight: {
      'default': '35px',
      '@media (max-width: 680px)': '30px',
    },
    overflowWrap: 'anywhere',
  },
  subtitle: {
    maxWidth: 680,
    marginTop: 7,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: '21px',
  },
  authors: {
    maxWidth: 680,
    marginTop: 10,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: colors.textMuted,
    fontSize: 14,
    fontWeight: 560,
    lineHeight: '20px',
  },
  headlineFacts: {
    display: 'flex',
    flexWrap: 'wrap',
    marginTop: 18,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: colors.textQuiet,
    fontSize: 12,
    fontWeight: 520,
    lineHeight: '17px',
  },
  headlineFact: {
    display: 'inline-flex',
    alignItems: 'center',
  },
  factSeparator: {
    marginRight: 7,
    marginLeft: 7,
    color: 'rgba(55, 57, 63, 0.28)',
  },
  readingActions: {
    display: 'flex',
    minHeight: 36,
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 9,
    marginTop: 24,
  },
  readControl: {
    display: 'inline-flex',
    height: 36,
    overflow: 'hidden',
    alignItems: 'stretch',
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.62)',
      '@media (prefers-contrast: more)': 'rgba(0, 67, 151, 0.7)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 11,
    backgroundColor: {
      'default': 'rgba(0, 105, 220, 0.82)',
      '@media (prefers-contrast: more)': 'rgb(0, 101, 211)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(0, 113, 227)',
    },
    backdropFilter: {
      'default': 'blur(18px) saturate(180%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': '0 6px 16px rgba(0, 72, 159, 0.2), 0 1px 3px rgba(0, 61, 134, 0.14), inset 0 1px rgba(255, 255, 255, 0.42)',
      ':focus-within': `0 0 0 2px ${colors.focus}, 0 6px 16px rgba(0, 72, 159, 0.2)`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.975)',
    },
    transitionDuration: {
      'default': '90ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'transform, opacity',
    transitionTimingFunction: 'ease-out',
  },
  readControlDisabled: {
    opacity: 0.76,
  },
  readButton: {
    display: 'inline-flex',
    minWidth: 86,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderWidth: 0,
    paddingRight: 13,
    paddingLeft: 12,
    backgroundColor: 'transparent',
    color: {
      'default': 'white',
      ':disabled': 'rgba(255, 255, 255, 0.58)',
    },
    cursor: 'default',
    fontFamily: 'inherit',
    fontSize: 13,
    fontWeight: 650,
    letterSpacing: 0,
    outline: 'none',
  },
  formatPicker: {
    position: 'relative',
    display: 'inline-flex',
    minWidth: 68,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderLeftColor: 'rgba(255, 255, 255, 0.28)',
    borderLeftStyle: 'solid',
    borderLeftWidth: 1,
    paddingRight: 9,
    paddingLeft: 10,
    color: 'white',
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: 0,
  },
  formatSelect: {
    position: 'absolute',
    zIndex: 1,
    inset: 0,
    width: '100%',
    height: '100%',
    borderWidth: 0,
    opacity: 0,
    cursor: 'default',
  },
  onlineReadingOption: {
    display: 'inline-flex',
    minHeight: 30,
    alignItems: 'center',
    gap: 6,
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 12,
    fontWeight: 530,
    lineHeight: '17px',
    userSelect: 'none',
  },
  onlineReadingCheckbox: {
    width: 15,
    height: 15,
    flexShrink: 0,
    margin: 0,
    accentColor: 'rgb(0, 113, 227)',
  },
  readingHelp: {
    display: 'grid',
    width: 24,
    height: 28,
    alignItems: 'center',
    justifyItems: 'center',
    borderRadius: 7,
    color: colors.textQuiet,
    cursor: 'help',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  deleteReadingButton: {
    display: 'grid',
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyItems: 'center',
    borderColor: 'rgba(255, 255, 255, 0.6)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    padding: 0,
    backgroundColor: {
      'default': 'rgba(246, 248, 251, 0.46)',
      ':hover': 'rgba(255, 255, 255, 0.62)',
      ':active': 'rgba(210, 214, 221, 0.58)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(239, 241, 244)',
    },
    backdropFilter: {
      'default': 'blur(16px) saturate(170%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    color: 'rgb(177, 45, 43)',
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': '0 3px 9px rgba(35, 42, 52, 0.08), inset 0 1px rgba(255, 255, 255, 0.72)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.95)',
    },
  },
  readingError: {
    marginTop: 10,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: 'rgb(166, 42, 40)',
    fontSize: 11,
    lineHeight: '16px',
  },
  metadataInspector: {
    gridArea: 'inspector',
    width: '100%',
    minWidth: 0,
    borderTopColor: 'rgba(67, 70, 76, 0.11)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 21,
  },
  inspectorTitle: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 15,
    marginLeft: 0,
    color: colors.text,
    fontSize: 15,
    fontWeight: 680,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  metadataGrid: {
    display: 'grid',
    gridTemplateColumns: {
      'default': 'repeat(2, minmax(0, 1fr))',
      '@media (max-width: 680px)': 'minmax(0, 1fr)',
    },
    columnGap: 40,
    rowGap: 17,
    margin: 0,
  },
  metadataItem: {
    minWidth: 0,
  },
  metadataTerm: {
    color: colors.textQuiet,
    fontSize: 11,
    fontWeight: 580,
    letterSpacing: 0,
    lineHeight: '17px',
  },
  metadataValue: {
    marginTop: 2,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: colors.text,
    fontSize: 13,
    lineHeight: '19px',
    overflowWrap: 'anywhere',
  },
  description: {
    gridArea: 'description',
    minWidth: 0,
    borderTopColor: 'rgba(67, 70, 76, 0.11)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 24,
  },
  sectionTitle: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 10,
    marginLeft: 0,
    fontSize: 15,
    fontWeight: 680,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  descriptionText: {
    margin: 0,
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: '22px',
    whiteSpace: 'pre-line',
  },
  descriptionUnavailable: {
    margin: 0,
    color: colors.textQuiet,
    fontSize: 13,
    fontStyle: 'italic',
    lineHeight: '20px',
  },
  technicalSection: {
    gridArea: 'technical',
    minWidth: 0,
    borderTopColor: 'rgba(67, 70, 76, 0.11)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 8,
  },
  disclosureButton: {
    display: 'flex',
    width: '100%',
    minHeight: 32,
    alignItems: 'center',
    borderWidth: 0,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    backgroundColor: 'transparent',
    color: colors.text,
    cursor: 'default',
    fontFamily: 'inherit',
    fontSize: 13,
    fontWeight: 610,
    letterSpacing: 0,
    lineHeight: '18px',
    outline: 'none',
    opacity: {
      'default': 1,
      ':active': 0.55,
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  disclosureIcon: {
    flexShrink: 0,
    marginRight: 5,
    color: colors.textQuiet,
    transform: 'rotate(0deg)',
    transitionDuration: {
      'default': '160ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'transform',
    transitionTimingFunction: 'ease-out',
  },
  disclosureIconOpen: {
    transform: 'rotate(90deg)',
  },
  technicalMetadata: {
    marginTop: 5,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 20,
  },
  technicalRow: {
    display: 'grid',
    gridTemplateColumns: {
      'default': '120px minmax(0, 1fr)',
      '@media (max-width: 680px)': '96px minmax(0, 1fr)',
    },
    columnGap: 18,
    borderTopColor: 'rgba(67, 70, 76, 0.09)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 8,
    paddingBottom: 8,
  },
  status: {
    display: 'flex',
    minHeight: 'calc(100vh - 150px)',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    gap: 10,
    color: colors.textQuiet,
    fontSize: 13,
    textAlign: 'center',
  },
  statusTitle: {
    margin: 0,
    color: colors.text,
    fontSize: 17,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '22px',
  },
  statusText: {
    maxWidth: 360,
    margin: 0,
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: '17px',
  },
  shelfLink: {
    display: 'inline-flex',
    height: 30,
    alignItems: 'center',
    borderRadius: 7,
    marginTop: 4,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: 'rgba(118, 118, 128, 0.09)',
    color: colors.text,
    cursor: 'default',
    fontSize: 12,
    fontWeight: 600,
    outline: 'none',
    textDecoration: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    opacity: {
      'default': 1,
      ':active': 0.58,
    },
  },
  spinner: {
    animationDuration: {
      'default': '850ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    animationIterationCount: 'infinite',
    animationName: stylex.keyframes({
      to: { transform: 'rotate(360deg)' },
    }),
    animationTimingFunction: 'linear',
  },
})
