import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'rgb(0, 113, 227)',
  accentPressed: 'rgb(0, 91, 187)',
  canvas: 'rgb(250, 250, 249)',
  danger: 'rgb(198, 48, 48)',
  focus: 'rgba(41, 97, 194, 0.84)',
  text: 'rgba(27, 28, 31, 0.92)',
  textMuted: 'rgba(46, 48, 54, 0.64)',
  textQuiet: 'rgba(55, 57, 63, 0.46)',
} as const

const controlTransition = {
  'default': '110ms',
  '@media (prefers-reduced-motion: reduce)': '0ms',
} as const

export const shelfRouteStyles = stylex.create({
  page: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    backgroundColor: colors.canvas,
    color: colors.text,
  },
  toolbarWrap: {
    position: 'absolute',
    zIndex: 14,
    top: 58,
    right: 28,
    left: 28,
    pointerEvents: 'none',
  },
  toolbar: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    overflow: 'visible',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 18,
  },
  sourceSwitcher: {
    position: 'relative',
    width: 220,
    minWidth: 148,
    flex: '0 1 220px',
    pointerEvents: 'auto',
  },
  sourceTrigger: {
    display: 'grid',
    width: '100%',
    height: 36,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '24px minmax(0, 1fr) 16px',
    gap: 5,
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.68)',
      '@media (prefers-contrast: more)': 'rgba(49, 54, 63, 0.5)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 18,
    paddingRight: 8,
    paddingLeft: 6,
    backgroundColor: {
      'default': 'rgba(246, 248, 251, 0.56)',
      ':hover': 'rgba(250, 251, 253, 0.68)',
      ':active': 'rgba(226, 230, 237, 0.66)',
      '@media (prefers-contrast: more)': 'rgba(250, 250, 251, 0.96)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(245, 246, 248)',
    },
    backdropFilter: {
      'default': 'blur(24px) saturate(175%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    color: colors.text,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': '0 5px 14px rgba(27, 34, 44, 0.11), 0 1px 3px rgba(27, 34, 44, 0.07), inset 0 1px rgba(255, 255, 255, 0.82)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.985)',
    },
    transitionDuration: controlTransition,
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  sourceTriggerIcon: {
    display: 'grid',
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyItems: 'center',
    color: colors.accent,
  },
  sourceTriggerLabel: {
    overflow: 'hidden',
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: '18px',
    textAlign: 'left',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  sourceMenu: {
    position: 'absolute',
    zIndex: 40,
    top: 44,
    left: 0,
    display: 'flex',
    width: 286,
    maxHeight: 390,
    minHeight: 0,
    overflow: 'hidden',
    flexDirection: 'column',
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.82)',
      '@media (prefers-contrast: more)': 'rgba(35, 39, 46, 0.62)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 15,
    padding: 5,
    backgroundColor: {
      'default': 'rgba(244, 246, 249, 0.5)',
      '@media (prefers-contrast: more)': 'rgba(250, 250, 251, 0.96)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(248, 249, 251)',
    },
    backgroundImage: 'linear-gradient(145deg, rgba(255, 255, 255, 0.34), rgba(255, 255, 255, 0.04))',
    backdropFilter: {
      'default': 'blur(20px) saturate(185%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 20px 48px rgba(26, 32, 42, 0.22), 0 4px 12px rgba(26, 32, 42, 0.1), inset 0 1px rgba(255, 255, 255, 0.94)',
    transformOrigin: 'top left',
  },
  sourceMenuScroll: {
    minHeight: 0,
    maxHeight: 270,
    overflowY: 'auto',
    overscrollBehavior: 'contain',
  },
  sourceMenuItem: {
    display: 'grid',
    width: '100%',
    minHeight: 38,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '18px minmax(0, 1fr) 18px',
    gap: 7,
    borderWidth: 0,
    borderRadius: 9,
    paddingTop: 5,
    paddingRight: 8,
    paddingBottom: 5,
    paddingLeft: 8,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(62, 72, 87, 0.08)',
      ':active': 'rgba(62, 72, 87, 0.14)',
    },
    color: colors.text,
    cursor: 'default',
    fontSize: 13,
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `inset 0 0 0 2px ${colors.focus}`,
    },
  },
  sourceMenuItemSelected: {
    backgroundColor: 'rgba(0, 113, 227, 0.1)',
    color: 'rgb(0, 94, 190)',
  },
  sourceMenuLabel: {
    display: 'flex',
    minWidth: 0,
    overflow: 'hidden',
    flexDirection: 'column',
    lineHeight: '17px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  menuSeparator: {
    height: 1,
    flex: '0 0 1px',
    marginTop: 4,
    marginRight: 7,
    marginBottom: 4,
    marginLeft: 7,
    backgroundColor: 'rgba(72, 80, 93, 0.12)',
  },
  searchBox: {
    display: 'grid',
    height: 34,
    width: 'clamp(160px, 24vw, 260px)',
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '18px minmax(0, 1fr) 22px',
    gap: 4,
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.62)',
      ':focus-within': 'rgba(0, 113, 227, 0.28)',
      '@media (prefers-contrast: more)': 'rgba(49, 54, 63, 0.5)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 17,
    paddingRight: 5,
    paddingLeft: 9,
    backgroundColor: {
      'default': 'rgba(239, 242, 246, 0.58)',
      ':focus-within': 'rgba(250, 251, 253, 0.72)',
      '@media (prefers-contrast: more)': 'rgba(250, 250, 251, 0.96)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(239, 240, 243)',
    },
    backdropFilter: {
      'default': 'blur(24px) saturate(175%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    color: colors.textQuiet,
    boxShadow: {
      'default': '0 5px 14px rgba(27, 34, 44, 0.1), 0 1px 3px rgba(27, 34, 44, 0.06), inset 0 1px rgba(255, 255, 255, 0.78)',
      ':focus-within': '0 0 0 3px rgba(0, 113, 227, 0.16), 0 5px 14px rgba(27, 34, 44, 0.1), inset 0 1px rgba(255, 255, 255, 0.86)',
    },
  },
  searchInput: {
    width: '100%',
    minWidth: 0,
    height: 30,
    borderWidth: 0,
    padding: 0,
    backgroundColor: 'transparent',
    color: colors.text,
    fontSize: 13,
    lineHeight: '18px',
    outline: 'none',
  },
  clearSearch: {
    display: 'grid',
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyItems: 'center',
    borderWidth: 0,
    borderRadius: 10,
    padding: 0,
    backgroundColor: 'rgba(61, 67, 77, 0.14)',
    color: colors.textMuted,
    cursor: 'default',
  },
  iconButton: {
    display: 'grid',
    width: 34,
    height: 34,
    flex: '0 0 34px',
    alignItems: 'center',
    justifyItems: 'center',
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.68)',
      '@media (prefers-contrast: more)': 'rgba(49, 54, 63, 0.5)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 17,
    padding: 0,
    backgroundColor: {
      'default': 'rgba(246, 248, 251, 0.56)',
      ':hover': 'rgba(250, 251, 253, 0.68)',
      ':active': 'rgba(226, 230, 237, 0.66)',
      ':disabled': 'rgba(246, 248, 251, 0.38)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(245, 246, 248)',
    },
    backdropFilter: {
      'default': 'blur(24px) saturate(175%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    color: {
      'default': colors.textMuted,
      ':disabled': 'rgba(46, 48, 54, 0.25)',
    },
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': '0 5px 14px rgba(27, 34, 44, 0.1), 0 1px 3px rgba(27, 34, 44, 0.06), inset 0 1px rgba(255, 255, 255, 0.82)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
      ':disabled': 'scale(1)',
    },
    transitionDuration: controlTransition,
    transitionProperty: 'background-color, color, transform',
    transitionTimingFunction: 'ease-out',
  },
  toolbarTrailing: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 8,
    pointerEvents: 'auto',
  },
  loadMoreFooter: {
    display: 'flex',
    justifyContent: 'center',
    paddingTop: 4,
    paddingBottom: 22,
  },
  scrollViewport: {
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflowX: 'hidden',
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    paddingRight: 28,
    paddingBottom: 52,
    paddingLeft: 28,
  },
  scrollViewportWithToolbar: {
    paddingTop: 112,
    scrollPaddingTop: 112,
  },
  scrollViewportEmpty: {
    paddingTop: 54,
    scrollPaddingTop: 54,
  },
  virtualSizer: {
    position: 'relative',
    width: '100%',
    maxWidth: 1500,
    minHeight: 1,
    marginRight: 'auto',
    marginLeft: 'auto',
  },
  virtualRow: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
  },
  overviewCollection: {
    width: '100%',
    maxWidth: 1500,
    marginRight: 'auto',
    marginLeft: 'auto',
  },
  browserHeader: {
    paddingTop: 8,
    paddingRight: 2,
    paddingBottom: 18,
    paddingLeft: 2,
  },
  browserTitle: {
    margin: 0,
    fontSize: 24,
    fontWeight: 700,
    letterSpacing: '-0.018em',
    lineHeight: '30px',
  },
  browserSubtitle: {
    maxWidth: 720,
    marginTop: 4,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: '17px',
  },
  overviewSection: {
    minHeight: 118,
    paddingBottom: 18,
  },
  overviewHeader: {
    display: 'flex',
    minHeight: 48,
    alignItems: 'center',
    gap: 8,
    paddingRight: 2,
    paddingLeft: 2,
  },
  overviewHeadingAction: {
    display: 'inline-flex',
    maxWidth: '100%',
    minWidth: 0,
    alignItems: 'center',
    gap: 7,
    borderWidth: 0,
    borderRadius: 6,
    paddingTop: 4,
    paddingRight: 3,
    paddingBottom: 4,
    paddingLeft: 0,
    backgroundColor: 'transparent',
    color: colors.text,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    opacity: {
      'default': 1,
      ':active': 0.62,
    },
  },
  overviewTitleStack: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    gap: 1,
  },
  overviewTitle: {
    overflow: 'hidden',
    margin: 0,
    fontSize: 15,
    fontWeight: 660,
    letterSpacing: 0,
    lineHeight: '20px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  overviewSubtitle: {
    overflow: 'hidden',
    color: colors.textQuiet,
    fontSize: 11,
    lineHeight: '15px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  catalogChevron: {
    flex: '0 0 auto',
    color: 'rgba(55, 57, 63, 0.34)',
  },
  catalogSectionHeader: {
    display: 'inline-grid',
    maxWidth: '100%',
    minHeight: 44,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: 'minmax(0, auto) 14px',
    gap: 5,
    borderWidth: 0,
    borderRadius: 6,
    paddingRight: 3,
    paddingLeft: 2,
    backgroundColor: 'transparent',
    color: colors.text,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    opacity: {
      'default': 1,
      ':active': 0.62,
    },
  },
  previewState: {
    display: 'flex',
    minHeight: 76,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    color: colors.textQuiet,
    fontSize: 12,
  },
  horizontalShelfViewport: {
    width: '100%',
    minWidth: 0,
    overflowX: 'auto',
    overflowY: 'hidden',
    paddingTop: 14,
    paddingBottom: 22,
    outline: 'none',
    scrollbarWidth: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `inset 0 0 0 2px ${colors.focus}`,
    },
  },
  horizontalShelfSizer: {
    position: 'relative',
    height: 272,
    minWidth: '100%',
  },
  horizontalShelfItem: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 140,
  },
  horizontalShelfStatus: {
    display: 'flex',
    width: 140,
    height: 203,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    gap: 8,
    paddingRight: 10,
    paddingLeft: 10,
    color: colors.textQuiet,
    fontSize: 11,
    lineHeight: '15px',
    textAlign: 'center',
  },
  horizontalRetry: {
    borderWidth: 0,
    borderRadius: 5,
    paddingTop: 3,
    paddingRight: 5,
    paddingBottom: 3,
    paddingLeft: 5,
    backgroundColor: 'transparent',
    color: colors.accent,
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
    outline: 'none',
    opacity: {
      'default': 1,
      ':active': 0.58,
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  groupHeading: {
    display: 'flex',
    minHeight: 64,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 18,
    borderBottomColor: 'rgba(67, 70, 76, 0.11)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingRight: 2,
    paddingLeft: 2,
  },
  groupTitleLine: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 8,
  },
  sourceGlyph: {
    display: 'grid',
    width: 26,
    height: 26,
    flex: '0 0 26px',
    alignItems: 'center',
    justifyItems: 'center',
    color: colors.accent,
  },
  groupTitle: {
    overflow: 'hidden',
    margin: 0,
    fontSize: 15,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '20px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  groupCount: {
    flex: '0 0 auto',
    color: colors.textQuiet,
    fontSize: 12,
    fontVariantNumeric: 'tabular-nums',
  },
  inlineIssue: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 6,
    overflow: 'hidden',
    color: 'rgb(159, 88, 13)',
    fontSize: 12,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  selectedSourceIssue: {
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    borderColor: 'rgba(166, 98, 24, 0.16)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    marginBottom: 12,
    paddingTop: 8,
    paddingRight: 10,
    paddingBottom: 8,
    paddingLeft: 10,
    backgroundColor: 'rgba(232, 153, 58, 0.08)',
    color: 'rgb(145, 79, 10)',
    fontSize: 12,
  },
  publicationRow: {
    display: 'grid',
    width: '100%',
    gap: 24,
    paddingTop: 18,
    paddingBottom: 26,
  },
  publication: {
    minWidth: 0,
  },
  coverFrame: {
    position: 'relative',
    width: '100%',
    overflow: 'hidden',
    aspectRatio: '0.69',
    borderColor: 'rgba(54, 58, 65, 0.1)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: 'rgb(231, 229, 223)',
    boxShadow: '0 7px 16px rgba(31, 34, 39, 0.13), 0 1px 3px rgba(31, 34, 39, 0.08)',
  },
  coverImage: {
    display: 'block',
    width: '100%',
    height: '100%',
    animationDuration: {
      'default': '180ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    animationName: stylex.keyframes({
      from: { opacity: 0, transform: 'scale(1.01)' },
      to: { opacity: 1, transform: 'scale(1)' },
    }),
    animationTimingFunction: 'ease-out',
    objectFit: 'cover',
  },
  coverPlaceholder: {
    display: 'flex',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    gap: 12,
    paddingTop: 22,
    paddingRight: 18,
    paddingBottom: 22,
    paddingLeft: 18,
    backgroundColor: 'rgb(229, 226, 217)',
    color: 'rgba(74, 67, 57, 0.52)',
    textAlign: 'center',
  },
  coverPlaceholderLoading: {
    backgroundColor: 'rgb(232, 231, 226)',
    backgroundImage: 'linear-gradient(112deg, rgba(255, 255, 255, 0.08) 20%, rgba(255, 255, 255, 0.56) 42%, rgba(255, 255, 255, 0.08) 64%)',
    backgroundPositionX: '100%',
    backgroundSize: '220% 100%',
    animationDuration: {
      'default': '1500ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    animationIterationCount: 'infinite',
    animationName: stylex.keyframes({
      from: { backgroundPositionX: '100%' },
      to: { backgroundPositionX: '-100%' },
    }),
    animationTimingFunction: 'ease-in-out',
    color: 'rgba(62, 67, 76, 0.48)',
  },
  coverPlaceholderError: {
    backgroundColor: 'rgb(235, 226, 220)',
    color: 'rgba(132, 68, 49, 0.68)',
  },
  coverPlaceholderTitle: {
    display: '-webkit-box',
    overflow: 'hidden',
    maxWidth: '100%',
    color: 'inherit',
    fontFamily: 'ui-serif, "New York", Georgia, serif',
    fontSize: 'clamp(13px, 1.25vw, 18px)',
    fontWeight: 600,
    letterSpacing: '-0.01em',
    lineHeight: 1.28,
    overflowWrap: 'anywhere',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: 6,
  },
  coverPlaceholderStatus: {
    color: 'inherit',
    fontFamily: 'system-ui, sans-serif',
    fontSize: 10,
    fontWeight: 600,
    letterSpacing: '0.02em',
    lineHeight: '14px',
  },
  publicationText: {
    position: 'relative',
    paddingTop: 10,
    paddingRight: 2,
    paddingLeft: 2,
  },
  publicationTitle: {
    display: '-webkit-box',
    overflow: 'hidden',
    margin: 0,
    color: colors.text,
    fontSize: 13,
    fontWeight: 620,
    letterSpacing: 0,
    lineHeight: '17px',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: 2,
  },
  publicationAuthor: {
    overflow: 'hidden',
    marginTop: 4,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: colors.textMuted,
    fontSize: 11,
    lineHeight: '15px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  formatLabel: {
    position: 'absolute',
    top: -20,
    right: 6,
    display: 'inline-flex',
    height: 16,
    alignItems: 'center',
    borderRadius: 4,
    paddingRight: 4,
    paddingLeft: 4,
    backgroundColor: 'rgba(21, 24, 28, 0.72)',
    color: 'rgba(255, 255, 255, 0.92)',
    fontSize: 8,
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: '10px',
  },
  loadingState: {
    display: 'flex',
    minHeight: 'calc(100vh - 230px)',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    gap: 10,
    color: colors.textQuiet,
    fontSize: 13,
  },
  spinner: {
    animationDuration: {
      'default': '850ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    animationIterationCount: 'infinite',
    animationName: stylex.keyframes({
      to: { transform: 'rotate(360deg)' },
    }),
    animationTimingFunction: 'linear',
  },
  emptyState: {
    display: 'flex',
    minHeight: 'calc(100vh - 230px)',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    paddingBottom: 36,
    textAlign: 'center',
  },
  emptyIcon: {
    width: 28,
    height: 28,
    marginBottom: 12,
    color: 'rgba(39, 72, 118, 0.62)',
  },
  emptyTitle: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 5,
    marginLeft: 0,
    fontSize: 17,
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: '22px',
  },
  emptyText: {
    maxWidth: 320,
    marginTop: 0,
    marginRight: 0,
    marginBottom: 16,
    marginLeft: 0,
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: '17px',
  },
  sheetLayer: {
    position: 'fixed',
    zIndex: 100,
    inset: 0,
    display: 'grid',
    alignItems: 'center',
    justifyItems: 'center',
  },
  sheetScrim: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    borderWidth: 0,
    padding: 0,
    backgroundColor: 'rgba(24, 27, 33, 0.12)',
  },
  sheet: {
    position: 'relative',
    display: 'flex',
    width: 'min(480px, calc(100vw - 48px))',
    maxHeight: 'calc(100vh - 72px)',
    overflow: 'hidden',
    flexDirection: 'column',
    borderColor: {
      'default': 'rgba(255, 255, 255, 0.78)',
      '@media (prefers-contrast: more)': 'rgba(33, 37, 44, 0.64)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 16,
    backgroundColor: {
      'default': 'rgba(250, 251, 253, 0.82)',
      '@media (prefers-contrast: more)': 'rgba(249, 249, 250, 0.96)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(249, 249, 250)',
    },
    backgroundImage: 'linear-gradient(145deg, rgba(255, 255, 255, 0.42) 0%, rgba(255, 255, 255, 0.1) 38%, rgba(237, 243, 251, 0.08) 100%), linear-gradient(180deg, rgba(255, 255, 255, 0.16) 0%, rgba(255, 255, 255, 0) 30%)',
    backdropFilter: {
      'default': 'blur(36px) saturate(170%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 30px 76px rgba(23, 28, 36, 0.25), 0 8px 22px rgba(23, 28, 36, 0.12), inset 1px 1px rgba(255, 255, 255, 0.84), inset -1px -1px rgba(48, 56, 69, 0.1)',
  },
  sheetHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 20,
    paddingTop: 24,
    paddingRight: 20,
    paddingBottom: 18,
    paddingLeft: 24,
  },
  managerHeading: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'flex-start',
    gap: 8,
  },
  managerBody: {
    display: 'flex',
    minHeight: 260,
    overflow: 'hidden',
    flexDirection: 'column',
  },
  managerList: {
    display: 'flex',
    minHeight: 0,
    overflowY: 'auto',
    flex: 1,
    flexDirection: 'column',
    gap: 2,
    paddingRight: 16,
    paddingBottom: 10,
    paddingLeft: 16,
  },
  managerSourceRow: {
    display: 'grid',
    minHeight: 58,
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '32px minmax(0, 1fr) 34px 34px',
    gap: 4,
    borderRadius: 10,
    paddingRight: 7,
    paddingLeft: 9,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(77, 84, 94, 0.06)',
    },
  },
  managerSourceIcon: {
    display: 'grid',
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyItems: 'center',
    borderRadius: 8,
    backgroundColor: 'rgba(0, 113, 227, 0.09)',
    color: colors.accent,
  },
  managerSourceDetails: {
    display: 'flex',
    minWidth: 0,
    overflow: 'hidden',
    flexDirection: 'column',
    gap: 2,
    borderWidth: 0,
    padding: 0,
    backgroundColor: 'transparent',
    color: colors.text,
    cursor: 'default',
    outline: 'none',
    textAlign: 'left',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  managerRemoveButton: {
    display: 'grid',
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyItems: 'center',
    borderWidth: 0,
    borderRadius: 9,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(198, 48, 48, 0.1)',
      ':active': 'rgba(198, 48, 48, 0.16)',
    },
    color: {
      'default': colors.textQuiet,
      ':hover': colors.danger,
    },
    cursor: 'default',
    outline: 'none',
  },
  managerActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    borderTopColor: 'rgba(255, 255, 255, 0.36)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: 14,
    paddingRight: 20,
    paddingBottom: 18,
    paddingLeft: 20,
  },
  sheetTitle: {
    margin: 0,
    fontSize: 21,
    fontWeight: 690,
    letterSpacing: 0,
    lineHeight: '26px',
  },
  sheetSubtitle: {
    maxWidth: 370,
    marginTop: 5,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: '17px',
  },
  sourceForm: {
    display: 'flex',
    minHeight: 0,
    overflowY: 'auto',
    flexDirection: 'column',
    gap: 15,
    paddingRight: 24,
    paddingBottom: 22,
    paddingLeft: 24,
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: 600,
  },
  fieldOptional: {
    marginLeft: 5,
    color: colors.textQuiet,
    fontSize: 10,
    fontWeight: 500,
  },
  textInput: {
    width: '100%',
    height: 36,
    borderColor: {
      'default': 'rgba(60, 60, 67, 0.16)',
      ':focus': 'rgba(0, 113, 227, 0.72)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: {
      'default': 'rgba(92, 92, 100, 0.1)',
      ':focus': 'rgba(255, 255, 255, 0.82)',
      '@media (prefers-contrast: more)': 'rgba(255, 255, 255, 0.9)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(235, 235, 237)',
    },
    caretColor: colors.accent,
    color: colors.text,
    fontSize: 13,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus': '0 0 0 3px rgba(0, 113, 227, 0.18)',
    },
    transitionDuration: controlTransition,
    transitionProperty: 'background-color, border-color, box-shadow',
    transitionTimingFunction: 'ease-out',
  },
  accountDisclosure: {
    display: 'flex',
    width: '100%',
    height: 34,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderColor: 'rgba(52, 59, 70, 0.08)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 9,
    paddingRight: 8,
    paddingLeft: 8,
    backgroundColor: {
      'default': 'rgba(42, 49, 61, 0.035)',
      ':hover': 'rgba(42, 49, 61, 0.07)',
      ':active': 'rgba(70, 78, 90, 0.1)',
    },
    color: colors.textMuted,
    cursor: 'default',
    fontSize: 12,
    outline: 'none',
    boxShadow: 'inset 0 1px rgba(255, 255, 255, 0.2)',
  },
  accountLabel: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
  },
  accountFields: {
    display: 'flex',
    overflow: 'hidden',
    flexDirection: 'column',
    gap: 12,
  },
  privacyNote: {
    margin: 0,
    color: colors.textQuiet,
    fontSize: 10,
    lineHeight: '15px',
  },
  formError: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 7,
    borderRadius: 9,
    paddingTop: 9,
    paddingRight: 10,
    paddingBottom: 9,
    paddingLeft: 10,
    backgroundColor: 'rgba(198, 48, 48, 0.09)',
    color: 'rgb(158, 38, 38)',
    fontSize: 11,
    lineHeight: '16px',
  },
  sheetActions: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
    borderTopColor: 'rgba(255, 255, 255, 0.36)',
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    marginTop: 2,
    paddingTop: 16,
  },
  primaryButton: {
    display: 'inline-flex',
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderColor: 'rgba(0, 83, 170, 0.16)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 11,
    paddingRight: 14,
    paddingLeft: 12,
    backgroundColor: {
      'default': colors.accent,
      ':hover': 'rgb(0, 105, 211)',
      ':active': colors.accentPressed,
      ':disabled': 'rgba(0, 113, 227, 0.48)',
    },
    color: 'white',
    cursor: 'default',
    fontSize: 13,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': '0 4px 11px rgba(0, 86, 178, 0.2), inset 0 1px rgba(255, 255, 255, 0.24)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.975)',
    },
    transitionDuration: controlTransition,
    transitionProperty: 'background-color, transform',
  },
  secondaryButton: {
    display: 'inline-flex',
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: 'rgba(255, 255, 255, 0.42)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 11,
    paddingRight: 14,
    paddingLeft: 14,
    backgroundColor: {
      'default': 'rgba(235, 240, 247, 0.18)',
      ':hover': 'rgba(255, 255, 255, 0.38)',
      ':active': 'rgba(71, 79, 91, 0.1)',
      ':disabled': 'rgba(235, 240, 247, 0.1)',
    },
    color: colors.text,
    cursor: 'default',
    fontSize: 13,
    fontWeight: 550,
    outline: 'none',
    boxShadow: {
      'default': 'inset 0 1px rgba(255, 255, 255, 0.54), 0 1px 2px rgba(35, 42, 52, 0.06)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  confirmSheet: {
    position: 'relative',
    display: 'flex',
    width: 'min(390px, calc(100vw - 48px))',
    alignItems: 'center',
    flexDirection: 'column',
    borderColor: 'rgba(255, 255, 255, 0.84)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 22,
    paddingTop: 25,
    paddingRight: 25,
    paddingBottom: 22,
    paddingLeft: 25,
    backgroundColor: {
      'default': 'rgba(248, 248, 250, 0.86)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(249, 249, 250)',
    },
    backdropFilter: {
      'default': 'blur(42px) saturate(180%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: '0 34px 90px rgba(23, 28, 36, 0.28), 0 8px 24px rgba(23, 28, 36, 0.13), inset 0 1px rgba(255, 255, 255, 0.95)',
    textAlign: 'center',
  },
  destructiveGlyph: {
    display: 'grid',
    width: 46,
    height: 46,
    alignItems: 'center',
    justifyItems: 'center',
    marginBottom: 13,
    borderRadius: 14,
    backgroundColor: 'rgba(198, 48, 48, 0.1)',
    color: colors.danger,
  },
  confirmTitle: {
    margin: 0,
    fontSize: 18,
    fontWeight: 670,
    letterSpacing: 0,
    lineHeight: '23px',
  },
  confirmText: {
    maxWidth: 320,
    marginTop: 8,
    marginRight: 0,
    marginBottom: 20,
    marginLeft: 0,
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: '18px',
  },
  confirmActions: {
    display: 'grid',
    width: '100%',
    gridTemplateColumns: '1fr 1fr',
    gap: 8,
  },
  destructiveButton: {
    minHeight: 36,
    borderWidth: 0,
    borderRadius: 11,
    paddingRight: 14,
    paddingLeft: 14,
    backgroundColor: {
      'default': colors.danger,
      ':hover': 'rgb(181, 40, 40)',
      ':active': 'rgb(158, 32, 32)',
      ':disabled': 'rgba(198, 48, 48, 0.52)',
    },
    color: 'white',
    cursor: 'default',
    fontSize: 13,
    fontWeight: 600,
    outline: 'none',
    boxShadow: {
      'default': '0 4px 11px rgba(157, 29, 29, 0.18), inset 0 1px rgba(255, 255, 255, 0.2)',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
})
