import * as stylex from '@stylexjs/stylex'

const spin = stylex.keyframes({
  to: { transform: 'rotate(360deg)' },
})

const colors = {
  error: 'rgb(176, 54, 50)',
  focus: 'rgba(0, 96, 204, 0.44)',
  muted: 'rgba(45, 50, 58, 0.56)',
  text: 'rgba(23, 27, 33, 0.94)',
} as const

const controlShadow = '0 2px 6px rgba(31, 38, 48, 0.08), 0 0 0 0.5px rgba(55, 63, 74, 0.08), inset 0 1px rgba(255, 255, 255, 0.98), inset 0 -1px rgba(72, 79, 90, 0.07)'

export const ankiReviewPageStyles = stylex.create({
  page: {
    position: 'relative',
    display: 'grid',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    gridTemplateRows: 'minmax(0, 1fr) auto',
    overflow: 'hidden',
    paddingTop: 56,
    backgroundColor: 'rgb(255, 255, 255)',
    color: colors.text,
  },
  mediaWarning: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 10,
    marginLeft: 0,
    borderRadius: 7,
    paddingTop: 7,
    paddingRight: 10,
    paddingBottom: 7,
    paddingLeft: 10,
    backgroundColor: 'rgba(255, 247, 246, 0.96)',
    boxShadow: 'inset 0 0 0 1px rgba(176, 54, 50, 0.13)',
    color: colors.error,
    fontSize: 10,
    letterSpacing: 0,
    lineHeight: '15px',
  },
  titlebarActions: {
    display: 'flex',
    alignItems: 'center',
  },
  centered: {
    display: 'flex',
    gridRow: '1 / -1',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    gap: 9,
    padding: 28,
    color: colors.muted,
    fontSize: 12,
    letterSpacing: 0,
    textAlign: 'center',
  },
  statusTitle: {
    margin: 0,
    color: colors.text,
    fontSize: 18,
    fontWeight: 680,
    letterSpacing: 0,
    lineHeight: '24px',
  },
  statusMessage: {
    width: 'min(460px, 100%)',
    margin: 0,
    lineHeight: '18px',
  },
  statusActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
  },
  statusButton: {
    display: 'inline-flex',
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: 'rgba(52, 59, 69, 0.13)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 7,
    paddingRight: 13,
    paddingLeft: 13,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    boxShadow: controlShadow,
    color: colors.text,
    cursor: 'default',
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: 0,
    outline: 'none',
    textDecoration: 'none',
  },
  spinner: {
    animationDuration: '800ms',
    animationIterationCount: 'infinite',
    animationName: spin,
    animationTimingFunction: 'linear',
  },
})
