import * as stylex from '@stylexjs/stylex'
import { editorColors } from '../../common/editor-theme.stylex'

export const imageViewStyles = stylex.create({
  resizable: {
    position: 'relative',
    boxSizing: 'border-box',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 64,
    minHeight: 64,
    maxWidth: '100%',
    maxHeight: 600,
    overflow: 'hidden',
    marginBlock: 8,
    outlineColor: 'transparent',
    outlineStyle: 'solid',
    outlineWidth: 2,
  },
  selected: {
    outlineColor: editorColors.blue500,
  },
  image: {
    display: 'block',
    width: '100%',
    height: '100%',
    maxWidth: '100%',
    maxHeight: '100%',
    objectFit: 'contain',
  },
  occlusionPreview: {
    position: 'absolute',
    inset: 0,
    zIndex: 1,
    display: 'block',
    width: '100%',
    height: '100%',
    overflow: 'visible',
    pointerEvents: 'none',
  },
  handle: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 24,
    height: 24,
    margin: 6,
    borderWidth: 0,
    borderRadius: 4,
    padding: 4,
    backgroundColor: 'rgb(17 24 39 / 30%)',
    color: 'rgb(255 255 255 / 50%)',
    opacity: {
      'default': 0,
      ':hover': 1,
    },
    transitionDuration: '150ms',
  },
  overlay: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    padding: 8,
    backgroundColor: editorColors.gray200,
    color: editorColors.gray800,
    fontSize: 14,
    textAlign: 'center',
  },
  error: {
    color: editorColors.red500,
  },
  bubble: {
    position: 'absolute',
    top: 8,
    left: '50%',
    zIndex: 2,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 4,
    transform: 'translateX(-50%)',
  },
  bubbleButton: {
    boxSizing: 'border-box',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    minHeight: 30,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'rgb(255 255 255 / 35%)',
    borderRadius: 6,
    paddingBlock: 5,
    paddingInline: 10,
    backgroundColor: 'rgb(25 28 34 / 78%)',
    backdropFilter: 'blur(14px) saturate(140%)',
    boxShadow: '0 6px 18px rgb(0 0 0 / 20%)',
    color: '#ffffff',
    fontSize: 12,
    lineHeight: 1.2,
    whiteSpace: 'nowrap',
    cursor: 'pointer',
    opacity: {
      ':disabled': 0.55,
    },
  },
  bubbleError: {
    borderRadius: 4,
    paddingBlock: 3,
    paddingInline: 6,
    backgroundColor: 'rgb(127 29 29 / 88%)',
    color: '#ffffff',
    fontSize: 11,
    lineHeight: 1.2,
    whiteSpace: 'nowrap',
  },
  spinner: {
    'animationName': stylex.keyframes({
      to: { transform: 'rotate(360deg)' },
    }),
    'animationDuration': '800ms',
    'animationIterationCount': 'infinite',
    'animationTimingFunction': 'linear',
    '@media (prefers-reduced-motion: reduce)': {
      animationName: 'none',
    },
  },
})
