import * as stylex from '@stylexjs/stylex'

const colors = {
  accent: 'var(--ui-accent, rgb(0, 113, 227))',
  border: 'var(--ui-border, rgba(71, 76, 86, 0.2))',
  canvas: 'var(--ui-canvas, rgb(250, 250, 249))',
  controlHover: 'var(--ui-control-hover, rgba(76, 84, 96, 0.07))',
  controlPressed: 'var(--ui-control-pressed, rgba(80, 91, 108, 0.14))',
  danger: 'var(--ui-danger, rgb(166, 53, 53))',
  divider: 'var(--ui-divider, rgba(55, 61, 70, 0.11))',
  focus: 'var(--ui-focus, rgba(41, 97, 194, 0.84))',
  overlayShadow: 'var(--ui-overlay-shadow, 0 20px 48px rgba(26, 32, 42, 0.22), 0 4px 12px rgba(26, 32, 42, 0.1))',
  surface: 'var(--ui-surface, rgba(250, 250, 251, 0.9))',
  surfaceRaised: 'var(--ui-surface-raised, rgba(250, 251, 253, 0.96))',
  text: 'var(--ui-text, rgba(27, 28, 31, 0.92))',
  textMuted: 'var(--ui-text-muted, rgba(46, 48, 54, 0.64))',
  textQuiet: 'var(--ui-text-quiet, rgba(55, 57, 63, 0.46))',
} as const

const controlRadius = 'var(--ui-control-radius, 8px)'
const transitionDuration = 'var(--ui-motion-duration, 140ms)'
const motionEasing = 'var(--ui-motion-easing, ease-out)'

export const panelStyles = stylex.create({
  panel: {
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    flexDirection: 'column',
    overflow: 'hidden',
    borderColor: colors.border,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: colors.canvas,
    color: colors.text,
    boxShadow: colors.overlayShadow,
  },
  tabBar: {
    display: 'flex',
    height: 54,
    flex: '0 0 54px',
    alignItems: 'center',
    paddingRight: 14,
    paddingLeft: 14,
    borderBottomColor: colors.divider,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    backgroundColor: colors.surface,
  },
  tabList: {
    width: '100%',
    display: 'flex',
    backgroundColor: colors.controlHover,
  },
  tabTrigger: {
    height: 32,
    flex: '1 1 0',
    fontSize: 13,
    letterSpacing: 0,
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.985)',
    },
  },
  content: {
    position: 'relative',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflow: 'hidden',
  },
  contentMotion: {
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
  },
  tabPanel: {
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    flexDirection: 'column',
  },
  sectionHeader: {
    display: 'flex',
    height: 58,
    flex: '0 0 58px',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingRight: 18,
    paddingLeft: 22,
  },
  sectionHeading: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'baseline',
    gap: 8,
  },
  sectionTitle: {
    margin: 0,
    color: colors.text,
    fontSize: 15,
    fontWeight: 620,
    letterSpacing: 0,
    lineHeight: '22px',
  },
  count: {
    color: colors.textQuiet,
    fontSize: 12,
    fontWeight: 500,
    letterSpacing: 0,
    lineHeight: '18px',
  },
  iconButton: {
    display: 'grid',
    width: 30,
    height: 30,
    flex: '0 0 30px',
    placeItems: 'center',
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 0,
    borderRadius: controlRadius,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': colors.controlHover,
      ':active': colors.controlPressed,
    },
    color: colors.textMuted,
    cursor: 'default',
    outline: 'none',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.96)',
    },
    transitionDuration,
    transitionProperty: 'background-color, color, transform',
    transitionTimingFunction: motionEasing,
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  taskList: {
    minHeight: 0,
    flex: 1,
    overflowX: 'hidden',
    overflowY: 'auto',
    overscrollBehaviorY: 'contain',
    paddingRight: 12,
    paddingBottom: 14,
    paddingLeft: 12,
  },
  taskRow: {
    display: 'flex',
    minHeight: 54,
    alignItems: 'flex-start',
    gap: 11,
    paddingTop: 9,
    paddingRight: 10,
    paddingBottom: 9,
    paddingLeft: 10,
    borderBottomColor: colors.divider,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
  },
  taskCheckbox: {
    width: 17,
    height: 17,
    flex: '0 0 17px',
    marginTop: 2,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    accentColor: colors.accent,
    cursor: 'default',
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  taskContent: {
    minWidth: 0,
    flex: 1,
  },
  taskText: {
    overflow: 'hidden',
    color: colors.text,
    fontSize: 13,
    fontWeight: 500,
    letterSpacing: 0,
    lineHeight: '19px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  taskMetadata: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 6,
    marginTop: 3,
    overflow: 'hidden',
    color: colors.textQuiet,
    fontSize: 11,
    fontWeight: 450,
    letterSpacing: 0,
    lineHeight: '16px',
    whiteSpace: 'nowrap',
  },
  doingLabel: {
    flex: '0 0 auto',
    color: colors.accent,
    fontWeight: 600,
  },
  taskSource: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  loadMore: {
    display: 'flex',
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 10,
    paddingBottom: 4,
  },
  inlineError: {
    display: 'flex',
    minHeight: 34,
    alignItems: 'center',
    gap: 7,
    marginRight: 18,
    marginBottom: 4,
    marginLeft: 18,
    paddingRight: 9,
    paddingLeft: 9,
    borderRadius: controlRadius,
    backgroundColor: `color-mix(in srgb, ${colors.danger} 8%, transparent)`,
    color: colors.danger,
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: '17px',
  },
  status: {
    display: 'flex',
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 24,
    color: colors.textMuted,
    fontSize: 13,
    letterSpacing: 0,
    lineHeight: '19px',
    textAlign: 'center',
  },
  empty: {
    display: 'grid',
    minHeight: 0,
    flex: 1,
    placeItems: 'center',
    padding: 24,
    color: colors.textQuiet,
    fontSize: 13,
    letterSpacing: 0,
    lineHeight: '19px',
  },
  retryButton: {
    minHeight: 28,
    borderColor: colors.border,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: controlRadius,
    paddingRight: 10,
    paddingLeft: 10,
    backgroundColor: {
      'default': colors.surfaceRaised,
      ':hover': colors.controlHover,
      ':active': colors.controlPressed,
    },
    color: colors.text,
    cursor: 'default',
    fontSize: 12,
    fontWeight: 550,
    letterSpacing: 0,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': `0 0 0 2px ${colors.focus}`,
    },
  },
  spinningIcon: {
    animationDuration: '900ms',
    animationIterationCount: 'infinite',
    animationName: stylex.keyframes({
      to: { transform: 'rotate(360deg)' },
    }),
    animationTimingFunction: 'linear',
  },
})
