import * as stylex from '@stylexjs/stylex'
import { editorColors } from './editor-theme.stylex'

const cursorBlink = stylex.keyframes({
  '0%, 100%': { opacity: 0.72 },
  '50%': { opacity: 1 },
})

export const editorCanvasStyles = stylex.create({
  cursorOverlay: {
    position: 'absolute',
    inset: 0,
    overflow: 'hidden',
    pointerEvents: 'none',
    zIndex: 2,
  },
  cursor: {
    position: 'absolute',
    width: 2,
    borderRadius: 1,
    backgroundColor: 'var(--ui-accent, #157a5b)',
    transformOrigin: 'top left',
    willChange: 'transform, opacity',
  },
  cursorTrail: {
    position: 'absolute',
    width: 1,
    height: 2,
    borderRadius: 1,
    backgroundColor: 'var(--ui-accent, #157a5b)',
    opacity: 0,
    transformOrigin: 'left center',
    willChange: 'transform, opacity',
  },
  cursorParticle: {
    position: 'absolute',
    width: 5,
    height: 5,
    borderRadius: 999,
    backgroundColor: 'var(--ui-accent, #157a5b)',
    transformOrigin: 'center',
    willChange: 'transform, opacity',
  },
  cursorParticleTrail: {
    width: 8,
    height: 2,
    borderRadius: 1,
  },
  cursorParticleTorpedo: {
    width: 6,
    height: 3,
    borderRadius: 999,
  },
  cursorParticlePixieDust: {
    width: 3,
    height: 3,
    borderRadius: 1,
  },
  cursorParticleSonicBoom: {
    width: 6,
    height: 6,
    borderRadius: 999,
  },
  cursorParticleRipple: {
    width: 8,
    height: 8,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--ui-accent, #157a5b)',
    backgroundColor: 'transparent',
  },
  cursorParticleWireframe: {
    width: 8,
    height: 8,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--ui-accent, #157a5b)',
    borderRadius: 1,
    backgroundColor: 'transparent',
  },
  cursorBlink: {
    animationName: cursorBlink,
    animationDuration: '600ms',
    animationTimingFunction: 'ease-in-out',
    animationIterationCount: 'infinite',
  },
  viewport: {
    boxSizing: 'border-box',
    display: 'flex',
    width: '100%',
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
    flexDirection: 'column',
    backgroundColor: editorColors.canvas,
    color: 'var(--ui-text, #000000)',
  },
  viewportEmbedded: {
    flex: '0 0 auto',
    minHeight: 'auto',
    overflow: 'visible',
  },
  viewportEmbeddedEmpty: {
    minHeight: 'inherit',
  },
  scrolling: {
    position: 'relative',
    boxSizing: 'border-box',
    width: '100%',
    minHeight: 0,
    flex: 1,
    overflowY: 'auto',
    backgroundColor: editorColors.canvas,
  },
  scrollingEmbedded: {
    flex: '0 0 auto',
    minHeight: 'auto',
    overflowY: 'visible',
  },
  scrollingEmbeddedEmpty: {
    minHeight: 'inherit',
  },
  content: {
    boxSizing: 'border-box',
    width: '100%',
    minHeight: '100%',
    paddingBlock: 32,
    paddingInline: 'max(4rem, calc(50% - 20rem))',
    outline: 'none',
  },
  contentEmbedded: {
    minHeight: 'auto',
    paddingTop: 8,
    paddingBottom: 12,
  },
  contentChoosingMode: {
    opacity: 0,
  },
  uploadStatus: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 34,
    borderBottomColor: 'var(--ui-divider, #dce1e5)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingInline: 12,
    backgroundColor: 'var(--ui-surface-sunken, #edf7f2)',
    color: 'var(--ui-text, #225a47)',
    fontSize: 13,
  },
  uploadStatusError: {
    backgroundColor: 'color-mix(in srgb, var(--ui-danger, #9e3030) 10%, var(--ui-canvas, #fff))',
    color: 'var(--ui-danger, #9e3030)',
  },
  uploadStatusButton: {
    borderWidth: 0,
    backgroundColor: 'transparent',
    color: 'inherit',
    cursor: 'pointer',
    fontWeight: 600,
  },
})
