import * as stylex from '@stylexjs/stylex'
import { editorColors } from '../../common/editor-theme.stylex'

export const cardMenuStyles = stylex.create({
  popup: {
    position: 'fixed',
    zIndex: 110,
    display: 'flex',
    width: 240,
    maxWidth: 'calc(100vw - 24px)',
    flexDirection: 'column',
    gap: 6,
    borderRadius: 8,
    padding: 8,
    color: editorColors.gray900,
    fontSize: 12,
    userSelect: 'none',
  },
  row: {
    display: 'grid',
    width: '100%',
    alignItems: 'center',
    gap: 8,
    gridTemplateColumns: '64px minmax(0, 1fr)',
  },
  group: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    borderRadius: 8,
    padding: 2,
    backgroundColor: editorColors.gray100,
    boxShadow: 'inset 0 0 0 1px rgb(46 67 88 / 6%)',
  },
  label: {
    color: editorColors.gray500,
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: '0.01em',
  },
  button: {
    'minWidth': 0,
    'height': 28,
    'flex': 1,
    'borderWidth': 0,
    'borderRadius': 6,
    'paddingInline': 6,
    'backgroundColor': {
      'default': 'transparent',
      ':hover': editorColors.gray200,
      ':active': editorColors.gray200,
    },
    'color': editorColors.gray900,
    'cursor': 'pointer',
    'font': 'inherit',
    'fontSize': 12,
    'fontWeight': 550,
    'outline': 'none',
    'transitionDuration': '100ms',
    'transitionProperty': 'background-color, box-shadow, color, transform',
    ':active': {
      transform: 'scale(0.96)',
    },
    ':focus-visible': {
      boxShadow: `0 0 0 2px ${editorColors.blue500}`,
    },
  },
  selected: {
    backgroundColor: '#dcecf9',
    boxShadow: '0 2px 5px rgb(31 72 108 / 16%), inset 0 0 0 1px rgb(66 126 177 / 34%), inset 0 1px 0 rgb(255 255 255 / 72%)',
    color: '#174f7f',
    fontWeight: 680,
  },
  previewPopup: {
    position: 'fixed',
    zIndex: 110,
    boxSizing: 'border-box',
    display: 'flex',
    width: 440,
    maxWidth: 'calc(100vw - 24px)',
    maxHeight: 'calc(100vh - 24px)',
    overflow: 'hidden',
    flexDirection: 'column',
    borderRadius: 8,
    color: editorColors.gray900,
    outline: 'none',
  },
  previewHeader: {
    display: 'flex',
    minHeight: 42,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingInline: 12,
    boxShadow: `inset 0 -1px 0 ${editorColors.gray200}`,
  },
  previewTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    color: editorColors.gray800,
    fontSize: 12,
    fontWeight: 650,
  },
  iconButton: {
    'display': 'flex',
    'width': 28,
    'height': 28,
    'alignItems': 'center',
    'justifyContent': 'center',
    'borderWidth': 0,
    'borderRadius': 6,
    'padding': 0,
    'backgroundColor': {
      'default': 'transparent',
      ':hover': editorColors.gray100,
      ':active': editorColors.gray200,
    },
    'color': editorColors.gray500,
    'cursor': 'pointer',
    'outline': 'none',
    ':focus-visible': {
      boxShadow: `0 0 0 2px ${editorColors.blue500}`,
    },
  },
  previewDirection: {
    display: 'flex',
    flexShrink: 0,
    alignItems: 'center',
    gap: 2,
    marginBlock: 8,
    marginInline: 12,
    borderRadius: 8,
    padding: 2,
    backgroundColor: editorColors.gray100,
  },
  previewBody: {
    minHeight: 0,
    overflowY: 'auto',
    overscrollBehavior: 'contain',
  },
})
