import * as stylex from '@stylexjs/stylex'

const spin = stylex.keyframes({
  to: { transform: 'rotate(360deg)' },
})

const colors = {
  accent: 'rgb(0, 113, 227)',
  line: 'rgba(55, 61, 70, 0.11)',
  muted: 'rgba(48, 53, 61, 0.58)',
  text: 'rgba(24, 27, 32, 0.92)',
} as const

export const learningNotesStyles = stylex.create({
  workspace: {
    display: 'flex',
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
  },
  scroll: {
    width: '100%',
    minHeight: 0,
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    paddingTop: 16,
    paddingRight: 'clamp(20px, 5vw, 54px)',
    paddingBottom: 36,
    paddingLeft: 'clamp(20px, 5vw, 54px)',
  },
  content: {
    width: 'min(820px, 100%)',
    marginRight: 'auto',
    marginLeft: 'auto',
  },
  list: {
    display: 'flex',
    width: '100%',
    flexDirection: 'column',
    borderTopColor: colors.line,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
  },
  listItem: {
    width: '100%',
    borderBottomColor: 'rgba(55, 61, 70, 0.08)',
    borderBottomStyle: 'solid',
    borderBottomWidth: {
      'default': 1,
      ':last-child': 0,
    },
  },
  row: {
    display: 'grid',
    width: '100%',
    minWidth: 0,
    minHeight: 68,
    alignItems: 'center',
    gridTemplateColumns: {
      'default': '42px minmax(0, 1fr) minmax(168px, 196px) 32px',
      '@media (max-width: 760px)': '42px minmax(0, 1fr) minmax(148px, 184px) 32px',
      '@media (max-width: 540px)': '42px minmax(0, 1fr) 32px',
    },
    gap: 10,
    paddingTop: 8,
    paddingRight: 8,
    paddingBottom: 8,
    paddingLeft: 8,
    backgroundColor: 'transparent',
    color: colors.text,
  },
  noteIcon: {
    display: 'grid',
    width: 32,
    height: 32,
    placeItems: 'center',
    borderRadius: 8,
    backgroundColor: 'rgba(0, 113, 227, 0.085)',
    boxShadow: 'inset 0 0 0 0.5px rgba(0, 88, 184, 0.11)',
    color: 'rgba(0, 96, 204, 0.82)',
  },
  deckTreeItem: {
    width: '100%',
    borderBottomColor: 'rgba(55, 61, 70, 0.08)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
  },
  deckRow: {
    display: 'grid',
    width: '100%',
    minWidth: 0,
    minHeight: 60,
    alignItems: 'center',
    gridTemplateColumns: 'minmax(0, 1fr) 32px',
    gap: 10,
    paddingTop: 6,
    paddingRight: 8,
    paddingBottom: 6,
    paddingLeft: 0,
  },
  deckLeading: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 10,
  },
  disclosureButton: {
    display: 'grid',
    width: 20,
    height: 20,
    flex: '0 0 20px',
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: 6,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(45, 52, 62, 0.07)',
      ':active': 'rgba(45, 52, 62, 0.12)',
    },
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgba(0, 96, 204, 0.34)',
    },
    color: 'rgba(42, 49, 58, 0.58)',
    cursor: 'default',
    outline: 'none',
  },
  deckIcon: {
    display: 'grid',
    width: 32,
    height: 32,
    flex: '0 0 32px',
    placeItems: 'center',
    borderRadius: 8,
    backgroundColor: 'rgb(0, 113, 227)',
    boxShadow: 'inset 0 0 0 0.5px rgba(0, 72, 153, 0.32), 0 1px 2px rgba(0, 71, 153, 0.18)',
    color: 'white',
  },
  identity: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
  },
  deckTitleLine: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: 4,
  },
  noteTitle: {
    overflow: 'hidden',
    minWidth: 0,
    color: colors.text,
    fontSize: 13,
    fontWeight: 620,
    letterSpacing: 0,
    lineHeight: '18px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  metadata: {
    display: 'flex',
    overflow: 'hidden',
    minWidth: 0,
    alignItems: 'center',
    gap: 6,
    marginTop: 2,
    color: 'rgba(34, 66, 105, 0.56)',
    fontSize: 10,
    fontVariantNumeric: 'tabular-nums',
    letterSpacing: 0,
    lineHeight: '15px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  metadataSeparator: {
    color: 'rgba(34, 66, 105, 0.3)',
  },
  updatedMetadata: {
    display: {
      'default': 'inline-flex',
      '@media (max-width: 760px)': 'none',
    },
    alignItems: 'center',
    gap: 6,
  },
  optimizerControl: {
    display: 'flex',
    width: '100%',
    maxWidth: 190,
    minWidth: 0,
    alignItems: 'flex-end',
    flexDirection: 'column',
    gridColumn: {
      'default': 'auto',
      '@media (max-width: 540px)': '2',
    },
    justifySelf: {
      'default': 'end',
      '@media (max-width: 540px)': 'start',
    },
    marginTop: {
      'default': 0,
      '@media (max-width: 540px)': 5,
    },
  },
  optimizerField: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    minWidth: 0,
    height: 28,
    alignItems: 'center',
  },
  optimizerSelect: {
    width: '100%',
    height: 28,
    minWidth: 0,
    appearance: 'none',
    borderColor: {
      'default': 'rgba(50, 56, 65, 0.14)',
      ':hover': 'rgba(45, 51, 60, 0.22)',
      ':focus': 'rgba(0, 96, 204, 0.5)',
      '@media (prefers-contrast: more)': 'rgba(38, 44, 53, 0.58)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    paddingRight: 26,
    paddingLeft: 27,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.72)',
      ':hover': 'rgba(255, 255, 255, 0.94)',
      ':active': 'rgba(247, 248, 250, 0.88)',
      ':disabled': 'rgba(255, 255, 255, 0.58)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(255, 255, 255)',
      '@media (prefers-contrast: more)': 'rgb(255, 255, 255)',
    },
    backdropFilter: {
      'default': 'blur(16px) saturate(150%) contrast(1.025)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': '0 2px 5px rgba(31, 37, 47, 0.08), 0 0 0 0.5px rgba(58, 65, 76, 0.06), inset 0 1px rgba(255, 255, 255, 0.98), inset 0 -1px rgba(72, 79, 90, 0.06)',
      ':focus': '0 0 0 2px rgba(0, 96, 204, 0.22), 0 2px 5px rgba(31, 37, 47, 0.08), inset 0 1px rgba(255, 255, 255, 0.98)',
    },
    color: 'rgba(27, 32, 39, 0.84)',
    cursor: 'default',
    fontSize: 11,
    fontWeight: 570,
    letterSpacing: 0,
    lineHeight: '16px',
    outline: 'none',
    opacity: {
      'default': 1,
      ':disabled': 0.72,
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, border-color, box-shadow',
    transitionTimingFunction: 'ease-out',
  },
  optimizerIcon: {
    position: 'absolute',
    zIndex: 1,
    left: 8,
    color: 'rgba(48, 54, 63, 0.58)',
    pointerEvents: 'none',
  },
  optimizerStatusIcon: {
    position: 'absolute',
    zIndex: 1,
    right: 8,
    color: 'rgba(48, 54, 63, 0.48)',
    pointerEvents: 'none',
  },
  assignmentError: {
    overflow: 'hidden',
    width: '100%',
    marginTop: 2,
    color: 'rgb(166, 53, 53)',
    fontSize: 9,
    letterSpacing: 0,
    lineHeight: '12px',
    textAlign: 'right',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  studyButton: {
    display: 'grid',
    width: 30,
    height: 30,
    placeItems: 'center',
    gridColumn: {
      'default': 'auto',
      '@media (max-width: 540px)': '3',
    },
    gridRow: {
      'default': 'auto',
      '@media (max-width: 540px)': '1 / span 2',
    },
    justifySelf: 'end',
    borderColor: 'rgba(50, 56, 65, 0.14)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 7,
    backgroundColor: {
      'default': 'rgba(255, 255, 255, 0.72)',
      ':hover': 'rgba(255, 255, 255, 0.96)',
      ':active': 'rgba(235, 238, 242, 0.9)',
      '@media (prefers-reduced-transparency: reduce)': 'rgb(255, 255, 255)',
    },
    backdropFilter: {
      'default': 'blur(16px) saturate(150%)',
      '@media (prefers-reduced-transparency: reduce)': 'none',
    },
    boxShadow: {
      'default': '0 2px 5px rgba(31, 37, 47, 0.08), 0 0 0 0.5px rgba(58, 65, 76, 0.06), inset 0 1px rgba(255, 255, 255, 0.98), inset 0 -1px rgba(72, 79, 90, 0.06)',
      ':focus-visible': '0 0 0 2px rgba(0, 96, 204, 0.34)',
    },
    color: 'rgb(0, 94, 196)',
    cursor: 'default',
    outline: 'none',
    textDecoration: 'none',
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, box-shadow, transform',
    transitionTimingFunction: 'ease-out',
  },
  empty: {
    display: 'grid',
    minHeight: 150,
    placeItems: 'center',
    borderTopColor: colors.line,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    color: colors.muted,
    fontSize: 11,
    letterSpacing: 0,
  },
  status: {
    display: 'flex',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    color: colors.muted,
    fontSize: 11,
    letterSpacing: 0,
  },
  inlineStatus: {
    display: 'flex',
    minHeight: 60,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderBottomColor: 'rgba(55, 61, 70, 0.08)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    color: colors.muted,
    fontSize: 11,
    letterSpacing: 0,
  },
  spinner: {
    animationDuration: '800ms',
    animationIterationCount: 'infinite',
    animationName: spin,
    animationTimingFunction: 'linear',
  },
  retryButton: {
    borderWidth: 0,
    paddingTop: 3,
    paddingRight: 6,
    paddingBottom: 3,
    paddingLeft: 6,
    backgroundColor: 'transparent',
    color: colors.accent,
    cursor: 'default',
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0,
    outline: 'none',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgba(0, 96, 204, 0.72)',
    },
  },
})
