import * as stylex from '@stylexjs/stylex'

const rotate = stylex.keyframes({
  to: { transform: 'rotate(360deg)' },
})

const pulse = stylex.keyframes({
  '0%, 100%': { opacity: 0.38 },
  '50%': { opacity: 0.8 },
})

const colors = {
  accent: 'rgb(0, 113, 227)',
  accentStrong: 'rgb(0, 94, 196)',
  line: 'rgba(50, 57, 67, 0.1)',
  muted: 'rgba(48, 54, 63, 0.58)',
  text: 'rgba(24, 27, 32, 0.92)',
} as const

export const learningActivityStyles = stylex.create({
  panel: {
    width: '100%',
    marginBottom: 18,
    paddingTop: 4,
    paddingRight: 4,
    paddingBottom: 0,
    paddingLeft: 4,
    color: colors.text,
  },
  header: {
    display: 'flex',
    minHeight: 25,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  heading: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'baseline',
    gap: 8,
  },
  title: {
    margin: 0,
    color: colors.text,
    fontSize: 12,
    fontWeight: 680,
    letterSpacing: 0,
    lineHeight: '18px',
  },
  period: {
    color: colors.muted,
    fontSize: 10,
    fontVariantNumeric: 'tabular-nums',
    letterSpacing: 0,
    lineHeight: '16px',
  },
  refreshButton: {
    display: 'grid',
    width: 26,
    height: 26,
    placeItems: 'center',
    borderColor: {
      'default': 'transparent',
      ':hover': 'rgba(50, 57, 67, 0.11)',
      ':focus-visible': 'rgba(0, 96, 204, 0.38)',
    },
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 6,
    padding: 0,
    backgroundColor: {
      'default': 'transparent',
      ':hover': 'rgba(255, 255, 255, 0.78)',
      ':active': 'rgba(230, 234, 239, 0.8)',
    },
    color: 'rgba(47, 54, 64, 0.56)',
    cursor: 'default',
    outline: 'none',
    opacity: {
      'default': 1,
      ':disabled': 0.58,
    },
    transform: {
      'default': 'scale(1)',
      ':active': 'scale(0.94)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, border-color, transform',
    transitionTimingFunction: 'ease-out',
  },
  refreshing: {
    animationDuration: '720ms',
    animationIterationCount: 'infinite',
    animationName: rotate,
    animationTimingFunction: 'linear',
  },
  summary: {
    display: 'grid',
    alignItems: 'stretch',
    gridTemplateColumns: {
      'default': 'minmax(0, 1fr) 176px',
      '@media (max-width: 900px)': 'minmax(0, 1fr)',
    },
    gap: 14,
    marginTop: 8,
  },
  metrics: {
    display: 'grid',
    minWidth: 0,
    gridTemplateColumns: {
      'default': 'repeat(4, minmax(0, 1fr))',
      '@media (max-width: 900px)': 'repeat(2, minmax(0, 1fr))',
      '@media (max-width: 620px)': 'minmax(0, 1fr)',
    },
    columnGap: 12,
    rowGap: 12,
  },
  metric: {
    display: 'grid',
    minWidth: 0,
    alignItems: 'center',
    gridTemplateColumns: '24px minmax(0, 1fr)',
    gap: 7,
  },
  metricIcon: {
    display: 'grid',
    width: 24,
    height: 24,
    placeItems: 'center',
    borderRadius: 6,
  },
  metricIconBlue: {
    backgroundColor: 'rgba(0, 113, 227, 0.09)',
    color: 'rgba(0, 94, 196, 0.84)',
  },
  metricIconNeutral: {
    backgroundColor: 'rgba(72, 81, 94, 0.075)',
    color: 'rgba(55, 63, 74, 0.68)',
  },
  metricIconWarm: {
    backgroundColor: 'rgba(224, 130, 20, 0.095)',
    color: 'rgb(184, 95, 8)',
  },
  metricIconGreen: {
    backgroundColor: 'rgba(28, 152, 80, 0.09)',
    color: 'rgb(26, 128, 70)',
  },
  metricText: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
  },
  metricLabel: {
    overflow: 'hidden',
    color: colors.muted,
    fontSize: 9,
    fontWeight: 610,
    letterSpacing: 0,
    lineHeight: '13px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  metricValue: {
    overflow: 'hidden',
    color: colors.text,
    fontSize: 15,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: '19px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  trend: {
    display: 'flex',
    minWidth: 0,
    justifyContent: 'center',
    borderLeftColor: {
      'default': colors.line,
      '@media (max-width: 900px)': 'transparent',
    },
    borderLeftStyle: 'solid',
    borderLeftWidth: 1,
    borderTopColor: {
      'default': 'transparent',
      '@media (max-width: 900px)': colors.line,
    },
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: {
      'default': 0,
      '@media (max-width: 900px)': 10,
    },
    paddingLeft: {
      'default': 14,
      '@media (max-width: 900px)': 0,
    },
    flexDirection: 'column',
  },
  trendLabel: {
    color: colors.muted,
    fontSize: 9,
    fontWeight: 610,
    letterSpacing: 0,
    lineHeight: '13px',
  },
  sparkline: {
    display: 'block',
    width: '100%',
    height: 38,
    marginTop: 2,
    color: colors.accent,
    overflow: 'visible',
  },
  goal: {
    marginTop: 13,
  },
  goalLabels: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: 4,
    color: colors.muted,
    fontSize: 9,
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 580,
    letterSpacing: 0,
    lineHeight: '13px',
  },
  goalTrack: {
    width: '100%',
    height: 5,
    overflow: 'hidden',
    borderRadius: 3,
    backgroundColor: 'rgba(60, 69, 82, 0.1)',
  },
  goalFill: {
    display: 'block',
    height: '100%',
    borderRadius: 3,
    backgroundColor: colors.accent,
  },
  heatmap: {
    display: 'grid',
    minWidth: 0,
    alignItems: 'start',
    gridTemplateColumns: '14px minmax(0, 1fr)',
    gap: 5,
    marginTop: 13,
  },
  weekdays: {
    display: 'grid',
    height: 88,
    gridTemplateRows: 'repeat(7, 10px)',
    gap: 3,
    color: 'rgba(48, 54, 63, 0.48)',
    fontSize: 8,
    fontWeight: 580,
    letterSpacing: 0,
    lineHeight: '10px',
    textAlign: 'center',
  },
  activityScroll: {
    minWidth: 0,
    overflowX: 'auto',
    overflowY: 'hidden',
    paddingBottom: 5,
    scrollbarColor: 'rgba(60, 69, 82, 0.2) transparent',
    scrollbarWidth: 'thin',
  },
  activityGrid: {
    display: 'grid',
    width: 'max-content',
    height: 88,
    gridAutoColumns: 10,
    gridAutoFlow: 'column',
    gridTemplateRows: 'repeat(7, 10px)',
    gap: 3,
  },
  activityCell: {
    width: 10,
    height: 10,
    borderRadius: 2,
    boxShadow: {
      'default': 'inset 0 0 0 0.5px rgba(35, 43, 54, 0.05)',
      ':hover': 'inset 0 0 0 1px rgba(27, 34, 44, 0.28)',
    },
    transitionDuration: {
      'default': '100ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'box-shadow, transform',
    transitionTimingFunction: 'ease-out',
    transform: {
      'default': 'scale(1)',
      ':hover': 'scale(1.13)',
    },
  },
  activityCellSpacer: {
    width: 10,
    height: 10,
  },
  activityCellEmpty: {
    backgroundColor: 'rgba(58, 68, 82, 0.085)',
  },
  activityCellLow: {
    backgroundColor: 'rgba(0, 113, 227, 0.26)',
  },
  activityCellMedium: {
    backgroundColor: 'rgba(0, 113, 227, 0.48)',
  },
  activityCellHigh: {
    backgroundColor: 'rgba(0, 103, 213, 0.72)',
  },
  activityCellPeak: {
    backgroundColor: colors.accentStrong,
  },
  activityCellToday: {
    boxShadow: 'inset 0 0 0 1.5px rgb(26, 128, 70), 0 0 0 1px rgba(255, 255, 255, 0.9)',
  },
  legend: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 3,
    marginTop: 3,
    color: 'rgba(48, 54, 63, 0.48)',
    fontSize: 8,
    letterSpacing: 0,
    lineHeight: '10px',
  },
  legendCell: {
    display: 'inline-block',
    width: 8,
    height: 8,
    borderRadius: 2,
  },
  loadingPanel: {
    display: 'flex',
    minHeight: 180,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  loadingPulse: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.accent,
    animationDuration: '900ms',
    animationIterationCount: 'infinite',
    animationName: pulse,
    animationTimingFunction: 'ease-in-out',
  },
  loadingText: {
    color: colors.muted,
    fontSize: 10,
    letterSpacing: 0,
  },
  errorPanel: {
    display: 'flex',
    minHeight: 60,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    color: 'rgb(166, 53, 53)',
    fontSize: 10,
    letterSpacing: 0,
  },
  retryButton: {
    borderWidth: 0,
    paddingTop: 3,
    paddingRight: 5,
    paddingBottom: 3,
    paddingLeft: 5,
    backgroundColor: 'transparent',
    boxShadow: {
      'default': 'none',
      ':focus-visible': '0 0 0 2px rgba(0, 96, 204, 0.45)',
    },
    color: colors.accentStrong,
    cursor: 'default',
    fontSize: 10,
    fontWeight: 620,
    letterSpacing: 0,
    outline: 'none',
  },
})
